// ═══════════════════════════════════════════════════════
//  Combitech AW Quiz – Extrafrågor v2
//  Dubblar antalet frågor per kategori för mer variation
// ═══════════════════════════════════════════════════════

const QUESTION_DB3 = {

  "🎵 80-tals musik": [
    {q:"Vilket band sjöng 'Hungry Like the Wolf'?",o:["Spandau Ballet","Duran Duran","Culture Club","ABC"],a:1,d:1},
    {q:"Vem sjunger 'We Are the World'?",o:["USA for Africa","Live Aid","Band Aid","Artists United"],a:0,d:1},
    {q:"Vilket band sjöng 'Footloose'?",o:["Wham!","Hall & Oates","Kenny Loggins","Huey Lewis"],a:2,d:1},
    {q:"Vem sjunger 'Ebony and Ivory'?",o:["Michael Jackson & Paul McCartney","Paul McCartney & Stevie Wonder","Michael Jackson & Diana Ross","Elton John & George Michael"],a:1,d:1},
    {q:"Vilket band sjöng 'Ring Ring' (80-tals hit)?",o:["ABBA","Roxette","Europe","Ace of Base"],a:0,d:1},
    {q:"Vilket band sjöng 'Girls on Film'?",o:["Culture Club","Duran Duran","Spandau Ballet","The Human League"],a:1,d:1},
    {q:"Vem sjunger 'I Feel for You'?",o:["Tina Turner","Whitney Houston","Chaka Khan","Aretha Franklin"],a:2,d:1},
    {q:"Vilket band sjöng 'Shout'?",o:["Human League","Tears for Fears","Simple Minds","OMD"],a:1,d:1},
    {q:"Vilket band sjöng 'Eye of the Tiger'?",o:["Foreigner","Night Ranger","Survivor","Asia"],a:2,d:1},
    {q:"Vem sjunger 'Livin' on a Prayer'?",o:["Aerosmith","Bon Jovi","Journey","Def Leppard"],a:1,d:1},
    {q:"Vilket band sjöng 'Take My Breath Away'?",o:["Berlin","Roxette","Blondie","Heart"],a:0,d:2},
    {q:"Vilket år kom Madonnas 'Like a Prayer'?",o:["1987","1989","1991","1993"],a:1,d:2},
    {q:"Vilket band sjöng 'She Drives Me Crazy'?",o:["Talk Talk","Simply Red","Fine Young Cannibals","The Housemartins"],a:2,d:2},
    {q:"Vem sjunger 'Don't You Want Me'?",o:["Erasure","Pet Shop Boys","Human League","Yazoo"],a:2,d:2},
    {q:"Vilket år kom Cyndi Laupers debut?",o:["1981","1983","1985","1987"],a:1,d:2},
    {q:"Vilket band sjöng 'Sledgehammer'?",o:["Peter Gabriel","Phil Collins","Simple Minds","Genesis"],a:0,d:2},
    {q:"Vilket band sjöng 'Vienna'?",o:["The Human League","Ultravox","Japan","Visage"],a:1,d:3},
    {q:"Vem producerade The Human Leagues 'Don't You Want Me'?",o:["Martin Rushent","Trevor Horn","Steve Hillage","Colin Thurston"],a:0,d:3},
    {q:"Vilket år kom Kraftwerks 'Computer World'?",o:["1979","1981","1983","1985"],a:1,d:3},
    {q:"Vilket band sjöng 'Fade to Grey'?",o:["Visage","Japan","Ultravox","Gary Numan"],a:0,d:3},
  ],

  "🎶 90-tals musik": [
    {q:"Vilket band sjöng 'Creep'?",o:["Oasis","Blur","Radiohead","Suede"],a:2,d:1},
    {q:"Vem sjunger 'Waterfalls'?",o:["Destiny's Child","En Vogue","TLC","Brandy"],a:2,d:1},
    {q:"Vilket band sjöng 'Semi-Charmed Life'?",o:["Matchbox Twenty","Third Eye Blind","Counting Crows","Spin Doctors"],a:1,d:1},
    {q:"Vilket band sjöng 'Mmm Mmm Mmm'?",o:["Barenaked Ladies","Crash Test Dummies","The Tragically Hip","54-40"],a:1,d:1},
    {q:"Vem sjunger 'I'm Too Sexy'?",o:["Right Said Fred","Vanilla Ice","MC Hammer","Snow"],a:0,d:1},
    {q:"Vilket band sjöng 'Black Hole Sun'?",o:["Pearl Jam","Alice in Chains","Soundgarden","Stone Temple Pilots"],a:2,d:1},
    {q:"Vem sjunger 'Believe' (1998)?",o:["Madonna","Kylie Minogue","Cher","Whitney Houston"],a:2,d:1},
    {q:"Vilket band sjöng 'No Scrubs'?",o:["Destiny's Child","En Vogue","TLC","SWV"],a:2,d:1},
    {q:"Vilket band sjöng 'Torn'?",o:["Natalie Imbruglia","Alanis Morissette","Sheryl Crow","Shania Twain"],a:0,d:1},
    {q:"Vilket band sjöng 'Spice Up Your Life'?",o:["TLC","Destiny's Child","Spice Girls","En Vogue"],a:2,d:1},
    {q:"Vilket band sjöng 'Push It'?",o:["TLC","Salt-N-Pepa","En Vogue","Destiny's Child"],a:1,d:1},
    {q:"Vem sjunger 'Baby Got Back'?",o:["MC Hammer","Vanilla Ice","Sir Mix-a-Lot","Coolio"],a:2,d:1},
    {q:"Vilket band sjöng 'Champagne Supernova'?",o:["Blur","Pulp","Oasis","Suede"],a:2,d:2},
    {q:"Vilket år kom Backstreet Boys debutalbum?",o:["1994","1996","1998","2000"],a:1,d:2},
    {q:"Vilket band sjöng 'No Diggity'?",o:["Boyz II Men","Blackstreet","112","Dru Hill"],a:1,d:2},
    {q:"Vilket band sjöng 'Gangsta's Paradise'?",o:["Coolio","Ice Cube","Snoop Dogg","Dr. Dre"],a:0,d:2},
    {q:"Vilket år kom Madonnas 'Ray of Light'?",o:["1996","1998","2000","2002"],a:1,d:2},
    {q:"Vilket band sjöng 'Under the Bridge'?",o:["Pearl Jam","Red Hot Chili Peppers","Soundgarden","Stone Temple Pilots"],a:1,d:2},
    {q:"Vilket år kom Jay-Zs debutalbum?",o:["1994","1996","1998","2000"],a:1,d:2},
    {q:"Vilket band sjöng 'One Week'?",o:["Barenaked Ladies","The Tragically Hip","Our Lady Peace","Default"],a:0,d:2},
    {q:"Vad heter Lauryn Hills soloalbum 1998?",o:["The Score","The Miseducation of Lauryn Hill","Ex-Factor","Killing Me Softly"],a:1,d:3},
    {q:"Vilket år kom Daft Punks 'Homework'?",o:["1995","1997","1999","2001"],a:1,d:3},
    {q:"Vad heter Biggie Smalls riktiga namn?",o:["Christopher Williams","Christopher Wallace","Christopher Martin","Christopher Brown"],a:1,d:3},
    {q:"Vilket år kom Radioheads 'The Bends'?",o:["1993","1995","1997","1999"],a:1,d:3},
    {q:"Vad heter Dr. Dres riktiga namn?",o:["Andre Young","Dre Williams","Calvin Broadus","Andre Brown"],a:0,d:3},
  ],

  "🎤 Ny musik (2010-idag)": [
    {q:"Vem sjunger 'Shake It Off'?",o:["Katy Perry","Ariana Grande","Taylor Swift","Selena Gomez"],a:2,d:1},
    {q:"Vem sjunger 'Royals'?",o:["Lorde","Lana Del Rey","Halsey","Billie Eilish"],a:0,d:1},
    {q:"Vilket band sjöng 'Counting Stars'?",o:["Imagine Dragons","OneRepublic","Maroon 5","The Script"],a:1,d:1},
    {q:"Vilket band sjöng 'Radioactive'?",o:["Imagine Dragons","Twenty One Pilots","Fall Out Boy","Muse"],a:0,d:1},
    {q:"Vem sjunger 'Happy'?",o:["Bruno Mars","Justin Timberlake","Pharrell Williams","Jason Derulo"],a:2,d:1},
    {q:"Vem sjunger 'Sunflower'?",o:["Post Malone & Swae Lee","Drake & Future","The Weeknd","Travis Scott"],a:0,d:1},
    {q:"Vem sjunger 'Stay With Me'?",o:["Ed Sheeran","Sam Smith","James Arthur","Olly Murs"],a:1,d:1},
    {q:"Vilket band sjöng 'Somebody That I Used to Know'?",o:["Foster the People","Gotye ft. Kimbra","Passion Pit","fun."],a:1,d:1},
    {q:"Vem sjunger 'Watermelon Sugar'?",o:["Ed Sheeran","Harry Styles","Niall Horan","Shawn Mendes"],a:1,d:1},
    {q:"Vem sjunger 'Work'?",o:["Beyoncé","Nicki Minaj","Rihanna","Cardi B"],a:2,d:1},
    {q:"Vem sjunger 'Humble'?",o:["Drake","J. Cole","Kendrick Lamar","Travis Scott"],a:2,d:1},
    {q:"Vem sjunger 'God's Plan'?",o:["Travis Scott","Post Malone","Drake","The Weeknd"],a:2,d:1},
    {q:"Vilket år kom Adeles '25'?",o:["2013","2015","2017","2019"],a:1,d:2},
    {q:"Vem sjunger 'Levitating'?",o:["Dua Lipa","Doja Cat","Olivia Rodrigo","Ariana Grande"],a:0,d:2},
    {q:"Vilket år vann Billie Eilish fyra Grammy?",o:["2019","2020","2021","2022"],a:1,d:2},
    {q:"Vem sjunger 'Industry Baby'?",o:["Lil Nas X ft. Jack Harlow","Travis Scott","Cardi B","Megan Thee Stallion"],a:0,d:2},
    {q:"Vilket år kom Dua Lipas 'Future Nostalgia'?",o:["2018","2020","2022","2024"],a:1,d:2},
    {q:"Vilket år kom Kendrick Lamars 'DAMN.'?",o:["2015","2017","2019","2021"],a:1,d:2},
    {q:"Vem sjunger 'Montero'?",o:["Tyler the Creator","Lil Nas X","Frank Ocean","ASAP Rocky"],a:1,d:2},
    {q:"Vilket år kom Taylor Swifts 'Folklore'?",o:["2018","2019","2020","2021"],a:2,d:2},
    {q:"Vem sjunger 'Espresso'?",o:["Dua Lipa","Sabrina Carpenter","Olivia Rodrigo","Ariana Grande"],a:1,d:2},
    {q:"Vem sjunger 'Flowers'?",o:["Dua Lipa","Miley Cyrus","Selena Gomez","Lizzo"],a:1,d:2},
    {q:"Vilket år kom Kendrick Lamars 'To Pimp a Butterfly'?",o:["2013","2015","2017","2019"],a:1,d:3},
    {q:"Vilket år kom Frank Oceans 'Blonde'?",o:["2014","2016","2018","2020"],a:1,d:3},
    {q:"Vilket år kom Tyler the Creators 'IGOR'?",o:["2017","2019","2021","2023"],a:1,d:3},
    {q:"Vilket år kom SZAs 'Ctrl'?",o:["2015","2017","2019","2021"],a:1,d:3},
    {q:"Vad heter Billie Eilish bror och producent?",o:["Ryan","Finneas","Declan","Ryder"],a:1,d:3},
    {q:"Vem producerade Dua Lipas 'Future Nostalgia'?",o:["Max Martin","Stuart Price","Ian Kirkpatrick","Jeff Bhasker"],a:1,d:3},
  ],

  "🎵 Popmusik (allmänt)": [
    {q:"Vilket band sjöng 'Don't Stop Me Now'?",o:["Dire Straits","Queen","Elton John","David Bowie"],a:1,d:1},
    {q:"Vem sjunger 'Poker Face'?",o:["Katy Perry","Rihanna","Lady Gaga","Pink"],a:2,d:1},
    {q:"Vilket år kom PSY's 'Gangnam Style'?",o:["2010","2012","2014","2016"],a:1,d:1},
    {q:"Vem sjunger 'Born This Way'?",o:["Katy Perry","Rihanna","Lady Gaga","Kesha"],a:2,d:1},
    {q:"Vem sjunger 'Umbrella'?",o:["Beyoncé","Rihanna","Ciara","Alicia Keys"],a:1,d:1},
    {q:"Vem sjunger 'Since U Been Gone'?",o:["Pink","Kelly Clarkson","Avril Lavigne","Alanis Morissette"],a:1,d:1},
    {q:"Vilket band sjöng 'Mr. Brightside'?",o:["The Strokes","The Killers","Interpol","Franz Ferdinand"],a:1,d:1},
    {q:"Vem sjunger 'Halo'?",o:["Alicia Keys","Rihanna","Beyoncé","Mariah Carey"],a:2,d:1},
    {q:"Vilket år vann Loreen Eurovision första gången?",o:["2010","2012","2014","2016"],a:1,d:1},
    {q:"Vad heter Lady Gagas riktiga namn?",o:["Stefani Germanotta","Stefani Joanne Germanotta","Joanne Germanotta","Stefani Angelina"],a:1,d:2},
    {q:"Vad heter Madonnas debutalbum?",o:["True Blue","Like a Virgin","Madonna","Immaculate Collection"],a:2,d:2},
    {q:"Vad heter Beyoncés soloalbum från 2003?",o:["Lemonade","4","Dangerously in Love","B'Day"],a:2,d:2},
    {q:"Vilket år grundades Spice Girls?",o:["1992","1994","1996","1998"],a:1,d:2},
    {q:"Vilket år kom Rihannas 'Umbrella'?",o:["2005","2007","2009","2011"],a:1,d:2},
    {q:"Vilket år kom Adeles '21'?",o:["2009","2011","2013","2015"],a:1,d:2},
    {q:"Vilket land vann Eurovision 2024?",o:["Sverige","Schweiz","Spanien","Kroatien"],a:1,d:2},
    {q:"Vem sjunger 'Flowers' (2023)?",o:["Dua Lipa","Miley Cyrus","Selena Gomez","Lizzo"],a:1,d:2},
    {q:"Vilket år kom Kylie Minogues 'Fever'?",o:["1999","2001","2003","2005"],a:1,d:3},
    {q:"Vad heter Beyoncés album från 2016?",o:["Renaissance","4","Lemonade","Self-titled"],a:2,d:3},
    {q:"Vilket skivbolag gav ut Lady Gagas debutalbum?",o:["Universal","Interscope","Atlantic","Columbia"],a:1,d:3},
    {q:"Vem producerade Madonnas 'Like a Prayer'?",o:["Nile Rodgers","Patrick Leonard","Jellybean Benitez","Steve Bray"],a:1,d:3},
    {q:"Vilket år bildades Queen?",o:["1968","1970","1972","1974"],a:1,d:3},
    {q:"Vad heter ABBA-Agnethas efternamn?",o:["Fältskog","Lindqvist","Andersson","Björk"],a:0,d:3},
  ],

  "🎸 Rock & Metal": [
    {q:"Vilket band sjöng 'Thunderstruck'?",o:["Aerosmith","Kiss","AC/DC","Motörhead"],a:2,d:1},
    {q:"Vem sjunger i Guns N' Roses?",o:["Sebastian Bach","Steven Tyler","Axl Rose","David Coverdale"],a:2,d:1},
    {q:"Vilket band sjöng 'Whole Lotta Love'?",o:["Deep Purple","Black Sabbath","Led Zeppelin","Free"],a:2,d:1},
    {q:"Vilket band sjöng 'Seven Nation Army'?",o:["The Strokes","The White Stripes","The Black Keys","The Raconteurs"],a:1,d:1},
    {q:"Vem sjunger i Foo Fighters?",o:["Eddie Vedder","Chris Cornell","Dave Grohl","Scott Weiland"],a:2,d:1},
    {q:"Vilket band sjöng 'Come As You Are'?",o:["Pearl Jam","Soundgarden","Nirvana","Alice in Chains"],a:2,d:1},
    {q:"Vilket band sjöng 'Yellow'?",o:["Travis","Keane","Coldplay","Snow Patrol"],a:2,d:1},
    {q:"Vilket band sjöng 'Paint It Black'?",o:["The Who","Rolling Stones","The Kinks","The Animals"],a:1,d:1},
    {q:"Vilket band sjöng 'Roxanne'?",o:["The Clash","The Police","Elvis Costello","Joe Jackson"],a:1,d:1},
    {q:"Vem spelar bas i Red Hot Chili Peppers?",o:["Dave Navarro","John Frusciante","Flea","Chad Smith"],a:2,d:1},
    {q:"Vilket band sjöng 'Hysteria'?",o:["Whitesnake","Bon Jovi","Def Leppard","Europe"],a:2,d:1},
    {q:"Vilket band sjöng 'With or Without You'?",o:["Simple Minds","Depeche Mode","U2","The Police"],a:2,d:1},
    {q:"Vilket år kom Foo Fighters debutalbum?",o:["1993","1995","1997","1999"],a:1,d:2},
    {q:"Vilket år kom Green Days 'Dookie'?",o:["1992","1994","1996","1998"],a:1,d:2},
    {q:"Vilket band sjöng 'Everlong'?",o:["Pearl Jam","Foo Fighters","Green Day","The Offspring"],a:1,d:2},
    {q:"Vilket band sjöng 'Numb'?",o:["Korn","Slipknot","Linkin Park","Papa Roach"],a:2,d:2},
    {q:"Vilket år kom The White Stripes 'Elephant'?",o:["2001","2003","2005","2007"],a:1,d:2},
    {q:"Vilket band sjöng 'Knights of Cydonia'?",o:["Radiohead","Muse","Placebo","Biffy Clyro"],a:1,d:2},
    {q:"Vem spelar bas i The Beatles?",o:["John Lennon","George Harrison","Paul McCartney","Ringo Starr"],a:2,d:2},
    {q:"Vilket band sjöng 'In Bloom'?",o:["Pearl Jam","Soundgarden","Nirvana","Alice in Chains"],a:2,d:2},
    {q:"Vilket år kom Arctic Monkeys debutalbum?",o:["2004","2006","2008","2010"],a:1,d:2},
    {q:"Vilket band sjöng 'Maps'?",o:["The Strokes","Interpol","Yeah Yeah Yeahs","Franz Ferdinand"],a:2,d:2},
    {q:"Vilket år kom Sonic Youths 'Daydream Nation'?",o:["1986","1988","1990","1992"],a:1,d:3},
    {q:"Vilket år kom Pixies 'Doolittle'?",o:["1987","1989","1991","1993"],a:1,d:3},
    {q:"Vilket band sjöng 'Where Is My Mind'?",o:["The Breeders","Belly","Pixies","Throwing Muses"],a:2,d:3},
    {q:"Vilket år kom The Strokes debutalbum?",o:["1999","2001","2003","2005"],a:1,d:3},
  ],

  "🔥 Heavy Metal": [
    {q:"Vilket band sjöng 'Breaking the Law'?",o:["Black Sabbath","Iron Maiden","Judas Priest","Motörhead"],a:2,d:1},
    {q:"Vem är sångare i Slayer?",o:["Dave Mustaine","Phil Anselmo","Tom Araya","Chuck Billy"],a:2,d:1},
    {q:"Vilket band sjöng 'Bark at the Moon'?",o:["Black Sabbath","Ozzy Osbourne","Dio","Rainbow"],a:1,d:1},
    {q:"Vilket band sjöng 'The Trooper'?",o:["Judas Priest","Saxon","Iron Maiden","Motörhead"],a:2,d:1},
    {q:"Vilket band sjöng 'Symphony of Destruction'?",o:["Metallica","Megadeth","Slayer","Anthrax"],a:1,d:1},
    {q:"Vilket band sjöng 'We're Not Gonna Take It'?",o:["Kiss","Twisted Sister","Ratt","Poison"],a:1,d:1},
    {q:"Vilket band sjöng 'Heaven and Hell'?",o:["Black Sabbath med Dio","Ozzy Osbourne","Rainbow","Deep Purple"],a:0,d:1},
    {q:"Vilket band sjöng 'Balls to the Wall'?",o:["Scorpions","Accept","Ratt","Dokken"],a:1,d:1},
    {q:"Vilket band sjöng 'Holy Diver'?",o:["Black Sabbath","Rainbow","Dio","Ozzy Osbourne"],a:2,d:1},
    {q:"Vilket band sjöng 'Am I Evil'?",o:["Iron Maiden","Diamond Head","Saxon","Judas Priest"],a:1,d:1},
    {q:"Vilket band sjöng 'Stone Cold Crazy'?",o:["Black Sabbath","Deep Purple","Queen","Led Zeppelin"],a:2,d:1},
    {q:"Vilket band sjöng 'Fear of the Dark'?",o:["Judas Priest","Saxon","Iron Maiden","Motörhead"],a:2,d:1},
    {q:"Vilket år kom Pantera 'Cowboys from Hell'?",o:["1988","1990","1992","1994"],a:1,d:2},
    {q:"Vilket år kom Slipknots debutalbum?",o:["1997","1999","2001","2003"],a:1,d:2},
    {q:"Vilket band sjöng 'Chop Suey!'?",o:["Slipknot","Korn","System of a Down","Linkin Park"],a:2,d:2},
    {q:"Vilket band sjöng 'B.Y.O.B.'?",o:["Slipknot","Korn","System of a Down","Linkin Park"],a:2,d:2},
    {q:"Vilket band sjöng 'Freak on a Leash'?",o:["Slipknot","Mudvayne","Korn","Deftones"],a:2,d:2},
    {q:"Vilket år kom Iron Maidens 'Number of the Beast'?",o:["1980","1982","1984","1986"],a:1,d:2},
    {q:"Vilket band sjöng 'Toxicity'?",o:["Slipknot","Korn","System of a Down","Linkin Park"],a:2,d:2},
    {q:"Vilket år kom Metallicas 'Ride the Lightning'?",o:["1982","1984","1986","1988"],a:1,d:2},
    {q:"Vilket band sjöng 'My Own Summer'?",o:["Korn","Slipknot","Deftones","Tool"],a:2,d:2},
    {q:"Vilket band sjöng 'Down with the Sickness'?",o:["Slipknot","Disturbed","Drowning Pool","Papa Roach"],a:1,d:2},
    {q:"Vad heter Tools sångare?",o:["Maynard James Keenan","Phil Anselmo","Corey Taylor","Chino Moreno"],a:0,d:3},
    {q:"Vad heter gitarristen i Metallica (ej James Hetfield)?",o:["Dave Mustaine","Kirk Hammett","Phil Demmel","Marty Friedman"],a:1,d:3},
    {q:"Vilket år kom Slayers 'Reign in Blood'?",o:["1984","1986","1988","1990"],a:1,d:3},
    {q:"Vad heter basen i Motörhead?",o:["Lemmy Kilmister","Phil Campbell","Mikkey Dee","Fast Eddie Clarke"],a:0,d:3},
    {q:"Vem grundade Megadeth?",o:["Lars Ulrich","Kirk Hammett","Dave Mustaine","Jason Newsted"],a:2,d:3},
    {q:"Vilket år dog Dimebag Darrell?",o:["2002","2004","2006","2008"],a:1,d:3},
  ],

  "🇸🇪 Svensk musik": [
    {q:"Vem sjunger 'Dancing on My Own'?",o:["Zara Larsson","Robyn","Tove Lo","MØ"],a:1,d:1},
    {q:"Vilket band sjöng 'Hate to Say I Told You So'?",o:["The Hellacopters","The Hives","Refused","Soundtrack of Our Lives"],a:1,d:1},
    {q:"Vilket band sjöng 'Erase/Rewind'?",o:["Roxette","Robyn","The Cardigans","Ace of Base"],a:2,d:1},
    {q:"Vem sjunger 'Tattoo' (Eurovision 2023)?",o:["Cornelia Jakobs","Loreen","Linda Bengtzing","Carola"],a:1,d:1},
    {q:"Vem sjunger 'Habits (Stay High)'?",o:["Zara Larsson","Robyn","Tove Lo","MØ"],a:2,d:1},
    {q:"Vad heter Swedish House Mafias comeback-singel 2012?",o:["Save the World","Don't You Worry Child","One","Greyhound"],a:1,d:1},
    {q:"Vem sjunger 'Karolina'?",o:["Håkan Hellström","Lars Winnerbäck","Bob Hund","Ulf Lundell"],a:0,d:1},
    {q:"Vilket band sjöng 'Disconnected' (Robyn)?",o:["Robyn","Ace of Base","Roxette","The Cardigans"],a:0,d:1},
    {q:"Vad heter Zara Larssons genombrott slåt?",o:["Lush Life","Never Forget You","Symphony","So Good"],a:0,d:1},
    {q:"Vilket band sjöng 'Sommartider'?",o:["Gyllene Tider","Roxette","Per Gessle solo","Bob Hund"],a:0,d:1},
    {q:"Vem sjunger 'En dag'?",o:["Lars Winnerbäck","Håkan Hellström","Magnus Uggla","Ulf Lundell"],a:0,d:1},
    {q:"Vad heter Aviciis mest kända låt?",o:["Fade into Darkness","Levels","Wake Me Up","Hey Brother"],a:1,d:1},
    {q:"Vilket år kom Tove Los debutalbum?",o:["2012","2014","2016","2018"],a:1,d:2},
    {q:"Vilket år kom Zara Larssons debutalbum?",o:["2012","2014","2016","2018"],a:1,d:2},
    {q:"Vilket år bildades Refused?",o:["1989","1991","1993","1995"],a:1,d:2},
    {q:"Vilket år kom The Hives 'Veni Vidi Vicious'?",o:["1998","2000","2002","2004"],a:1,d:2},
    {q:"Vilket år kom Robyn's 'Body Talk'?",o:["2008","2010","2012","2014"],a:1,d:2},
    {q:"Vilket år kom Aviciis 'True'?",o:["2011","2013","2015","2017"],a:1,d:2},
    {q:"Vilken stad kommer The Hives ifrån?",o:["Stockholm","Göteborg","Fagersta","Örebro"],a:2,d:2},
    {q:"Vilket år bildades Gyllene Tider?",o:["1974","1976","1978","1980"],a:1,d:2},
    {q:"Vilket år debuterade Robyn?",o:["1993","1995","1997","1999"],a:1,d:2},
    {q:"Vilket år vann Loreen Eurovision andra gången?",o:["2021","2022","2023","2024"],a:2,d:2},
    {q:"Vad heter Tove Los riktiga namn?",o:["Tova Magnusson-Forssa","Tova Nilsson","Tova Lindqvist","Tova Andersson"],a:0,d:3},
    {q:"Vad heter Swedish House Mafias tre medlemmar?",o:["Axwell/Steve Angello/Sebastian Ingrosso","Axwell/Avicii/Alesso","Avicii/Alesso/Ingrosso","Axwell/Tiesto/Ingrosso"],a:0,d:3},
    {q:"Vilket år grundades Ace of Base?",o:["1987","1989","1991","1993"],a:1,d:3},
    {q:"Vem var sångare i Imperiet?",o:["Håkan Hellström","Joakim Thåström","Thomas Eriksson","Ulf Lundell"],a:1,d:3},
    {q:"Vilket år kom Gyllene Tiiders 'Puls'?",o:["1980","1982","1984","1986"],a:1,d:3},
    {q:"Vilket skivbolag är The Hives på?",o:["Burning Heart","Epitaph","Poptones","Atlantic"],a:0,d:3},
  ],

  "🎬 Movie Quiz": [
    {q:"Vem spelar Thor i MCU?",o:["Chris Evans","Robert Downey Jr.","Chris Hemsworth","Mark Ruffalo"],a:2,d:1},
    {q:"Vilket år kom Inception?",o:["2008","2010","2012","2014"],a:1,d:1},
    {q:"Vem spelar Gandalf i Sagan om Ringen?",o:["Ian McKellen","Patrick Stewart","Anthony Hopkins","Christopher Lee"],a:0,d:1},
    {q:"Vilket år kom Interstellar?",o:["2012","2014","2016","2018"],a:1,d:1},
    {q:"Vem regisserade Goodfellas?",o:["Francis Ford Coppola","Brian De Palma","Martin Scorsese","Quentin Tarantino"],a:2,d:1},
    {q:"Vilket år kom Joker (2019)?",o:["2017","2019","2021","2023"],a:1,d:1},
    {q:"Vem spelar Joker i 'Joker' (2019)?",o:["Heath Ledger","Jared Leto","Joaquin Phoenix","Jack Nicholson"],a:2,d:1},
    {q:"Vilket år kom The Matrix?",o:["1997","1999","2001","2003"],a:1,d:1},
    {q:"Vem regisserade The Matrix?",o:["James Cameron","The Wachowskis","Steven Spielberg","Ridley Scott"],a:1,d:1},
    {q:"Vilket år kom Avengers Endgame?",o:["2017","2019","2021","2023"],a:1,d:1},
    {q:"Vem regisserade Avatar?",o:["Steven Spielberg","James Cameron","Ridley Scott","Peter Jackson"],a:1,d:1},
    {q:"Vilket år kom The Dark Knight?",o:["2006","2008","2010","2012"],a:1,d:1},
    {q:"Vem regisserade Tarantinos 'Kill Bill'?",o:["Robert Rodriguez","Quentin Tarantino","Guy Ritchie","Wes Anderson"],a:1,d:2},
    {q:"Vilket år kom Fight Club?",o:["1997","1999","2001","2003"],a:1,d:2},
    {q:"Vem regisserade Fight Club?",o:["Quentin Tarantino","David Fincher","Christopher Nolan","Darren Aronofsky"],a:1,d:2},
    {q:"Vilket år kom No Country for Old Men?",o:["2005","2007","2009","2011"],a:1,d:2},
    {q:"Vilket år kom The Social Network?",o:["2008","2010","2012","2014"],a:1,d:2},
    {q:"Vilket år vann Parasite Oscar för bästa film?",o:["2018","2019","2020","2021"],a:2,d:2},
    {q:"Vem spelar Daniel Plainview i There Will Be Blood?",o:["Daniel Day-Lewis","Javier Bardem","Tommy Lee Jones","Josh Brolin"],a:0,d:2},
    {q:"Vilket år kom Gladiator?",o:["1998","2000","2002","2004"],a:1,d:2},
    {q:"Vem spelar Wolverine i X-Men?",o:["Chris Evans","Hugh Jackman","Ryan Reynolds","Ben Affleck"],a:1,d:2},
    {q:"Vilket år kom Whiplash?",o:["2012","2014","2016","2018"],a:1,d:2},
    {q:"Vilket år kom Chinatown?",o:["1972","1974","1976","1978"],a:1,d:3},
    {q:"Vem regisserade Chinatown?",o:["Francis Ford Coppola","Roman Polanski","Martin Scorsese","Sidney Lumet"],a:1,d:3},
    {q:"Vem spelade Travis Bickle i Taxi Driver?",o:["Al Pacino","Jack Nicholson","Robert De Niro","Dustin Hoffman"],a:2,d:3},
    {q:"Vilket år kom The Godfather?",o:["1970","1972","1974","1976"],a:1,d:3},
    {q:"Vem komponerade musiken till Star Wars?",o:["Hans Zimmer","Danny Elfman","John Williams","Ennio Morricone"],a:2,d:3},
    {q:"Vem regisserade 'Days of Heaven'?",o:["Terrence Malick","Robert Altman","Hal Ashby","Bob Rafelson"],a:0,d:3},
  ],

  "📺 TV-serier": [
    {q:"Vilket år kom Succession?",o:["2016","2018","2020","2022"],a:1,d:1},
    {q:"Vem spelar Logan Roy i Succession?",o:["Brian Cox","Jeff Bridges","Anthony Hopkins","Gary Oldman"],a:0,d:1},
    {q:"Vilket år kom Ozark?",o:["2015","2017","2019","2021"],a:1,d:1},
    {q:"Vem spelar Marty Byrde i Ozark?",o:["Bryan Cranston","Jason Bateman","Kevin Spacey","Michael C. Hall"],a:1,d:1},
    {q:"Vilket år kom Peaky Blinders?",o:["2011","2013","2015","2017"],a:1,d:1},
    {q:"Vem spelar Tommy Shelby i Peaky Blinders?",o:["Tom Hardy","Cillian Murphy","Idris Elba","James McAvoy"],a:1,d:1},
    {q:"Vilket år kom Squid Game?",o:["2019","2021","2022","2023"],a:1,d:1},
    {q:"Vilket land producerade Squid Game?",o:["Japan","Kina","Sydkorea","Thailand"],a:2,d:1},
    {q:"Vem spelar i Euphoria (huvudroll)?",o:["Billie Eilish","Zendaya","Olivia Rodrigo","Ariana Grande"],a:1,d:1},
    {q:"Vilket år kom The Last of Us (HBO)?",o:["2021","2023","2024","2025"],a:1,d:1},
    {q:"Vilket år kom White Lotus?",o:["2019","2021","2022","2023"],a:1,d:1},
    {q:"Vem spelar Daenerys i Game of Thrones?",o:["Sophie Turner","Natalie Dormer","Emilia Clarke","Kit Harington"],a:2,d:1},
    {q:"Vilket år kom Better Call Saul?",o:["2013","2015","2017","2019"],a:1,d:2},
    {q:"Vem skapade Better Call Saul?",o:["David Chase","David Simon","Vince Gilligan & Peter Gould","Matthew Weiner"],a:2,d:2},
    {q:"Vilket år kom Twin Peaks?",o:["1988","1990","1992","1994"],a:1,d:2},
    {q:"Vem skapade Twin Peaks?",o:["Steven Spielberg","David Lynch & Mark Frost","Ridley Scott","Jim Jarmusch"],a:1,d:2},
    {q:"Vilket år kom The Americans?",o:["2011","2013","2015","2017"],a:1,d:2},
    {q:"Vilket år kom Lost?",o:["2002","2004","2006","2008"],a:1,d:2},
    {q:"Vilket år kom Six Feet Under?",o:["1999","2001","2003","2005"],a:1,d:2},
    {q:"Vilket år kom Mad Men?",o:["2005","2007","2009","2011"],a:1,d:2},
    {q:"Vem skapade Mad Men?",o:["David Chase","David Simon","Vince Gilligan","Matthew Weiner"],a:3,d:2},
    {q:"Vilket år kom Severance?",o:["2020","2022","2023","2024"],a:1,d:2},
    {q:"Vem skapade Breaking Bad?",o:["David Chase","David Simon","Vince Gilligan","Matthew Weiner"],a:2,d:3},
    {q:"Vem skapade The Wire?",o:["David Chase","David Simon","Vince Gilligan","Ed Burns"],a:1,d:3},
    {q:"Vem skapade The Sopranos?",o:["David Chase","David Simon","Vince Gilligan","Matthew Weiner"],a:0,d:3},
    {q:"Vem spelar Elliot i Mr. Robot?",o:["Christian Slater","Rami Malek","B.D. Wong","Martin Wallström"],a:1,d:3},
    {q:"Vem skapade Deadwood?",o:["David Chase","David Milch","Vince Gilligan","Alan Ball"],a:1,d:3},
    {q:"Vilket år kom Battlestar Galactica (nya)?",o:["2001","2003","2005","2007"],a:1,d:3},
  ],

  "🏰 Disney Klassiker": [
    {q:"Vad heter häxan i Törnrosa?",o:["Ursula","Maleficent","Den onda drottningen","Mother Gothel"],a:1,d:1},
    {q:"Vad heter Timons kompis i Lejonkungen?",o:["Simba","Nala","Pumba","Rafiki"],a:2,d:1},
    {q:"Vilket år kom Den lilla sjöjungfrun?",o:["1987","1989","1991","1993"],a:1,d:1},
    {q:"Vad heter Cinderellas onda styvmor?",o:["Lady Tremaine","Madam Mim","The Evil Queen","Mother Gothel"],a:0,d:1},
    {q:"Vilket år kom Pinocchio?",o:["1938","1940","1942","1944"],a:1,d:1},
    {q:"Vilket år kom Bambi?",o:["1940","1942","1944","1946"],a:1,d:1},
    {q:"Vilket år kom Askungen (Disney)?",o:["1948","1950","1952","1954"],a:1,d:1},
    {q:"Vilket år kom 101 Dalmatiner?",o:["1959","1961","1963","1965"],a:1,d:1},
    {q:"Vad heter antagonisten i 101 Dalmatiner?",o:["Maleficent","Cruella de Vil","Ursula","Lady Tremaine"],a:1,d:1},
    {q:"Vilket år kom Djungelboken (Disney)?",o:["1964","1966","1968","1970"],a:1,d:1},
    {q:"Vad heter häxan i Den lilla sjöjungfrun?",o:["Maleficent","Ursula","Gothel","The Evil Queen"],a:1,d:1},
    {q:"Vad heter Robin Hood i Disneys version?",o:["En räv","En björn","En lo","En varg"],a:0,d:1},
    {q:"Vem röstade Woody i Toy Story?",o:["Tom Hanks","Tim Allen","Billy Crystal","John Goodman"],a:0,d:2},
    {q:"Vem röstade Simba vuxen i Lejonkungen?",o:["Will Smith","Matthew McConaughey","Matthew Broderick","James Earl Jones"],a:2,d:2},
    {q:"Vem röstade Mufasa i Lejonkungen?",o:["Morgan Freeman","James Earl Jones","Samuel L. Jackson","Denzel Washington"],a:1,d:2},
    {q:"Vilket år kom Hercules (Disney)?",o:["1995","1997","1999","2001"],a:1,d:2},
    {q:"Vilket år kom Tarzan (Disney)?",o:["1997","1999","2001","2003"],a:1,d:2},
    {q:"Vad heter Ariels pappa i Sjöjungfrun?",o:["Triton","Poseidon","Neptune","Aquaman"],a:0,d:2},
    {q:"Vilket år kom Mulan?",o:["1994","1996","1998","2000"],a:2,d:2},
    {q:"Vad heter feen i Pinocchio?",o:["Tinker Bell","Blue Fairy","Fairy Godmother","Periwinkle"],a:1,d:2},
    {q:"Vilket år kom Beauty and the Beast?",o:["1989","1991","1993","1995"],a:1,d:2},
    {q:"Vilket år kom Aladdin?",o:["1990","1992","1994","1996"],a:1,d:2},
    {q:"Vem röstade Scar i Lejonkungen?",o:["Tim Curry","Jeremy Irons","Ian McKellen","Alan Rickman"],a:1,d:3},
    {q:"Vem röstade Genie i Aladdin?",o:["Jim Carrey","Steve Martin","Robin Williams","Billy Crystal"],a:2,d:3},
    {q:"Vilket år kom Fantasia?",o:["1938","1940","1942","1944"],a:1,d:3},
    {q:"Vem röstade Ursula i Sjöjungfrun?",o:["Cloris Leachman","Bette Midler","Pat Carroll","Rosie O'Donnell"],a:2,d:3},
    {q:"Vem komponerade musiken till Lejonkungen?",o:["Alan Menken","Howard Ashman","Hans Zimmer","Elton John"],a:2,d:3},
    {q:"Vilket år kom Disneys 'Sleeping Beauty'?",o:["1957","1959","1961","1963"],a:1,d:3},
  ],

  "❄️ Frost & Moderna Disney": [
    {q:"Vad heter snögubben i Frost?",o:["Olaf","Sven","Kristoff","Hans"],a:0,d:1},
    {q:"Vilket år kom Frost 2?",o:["2017","2019","2021","2023"],a:1,d:1},
    {q:"Vad heter halvguden i Vaiana?",o:["Tamatoa","Maui","Hei Hei","Te Ka"],a:1,d:1},
    {q:"Vad heter huvudpersonen i Encanto?",o:["Luisa","Isabela","Mirabel","Dolores"],a:2,d:1},
    {q:"Vilket år kom Zootopia?",o:["2014","2016","2018","2020"],a:1,d:1},
    {q:"Vilket år kom Coco (Pixar)?",o:["2015","2017","2019","2021"],a:1,d:1},
    {q:"Vad heter räven i Zootopia?",o:["Jack","Nick","Fin","Rex"],a:1,d:1},
    {q:"Vilket år kom Inside Out?",o:["2013","2015","2017","2019"],a:1,d:1},
    {q:"Vilket år kom Turning Red (Pixar)?",o:["2020","2022","2023","2024"],a:1,d:1},
    {q:"Vad heter antagonisten i Frost?",o:["Kristoff","Hans","Duke of Weselton","Marshmallow"],a:1,d:1},
    {q:"Vilket år kom Vaiana/Moana?",o:["2014","2016","2018","2020"],a:1,d:1},
    {q:"Vilket år kom Encanto?",o:["2019","2021","2022","2023"],a:1,d:1},
    {q:"Vem sjunger 'Let It Go' i Frost?",o:["Idina Menzel","Kristen Bell","Anna Kendrick","Lea Michele"],a:0,d:2},
    {q:"Vilket år kom Big Hero 6?",o:["2012","2014","2016","2018"],a:1,d:2},
    {q:"Vad heter roboten i Big Hero 6?",o:["Baymax","Hiro","Tadashi","Go Go"],a:0,d:2},
    {q:"Vad heter Elsas och Annas mamma?",o:["Elsa","Iduna","Gerda","Ingrid"],a:1,d:2},
    {q:"Vilket år kom Raya and the Last Dragon?",o:["2019","2021","2022","2023"],a:1,d:2},
    {q:"Vilket år kom Inside Out 2?",o:["2022","2023","2024","2025"],a:2,d:2},
    {q:"Vad heter det nya känslot i Inside Out 2?",o:["Stress","Anxiety","Embarrassment","Envy"],a:1,d:2},
    {q:"Vad heter Moanas höna i Vaiana?",o:["Tamatoa","Maui","Hei Hei","Te Fiti"],a:2,d:2},
    {q:"Vilket år kom Pixars 'Soul'?",o:["2018","2020","2022","2024"],a:1,d:2},
    {q:"Vad heter hästen i Tangled/Trassel?",o:["Maximus","Samson","Angus","Achilles"],a:0,d:2},
    {q:"Vem regisserade Frost?",o:["John Lasseter","Pete Docter","Chris Buck & Jennifer Lee","Andrew Stanton"],a:2,d:3},
    {q:"Vad heter byn i Encanto?",o:["Casita","Colombia","La Familia","Madrigal"],a:0,d:3},
    {q:"Vem sjunger 'We Don't Talk About Bruno'?",o:["Mirabel","Dolores","Camilo","Flera karaktärer"],a:3,d:3},
    {q:"Vilket år kom Lightyear (Pixar)?",o:["2020","2022","2023","2024"],a:1,d:3},
    {q:"Vem sjunger 'Surface Pressure' i Encanto?",o:["Luisa","Mirabel","Isabela","Dolores"],a:0,d:3},
    {q:"Vilket år kom Pixars 'Luca'?",o:["2019","2021","2022","2023"],a:1,d:3},
  ],

  "🎠 Barnfilmer & Ungdomsfilmer": [
    {q:"Vilket år kom första Harry Potter-filmen?",o:["1999","2001","2003","2005"],a:1,d:1},
    {q:"Vad heter åsnan i Shrek?",o:["Donkey","Burro","Mule","Percy"],a:0,d:1},
    {q:"Vilket år kom Narnia: Häxan och lejonet?",o:["2003","2005","2007","2009"],a:1,d:1},
    {q:"Vem spelar Katniss i Hunger Games?",o:["Emma Stone","Jennifer Lawrence","Shailene Woodley","Kristen Stewart"],a:1,d:1},
    {q:"Vem spelar Edward i Twilight?",o:["Taylor Lautner","Kellan Lutz","Robert Pattinson","Jackson Rathbone"],a:2,d:1},
    {q:"Vilket år kom Hobbit del 1?",o:["2010","2012","2014","2016"],a:1,d:1},
    {q:"Vilket år kom E.T.?",o:["1980","1982","1984","1986"],a:1,d:1},
    {q:"Vilket år kom Jumanji?",o:["1993","1995","1997","1999"],a:1,d:1},
    {q:"Vem spelar Kevin i Home Alone?",o:["Macaulay Culkin","Haley Joel Osment","Joseph Gordon-Levitt","Ryan Gosling"],a:0,d:1},
    {q:"Vem spelar Bilbo i Hobbit?",o:["Ian McKellen","Martin Freeman","Benedict Cumberbatch","Richard Armitage"],a:1,d:1},
    {q:"Vilket år kom Twilight?",o:["2006","2008","2010","2012"],a:1,d:1},
    {q:"Vem spelar Frodo i Sagan om Ringen?",o:["Sean Bean","Orlando Bloom","Elijah Wood","Dominic Monaghan"],a:2,d:1},
    {q:"Vilket år kom Home Alone?",o:["1988","1990","1992","1994"],a:1,d:2},
    {q:"Vilket år kom Sagan om Ringen del 1?",o:["1999","2001","2003","2005"],a:1,d:2},
    {q:"Vilket år kom Divergent?",o:["2012","2014","2016","2018"],a:1,d:2},
    {q:"Vilket år kom The Maze Runner?",o:["2012","2014","2016","2018"],a:1,d:2},
    {q:"Vem spelar Albus Dumbledore i HP ursprungligen?",o:["Richard Harris","Michael Gambon","Ian McKellen","Patrick Stewart"],a:0,d:2},
    {q:"Vilket år kom Matilda filmen?",o:["1992","1994","1996","1998"],a:2,d:2},
    {q:"Vem spelar i Jumanji 1995?",o:["Tom Hanks","Robin Williams","Jim Carrey","Steve Martin"],a:1,d:2},
    {q:"Vilket år kom Shrek?",o:["1999","2001","2003","2005"],a:1,d:2},
    {q:"Vad heter häxan i Roald Dahls Häxorna 1990?",o:["Anjelica Huston","Meryl Streep","Glenn Close","Sigourney Weaver"],a:0,d:2},
    {q:"Vilket år kom Stand by Me?",o:["1984","1986","1988","1990"],a:1,d:2},
    {q:"Vem skriver böckerna om Harry Potter?",o:["Roald Dahl","J.R.R. Tolkien","J.K. Rowling","C.S. Lewis"],a:2,d:3},
    {q:"Vilket år kom Goonies?",o:["1983","1985","1987","1989"],a:1,d:3},
    {q:"Vilket år kom Beetlejuice?",o:["1986","1988","1990","1992"],a:1,d:3},
    {q:"Vem regisserade Beetlejuice?",o:["John Hughes","Tim Burton","Joe Dante","Chris Columbus"],a:1,d:3},
    {q:"Vem regisserade E.T.?",o:["George Lucas","Steven Spielberg","Robert Zemeckis","Ron Howard"],a:1,d:3},
    {q:"Vilket år kom Karate Kid originalet?",o:["1982","1984","1986","1988"],a:1,d:3},
  ],

  "⚽ Fotboll": [
    {q:"Vilket lag spelar hemma på Anfield?",o:["Arsenal","Everton","Liverpool","Manchester City"],a:2,d:1},
    {q:"Vilket lag spelar hemma på Santiago Bernabeu?",o:["Atletico Madrid","Real Madrid","Sevilla","Valencia"],a:1,d:1},
    {q:"Vilket år kom Zlatan till PSG?",o:["2010","2012","2014","2016"],a:1,d:1},
    {q:"Vem vann Ballon d'Or 2022?",o:["Erling Haaland","Kylian Mbappe","Karim Benzema","Vinicius Jr."],a:2,d:1},
    {q:"Vilket land vann EM 2021?",o:["Frankrike","England","Portugal","Italien"],a:3,d:1},
    {q:"Vilket lag spelar hemma på Emirates Stadium?",o:["Arsenal","Chelsea","Tottenham","West Ham"],a:0,d:1},
    {q:"Vad heter Zlatans moderklubb?",o:["Malmo FF","IFK Goteborg","AIK","Djurgarden"],a:0,d:1},
    {q:"Vilket lag vann Champions League 2024?",o:["Liverpool","PSG","Bayern Munchen","Real Madrid"],a:3,d:1},
    {q:"Vilket land vann damernas VM 2023?",o:["USA","Australien","England","Spanien"],a:3,d:1},
    {q:"Vem vann Ballon d'Or 2023?",o:["Erling Haaland","Kylian Mbappe","Lionel Messi","Vinicius Jr."],a:2,d:1},
    {q:"Hur manga VM har Brasilien vunnit?",o:["3","4","5","6"],a:2,d:1},
    {q:"Vilket lag vann Champions League flest ganger?",o:["Barcelona","Bayern Munchen","Real Madrid","AC Milan"],a:2,d:1},
    {q:"Vilket ar vann Sverige VM-brons?",o:["1950","1958","1966","1974"],a:1,d:2},
    {q:"Vilket ar grundades Premier League?",o:["1988","1990","1992","1994"],a:2,d:2},
    {q:"Vilket ar introducerades VAR i fotbolls-VM?",o:["2014","2016","2018","2020"],a:2,d:2},
    {q:"Hur manga VM-titlar har Frankrike?",o:["1","2","3","4"],a:1,d:2},
    {q:"Vilket ar vann Frankrike sitt andra VM?",o:["2014","2016","2018","2020"],a:2,d:2},
    {q:"Vilket land har flest VM-titlar for damer?",o:["Brasilien","Sverige","USA","Australien"],a:2,d:2},
    {q:"Vilket ar kom VAR till Premier League?",o:["2017","2019","2021","2023"],a:1,d:2},
    {q:"Vilket lag vann Champions League 2022?",o:["Colorado Avalanche","Bayern Munchen","Chelsea","Real Madrid"],a:3,d:2},
    {q:"Vilket lag vann Champions League 2019?",o:["Barcelona","Juventus","Liverpool","PSG"],a:2,d:2},
    {q:"Vem satte rekord for flest mal i Premier League en sasong?",o:["Wayne Rooney","Thierry Henry","Alan Shearer","Mohamed Salah"],a:3,d:2},
    {q:"Vilket ar spelade Sverige sin forsta VM-match?",o:["1930","1934","1938","1950"],a:1,d:3},
    {q:"Vilket ar vann Grekland EM?",o:["2000","2002","2004","2006"],a:2,d:3},
    {q:"Vilket ar grundades FIFA?",o:["1900","1904","1908","1912"],a:1,d:3},
    {q:"Vad heter rekordet for flest mal i ett VM?",o:["Just Fontaine 1958","Pele 1970","Gerd Muller 1970","Ronaldo 2002"],a:0,d:3},
    {q:"Vilket ar kom offside-regeln i fotboll?",o:["1863","1878","1896","1925"],a:3,d:3},
    {q:"Vilket lag vann Champions League 2012?",o:["Barcelona","Bayern Munchen","Chelsea","Real Madrid"],a:2,d:3},
  ],

  "🏒 Ishockey": [
    {q:"Vad kallas Wayne Gretzky?",o:["The Boss","The Great One","The Rocket","Mr. Hockey"],a:1,d:1},
    {q:"Vilket lag vann Stanley Cup 2024?",o:["Colorado Avalanche","Florida Panthers","Edmonton Oilers","Rangers"],a:1,d:1},
    {q:"Vilket lag spelar i Gavle i SHL?",o:["Brynas IF","Frolunda","Djurgardens IF","HV71"],a:0,d:1},
    {q:"Vilket lag spelar i Jonkoping i SHL?",o:["Brynas IF","Frolunda","Djurgardens IF","HV71"],a:3,d:1},
    {q:"Hur manga perioder spelas i ishockey?",o:["2","3","4","5"],a:1,d:1},
    {q:"Vilket land har vunnit flest VM i ishockey?",o:["Sverige","Finland","Kanada","Sovjet/Ryssland"],a:2,d:1},
    {q:"Vad heter NHL:s mastarskapstrofe?",o:["Presidents Trophy","Hart Trophy","Stanley Cup","Conn Smythe"],a:2,d:1},
    {q:"Vilket ar grundades NHL?",o:["1910","1917","1924","1930"],a:1,d:1},
    {q:"Vem haller rekord for flest NHL-poang?",o:["Mario Lemieux","Mark Messier","Wayne Gretzky","Gordie Howe"],a:2,d:1},
    {q:"Vilket lag spelar hemma pa Scandinavium?",o:["Brynas IF","Frolunda","Djurgardens IF","MODO"],a:1,d:1},
    {q:"Hur manga lag finns i NHL?",o:["28","30","32","34"],a:2,d:1},
    {q:"Vilket ar vann Sverige OS-guld i ishockey?",o:["1994","2002","2006","2018"],a:0,d:1},
    {q:"Vilket lag vann Stanley Cup 2021?",o:["Colorado Avalanche","Tampa Bay Lightning","Vegas Golden Knights","Montreal"],a:1,d:2},
    {q:"Vilket lag vann Stanley Cup 2022?",o:["Colorado Avalanche","Tampa Bay Lightning","Vegas Golden Knights","Florida Panthers"],a:0,d:2},
    {q:"Vilket ar kom Peter Forsberg till NHL?",o:["1993","1995","1997","1999"],a:1,d:2},
    {q:"Vad heter trofeen for baste malvakt i NHL?",o:["Vezina Trophy","Hart Trophy","Norris Trophy","Calder Trophy"],a:0,d:2},
    {q:"Hur lang ar en ishockeyplan?",o:["Ca 50 m","Ca 60 m","Ca 70 m","Ca 80 m"],a:1,d:2},
    {q:"Vilket land vann damernas OS i ishockey 2022?",o:["Sverige","USA","Kanada","Finland"],a:1,d:2},
    {q:"Vilket ar vann Sverige VM i ishockey senast?",o:["2016","2017","2018","2019"],a:1,d:2},
    {q:"Vilket ar grundades Djurgardens IF hockey?",o:["1912","1921","1930","1945"],a:1,d:2},
    {q:"Vilket ar kom Nicklas Backstrom till NHL?",o:["2005","2007","2009","2011"],a:1,d:2},
    {q:"Vilket ar kom William Nylander till NHL?",o:["2014","2016","2018","2020"],a:1,d:2},
    {q:"Vem scores mest poang i NHL-historia en sasong?",o:["Mario Lemieux","Brett Hull","Wayne Gretzky 215p","Jari Kurri"],a:2,d:3},
    {q:"Vad heter trofeen for baste rookie i NHL?",o:["Vezina Trophy","Hart Trophy","Norris Trophy","Calder Trophy"],a:3,d:3},
    {q:"Vilket ar grundades Brynas IF?",o:["1908","1920","1930","1940"],a:2,d:3},
    {q:"Vad heter trofeen for mest poang i NHL-sasong?",o:["Vezina Trophy","Hart Trophy","Art Ross Trophy","Maurice Richard Trophy"],a:2,d:3},
    {q:"Vad heter trofeen for MVP i NHL playoffs?",o:["Vezina Trophy","Hart Trophy","Conn Smythe Trophy","Norris Trophy"],a:2,d:3},
    {q:"Vilket ar kom Viktor Hedman till NHL?",o:["2007","2009","2011","2013"],a:1,d:3},
  ],

  "🏅 Sport (allmänt)": [
    {q:"Vilket ar holls OS i Stockholm?",o:["1908","1912","1920","1924"],a:1,d:1},
    {q:"Hur langt ar ett marathonlopp?",o:["40 km","42.195 km","45 km","50 km"],a:1,d:1},
    {q:"Vilket land har vunnit flest OS-guld totalt?",o:["Ryssland","Kina","USA","Tyskland"],a:2,d:1},
    {q:"I vilken sport tavlar man i Tour de France?",o:["Triathlon","Lopning","Cykling","Simning"],a:2,d:1},
    {q:"Vilken sport spelas i Wimbledon?",o:["Badminton","Squash","Tennis","Padel"],a:2,d:1},
    {q:"Vem satte 100m-rekordet pa 9.58 sek?",o:["Carl Lewis","Maurice Greene","Usain Bolt","Justin Gatlin"],a:2,d:1},
    {q:"Vem vann Formel 1-VM 2021?",o:["Lewis Hamilton","Max Verstappen","Valtteri Bottas","Sebastian Vettel"],a:1,d:1},
    {q:"Hur manga Grand Slam finns det i tennis?",o:["2","3","4","5"],a:2,d:1},
    {q:"Vilket ar spelades moderna OS forsta gangen?",o:["1894","1896","1900","1904"],a:1,d:1},
    {q:"I vilken sport tavlar man om yellow jersey?",o:["Cykling","Triathlon","Lopning","Simning"],a:0,d:1},
    {q:"Vem vann Wimbledon damer 2023?",o:["Iga Swiatek","Coco Gauff","Marketa Vondrousova","Aryna Sabalenka"],a:2,d:1},
    {q:"Vilket ar holls OS i Rio de Janeiro?",o:["2012","2014","2016","2018"],a:2,d:1},
    {q:"Hur manga Grand Slam har Roger Federer vunnit?",o:["18","20","22","24"],a:1,d:2},
    {q:"Vem vann Formel 1-VM flest ganger?",o:["Ayrton Senna","Michael Schumacher","Lewis Hamilton","Sebastian Vettel"],a:1,d:2},
    {q:"Vilket land har flest Tour de France-segrar?",o:["Frankrike","Belgien","Spanien","USA"],a:2,d:2},
    {q:"Vem satte varldrekordet pa maraton 2023?",o:["Eliud Kipchoge","Kenenisa Bekele","Kelvin Kiptum","Geoffrey Kamworor"],a:2,d:2},
    {q:"Vem vann Formel 1-VM 2023?",o:["Lewis Hamilton","Max Verstappen","Charles Leclerc","Sergio Perez"],a:1,d:2},
    {q:"Vem vann Tour de France flest ganger?",o:["Bernard Hinault","Eddy Merckx","Miguel Indurain","Lance Armstrong disqual."],a:1,d:2},
    {q:"Vilket ar holls OS i Munchen dar terrordadet skedde?",o:["1968","1972","1976","1980"],a:1,d:2},
    {q:"Vilken nation har flest OS-guld i simning?",o:["Australien","Kina","Ryssland","USA"],a:3,d:2},
    {q:"Hur manga set spelas i herrtennismatch pa Grand Slam?",o:["3","5","4","2"],a:1,d:2},
    {q:"Vilket ar holls OS i Tokyo?",o:["2018","2020","2021","2022"],a:2,d:2},
    {q:"Vilket ar vann Bjorn Borg sitt sista Wimbledon?",o:["1978","1980","1981","1983"],a:1,d:3},
    {q:"Vilket land har vunnit flest F1-VM konstruktorer?",o:["Ferrari","McLaren","Mercedes","Williams"],a:0,d:3},
    {q:"Vilket ar grundades FIFA?",o:["1900","1904","1908","1912"],a:1,d:3},
    {q:"Vilket ar vann Sverige damernas VM i fotboll?",o:["Sverige har aldrig vunnit","1991","1995","2003"],a:0,d:3},
    {q:"Vem vann Wimbledon herrar 2023?",o:["Novak Djokovic","Carlos Alcaraz","Jannik Sinner","Daniil Medvedev"],a:1,d:3},
    {q:"Vilket ar kom nya F1-regler?",o:["2020","2022","2023","2024"],a:1,d:3},
  ],

  "💻 Teknik & IT": [
    {q:"Vilket ar kom iPhone X?",o:["2015","2017","2019","2021"],a:1,d:1},
    {q:"Vad heter Googles sokmotor-algoritm?",o:["PageRank","SearchRank","WebCrawl","IndexBot"],a:0,d:1},
    {q:"Vilket ar kom YouTube?",o:["2003","2005","2007","2009"],a:1,d:1},
    {q:"Vad heter Apples betaltjanst?",o:["Apple Cash","Apple Wallet","Apple Pay","iPayment"],a:2,d:1},
    {q:"Vilket ar grundades Samsung?",o:["1928","1938","1948","1958"],a:1,d:1},
    {q:"Vilket ar kom WhatsApp?",o:["2007","2009","2011","2013"],a:1,d:1},
    {q:"Vad heter Amazons smarta assistent?",o:["Siri","Cortana","Alexa","Google"],a:2,d:1},
    {q:"Vilket ar grundades Netflix?",o:["1995","1997","1999","2001"],a:1,d:1},
    {q:"Vilket ar kom iPad?",o:["2008","2010","2012","2014"],a:1,d:1},
    {q:"Vilket ar grundades Airbnb?",o:["2006","2008","2010","2012"],a:1,d:1},
    {q:"Vad heter Microsofts virtuell assistent?",o:["Siri","Alexa","Cortana","Bixby"],a:2,d:1},
    {q:"Vilket ar kom Snapchat?",o:["2009","2011","2013","2015"],a:1,d:1},
    {q:"Vilket ar kom Instagram?",o:["2008","2010","2012","2014"],a:1,d:2},
    {q:"Vilket ar kom TikTok globalt?",o:["2014","2016","2018","2020"],a:2,d:2},
    {q:"Vilket ar lanserades ChatGPT?",o:["2020","2021","2022","2023"],a:2,d:2},
    {q:"Vilket ar grundades Uber?",o:["2007","2009","2011","2013"],a:1,d:2},
    {q:"Vem grundade LinkedIn?",o:["Bill Gates","Reid Hoffman","Mark Zuckerberg","Jack Dorsey"],a:1,d:2},
    {q:"Vilket ar grundades OpenAI?",o:["2013","2015","2017","2019"],a:1,d:2},
    {q:"Vem grundade SpaceX?",o:["Jeff Bezos","Richard Branson","Elon Musk","Larry Page"],a:2,d:2},
    {q:"Vilket ar kom Android 1.0?",o:["2006","2008","2010","2012"],a:1,d:2},
    {q:"Vilket ar kom forsta versionen av Windows?",o:["1981","1983","1985","1987"],a:2,d:2},
    {q:"Vilket ar grundades NVIDIA?",o:["1989","1991","1993","1995"],a:2,d:2},
    {q:"Vem uppfann World Wide Web?",o:["Bill Gates","Steve Jobs","Tim Berners-Lee","Vint Cerf"],a:2,d:3},
    {q:"Vilket ar kom forsta versionen av Linux?",o:["1989","1991","1993","1995"],a:1,d:3},
    {q:"Vad heter protokollet bakom internet?",o:["HTTP","TCP/IP","FTP","SMTP"],a:1,d:3},
    {q:"Vilket ar grundades Intel?",o:["1964","1966","1968","1970"],a:2,d:3},
    {q:"Vad heter Alan Turings test for AI?",o:["Turing Test","Intelligence Test","Machine Test","Imitation Game"],a:0,d:3},
    {q:"Vad heter Intels grundare?",o:["Bill Gates","Gordon Moore & Robert Noyce","Andy Grove","Ted Hoff"],a:1,d:3},
  ],

  "🔬 Vetenskap & Natur": [
    {q:"Vilket ar det hardaste naturliga materialet?",o:["Guld","Granit","Diamant","Jarn"],a:2,d:1},
    {q:"Hur manga ben har en insekt?",o:["4","6","8","10"],a:1,d:1},
    {q:"Vad ar den kemiska formeln for vatten?",o:["HO","H2O","H2O2","HO2"],a:1,d:1},
    {q:"Hur manga planeter finns i solsystemet?",o:["7","8","9","10"],a:1,d:1},
    {q:"Vilket ar jordens narmaste stjarna (forutom solen)?",o:["Sirius","Vega","Proxima Centauri","Betelgeuse"],a:2,d:1},
    {q:"Hur manga kromosompar har en manniska?",o:["21","23","25","46"],a:1,d:1},
    {q:"Vilket ar publicerade Darwin Arternas uppkomst?",o:["1849","1859","1869","1879"],a:1,d:1},
    {q:"Vilket grundamne har kemisk symbol Au?",o:["Silver","Aluminium","Guld","Koppar"],a:2,d:1},
    {q:"Vad ar ett ljusar?",o:["Tid ljuset tar till solen","Avstand ljuset fardas pa ett ar","Ljusets hastighet","Antalet fotoner"],a:1,d:1},
    {q:"Vilket grundamne ar flytande vid rumstemperatur?",o:["Brom","Jod","Fosfor","Selen"],a:0,d:1},
    {q:"Vilket grundamne har kemisk symbol Fe?",o:["Fluor","Fosfor","Jarn","Francium"],a:2,d:1},
    {q:"Vad ar DNA?",o:["Proteinkomplex","Ribosomalt RNA","Deoxiribonukleinsyra","Adenosintrifosfat"],a:2,d:1},
    {q:"Vilket ar publicerade Einstein sin relativitetsteori?",o:["1900","1905","1910","1915"],a:1,d:2},
    {q:"Hur lang tid tar ljuset att na jorden fran solen?",o:["Ca 4 minuter","Ca 8 minuter","Ca 16 minuter","Ca 30 minuter"],a:1,d:2},
    {q:"Vilket grundamne har atomnummer 79?",o:["Platina","Silver","Guld","Koppar"],a:2,d:2},
    {q:"Vilket ar sande Voyager 1 ivag?",o:["1973","1975","1977","1979"],a:2,d:2},
    {q:"Vad heter processen da en stjarna exploderar?",o:["Nova","Supernova","Neutronkollaps","Gamma-ray burst"],a:1,d:2},
    {q:"Hur djup ar Marianergraven?",o:["7 km","9 km","11 km","13 km"],a:2,d:2},
    {q:"Vad heter teorin om universums uppkomst?",o:["Steady State","Big Crunch","Big Bang","Inflation"],a:2,d:2},
    {q:"Vad ar kvantfysikens osäkerhetsprincip?",o:["Einsteins princip","Heisenbergs osäkerhetsprincip","Bohrs komplementaritet","Plancks kvantum"],a:1,d:2},
    {q:"Vilket ar togs det forsta svarta halets bild?",o:["2015","2017","2019","2021"],a:2,d:2},
    {q:"Hur manga grundamnen finns i periodiska systemet?",o:["98","108","118","128"],a:2,d:2},
    {q:"Vad ar ett svart hal?",o:["Kollapsad stjarna med oandlig gravitation","Tomrum i rymden","Morklagd nebulosa","En kvasar"],a:0,d:3},
    {q:"Vad heter Schrödingers tankeexperiment?",o:["Schrödingers paradox","Schrödingers katt","Schrödingers box","Kvantparadoxen"],a:1,d:3},
    {q:"Vad heter den svagaste av de fyra naturkrafterna?",o:["Stark karnkraft","Svag karnkraft","Elektromagnetism","Gravitation"],a:3,d:3},
    {q:"Vilket ar fick Curie sitt andra Nobelpris?",o:["1903","1907","1911","1915"],a:2,d:3},
    {q:"Vilket ar beraknade Newton gravitationslagen?",o:["1666 publicerad 1687","1700","1750","1800"],a:0,d:3},
    {q:"Vad ar fotosyntesens formel?",o:["6CO2+6H2O ger C6H12O6+6O2","6O2+6H2O ger C6H12O6+6CO2","CO2+H2O ger CH2O+O2","Annan"],a:0,d:3},
  ],

  "🌍 Geografi & Historia": [
    {q:"Vad ar Frankrikes huvudstad?",o:["Lyon","Marseille","Paris","Bordeaux"],a:2,d:1},
    {q:"Vilket hav ar storst?",o:["Atlantiska","Indiska","Arktiska","Stilla havet"],a:3,d:1},
    {q:"Vilket land ar storst till ytan?",o:["USA","Kanada","Kina","Ryssland"],a:3,d:1},
    {q:"Vad ar Australiens huvudstad?",o:["Sydney","Melbourne","Canberra","Brisbane"],a:2,d:1},
    {q:"Vilket ar foll Berlinmuren?",o:["1987","1989","1991","1993"],a:1,d:1},
    {q:"Vilket land har flest invanare?",o:["Indien","Kina","USA","Indonesien"],a:0,d:1},
    {q:"Vad ar Japans huvudstad?",o:["Osaka","Kyoto","Tokyo","Hiroshima"],a:2,d:1},
    {q:"Vilket ar landade manniskan pa manen?",o:["1967","1969","1971","1973"],a:1,d:1},
    {q:"Vilket land var tidigare kant som Persien?",o:["Irak","Iran","Turkiet","Syrien"],a:1,d:1},
    {q:"Vad ar Kanadas huvudstad?",o:["Toronto","Montreal","Vancouver","Ottawa"],a:3,d:1},
    {q:"Vilket ar borjade andra varldskriget?",o:["1937","1939","1941","1943"],a:1,d:1},
    {q:"Vad heter varldens hogsta berg?",o:["K2","Mont Blanc","Mount Everest","Kilimanjaro"],a:2,d:1},
    {q:"Vilket ar grundades FN?",o:["1943","1945","1947","1949"],a:1,d:2},
    {q:"Vilket land avsaffade apartheid 1994?",o:["Zimbabwe","Kenya","Sydafrika","Nigeria"],a:2,d:2},
    {q:"Vilket ar skedde Franska revolutionen?",o:["1776","1789","1799","1815"],a:1,d:2},
    {q:"Vilken stad var Osmanska rikets huvudstad?",o:["Ankara","Bagdad","Konstantinopel","Kairo"],a:2,d:2},
    {q:"Vilket ar sprack Sovjet upp?",o:["1989","1991","1993","1995"],a:1,d:2},
    {q:"Hur manga lander finns i Afrika?",o:["44","54","64","74"],a:1,d:2},
    {q:"Vilket ar invigdes Eiffeltornet?",o:["1885","1887","1889","1891"],a:2,d:2},
    {q:"Vilket ar grundades EU i Maastricht?",o:["1989","1991","1993","1995"],a:2,d:2},
    {q:"Vilket land var kolonialmakt over Vietnam?",o:["England","Holland","Frankrike","Portugal"],a:2,d:2},
    {q:"Vilket land har flest officiella sprak?",o:["Schweiz","Belgien","Sydafrika","Kanada"],a:2,d:2},
    {q:"Vilket ar grundades Romerska riket?",o:["753 f.Kr.","509 f.Kr.","264 f.Kr.","27 f.Kr."],a:0,d:3},
    {q:"Vilket ar grundades NATO?",o:["1945","1947","1949","1951"],a:2,d:3},
    {q:"Vilket land var forst med kvinnlig rosttratt?",o:["Sverige","USA","Nya Zeeland","Finland"],a:2,d:3},
    {q:"Vilket ar fick Finland sjalvstandighet?",o:["1915","1917","1919","1921"],a:1,d:3},
    {q:"Vilket ar borjade Forsta varldskriget?",o:["1912","1914","1916","1918"],a:1,d:3},
    {q:"Vilket ar slotes Wienkongressen?",o:["1810","1815","1820","1825"],a:1,d:3},
  ],

  "🍕 Mat & Dryck": [
    {q:"Vad ar huvudingrediensen i guacamole?",o:["Tomat","Avokado","Lime","Koriander"],a:1,d:1},
    {q:"Vilket land kommer sushi ifran?",o:["Kina","Korea","Japan","Thailand"],a:2,d:1},
    {q:"Vilket land kommer pizza ifran?",o:["Frankrike","Spanien","Italien","Grekland"],a:2,d:1},
    {q:"Vad ar en cappuccino?",o:["Bara mjolk","Espresso och angad mjolk","Te och mjolk","Kaffe och gradde"],a:1,d:1},
    {q:"Vilket land kommer paella ifran?",o:["Italien","Portugal","Frankrike","Spanien"],a:3,d:1},
    {q:"Vad kallas den japanska ratten med ra fisk?",o:["Sushi","Sashimi","Ramen","Udon"],a:1,d:1},
    {q:"Vilket land producerar mest olivolja?",o:["Italien","Spanien","Grekland","Turkiet"],a:1,d:1},
    {q:"Vad ar hummus gjort av?",o:["Linser","Kikartor","Bonor","Artor"],a:1,d:1},
    {q:"Vilket land kommer kimchi ifran?",o:["Japan","Kina","Korea","Vietnam"],a:2,d:1},
    {q:"Vilket land producerar mest vin?",o:["Frankrike","Spanien","Italien","USA"],a:2,d:1},
    {q:"Vad ar umami?",o:["Sott","Surt","Salt","Den femte grundsmaken"],a:3,d:1},
    {q:"Vilket land ar kant for Moules-frites?",o:["Frankrike","Holland","Belgien","Luxemburg"],a:2,d:1},
    {q:"Vad heter den franska ratten med sniglar?",o:["Foie gras","Bouillabaisse","Escargot","Souffle"],a:2,d:2},
    {q:"Vilket land kommer Pad Thai ifran?",o:["Vietnam","Kina","Thailand","Malaysia"],a:2,d:2},
    {q:"Vilket land kommer Pho ifran?",o:["Kina","Laos","Thailand","Vietnam"],a:3,d:2},
    {q:"Vad heter den spanska kallratten med tomater?",o:["Salmorejo","Gazpacho","Sofrito","Pisto"],a:1,d:2},
    {q:"Vad ar miso gjort av?",o:["Ris","Sojabonor","Sesamfron","Tofu"],a:1,d:2},
    {q:"Vilket land uppfann champagnen?",o:["Spanien","Italien","Frankrike","Belgien"],a:2,d:2},
    {q:"Vilket ar grundades McDonalds?",o:["1940","1948","1955","1960"],a:0,d:2},
    {q:"Vad ar Worcestershiresas gjord av?",o:["Tomat","Ansjovis","Pepparrot","Senap"],a:1,d:2},
    {q:"Vilket ar uppfanns pizza Margherita?",o:["1860","1889","1900","1920"],a:1,d:2},
    {q:"Vilken druvsorta anvands i Champagne?",o:["Chardonnay och Pinot Noir","Merlot och Cabernet","Riesling","Syrah och Grenache"],a:0,d:2},
    {q:"Vad ar en Maillard-reaktion?",o:["Kemisk reaktion vid jasning","Brunningsreaktion vid upphettning","Saltningsprocess","Konserveringsmetod"],a:1,d:3},
    {q:"Vilket land producerar Grand Cru-viner?",o:["Italien","Spanien","Frankrike","Portugal"],a:2,d:3},
    {q:"Vad heter den japanska metoden att skara fisk?",o:["Ikejime","Sashimi","Katsu","Mirin"],a:0,d:3},
    {q:"Vad ar koji i japansk matlagning?",o:["En fisk","En svamp och mogel","En sas","En ris-typ"],a:1,d:3},
    {q:"Vilket ar grundades Michelin-guiden?",o:["1895","1900","1910","1920"],a:1,d:3},
    {q:"Vad heter mexikansk ratten med agave?",o:["Mezcal","Pulque","Tequila","Alla tre ar agavebaserade"],a:3,d:3},
  ],
};

// Merge DB3 into main DB
(function() {
  if (typeof QUESTION_DB === 'undefined') return;
  Object.keys(QUESTION_DB3).forEach(cat => {
    if (QUESTION_DB[cat]) {
      QUESTION_DB[cat] = QUESTION_DB[cat].concat(QUESTION_DB3[cat]);
    } else {
      QUESTION_DB[cat] = QUESTION_DB3[cat];
    }
  });
})();
