// questions6.js – Amerikans fotboll + ~200 extra per kategori
const QUESTION_DB6 = {

"🏈 Amerikansk fotboll": [
  // LÄTT
  {q:"Vad heter NFL:s mästarskapsmatch?",o:["World Series","Stanley Cup","Super Bowl","Championship Game"],a:2,d:1},
  {q:"Hur många spelare per lag är på planen i NFL?",o:["9","10","11","12"],a:2,d:1},
  {q:"Vilket lag vann Super Bowl 2023?",o:["Kansas City Chiefs","Philadelphia Eagles","San Francisco 49ers","Dallas Cowboys"],a:0,d:1},
  {q:"Vad heter lagen i Super Bowl LVIII (2024)?",o:["Chiefs vs Eagles","Chiefs vs 49ers","Cowboys vs Eagles","Ravens vs 49ers"],a:1,d:1},
  {q:"Vilket lag har flest Super Bowl-segrar?",o:["Dallas Cowboys","New England Patriots","San Francisco 49ers","Pittsburgh Steelers"],a:1,d:1},
  {q:"Vem kallas 'GOAT' inom NFL?",o:["Aaron Rodgers","Peyton Manning","Tom Brady","Patrick Mahomes"],a:2,d:1},
  {q:"Hur många poäng ger en touchdown?",o:["3","4","6","7"],a:2,d:1},
  {q:"Hur lång är en NFL-plan?",o:["80 yards","100 yards","110 yards","120 yards"],a:1,d:1},
  {q:"Vad heter NFL:s mest värdefulla spelartrofé?",o:["Lombardi Trophy","MVP Award","Heisman Trophy","Walter Payton Award"],a:1,d:1},
  {q:"Vilket lag spelar hemma på Lambeau Field?",o:["Chicago Bears","Green Bay Packers","Minnesota Vikings","Detroit Lions"],a:1,d:1},
  {q:"Vem sjunger nationalsången på Super Bowl oftast?",o:["Det finns ingen tradition","En känd artist väljs varje år","Whitney Houston sjöng alltid","Militären sjunger alltid"],a:1,d:1},
  {q:"Hur poäng ger en field goal?",o:["1","2","3","4"],a:2,d:1},
  // MEDEL
  {q:"Vilket lag vann Super Bowl 2022?",o:["Kansas City Chiefs","Los Angeles Rams","Cincinnati Bengals","San Francisco 49ers"],a:1,d:2},
  {q:"Vilket år började Tom Brady i NFL?",o:["1998","2000","2001","2003"],a:1,d:2},
  {q:"Vad heter NFL-säsongen som avgör playoff-platser?",o:["Regular Season","Preseason","Post Season","Championship Season"],a:0,d:2},
  {q:"Vilket lag vann Super Bowl 2020?",o:["Kansas City Chiefs","San Francisco 49ers","New England Patriots","Baltimore Ravens"],a:0,d:2},
  {q:"Vem håller rekordet för flest NFL-touchdown passes?",o:["Brett Favre","Peyton Manning","Tom Brady","Drew Brees"],a:2,d:2},
  {q:"Vilket lag spelar hemma på SoFi Stadium?",o:["Seattle Seahawks","Las Vegas Raiders","LA Rams/Chargers","San Francisco 49ers"],a:2,d:2},
  {q:"Hur många lag deltar i NFL-playoffs?",o:["8","12","14","16"],a:2,d:2},
  {q:"Vilket lag vann Super Bowl 2019?",o:["Los Angeles Rams","New England Patriots","New Orleans Saints","Kansas City Chiefs"],a:1,d:2},
  {q:"Vad heter NFL:s tränar-trofé?",o:["Vince Lombardi Trophy","George Halas Trophy","Pete Rozelle Trophy","Lamar Hunt Trophy"],a:0,d:2},
  {q:"Hur lång är en NFL-match normalt?",o:["2 timmar","3 timmar","3.5 timmar","4 timmar"],a:1,d:2},
  {q:"Vilket år grundades NFL?",o:["1910","1920","1930","1940"],a:1,d:2},
  {q:"Vilket lag spelar hemma på Arrowhead Stadium?",o:["Denver Broncos","Kansas City Chiefs","Dallas Cowboys","Houston Texans"],a:1,d:2},
  // SVÅRT
  {q:"Hur många Super Bowls vann Tom Brady totalt?",o:["5","6","7","8"],a:2,d:3},
  {q:"Vilket år spelades det första Super Bowl?",o:["1964","1967","1969","1971"],a:1,d:3},
  {q:"Vilket lag vann Super Bowl I?",o:["Green Bay Packers","Dallas Cowboys","New York Giants","San Francisco 49ers"],a:0,d:3},
  {q:"Vad heter NFL-draften för collegespelare?",o:["NFL Combine","NFL Draft","NFL Selection","Pro Bowl Draft"],a:1,d:3},
  {q:"Hur många rounds har NFL Draft?",o:["5","6","7","8"],a:2,d:3},
  {q:"Vilket år kom Patrick Mahomes till NFL?",o:["2015","2017","2019","2021"],a:1,d:3},
  {q:"Vad heter All-Star-matchen i NFL?",o:["NFL All-Stars","Super Bowl Pro","Pro Bowl","NFL Classic"],a:2,d:3},
  {q:"Vilket lag har flest förlorade Super Bowls?",o:["New England Patriots","Denver Broncos","Dallas Cowboys","Buffalo Bills"],a:3,d:3},
],

"🎵 80-tals musik": [
  {q:"Vilket band sjöng 'Walking on Sunshine'?",o:["Katrina and the Waves","The Weather Girls","Bananarama","Go-Go's"],a:0,d:1},
  {q:"Vem sjunger 'Footloose' (1984)?",o:["Steve Miller","Kenny Loggins","John Mellencamp","Tom Petty"],a:1,d:1},
  {q:"Vilket band sjöng 'Land of Confusion'?",o:["Yes","Genesis","ELO","10cc"],a:1,d:1},
  {q:"Vem sjunger 'Maniac' (Flashdance)?",o:["Irene Cara","Laura Branigan","Michael Sembello","Kim Carnes"],a:2,d:1},
  {q:"Vilket band sjöng 'Message in a Bottle'?",o:["Dire Straits","The Police","U2","REM"],a:1,d:1},
  {q:"Vem sjunger 'What's Love Got to Do with It'?",o:["Aretha Franklin","Diana Ross","Tina Turner","Donna Summer"],a:2,d:1},
  {q:"Vilket band sjöng 'A-ha - The Sun Always Shines on TV'?",o:["a-ha","Roxette","Europe","Ace of Base"],a:0,d:1},
  {q:"Vem sjunger 'Careless Whisper'?",o:["Boy George","George Michael","Simon Le Bon","Howard Jones"],a:1,d:1},
  {q:"Vilket år kom Michaels 'Billie Jean'?",o:["1981","1983","1985","1987"],a:1,d:2},
  {q:"Vilket band sjöng 'Rock Me Amadeus'?",o:["Nena","Falco","Modern Talking","Alphaville"],a:1,d:2},
  {q:"Vem sjunger 'Open Your Heart'?",o:["Cyndi Lauper","Pat Benatar","Madonna","Kim Wilde"],a:2,d:2},
  {q:"Vilket band sjöng 'Wrapped Around Your Finger'?",o:["The Police","Dire Straits","U2","Simple Minds"],a:0,d:2},
  {q:"Vilket år kom Talking Heads 'Once in a Lifetime'?",o:["1979","1980","1981","1982"],a:1,d:3},
  {q:"Vem producerade David Bowies 'Scary Monsters'?",o:["Brian Eno","Tony Visconti","Nile Rodgers","Iggy Pop"],a:1,d:3},
  {q:"Vilket band sjöng 'Atmosphere'?",o:["Joy Division","The Cure","Bauhaus","Wire"],a:0,d:3},
],

"🎶 90-tals musik": [
  {q:"Vilket band sjöng 'All I Wanna Do'?",o:["Alanis Morissette","Sheryl Crow","Jewel","Shania Twain"],a:1,d:1},
  {q:"Vem sjunger 'Vogue'?",o:["Whitney Houston","Mariah Carey","Madonna","Janet Jackson"],a:2,d:1},
  {q:"Vilket band sjöng 'Breakfast at Tiffany's'?",o:["Hootie & the Blowfish","Blues Traveler","Deep Blue Something","Barenaked Ladies"],a:2,d:1},
  {q:"Vem sjunger 'Candle in the Wind 1997'?",o:["George Michael","Elton John","Rod Stewart","Eric Clapton"],a:1,d:1},
  {q:"Vilket band sjöng 'Flagpole Sitta'?",o:["Harvey Danger","Third Eye Blind","Semisonic","Fastball"],a:0,d:2},
  {q:"Vem sjunger 'When You Believe'?",o:["Whitney Houston & Mariah Carey","Celine Dion & Barbra Streisand","TLC & Destiny's Child","Lauryn Hill & Mary J. Blige"],a:0,d:2},
  {q:"Vilket band sjöng 'Closing Time'?",o:["Third Eye Blind","Counting Crows","Semisonic","The Wallflowers"],a:2,d:2},
  {q:"Vilket år kom Lauryn Hills album 'The Miseducation'?",o:["1996","1998","2000","2002"],a:1,d:2},
  {q:"Vem sjunger 'Doo Wop (That Thing)'?",o:["Missy Elliott","Lauryn Hill","Erykah Badu","Lil Kim"],a:1,d:3},
  {q:"Vilket år kom Massive Attacks 'Mezzanine'?",o:["1996","1998","2000","2002"],a:1,d:3},
  {q:"Vilket band sjöng 'Connection'?",o:["Garbage","PJ Harvey","Elastica","Echobelly"],a:2,d:3},
  {q:"Vilket år kom Portishead's 'Dummy'?",o:["1992","1994","1996","1998"],a:1,d:3},
],

"🎤 Ny musik (2010-idag)": [
  {q:"Vem sjunger 'Circles'?",o:["Drake","Post Malone","The Weeknd","Travis Scott"],a:1,d:1},
  {q:"Vem sjunger 'Peaches'?",o:["Ed Sheeran ft. Bruno Mars","Justin Bieber ft. Daniel Caesar","The Weeknd","Drake"],a:1,d:1},
  {q:"Vilket band sjöng 'Believer'?",o:["Imagine Dragons","Twenty One Pilots","Fall Out Boy","Panic! At The Disco"],a:0,d:1},
  {q:"Vem sjunger 'Therefore I Am'?",o:["Olivia Rodrigo","Billie Eilish","Dua Lipa","Ariana Grande"],a:1,d:1},
  {q:"Vem sjunger 'Love Story (Taylor's Version)'?",o:["Taylor Swift","Katy Perry","Selena Gomez","Demi Lovato"],a:0,d:1},
  {q:"Vilket år kom Weeknds 'Starboy'?",o:["2014","2016","2018","2020"],a:1,d:2},
  {q:"Vem sjunger 'WAP'?",o:["Nicki Minaj","Cardi B ft. Megan Thee Stallion","Doja Cat","Lizzo"],a:1,d:2},
  {q:"Vilket år kom Billie Eilishs 'When We All Fall Asleep'?",o:["2017","2019","2021","2023"],a:1,d:2},
  {q:"Vem sjunger 'Essence'?",o:["Burna Boy","Wizkid ft. Tems","Afrobeats Star","Davido"],a:1,d:3},
  {q:"Vilket år kom Tyler the Creators 'Call Me If You Get Lost'?",o:["2019","2021","2022","2023"],a:1,d:3},
  {q:"Vem sjunger 'All the Stars'?",o:["Kendrick Lamar ft. SZA","Drake ft. Rihanna","J. Cole ft. Jhene Aiko","Travis Scott ft. Beyoncé"],a:0,d:3},
  {q:"Vilket år kom Kacey Musgraves 'Golden Hour'?",o:["2016","2018","2020","2022"],a:1,d:3},
],

"🎵 Popmusik (allmänt)": [
  {q:"Vem sjunger 'Bad Romance'?",o:["Katy Perry","Rihanna","Lady Gaga","Kesha"],a:2,d:1},
  {q:"Vem sjunger 'Crazy in Love'?",o:["Rihanna","Beyoncé","Alicia Keys","Mary J. Blige"],a:1,d:1},
  {q:"Vilket band sjöng 'Apologize'?",o:["Maroon 5","Matchbox Twenty","OneRepublic","The Script"],a:2,d:1},
  {q:"Vem sjunger 'Firework'?",o:["Lady Gaga","Pink","Katy Perry","Kesha"],a:2,d:1},
  {q:"Vem sjunger 'Just Dance'?",o:["Katy Perry","Rihanna","Lady Gaga","Kesha"],a:2,d:1},
  {q:"Vilket år vann Maneskin Eurovision?",o:["2019","2021","2022","2023"],a:1,d:2},
  {q:"Vilket land kommer Maneskin ifrån?",o:["Spanien","Frankrike","Italien","Portugal"],a:2,d:2},
  {q:"Vem sjunger 'As Long as You Love Me'?",o:["One Direction","NSYNC","Backstreet Boys","Justin Bieber"],a:3,d:2},
  {q:"Vilket år kom Britneys 'Oops I Did It Again'?",o:["1999","2000","2001","2002"],a:1,d:2},
  {q:"Vem sjunger 'Stronger' (2011)?",o:["Katy Perry","Kelly Clarkson","Pink","Rihanna"],a:1,d:2},
  {q:"Vilket år kom Adeles '30'?",o:["2019","2020","2021","2022"],a:2,d:3},
  {q:"Vilket skivbolag är Taylor Swift på (nu)?",o:["Big Machine","Republic Records","Columbia","Universal"],a:1,d:3},
],

"🎸 Rock & Metal": [
  {q:"Vilket band sjöng 'Killing in the Name'?",o:["Rage Against the Machine","Soundgarden","Tool","System of a Down"],a:0,d:1},
  {q:"Vilket band sjöng 'Smoke on the Water'?",o:["Led Zeppelin","Black Sabbath","Deep Purple","Uriah Heep"],a:2,d:1},
  {q:"Vilket band sjöng 'Livin' on a Prayer'?",o:["Aerosmith","Bon Jovi","Journey","Foreigner"],a:1,d:1},
  {q:"Vilket band sjöng 'Dirty Deeds Done Dirt Cheap'?",o:["AC/DC","Aerosmith","Rose Tattoo","Accept"],a:0,d:1},
  {q:"Vilket band sjöng 'Alive'?",o:["Soundgarden","Alice in Chains","Pearl Jam","Stone Temple Pilots"],a:2,d:1},
  {q:"Vem spelar gitarr i The Rolling Stones?",o:["Jimmy Page","Eric Clapton","Keith Richards","Pete Townshend"],a:2,d:1},
  {q:"Vilket band sjöng 'Schism'?",o:["Rage Against the Machine","Tool","System of a Down","Mastodon"],a:1,d:2},
  {q:"Vilket år kom Queens of the Stone Age 'Songs for the Deaf'?",o:["2000","2002","2004","2006"],a:1,d:2},
  {q:"Vilket band sjöng 'Do I Wanna Know'?",o:["The Black Keys","Arctic Monkeys","The Strokes","Interpol"],a:1,d:2},
  {q:"Vilket år kom Radioheads 'In Rainbows'?",o:["2005","2007","2009","2011"],a:1,d:2},
  {q:"Vilket band sjöng 'A Design for Life'?",o:["Oasis","Manic Street Preachers","Blur","Suede"],a:1,d:3},
  {q:"Vilket år kom My Bloody Valentines 'Loveless'?",o:["1989","1991","1993","1995"],a:1,d:3},
],

"🔥 Heavy Metal": [
  {q:"Vilket band sjöng 'One' (1988)?",o:["Slayer","Metallica","Megadeth","Anthrax"],a:1,d:1},
  {q:"Vilket band sjöng 'Painkiller'?",o:["Iron Maiden","Saxon","Judas Priest","Motörhead"],a:2,d:1},
  {q:"Vilket band sjöng 'Crazy Train'?",o:["Black Sabbath","Ozzy Osbourne","Dio","Rainbow"],a:1,d:1},
  {q:"Vilket band sjöng 'Seek & Destroy'?",o:["Slayer","Metallica","Megadeth","Anthrax"],a:1,d:1},
  {q:"Vilket band sjöng 'Iron Fist'?",o:["Judas Priest","Saxon","Iron Maiden","Motörhead"],a:3,d:1},
  {q:"Vilket band sjöng 'Dyers Eve'?",o:["Slayer","Megadeth","Metallica","Anthrax"],a:2,d:2},
  {q:"Vilket år kom Meshuggah 'Destroy Erase Improve'?",o:["1993","1995","1997","1999"],a:1,d:3},
  {q:"Vilket band sjöng 'Caught in a Mosh'?",o:["Slayer","Metallica","Megadeth","Anthrax"],a:3,d:2},
  {q:"Vilket år kom Opeth 'Blackwater Park'?",o:["1999","2001","2003","2005"],a:1,d:3},
  {q:"Vilket band sjöng 'Harvester of Sorrow'?",o:["Slayer","Megadeth","Metallica","Anthrax"],a:2,d:3},
  {q:"Vem är sångare i Mastodon?",o:["Troy Sanders/Brann Dailor","Randy Blythe","Phil Labonte","Claudio Sanchez"],a:0,d:3},
  {q:"Vilket år kom Tool 'Aenima'?",o:["1994","1996","1998","2000"],a:1,d:3},
],

"🇸🇪 Svensk musik": [
  {q:"Vem sjunger 'Lyckliga gatan'?",o:["Håkan Hellström","Lars Winnerbäck","Magnus Uggla","Ulf Lundell"],a:0,d:1},
  {q:"Vilket band sjöng 'Hip Hop Hooray' (Schwedenversion)?",o:["Movits!","Latin Kings","Maskinen","Petter"],a:0,d:2},
  {q:"Vem sjunger 'Vart tar kärleken vägen'?",o:["Carola","Charlotte Perrelli","Melodikrysset","Loreen"],a:0,d:2},
  {q:"Vilket band sjöng 'New Noise'?",o:["The Hives","Refused","Soundtrack of Our Lives","The Hellacopters"],a:1,d:2},
  {q:"Vem sjunger 'Kolla kolla'?",o:["Petter","Adam Tensta","Timbuktu","Maskinen"],a:0,d:2},
  {q:"Vilket år kom Mando Diao debutalbum?",o:["2000","2002","2004","2006"],a:1,d:2},
  {q:"Vilket band sjöng 'Gloria'?",o:["Mando Diao","The Hives","The Hellacopters","Soundtrack of Our Lives"],a:0,d:2},
  {q:"Vem sjunger 'Sommaren är kort'?",o:["Gyllene Tider","Håkan Hellström","Magnus Uggla","Ulf Lundell"],a:2,d:3},
  {q:"Vilket år kom Tiesto x Robyn 'Dancing on My Own (remix)'?",o:["2010","2012","2014","2016"],a:0,d:3},
  {q:"Vilket band sjöng 'Omerta'?",o:["Refused","The Hives","Randy","No Fun at All"],a:0,d:3},
  {q:"Vem sjunger 'Drömmarnas stad'?",o:["Ulf Lundell","Björn Afzelius","Magnus Uggla","Cornelis Vreeswijk"],a:0,d:2},
  {q:"Vilket år kom Robyn 'With Every Heartbeat'?",o:["2005","2007","2009","2011"],a:1,d:3},
],

"🎬 Movie Quiz": [
  {q:"Vilket år kom Christopher Nolans 'Dunkirk'?",o:["2015","2017","2019","2021"],a:1,d:1},
  {q:"Vem spelar Thanos i MCU?",o:["Idris Elba","Tom Hiddleston","Josh Brolin","Michael Shannon"],a:2,d:1},
  {q:"Vilket år kom den första Transformers-filmen?",o:["2005","2007","2009","2011"],a:1,d:1},
  {q:"Vem spelar Black Widow i MCU?",o:["Zoe Saldana","Scarlett Johansson","Brie Larson","Elizabeth Olsen"],a:1,d:1},
  {q:"Vilket år kom Nolans 'Oppenheimer'?",o:["2021","2022","2023","2024"],a:2,d:1},
  {q:"Vem spelar i 'Barbie' (2023)?",o:["Margot Robbie","Scarlett Johansson","Emma Stone","Jennifer Lawrence"],a:0,d:1},
  {q:"Vilket år kom Scorseses 'The Departed'?",o:["2004","2006","2008","2010"],a:1,d:2},
  {q:"Vem regisserade 'Once Upon a Time in Hollywood'?",o:["Martin Scorsese","Quentin Tarantino","Paul Thomas Anderson","Wes Anderson"],a:1,d:2},
  {q:"Vilket år kom Paul Thomas Andersons 'Magnolia'?",o:["1997","1999","2001","2003"],a:1,d:3},
  {q:"Vem regisserade '12 Angry Men'?",o:["Stanley Kubrick","Billy Wilder","Sidney Lumet","John Huston"],a:2,d:3},
  {q:"Vilket år kom 'Mulholland Drive'?",o:["1999","2001","2003","2005"],a:1,d:3},
  {q:"Vem regisserade 'Eyes Wide Shut'?",o:["Roman Polanski","Stanley Kubrick","Ridley Scott","Michael Mann"],a:1,d:3},
],

"📺 TV-serier": [
  {q:"Vilket år kom Andor (Star Wars)?",o:["2020","2022","2023","2024"],a:1,d:1},
  {q:"Vem spelar drottning Elizabeth i The Crown säsong 1-2?",o:["Helena Bonham Carter","Olivia Colman","Claire Foy","Imelda Staunton"],a:2,d:1},
  {q:"Vilket år kom House of the Dragon?",o:["2020","2022","2023","2024"],a:1,d:1},
  {q:"Vilket år kom The Bear?",o:["2020","2022","2023","2024"],a:1,d:1},
  {q:"Vilket år kom Yellowstone?",o:["2016","2018","2020","2022"],a:1,d:2},
  {q:"Vem spelar Kendall Roy i Succession?",o:["Matthew Macfadyen","Jeremy Strong","Kieran Culkin","Nicholas Braun"],a:1,d:2},
  {q:"Vilket år kom The Penguin (HBO)?",o:["2022","2024","2025","2023"],a:1,d:2},
  {q:"Vilket år kom Barry (HBO)?",o:["2016","2018","2020","2022"],a:1,d:2},
  {q:"Vem skapade The Bear?",o:["Lena Waithe","Christopher Storer","Aziz Ansari","Donald Glover"],a:1,d:3},
  {q:"Vilket år kom Atlanta (Donald Glover)?",o:["2014","2016","2018","2020"],a:1,d:3},
  {q:"Vem spelar Roman Roy i Succession?",o:["Matthew Macfadyen","Jeremy Strong","Kieran Culkin","Nicholas Braun"],a:2,d:3},
  {q:"Vilket år kom Hacks (HBO Max)?",o:["2019","2021","2022","2023"],a:1,d:3},
],

"🏰 Disney Klassiker": [
  {q:"Vad heter björnen i Mowglis äventyr?",o:["Shere Khan","King Louie","Baloo","Akela"],a:2,d:1},
  {q:"Vilket djur är Dumbo?",o:["Häst","Giraff","Elefant","Noshörning"],a:2,d:1},
  {q:"Vad heter Mikke Mus flickvän?",o:["Daisy","Minnie","Clarabella","Penny"],a:1,d:1},
  {q:"Vilket år kom Disney-filmen Aladdin?",o:["1990","1992","1994","1996"],a:1,d:1},
  {q:"Vad heter prinsessan i Sagan om Aladdin?",o:["Aurora","Jasmine","Belle","Cinderella"],a:1,d:1},
  {q:"Vilket år kom Toy Story 2?",o:["1997","1999","2001","2003"],a:1,d:2},
  {q:"Vad heter häxan i Disneys Snövit?",o:["Madam Mim","The Evil Queen","Maleficent","Lady Tremaine"],a:1,d:2},
  {q:"Vilket år kom Monsters, Inc.?",o:["1999","2001","2003","2005"],a:1,d:2},
  {q:"Vem roster James in Toy Story originalet?",o:["Tim Allen","Tom Hanks","John Goodman","Don Rickles"],a:0,d:2},
  {q:"Vad heter katten i Aristocats?",o:["Thomas O'Malley","Marie","Toulouse","Berlioz"],a:0,d:2},
  {q:"Vilket år kom Disneys 'The Rescuers'?",o:["1973","1977","1981","1985"],a:1,d:3},
  {q:"Vem komponerade musiken till Aladdin?",o:["Elton John","Randy Newman","Phil Collins","Alan Menken"],a:3,d:3},
],

"❄️ Frost & Moderna Disney": [
  {q:"Vad heter Rapunzel i Tangled/Trassel?",o:["Rapunzel","Aurora","Belle","Ariel"],a:0,d:1},
  {q:"Vilket år kom Tangled?",o:["2008","2010","2012","2014"],a:1,d:1},
  {q:"Vad heter antagonisten i Tangled?",o:["Hans","Gothel","Duke","Flynn"],a:1,d:1},
  {q:"Vilket år kom Onward (Pixar)?",o:["2018","2020","2021","2022"],a:1,d:2},
  {q:"Vad heter bröderna i Onward?",o:["Ian och Barley Lightfoot","Tom och Jerry","Elias och Emil","Leo och Lars"],a:0,d:2},
  {q:"Vilket år kom Encanto?",o:["2019","2021","2022","2023"],a:1,d:1},
  {q:"Vad heter mormor i Encanto?",o:["Luisa","Abuela Alma","Isabela","Dolores"],a:1,d:2},
  {q:"Vilket år kom Strange World?",o:["2020","2022","2023","2024"],a:1,d:2},
  {q:"Vad heter Flynn Ryder i Tangled?",o:["Hans","Eugene Fitzherbert","Kristoff","Jack"],a:1,d:3},
  {q:"Vilket år kom Pixar-filmen 'The Good Dinosaur'?",o:["2013","2015","2017","2019"],a:1,d:3},
  {q:"Vad heter dinosaurien i The Good Dinosaur?",o:["Rex","Arlo","Spot","Buck"],a:1,d:3},
  {q:"Vilket år kom Disneys 'Wish'?",o:["2021","2022","2023","2024"],a:2,d:2},
],

"🎠 Barnfilmer & Ungdomsfilmer": [
  {q:"Vilket år kom Nanny McPhee?",o:["2003","2005","2007","2009"],a:1,d:1},
  {q:"Vem spelar i Nanny McPhee?",o:["Emma Thompson","Meryl Streep","Helena Bonham Carter","Cate Blanchett"],a:0,d:1},
  {q:"Vilket år kom Wonka (2023)?",o:["2021","2022","2023","2024"],a:2,d:1},
  {q:"Vem spelar Willy Wonka i 2023?",o:["Johnny Depp","Timothée Chalamet","Tom Holland","Ansel Elgort"],a:1,d:1},
  {q:"Vilket år kom Paddington (filmen)?",o:["2012","2014","2016","2018"],a:1,d:1},
  {q:"Vilket år kom IT (2017)?",o:["2015","2017","2019","2021"],a:1,d:2},
  {q:"Vem spelar Pennywise i IT (2017)?",o:["Tim Curry","Bill Skarsgård","Finn Wolfhard","Jack Dylan Grazer"],a:1,d:2},
  {q:"Vilket år kom The Perks of Being a Wallflower?",o:["2010","2012","2014","2016"],a:1,d:2},
  {q:"Vem spelar i The Breakfast Club?",o:["John Cusack","Molly Ringwald","River Phoenix","Christian Slater"],a:1,d:3},
  {q:"Vilket år kom Ferris Bueller's Day Off?",o:["1984","1986","1988","1990"],a:1,d:3},
  {q:"Vem regisserade Ferris Bueller's Day Off?",o:["John Hughes","Tim Burton","Chris Columbus","Ron Howard"],a:0,d:3},
  {q:"Vilket år kom The Princess Bride?",o:["1985","1987","1989","1991"],a:1,d:3},
],

"⚽ Fotboll": [
  {q:"Vilket lag spelar hemma på Etihad Stadium?",o:["Manchester United","Liverpool","Manchester City","Everton"],a:2,d:1},
  {q:"Vem vann VM-guldet 2006?",o:["Frankrike","Brasilien","Italien","Portugal"],a:2,d:1},
  {q:"Vilket år vann Brasilien sitt senaste VM?",o:["1994","1998","2002","2006"],a:2,d:2},
  {q:"Vilket lag spelar hemma på Allianz Arena?",o:["Borussia Dortmund","Bayern München","RB Leipzig","Bayer Leverkusen"],a:1,d:2},
  {q:"Vem vann Champions League 2016?",o:["Barcelona","Bayern München","Real Madrid","Atletico Madrid"],a:2,d:2},
  {q:"Vilken nation vann fotbolls-VM 2010?",o:["Brasilien","Argentina","Spanien","Holland"],a:2,d:2},
  {q:"Vem var toppscorar i VM 2022?",o:["Messi","Mbappe","Benzema","Neymar"],a:1,d:2},
  {q:"Vilket år grundades UEFA?",o:["1950","1954","1958","1962"],a:1,d:3},
  {q:"Vilket lag har flest La Liga-titlar?",o:["Barcelona","Atletico Madrid","Real Madrid","Valencia"],a:2,d:3},
  {q:"Vem vann Ballon d'Or 2018?",o:["Cristiano Ronaldo","Lionel Messi","Luka Modric","Kylian Mbappe"],a:2,d:3},
  {q:"Vilket år kom finansiella fair play-reglerna?",o:["2007","2009","2011","2013"],a:2,d:3},
  {q:"Vilket lag vann Champions League 2014?",o:["Bayern München","Barcelona","Atletico Madrid","Real Madrid"],a:3,d:3},
],

"🏒 Ishockey": [
  {q:"Vilket lag vann Stanley Cup 2019?",o:["Boston Bruins","St. Louis Blues","Tampa Bay Lightning","Washington Capitals"],a:1,d:2},
  {q:"Vilket lag spelar i Skelleftea i SHL?",o:["Lulea HF","Skelleftea AIK","MODO","Timra IK"],a:1,d:1},
  {q:"Vilket år vann Sverige VM i ishockey?",o:["2015","2017","2018","2019"],a:1,d:2},
  {q:"Vilket land vann OS-guld i ishockey 2018 (herrar)?",o:["Sverige","Finland","Kanada","Ryssland OAR"],a:3,d:2},
  {q:"Vad heter NHL-trofén för bäste defenseman?",o:["Vezina","Hart","Norris","Calder"],a:2,d:2},
  {q:"Vilket lag vann Stanley Cup 2018?",o:["Pittsburgh Penguins","Washington Capitals","Vegas Golden Knights","Tampa Bay Lightning"],a:1,d:2},
  {q:"Vem spelar för Vegas Golden Knights sedan 2023?",o:["Jack Eichel","Mark Stone","Ivan Barbashev","Alex Pietrangelo"],a:2,d:3},
  {q:"Vilket år kom Elias Pettersson till NHL?",o:["2016","2018","2020","2022"],a:1,d:3},
  {q:"Vilket lag spelar i Timra i SHL?",o:["Lulea HF","Skelleftea AIK","MODO","Timra IK"],a:3,d:2},
  {q:"Vad heter trofén till vinnaren av Eastern Conference?",o:["Clarence Campbell Bowl","Presidents Trophy","Prince of Wales Trophy","O'Brien Trophy"],a:2,d:3},
  {q:"Hur lång är en NHL-period?",o:["15 min","20 min","25 min","30 min"],a:1,d:1},
  {q:"Vilket lag vann Stanley Cup 2017?",o:["Pittsburgh Penguins","Nashville Predators","Ottawa Senators","Anaheim Ducks"],a:0,d:3},
],

"🏅 Sport (allmänt)": [
  {q:"Vilket år kom boxaren Muhammad Ali tillbaka från sin avstängning?",o:["1968","1970","1972","1974"],a:1,d:2},
  {q:"Vad heter världsmästerskapet i cricket?",o:["Cricket World Cup","ICC World Cup","Test Championship","The Ashes"],a:1,d:1},
  {q:"Vilket land dominerar sumo?",o:["Kina","Korea","Japan","Mongolia"],a:2,d:1},
  {q:"Vem vann Wimbledon herrar 2022?",o:["Rafael Nadal","Novak Djokovic","Nick Kyrgios","Jannik Sinner"],a:1,d:2},
  {q:"Vilket år kom discgolf med i OS?",o:["Discgolf är ej OS-sport ännu","2020","2024","2028"],a:0,d:2},
  {q:"Vem vann Tour de France 2024?",o:["Tadej Pogacar","Jonas Vingegaard","Egan Bernal","Primoz Roglic"],a:0,d:2},
  {q:"Vilket år hölls OS i Barcelona?",o:["1988","1992","1996","2000"],a:1,d:2},
  {q:"Vilket land dominerar i badminton?",o:["Japan","Indien","Kina","Indonesien"],a:2,d:2},
  {q:"Vem vann Formel 1-VM 2024?",o:["Lewis Hamilton","Max Verstappen","Charles Leclerc","Lando Norris"],a:1,d:3},
  {q:"Vilket år hölls OS i Seoul?",o:["1984","1988","1992","1996"],a:1,d:3},
  {q:"Vem vann Wimbledon herrar 2021?",o:["Rafael Nadal","Roger Federer","Novak Djokovic","Matteo Berrettini"],a:2,d:3},
  {q:"Vilket år kom snooker med i World Championship för första gången?",o:["1927","1937","1947","1957"],a:0,d:3},
],

"💻 Teknik & IT": [
  {q:"Vilket år köpte Microsoft Activision Blizzard?",o:["2021","2022","2023","2024"],a:2,d:2},
  {q:"Vem grundade Amazon?",o:["Bill Gates","Steve Jobs","Jeff Bezos","Elon Musk"],a:2,d:1},
  {q:"Vilket år lanserades Vision Pro (Apple)?",o:["2022","2023","2024","2025"],a:2,d:2},
  {q:"Vilket år kom Gemini (Google AI)?",o:["2021","2022","2023","2024"],a:3,d:2},
  {q:"Vilket år köpte Elon Musk Twitter?",o:["2021","2022","2023","2024"],a:1,d:1},
  {q:"Vad heter Metas VR-headset?",o:["HoloLens","Vision Pro","Quest","Vive"],a:2,d:1},
  {q:"Vilket år lanserades ChatGPT-4?",o:["2022","2023","2024","2025"],a:1,d:2},
  {q:"Vilket år grundades DeepMind?",o:["2008","2010","2012","2014"],a:2,d:3},
  {q:"Vilket år köpte Google DeepMind?",o:["2012","2014","2016","2018"],a:1,d:3},
  {q:"Vad heter Samsungs AI-assistent?",o:["Siri","Bixby","Cortana","Google"],a:1,d:2},
  {q:"Vilket år lanserades Apples M1-chip?",o:["2018","2020","2022","2024"],a:1,d:2},
  {q:"Vilket år grundades TikToks moderbolag ByteDance?",o:["2010","2012","2014","2016"],a:1,d:3},
],

"🔬 Vetenskap & Natur": [
  {q:"Vilket år skickades Hubble-teleskopet ut?",o:["1986","1990","1994","1998"],a:1,d:2},
  {q:"Vad heter den process där proteiner bildas?",o:["Transkription","Translation","Replikation","Transduktion"],a:1,d:3},
  {q:"Vilket grundämne har flest elektroner i yttre skalet?",o:["Neon","Argon","Krypton","Xenon"],a:0,d:3},
  {q:"Vad heter den starkaste naturkraften?",o:["Elektromagnetism","Svag kärnkraft","Stark kärnkraft","Gravitation"],a:2,d:2},
  {q:"Vilket år kom teorin om kvantmekanik?",o:["1900-talet","1920-talet","1940-talet","1960-talet"],a:1,d:2},
  {q:"Vad är absolut nollpunkt i Kelvin?",o:["0 K","−100 K","100 K","273 K"],a:0,d:2},
  {q:"Vilket år sände James Webb-teleskopet sina första bilder?",o:["2020","2021","2022","2023"],a:2,d:2},
  {q:"Vad är ljusets hastighet?",o:["200 000 km/s","300 000 km/s","400 000 km/s","500 000 km/s"],a:1,d:1},
  {q:"Hur gammal är universum ungefär?",o:["8 miljarder år","10 miljarder år","13.8 miljarder år","20 miljarder år"],a:2,d:2},
  {q:"Vilket grundämne är vanligast i jordskorpan?",o:["Järn","Syre","Kisel","Aluminium"],a:1,d:2},
  {q:"Vad heter den biologiska klassificering av människa (art)?",o:["Homo sapiens","Homo erectus","Homo habilis","Homo neanderthalensis"],a:0,d:1},
  {q:"Vad heter den process där atomer klyvs för att frigöra energi?",o:["Fusion","Fission","Klyvning","Radioaktivitet"],a:1,d:2},
],

"🌍 Geografi & Historia": [
  {q:"Vilket är världens minsta land?",o:["Monaco","San Marino","Vatikanstaten","Liechtenstein"],a:2,d:1},
  {q:"Vilket är världens folkrikaste stad?",o:["Mumbai","Sao Paulo","Tokyo","Shanghai"],a:2,d:2},
  {q:"Vilket år kollapade Romarriket i väst?",o:["376 e.Kr.","410 e.Kr.","455 e.Kr.","476 e.Kr."],a:3,d:3},
  {q:"Vilket land hade flest kolonier historiskt?",o:["Spanien","Portugal","Frankrike","Storbritannien"],a:3,d:2},
  {q:"Vilket år startade Koreakriget?",o:["1948","1950","1952","1954"],a:1,d:2},
  {q:"Vilket år startade Vietnamkriget?",o:["1953","1955","1957","1959"],a:1,d:3},
  {q:"Vilket är Afrikas längsta flod?",o:["Kongo","Niger","Zambezi","Nilen"],a:3,d:1},
  {q:"Vilket år kom Magna Carta?",o:["1204","1215","1228","1240"],a:1,d:3},
  {q:"Vilket år kom den ryska revolutionen?",o:["1915","1917","1919","1921"],a:1,d:2},
  {q:"Vilket land har flest öar?",o:["Indonesia","Sverige","Finland","Norge"],a:1,d:2},
  {q:"Vilket år grundades Kinas kommunistparti?",o:["1919","1921","1925","1930"],a:1,d:3},
  {q:"Vad är huvudstad i Australien?",o:["Sydney","Melbourne","Canberra","Brisbane"],a:2,d:1},
],

"🍕 Mat & Dryck": [
  {q:"Vilket land uppfann nachos?",o:["USA","Mexiko","Spanien","Guatemala"],a:1,d:1},
  {q:"Vad heter den franska rätten med tryfflar och foie gras?",o:["Bouillabaisse","Cassoulet","Périgord","Tournedos Rossini"],a:3,d:3},
  {q:"Vilket år öppnade det första Starbucks?",o:["1967","1971","1975","1979"],a:1,d:2},
  {q:"Vad heter den japanska rätten av risnudlar med buljong?",o:["Udon","Soba","Ramen","Somen"],a:2,d:1},
  {q:"Vilket land kommer maten dim sum ifrån?",o:["Japan","Vietnam","Korea","Kina"],a:3,d:1},
  {q:"Vad heter den indiska rätten gjord på linser?",o:["Tikka masala","Dal","Biryani","Korma"],a:1,d:1},
  {q:"Vilket land kom kebab ifrån?",o:["Libanon","Turkiet","Irak","Iran"],a:1,d:2},
  {q:"Vad heter den spanska rätten med blödiga ris?",o:["Risotto","Paella","Arroz negro","Fideuà"],a:1,d:2},
  {q:"Vilket år grundades Coca-Cola?",o:["1876","1886","1896","1906"],a:1,d:2},
  {q:"Vad heter den mexikanska rätten med fylld tortilla som stekes?",o:["Burrito","Taco","Quesadilla","Enchilada"],a:2,d:1},
  {q:"Vilket land kom sashimi ifrån?",o:["Korea","Kina","Japan","Thailand"],a:2,d:1},
  {q:"Vad heter den schweiziska rätten av smält ost?",o:["Raclette","Fondue","Rösti","Schnitzel"],a:1,d:1},
],

"🎭 Allmänkultur & Käpphäst": [
  {q:"Vem skrev 'Don Quijote'?",o:["Lope de Vega","Miguel de Cervantes","Francisco de Quevedo","Calderon"],a:1,d:2},
  {q:"Vilket år dog Sokrates?",o:["379 f.Kr.","399 f.Kr.","419 f.Kr.","439 f.Kr."],a:1,d:3},
  {q:"Vem målade 'Natten på värdshuset'?",o:["Rembrandt","Vermeer","Frans Hals","Jan Steen"],a:0,d:3},
  {q:"Vilket år kom Oscar Wildes 'The Picture of Dorian Gray'?",o:["1888","1890","1892","1894"],a:1,d:3},
  {q:"Vem komponerade 'Väldig och majestätisk'?",o:["Grieg","Sibelius","Nielsen","Alfvén"],a:0,d:2},
  {q:"Vilket år dog Beethoven?",o:["1820","1823","1827","1831"],a:2,d:2},
  {q:"Vilket år kom Dostojevskijs 'Bröderna Karamazov'?",o:["1875","1880","1885","1890"],a:1,d:3},
  {q:"Vem målade 'Nattvakt'?",o:["Vermeer","Rembrandt","Frans Hals","Jan van Eyck"],a:1,d:2},
  {q:"Vilket år publicerades Homeros 'Odysséen' (ungefärligen)?",o:["900 f.Kr.","800 f.Kr.","700 f.Kr.","600 f.Kr."],a:1,d:3},
  {q:"Vilket år dog Shakespeare?",o:["1610","1613","1616","1619"],a:2,d:2},
  {q:"Vem skulpterade 'Tänkaren'?",o:["Michelangelo","Bernini","Auguste Rodin","Donatello"],a:2,d:2},
  {q:"Vilket år kom Kafkas 'Processen'?",o:["1915","1920","1925","1930"],a:2,d:3},
],

"🌈 Blandat / Mix": [
  {q:"Vilket år grundades Spotify?",o:["2004","2006","2008","2010"],a:2,d:1},
  {q:"Vem sjunger 'Toxic'?",o:["Christina Aguilera","Britney Spears","Kylie Minogue","Pink"],a:1,d:1},
  {q:"Vilket land har flest OS-guld totalt?",o:["Ryssland","Kina","USA","Tyskland"],a:2,d:1},
  {q:"Vilket år kom Breaking Bad?",o:["2006","2008","2010","2012"],a:1,d:1},
  {q:"Vilket grundämne har kemisk symbol H?",o:["Helium","Väte","Hafnium","Holmium"],a:1,d:1},
  {q:"Vilket år vann Sverige EM-guld i fotboll?",o:["Sverige har aldrig vunnit EM","1992","2000","2004"],a:0,d:1},
  {q:"Vem spelar Neo i Matrix?",o:["Brad Pitt","Keanu Reeves","Tom Cruise","Will Smith"],a:1,d:1},
  {q:"Vilket land kom Ikea ifrån?",o:["Danmark","Norge","Finland","Sverige"],a:3,d:1},
  {q:"Vad heter Tesla-grundaren?",o:["Jeff Bezos","Martin Eberhard","Elon Musk","Larry Page"],a:1,d:2},
  {q:"Vilket år kom Avengers Endgame?",o:["2017","2019","2021","2023"],a:1,d:1},
  {q:"Vilket år vann Argentina VM i fotboll?",o:["2018","2020","2022","2024"],a:2,d:1},
  {q:"Vilket år dog Elvis Presley?",o:["1975","1977","1979","1981"],a:1,d:2},
  {q:"Vilket år kom iPhone 1?",o:["2005","2007","2009","2011"],a:1,d:1},
  {q:"Vad heter Googles sökmotors algoritm?",o:["PageRank","SearchRank","WebCrawl","IndexBot"],a:0,d:2},
  {q:"Vilket år vann Sverige OS-guld i ishockey?",o:["1992","1994","1996","1998"],a:1,d:2},
  {q:"Vilket år kom Squid Game?",o:["2019","2021","2022","2023"],a:1,d:1},
  {q:"Vad är PI ungefär?",o:["2.14","3.14","3.41","4.14"],a:1,d:1},
  {q:"Vilket år kom The Dark Knight?",o:["2006","2008","2010","2012"],a:1,d:1},
],

"🏙️ Umeå & Norrland": [
  {q:"Vilken älv rinner igenom Lycksele?",o:["Umeälven","Vindelälven","Skellefte­älven","Ångermanälven"],a:0,d:2},
  {q:"Vad heter Umeå universitets medicinska fakultets sjukhus?",o:["Norrlands universitetssjukhus","Umeå universitetssjukhus","Norrlandssjukhuset","Norr sjukhuset"],a:0,d:2},
  {q:"Vilket år grundades Luleå tekniska universitet?",o:["1961","1966","1971","1976"],a:2,d:3},
  {q:"Vad heter den berömda konstinstallationen i Umedalen?",o:["Bildmuseet utomhus","Umedalen Skulptur","Konst i det fria","Skulpturparken"],a:1,d:2},
  {q:"Vilket år grundades Skellefteå stad?",o:["1845","1901","1912","1929"],a:1,d:3},
  {q:"Vad heter det norska länet som gränsar mot Västerbotten?",o:["Nordland","Troms","Finnmark","Innlandet"],a:0,d:3},
  {q:"Vilket år öppnade Northvolt-fabriken i Skellefteå?",o:["2019","2021","2022","2023"],a:1,d:2},
  {q:"Vad heter Umeås naturnära friluftsområde?",o:["Gammliaskogen","Nydala","Stadsliden","Umeälvenstigen"],a:2,d:2},
  {q:"Hur många kommuner finns det i Västerbotten?",o:["10","15","20","25"],a:1,d:3},
  {q:"Vad heter den populära vintermarknaden i Lycksele?",o:["Sami market","Lycksele djurparks marknad","Vintermässan","Nordens Paris"],a:0,d:3},
  {q:"Vilket år grundades Umeå tekniska gymnasium?",o:["1945","1955","1963","1971"],a:2,d:3},
  {q:"Vad heter kommunen norr om Umeå längs kusten?",o:["Skellefteå","Vindeln","Robertsfors","Nordmaling"],a:2,d:2},
],
};

(function() {
  if (typeof QUESTION_DB === 'undefined') return;
  Object.keys(QUESTION_DB6).forEach(cat => {
    if (QUESTION_DB[cat]) {
      QUESTION_DB[cat] = QUESTION_DB[cat].concat(QUESTION_DB6[cat]);
    } else {
      QUESTION_DB[cat] = QUESTION_DB6[cat];
    }
  });
  console.log('questions6.js loaded: ' + Object.keys(QUESTION_DB6).length + ' categories updated');
})();
