// questions8.js – ~1400 nya frågor mot målet 120+ per kategori
const QUESTION_DB8 = {

"🎵 80-tals musik": [
  {q:"Vilket band sjöng 'The Power of Love' (1984)?",o:["Frankie Goes to Hollywood","Pet Shop Boys","Erasure","Soft Cell"],a:0,d:1},
  {q:"Vem sjunger 'Time After Time'?",o:["Pat Benatar","Cyndi Lauper","Kim Wilde","Debbie Harry"],a:1,d:1},
  {q:"Vilket band sjöng 'It's Raining Men'?",o:["Bangles","Go-Go's","The Weather Girls","Wilson Phillips"],a:2,d:1},
  {q:"Vem sjunger 'Bette Davis Eyes'?",o:["Pat Benatar","Kim Carnes","Laura Branigan","Stevie Nicks"],a:1,d:1},
  {q:"Vilket band sjöng 'I Love Rock 'n' Roll'?",o:["Joan Jett & the Blackhearts","Pat Benatar","The Runaways","Suzi Quatro"],a:0,d:1},
  {q:"Vem sjunger 'Hungry Eyes' (Dirty Dancing)?",o:["Eric Carmen","Patrick Swayze","Frankie Previte","Kenny Loggins"],a:0,d:1},
  {q:"Vilket band sjöng 'Don't Stand So Close to Me'?",o:["U2","The Police","Dire Straits","Sting"],a:1,d:1},
  {q:"Vem sjunger 'I Wanna Dance with Somebody'?",o:["Cyndi Lauper","Janet Jackson","Whitney Houston","Tina Turner"],a:2,d:1},
  {q:"Vilket band sjöng 'Express Yourself'?",o:["Madonna","Cyndi Lauper","Heart","Pat Benatar"],a:0,d:1},
  {q:"Vem sjunger 'Lucky Star'?",o:["Cyndi Lauper","Debbie Harry","Madonna","Kim Wilde"],a:2,d:1},
  {q:"Vilket band sjöng 'Melt with You'?",o:["The Cure","Modern English","Echo and the Bunnymen","The Psychedelic Furs"],a:1,d:2},
  {q:"Vem sjunger 'Whip It'?",o:["Talking Heads","Devo","B-52s","XTC"],a:1,d:2},
  {q:"Vilket band sjöng 'Temptation' (1982)?",o:["Depeche Mode","New Order","Duran Duran","Heaven 17"],a:1,d:2},
  {q:"Vilket år kom Michael Jacksons 'Off the Wall'?",o:["1977","1979","1981","1983"],a:1,d:2},
  {q:"Vem sjunger 'Obsession'?",o:["Animotion","Berlin","Book of Love","When in Rome"],a:0,d:2},
  {q:"Vilket band sjöng 'Something to Talk About'?",o:["Bonnie Raitt","Stevie Nicks","Emmylou Harris","Linda Ronstadt"],a:0,d:2},
  {q:"Vem sjunger 'I'm Still Standing'?",o:["Rod Stewart","David Bowie","Elton John","Billy Joel"],a:2,d:2},
  {q:"Vilket band sjöng 'White Wedding'?",o:["Siouxsie and the Banshees","Bauhaus","Billy Idol","The Cure"],a:2,d:2},
  {q:"Vilket år kom New Orders debutalbum 'Movement'?",o:["1980","1981","1982","1983"],a:1,d:3},
  {q:"Vem producerade Madonnas debut?",o:["Reggie Lucas och Mark Kamins","Nile Rodgers","Patrick Leonard","Steve Bray"],a:0,d:3},
  {q:"Vilket band sjöng 'Just Like Heaven'?",o:["The Smiths","The Cure","The Psychedelic Furs","Echo and the Bunnymen"],a:1,d:3},
  {q:"Vilket år upplöstes Joy Division?",o:["1979","1980","1981","1982"],a:1,d:3},
  {q:"Vem sjunger 'Two Tribes'?",o:["Pet Shop Boys","Erasure","Frankie Goes to Hollywood","Bronski Beat"],a:2,d:3},
  {q:"Vilket år kom Depeche Modes 'Music for the Masses'?",o:["1985","1987","1989","1991"],a:1,d:3},
],

"🎶 90-tals musik": [
  {q:"Vilket band sjöng 'Common People'?",o:["Blur","Pulp","Oasis","Elastica"],a:1,d:1},
  {q:"Vem sjunger 'Torn' (1997)?",o:["Alanis Morissette","Natalie Imbruglia","Sheryl Crow","Shania Twain"],a:1,d:1},
  {q:"Vilket band sjöng 'What's Up' (1992)?",o:["Alanis Morissette","4 Non Blondes","Sheryl Crow","Melissa Etheridge"],a:1,d:1},
  {q:"Vem sjunger 'Fast Car'?",o:["Tracy Chapman","Bonnie Raitt","Joan Armatrading","Rickie Lee Jones"],a:0,d:1},
  {q:"Vilket band sjöng 'Evenflow'?",o:["Soundgarden","Alice in Chains","Pearl Jam","Stone Temple Pilots"],a:2,d:1},
  {q:"Vem sjunger 'Dreams' (Fleetwood Mac cover, 90-tal)?",o:["Cranberries","Alanis Morissette","Sheryl Crow","The Corrs"],a:0,d:2},
  {q:"Vilket band sjöng 'Three Little Pigs'?",o:["Green Jelly","NOFX","Dead Milkmen","Ween"],a:0,d:2},
  {q:"Vem sjunger 'Stay (I Missed You)'?",o:["Lisa Loeb","Juliana Hatfield","Liz Phair","Belly"],a:0,d:2},
  {q:"Vilket år kom Nirvanas 'MTV Unplugged'?",o:["1993","1994","1995","1996"],a:1,d:2},
  {q:"Vem sjunger 'MMM MMM MMM MMM'?",o:["Barenaked Ladies","Crash Test Dummies","Toad the Wet Sprocket","Gin Blossoms"],a:1,d:2},
  {q:"Vilket band sjöng 'The Freshman'?",o:["Verve Pipe","Toad the Wet Sprocket","Gin Blossoms","Barenaked Ladies"],a:0,d:2},
  {q:"Vilket år kom Weezer's 'Blue Album'?",o:["1992","1994","1996","1998"],a:1,d:2},
  {q:"Vem sjunger 'Strong Enough'?",o:["Alanis Morissette","Sheryl Crow","Jewel","Fiona Apple"],a:1,d:2},
  {q:"Vilket band sjöng 'Mr. Jones'?",o:["Gin Blossoms","Counting Crows","Blues Traveler","Toad the Wet Sprocket"],a:1,d:2},
  {q:"Vilket år kom Beck's 'Odelay'?",o:["1994","1996","1998","2000"],a:1,d:3},
  {q:"Vilket band sjöng 'Daughter'?",o:["Soundgarden","Alice in Chains","Pearl Jam","Stone Temple Pilots"],a:2,d:3},
  {q:"Vem sjunger 'Criminal' (1996)?",o:["Alanis Morissette","Fiona Apple","Liz Phair","PJ Harvey"],a:1,d:3},
  {q:"Vilket år kom Björks 'Post'?",o:["1993","1995","1997","1999"],a:1,d:3},
  {q:"Vilket band sjöng 'Pepper'?",o:["Butthole Surfers","Ween","They Might Be Giants","Primus"],a:0,d:3},
  {q:"Vilket år kom Massive Attack 'Blue Lines'?",o:["1989","1991","1993","1995"],a:1,d:3},
],

"🎤 Ny musik (2010-idag)": [
  {q:"Vem sjunger 'Midnight Rain'?",o:["Olivia Rodrigo","Taylor Swift","Billie Eilish","Sabrina Carpenter"],a:1,d:1},
  {q:"Vilket år kom Harry Styles soloalbum 'Harry's House'?",o:["2018","2020","2022","2024"],a:2,d:1},
  {q:"Vem sjunger 'Unholy' (2022)?",o:["Sam Smith ft Kim Petras","Olly Alexander","Years & Years","Troye Sivan"],a:0,d:1},
  {q:"Vilket band sjöng 'Heat Waves'?",o:["The 1975","Glass Animals","Tame Impala","Jungle"],a:1,d:1},
  {q:"Vem sjunger 'As It Was' (2022)?",o:["Ed Sheeran","Harry Styles","Niall Horan","Louis Tomlinson"],a:1,d:1},
  {q:"Vilket år kom Olivia Rodrigos 'SOUR'?",o:["2019","2020","2021","2022"],a:2,d:1},
  {q:"Vem sjunger 'Cruel Summer'?",o:["Katy Perry","Taylor Swift","Dua Lipa","Ariana Grande"],a:1,d:1},
  {q:"Vilket år kom Adeles 'Hello'?",o:["2013","2015","2017","2019"],a:1,d:1},
  {q:"Vem sjunger 'Lose You to Love Me'?",o:["Ariana Grande","Demi Lovato","Selena Gomez","Miley Cyrus"],a:2,d:1},
  {q:"Vilket år kom Weeknds 'Beauty Behind the Madness'?",o:["2013","2015","2017","2019"],a:1,d:2},
  {q:"Vem sjunger 'drivers license'?",o:["Billie Eilish","Olivia Rodrigo","Sabrina Carpenter","Gracie Abrams"],a:1,d:1},
  {q:"Vilket år kom Taylor Swifts 'Reputation'?",o:["2015","2016","2017","2018"],a:2,d:2},
  {q:"Vem sjunger 'Die for You'?",o:["Drake","The Weeknd","Post Malone","Travis Scott"],a:1,d:2},
  {q:"Vilket år kom Lizzo 'Cuz I Love You'?",o:["2017","2019","2021","2023"],a:1,d:2},
  {q:"Vem sjunger 'Hurricane' (Kanye 2021)?",o:["Kanye West","The Weeknd","Travis Scott","21 Savage"],a:0,d:2},
  {q:"Vilket år kom Lana Del Reys 'Born to Die'?",o:["2010","2012","2014","2016"],a:1,d:2},
  {q:"Vem sjunger 'Positions'?",o:["Cardi B","Doja Cat","Ariana Grande","Nicki Minaj"],a:2,d:2},
  {q:"Vilket år kom Post Malones 'Hollywood's Bleeding'?",o:["2017","2019","2021","2023"],a:1,d:2},
  {q:"Vem sjunger 'Good Days' (2021)?",o:["H.E.R.","SZA","Summer Walker","Jhene Aiko"],a:1,d:3},
  {q:"Vilket år kom Burna Boys 'Twice as Tall'?",o:["2018","2020","2022","2024"],a:1,d:3},
  {q:"Vem producerade Kacey Musgraves 'Golden Hour'?",o:["Daniel Tashian och Ian Fitchuk","Max Martin","Jack Antonoff","Greg Kurstin"],a:0,d:3},
  {q:"Vilket år kom Clairos 'Immunity'?",o:["2017","2019","2021","2023"],a:1,d:3},
],

"🎵 Popmusik (allmänt)": [
  {q:"Vem sjunger 'Satisfaction' (Rolling Stones)?",o:["Paul McCartney","Mick Jagger","Roger Daltrey","Ray Davies"],a:1,d:1},
  {q:"Vilket band sjöng 'Livin' La Vida Loca'?",o:["Marc Anthony","Ricky Martin","Enrique Iglesias","Shakira"],a:1,d:1},
  {q:"Vem sjunger 'Hero' (Mariah Carey)?",o:["Whitney Houston","Mariah Carey","Celine Dion","Beyoncé"],a:1,d:1},
  {q:"Vilket band sjöng 'Shape of My Heart'?",o:["Backstreet Boys","NSYNC","Boyz II Men","New Kids on the Block"],a:0,d:1},
  {q:"Vem sjunger 'Cry Me a River' (Justin Timberlake)?",o:["Justin Bieber","Justin Timberlake","Usher","Ne-Yo"],a:1,d:1},
  {q:"Vilket band sjöng 'Toxic' (Britney Spears)?",o:["Christina Aguilera","Britney Spears","Kylie Minogue","Pink"],a:1,d:1},
  {q:"Vem sjunger 'Irreplaceable'?",o:["Rihanna","Alicia Keys","Beyoncé","Mary J Blige"],a:2,d:1},
  {q:"Vilket år kom Mariah Careys 'All I Want for Christmas'?",o:["1990","1992","1994","1996"],a:1,d:1},
  {q:"Vem sjunger 'Beautiful' (2002)?",o:["Alicia Keys","Nelly Furtado","Christina Aguilera","Beyoncé"],a:2,d:1},
  {q:"Vilket band sjöng 'Milkshake'?",o:["Kelis","Missy Elliott","M.I.A.","Lil Kim"],a:0,d:1},
  {q:"Vem sjunger 'Gold Digger'?",o:["Jay-Z","Kanye West","Ludacris","T.I."],a:1,d:2},
  {q:"Vilket år kom Destiny's Child 'Survivor'?",o:["1999","2001","2003","2005"],a:1,d:2},
  {q:"Vem sjunger 'Waterfalls' (TLC)?",o:["Left Eye","T-Boz","Chilli","Alle tre"],a:3,d:2},
  {q:"Vilket år kom Usher 'Confessions'?",o:["2002","2004","2006","2008"],a:1,d:2},
  {q:"Vem sjunger 'Genie in a Bottle'?",o:["Britney Spears","Christina Aguilera","Jessica Simpson","Mandy Moore"],a:1,d:2},
  {q:"Vilket år kom Amy Winehouse 'Back to Black'?",o:["2004","2006","2008","2010"],a:1,d:2},
  {q:"Vem sjunger 'Crazy' (Gnarls Barkley)?",o:["Cee Lo Green","Bruno Mars","John Legend","Common"],a:0,d:2},
  {q:"Vilket år kom P!nks 'Missundaztood'?",o:["1999","2001","2003","2005"],a:1,d:2},
  {q:"Vem sjunger 'Try' (Pink 2012)?",o:["Kelly Clarkson","Pink","Katy Perry","Kesha"],a:1,d:2},
  {q:"Vilket år debuterade One Direction?",o:["2008","2009","2010","2011"],a:2,d:2},
  {q:"Vem sjunger 'No One' (Alicia Keys)?",o:["Alicia Keys","Beyoncé","Mary J Blige","Rihanna"],a:0,d:2},
  {q:"Vilket år kom Rihannas 'Good Girl Gone Bad'?",o:["2005","2007","2009","2011"],a:1,d:2},
  {q:"Vem sjunger 'My Immortal'?",o:["Paramore","Evanescence","Flyleaf","Within Temptation"],a:1,d:3},
  {q:"Vilket år kom Nelly Furtados 'Loose'?",o:["2004","2006","2008","2010"],a:1,d:3},
  {q:"Vem sjunger 'Rehab' (Amy Winehouse)?",o:["Amy Winehouse","Duffy","Adele","Paloma Faith"],a:0,d:3},
],

"🎸 Rock & Metal": [
  {q:"Vilket band sjöng 'Stairway to Heaven'?",o:["Deep Purple","Black Sabbath","Led Zeppelin","Uriah Heep"],a:2,d:1},
  {q:"Vem sjunger 'Born to Run'?",o:["Tom Petty","Bruce Springsteen","John Mellencamp","Bob Seger"],a:1,d:1},
  {q:"Vilket band sjöng 'Sultans of Swing'?",o:["The Police","Dire Straits","U2","Fleetwood Mac"],a:1,d:1},
  {q:"Vem sjunger 'Piece of My Heart'?",o:["Tina Turner","Janis Joplin","Grace Slick","Aretha Franklin"],a:1,d:1},
  {q:"Vilket band sjöng 'Fortunate Son'?",o:["Creedence Clearwater Revival","The Eagles","Lynyrd Skynyrd","ZZ Top"],a:0,d:1},
  {q:"Vem sjunger 'Layla'?",o:["Jimi Hendrix","Eric Clapton","Jeff Beck","Carlos Santana"],a:1,d:1},
  {q:"Vilket band sjöng 'More Than a Feeling'?",o:["Journey","Foreigner","Boston","REO Speedwagon"],a:2,d:1},
  {q:"Vem sjunger 'Free Bird'?",o:["The Allman Brothers","Lynyrd Skynyrd","ZZ Top","38 Special"],a:1,d:1},
  {q:"Vilket band sjöng 'Dream On'?",o:["Bon Jovi","Aerosmith","Kiss","Twisted Sister"],a:1,d:1},
  {q:"Vem sjunger 'Barracuda'?",o:["Joan Jett","Pat Benatar","Heart","Stevie Nicks"],a:2,d:1},
  {q:"Vilket band sjöng 'It's Only Rock 'n Roll'?",o:["The Who","The Rolling Stones","The Kinks","The Faces"],a:1,d:2},
  {q:"Vem sjunger 'Black Betty'?",o:["CCR","Ram Jam","Bob Seger","Canned Heat"],a:1,d:2},
  {q:"Vilket band sjöng 'Gimme Shelter'?",o:["The Who","Rolling Stones","Led Zeppelin","Jimi Hendrix"],a:1,d:2},
  {q:"Vilket år kom The Clash 'London Calling'?",o:["1977","1979","1981","1983"],a:1,d:2},
  {q:"Vem sjunger 'Won't Get Fooled Again'?",o:["Led Zeppelin","The Who","Deep Purple","Black Sabbath"],a:1,d:2},
  {q:"Vilket band sjöng 'Teen Spirit' – fullständigt albumnamn?",o:["Nevermind","Bleach","In Utero","Insecticide"],a:0,d:2},
  {q:"Vilket år kom The Pixies 'Surfer Rosa'?",o:["1986","1988","1990","1992"],a:1,d:3},
  {q:"Vem spelar trummor i Led Zeppelin?",o:["Keith Moon","Ginger Baker","John Bonham","Ian Paice"],a:2,d:3},
  {q:"Vilket band sjöng 'Love Removal Machine'?",o:["The Cult","Sisters of Mercy","Fields of the Nephilim","Christian Death"],a:0,d:3},
  {q:"Vilket år kom Sonic Youth 'Goo'?",o:["1988","1990","1992","1994"],a:1,d:3},
],

"🔥 Heavy Metal": [
  {q:"Vilket band sjöng 'Fuel' (Metallica)?",o:["Slayer","Metallica","Megadeth","Anthrax"],a:1,d:1},
  {q:"Vilket band sjöng 'Run to the Hills'?",o:["Judas Priest","Saxon","Iron Maiden","Motörhead"],a:2,d:1},
  {q:"Vem är sångare i Judas Priest sedan 1990?",o:["Rob Halford","Tim Owens","Scott Travis","Glenn Tipton"],a:0,d:1},
  {q:"Vilket band sjöng 'Schism' (Tool)?",o:["Rage Against the Machine","Tool","System of a Down","Mastodon"],a:1,d:1},
  {q:"Vilket band sjöng 'Roots Bloody Roots'?",o:["Slayer","Pantera","Sepultura","Machine Head"],a:2,d:1},
  {q:"Vilket band sjöng 'The Beautiful People'?",o:["Nine Inch Nails","Marilyn Manson","Rob Zombie","White Zombie"],a:1,d:1},
  {q:"Vilket band sjöng 'Dragula'?",o:["Marilyn Manson","White Zombie","Rob Zombie","Nine Inch Nails"],a:2,d:1},
  {q:"Vilket band sjöng 'Laid to Rest'?",o:["Slipknot","Trivium","Lamb of God","Machine Head"],a:2,d:2},
  {q:"Vilket år kom Pantera 'Vulgar Display of Power'?",o:["1990","1992","1994","1996"],a:1,d:2},
  {q:"Vilket band sjöng 'Before I Forget'?",o:["Korn","Slipknot","Disturbed","Drowning Pool"],a:1,d:2},
  {q:"Vilket år kom Opeth 'Ghost Reveries'?",o:["2003","2005","2007","2009"],a:1,d:3},
  {q:"Vilket band sjöng 'The Pot'?",o:["Rage Against the Machine","Tool","System of a Down","Mastodon"],a:1,d:2},
  {q:"Vilket år kom Neurosis 'A Sun That Never Sets'?",o:["1999","2001","2003","2005"],a:1,d:3},
  {q:"Vilket band sjöng 'Disciple'?",o:["Disturbed","Slipknot","Trivium","Lamb of God"],a:0,d:2},
  {q:"Vilket år kom Between the Buried and Me 'Colors'?",o:["2005","2007","2009","2011"],a:1,d:3},
  {q:"Vilket band sjöng 'Holy Wars'?",o:["Slayer","Megadeth","Metallica","Anthrax"],a:1,d:2},
  {q:"Vilket år kom Kvelertak debutalbum?",o:["2008","2010","2012","2014"],a:1,d:3},
  {q:"Vilket band sjöng 'Vigil'?",o:["Tool","Mastodon","Neurosis","Isis"],a:2,d:3},
  {q:"Vilket år kom Gojira 'From Mars to Sirius'?",o:["2003","2005","2007","2009"],a:1,d:3},
  {q:"Vilket band sjöng 'Walk with Me in Hell'?",o:["Trivium","Killswitch Engage","Lamb of God","As I Lay Dying"],a:2,d:3},
],

"🇸🇪 Svensk musik": [
  {q:"Vem sjunger 'Det löser sig'?",o:["Lars Winnerbäck","Håkan Hellström","Bob Hund","Magnus Uggla"],a:1,d:1},
  {q:"Vilket band sjöng 'Mitt i ett äventyr'?",o:["Gyllene Tider","Grönkulla","Rebecka Törnqvist","Ratata"],a:3,d:2},
  {q:"Vem sjunger 'Torsdag'?",o:["Lars Winnerbäck","Håkan Hellström","Bob Hund","Ulf Lundell"],a:0,d:1},
  {q:"Vilket band sjöng 'Kärleksvisan'?",o:["Laleh","Tove Lo","Zara Larsson","Lykke Li"],a:0,d:2},
  {q:"Vem sjunger 'Postman'?",o:["Robyn","Lykke Li","Miike Snow","Little Dragon"],a:2,d:2},
  {q:"Vilket band sjöng 'Your Call'?",o:["Miike Snow","Little Dragon","The Knife","Jose Gonzalez"],a:0,d:2},
  {q:"Vem sjunger 'Violent Game'?",o:["The Knife","Fever Ray","Lykke Li","Miike Snow"],a:0,d:3},
  {q:"Vilket år kom The Knifes 'Silent Shout'?",o:["2004","2006","2008","2010"],a:1,d:3},
  {q:"Vem sjunger 'Phantom of the Opera' på svenska?",o:["Charlotte Perrelli","Carola","Helen Sjöholm","Sarah Dawn Finer"],a:2,d:2},
  {q:"Vilket band sjöng 'Röd'?",o:["Laleh","Miss Li","Lisa Nilsson","Marit Bergman"],a:0,d:2},
  {q:"Vem sjunger 'Flickan och kråkan'?",o:["Laleh","Lykke Li","Miriam Bryant","Rebecca & Fiona"],a:0,d:2},
  {q:"Vilket år kom Lykke Lis debutalbum?",o:["2006","2008","2010","2012"],a:1,d:2},
  {q:"Vem sjunger 'I Follow Rivers'?",o:["Lykke Li","Robyn","Fever Ray","Little Dragon"],a:0,d:2},
  {q:"Vilket band sjöng 'Triangler'?",o:["Familjen","Movits","Veronica Maggio","Kent"],a:3,d:3},
  {q:"Vem sjunger 'Välkommen in'?",o:["Kent","Håkan Hellström","Lars Winnerbäck","Ulf Lundell"],a:0,d:2},
  {q:"Vilket år kom Kents sista album?",o:["2014","2016","2018","2020"],a:1,d:3},
  {q:"Vem sjunger 'Flytta på dig'?",o:["Veronica Maggio","Laleh","Lisa Nilsson","Miss Li"],a:0,d:2},
  {q:"Vilket band sjöng 'Åtta minuter'?",o:["Kent","Gyllene Tider","Takida","Mustasch"],a:0,d:3},
  {q:"Vem sjunger 'Glömde att du inte längre bodde här'?",o:["Lars Winnerbäck","Joakim Thåström","Ulf Lundell","Håkan Hellström"],a:0,d:2},
  {q:"Vilket år kom Swedish House Mafias 'One Last Tour'?",o:["2010","2012","2013","2014"],a:2,d:3},
],

"🎬 Movie Quiz": [
  {q:"Vilket år kom Nolans 'Memento'?",o:["1998","2000","2002","2004"],a:1,d:1},
  {q:"Vem spelar Bruce Wayne i Nolans Batman?",o:["Ben Affleck","Michael Keaton","Christian Bale","Val Kilmer"],a:2,d:1},
  {q:"Vilket år kom Jordan Peeles 'Get Out'?",o:["2015","2017","2019","2021"],a:1,d:1},
  {q:"Vem regisserade 'La La Land'?",o:["J.J. Abrams","Damien Chazelle","Baz Luhrmann","Wes Anderson"],a:1,d:1},
  {q:"Vilket år kom 'Mad Max: Fury Road'?",o:["2013","2015","2017","2019"],a:1,d:1},
  {q:"Vem spelar i 'Mad Max: Fury Road'?",o:["Tom Hardy och Charlize Theron","Chris Evans och Scarlett Johansson","Ryan Gosling och Emma Stone","Jake Gyllenhaal och Amy Adams"],a:0,d:1},
  {q:"Vilket år kom Ari Asters 'Hereditary'?",o:["2016","2018","2020","2022"],a:1,d:1},
  {q:"Vem regisserade 'Parasite'?",o:["Park Chan-wook","Kim Jee-woon","Bong Joon-ho","Na Hong-jin"],a:2,d:2},
  {q:"Vilket år kom Robert Eggers 'The Witch'?",o:["2013","2015","2017","2019"],a:1,d:2},
  {q:"Vem spelar huvudrollen i 'Dune' (2021)?",o:["Tom Holland","Timothée Chalamet","Ansel Elgort","Lucas Hedges"],a:1,d:2},
  {q:"Vilket år kom 'Everything Everywhere All at Once'?",o:["2020","2022","2023","2024"],a:1,d:2},
  {q:"Vem regisserade 'Arrival' (2016)?",o:["Christopher Nolan","Denis Villeneuve","Ridley Scott","David Fincher"],a:1,d:2},
  {q:"Vilket år kom 'The Lighthouse'?",o:["2017","2019","2021","2023"],a:1,d:3},
  {q:"Vem regisserade 'Mulholland Drive'?",o:["Roman Polanski","David Lynch","Terry Gilliam","Darren Aronofsky"],a:1,d:3},
  {q:"Vilket år kom Paul Thomas Andersons 'There Will Be Blood'?",o:["2005","2007","2009","2011"],a:1,d:3},
  {q:"Vem spelar Daniel Plainview i 'There Will Be Blood'?",o:["Daniel Day-Lewis","Javier Bardem","Tommy Lee Jones","Josh Brolin"],a:0,d:3},
  {q:"Vilket år kom Terrence Malicks 'The Tree of Life'?",o:["2007","2009","2011","2013"],a:2,d:3},
  {q:"Vilket år kom Bergmans 'Scener ur ett äktenskap'?",o:["1971","1973","1975","1977"],a:1,d:3},
],

"📺 TV-serier": [
  {q:"Vilket år kom Prestige TV-serien 'Deadwood'?",o:["2002","2004","2006","2008"],a:1,d:2},
  {q:"Vem spelar Walter White i Breaking Bad?",o:["Bryan Cranston","Aaron Paul","Bob Odenkirk","Dean Norris"],a:0,d:1},
  {q:"Vilket år kom 'Fleabag'?",o:["2014","2016","2018","2020"],a:1,d:1},
  {q:"Vem skapade och spelar i 'Fleabag'?",o:["Sharon Horgan","Phoebe Waller-Bridge","Lena Dunham","Mindy Kaling"],a:1,d:1},
  {q:"Vilket år kom 'Chernobyl' (HBO)?",o:["2017","2019","2021","2023"],a:1,d:1},
  {q:"Vem spelar Viktor Chernobyl i Chernobyl?",o:["Jared Harris","Stellan Skarsgård","Paul Ritter","Sam Troughton"],a:0,d:2},
  {q:"Vilket år kom 'The Boys' (Amazon)?",o:["2017","2019","2021","2023"],a:1,d:1},
  {q:"Vilket år kom 'Shogun' (FX 2024)?",o:["2022","2023","2024","2025"],a:2,d:2},
  {q:"Vem spelar Lord Toranaga i Shogun 2024?",o:["Hiroyuki Sanada","Ken Watanabe","Tadanobu Asano","Masahiro Motoki"],a:0,d:3},
  {q:"Vilket år kom 'Slow Horses' (Apple TV+)?",o:["2019","2022","2023","2024"],a:1,d:2},
  {q:"Vilket år kom 'Dark' (tysk Netflix)?",o:["2015","2017","2019","2021"],a:1,d:2},
  {q:"Vem spelar den manliga huvudrollen i 'Normal People'?",o:["Paul Mescal","Andrew Scott","Barry Keoghan","Domhnall Gleeson"],a:0,d:2},
  {q:"Vilket år kom 'Succession' säsong 4?",o:["2021","2022","2023","2024"],a:2,d:2},
  {q:"Vilket år kom 'Station Eleven'?",o:["2019","2021","2022","2023"],a:1,d:2},
  {q:"Vem spelar i 'The Idol' (HBO)?",o:["The Weeknd & Lily-Rose Depp","Justin Bieber & Hailey Baldwin","Drake & Rihanna","Travis Scott & Kylie Jenner"],a:0,d:3},
  {q:"Vilket år kom 'Tokyo Vice'?",o:["2020","2022","2023","2024"],a:1,d:3},
  {q:"Vem skapade 'Succession'?",o:["David Chase","Jesse Armstrong","Vince Gilligan","Alan Ball"],a:1,d:3},
  {q:"Vilket år kom 'The Knick'?",o:["2012","2014","2016","2018"],a:1,d:3},
],

"🏰 Disney Klassiker": [
  {q:"Vad heter hunden i 'Lady and the Tramp'?",o:["Lady och Lufsen","Pongo","Perdita","Pluto"],a:0,d:1},
  {q:"Vilket år kom 'Lady and the Tramp'?",o:["1953","1955","1957","1959"],a:1,d:2},
  {q:"Vad heter häxan i 'The Little Mermaid'?",o:["Maleficent","Ursula","Mother Gothel","Evil Queen"],a:1,d:1},
  {q:"Vilket år kom Disney's 'Robin Hood'?",o:["1971","1973","1975","1977"],a:1,d:2},
  {q:"Vad heter tigern i 'Aladdin'?",o:["Abu","Rajah","Khan","Shere"],a:1,d:2},
  {q:"Vilket år kom Disney's 'The Fox and the Hound'?",o:["1979","1981","1983","1985"],a:1,d:3},
  {q:"Vad heter elefanten i 'Jungle Book'?",o:["Hathi","Baloo","Shere Khan","Colonel Hathi"],a:3,d:2},
  {q:"Vilket år kom Pinocchio?",o:["1938","1940","1942","1944"],a:1,d:2},
  {q:"Vad heter Simba's bästa vän i Lejonkungen?",o:["Timon","Pumba","Nala","Rafiki"],a:2,d:1},
  {q:"Vilket år kom Disney's 'Oliver & Company'?",o:["1986","1988","1990","1992"],a:1,d:3},
  {q:"Vad heter trollet i 'Beauty and the Beast'?",o:["Gaston","Lumiere","Cogsworth","Adam (Beasts riktiga namn)"],a:3,d:3},
  {q:"Vilket år kom 'The Aristocats'?",o:["1968","1970","1972","1974"],a:1,d:3},
  {q:"Vad heter kaninen i 'Bambi'?",o:["Peter","Thumper","Flower","Faline"],a:1,d:2},
  {q:"Vilket år kom Disney's 'The Great Mouse Detective'?",o:["1984","1986","1988","1990"],a:1,d:3},
  {q:"Vad heter feen i 'Askungen'?",o:["Tinker Bell","Blue Fairy","Fairy Godmother","Periwinkle"],a:2,d:2},
  {q:"Vilket år kom 'Fantasia 2000'?",o:["1996","1998","1999","2001"],a:2,d:3},
],

"❄️ Frost & Moderna Disney": [
  {q:"Vad heter karaktären Flynn Ryder egentligen?",o:["Hans","Eugene Fitzherbert","Kristoff","Jack"],a:1,d:2},
  {q:"Vilket år kom Pixar 'Onward'?",o:["2018","2020","2021","2022"],a:1,d:1},
  {q:"Vad heter bröderna i 'Onward'?",o:["Ian och Barley Lightfoot","Tom och Jerry","Sam och Frodo","Mike och Sully"],a:0,d:2},
  {q:"Vilket år kom Disney 'Wish'?",o:["2021","2022","2023","2024"],a:2,d:2},
  {q:"Vad heter prinsessan i 'Brave' (Vild)?",o:["Raya","Moana","Merida","Vaiana"],a:2,d:1},
  {q:"Vilket år kom Pixar 'The Good Dinosaur'?",o:["2013","2015","2017","2019"],a:1,d:3},
  {q:"Vad heter dinosaurien i 'The Good Dinosaur'?",o:["Rex","Arlo","Spot","Buck"],a:1,d:3},
  {q:"Vilket år kom Disney 'Encanto'?",o:["2019","2021","2022","2023"],a:1,d:1},
  {q:"Vad heter det musikaliska numret som kungen sjunger i Frost 2?",o:["Lost in the Woods","Into the Unknown","When I Am Older","All Is Found"],a:0,d:3},
  {q:"Vilket år kom Pixar 'Elemental'?",o:["2021","2022","2023","2024"],a:2,d:2},
  {q:"Vad heter den äldre brodern i 'Onward'?",o:["Ian","Barley","Wilden","Corey"],a:1,d:2},
  {q:"Vilket år kom Disney 'Ralph Breaks the Internet'?",o:["2016","2018","2020","2022"],a:1,d:2},
  {q:"Vad heter antagonisten i 'Tangled'?",o:["Hans","Mother Gothel","Duke","Flynn"],a:1,d:2},
  {q:"Vilket år kom Pixar 'Monsters University'?",o:["2011","2013","2015","2017"],a:1,d:2},
  {q:"Vad heter den manlige karaktären i 'Strange World'?",o:["Searcher Clade","Jaeger Clade","Ethan Clade","Marco Clade"],a:0,d:3},
],

"🎠 Barnfilmer & Ungdomsfilmer": [
  {q:"Vilket år kom 'The NeverEnding Story'?",o:["1982","1984","1986","1988"],a:1,d:1},
  {q:"Vilket år kom 'Labyrinth' med David Bowie?",o:["1984","1986","1988","1990"],a:1,d:1},
  {q:"Vem spelar Jareth i 'Labyrinth'?",o:["Sting","David Bowie","Roger Daltrey","Peter Gabriel"],a:1,d:2},
  {q:"Vilket år kom 'The Princess Bride'?",o:["1985","1987","1989","1991"],a:1,d:2},
  {q:"Vilket år kom 'My Neighbor Totoro'?",o:["1986","1988","1990","1992"],a:1,d:2},
  {q:"Vem regisserade 'My Neighbor Totoro'?",o:["Mamoru Oshii","Satoshi Kon","Isao Takahata","Hayao Miyazaki"],a:3,d:2},
  {q:"Vilket år kom 'Spirited Away'?",o:["1999","2001","2003","2005"],a:1,d:2},
  {q:"Vem regisserade 'Spirited Away'?",o:["Mamoru Oshii","Satoshi Kon","Isao Takahata","Hayao Miyazaki"],a:3,d:2},
  {q:"Vilket år kom 'The Iron Giant'?",o:["1997","1999","2001","2003"],a:1,d:2},
  {q:"Vem regisserade 'The Iron Giant'?",o:["Brad Bird","Pete Docter","Andrew Stanton","Lee Unkrich"],a:0,d:3},
  {q:"Vilket år kom 'Coraline'?",o:["2007","2009","2011","2013"],a:1,d:2},
  {q:"Vem regisserade 'Coraline'?",o:["Tim Burton","Henry Selick","Laika Studios","Pete Docter"],a:1,d:3},
  {q:"Vilket år kom 'Howl's Moving Castle'?",o:["2002","2004","2006","2008"],a:1,d:3},
  {q:"Vilket år kom 'Kiki's Delivery Service'?",o:["1987","1989","1991","1993"],a:1,d:3},
  {q:"Vem spelar Bilbo i 'The Hobbit' filmerna?",o:["Ian McKellen","Martin Freeman","Benedict Cumberbatch","Richard Armitage"],a:1,d:1},
  {q:"Vilket år kom 'Percy Jackson & the Olympians' (filmen)?",o:["2008","2010","2012","2014"],a:1,d:2},
],

"⚽ Fotboll": [
  {q:"Vilket lag spelar hemma på Signal Iduna Park?",o:["Bayern München","RB Leipzig","Borussia Dortmund","Bayer Leverkusen"],a:2,d:1},
  {q:"Vem vann EM-guld 2020 (spelat 2021)?",o:["Frankrike","England","Portugal","Italien"],a:3,d:1},
  {q:"Vilket lag spelar hemma på Nou Mestalla?",o:["Real Madrid","Atletico Madrid","Valencia","Sevilla"],a:2,d:2},
  {q:"Vem vann Champions League 2015?",o:["Barcelona","Bayern München","Real Madrid","Juventus"],a:0,d:2},
  {q:"Vilket land vann Womens World Cup 2019?",o:["England","Frankrike","USA","Kanada"],a:2,d:2},
  {q:"Vem är allsvenskans mest historiske toppscorer?",o:["Kennet Andersson","Henrik Larsson","Martin Dahlin","Zlatan Ibrahimovic"],a:1,d:3},
  {q:"Vilket år vann IFK Göteborg Uefacupen?",o:["1981 och 1984","1982 och 1985","1983 och 1986","1984 och 1987"],a:2,d:3},
  {q:"Vilket lag spelar hemma på Parken i Köpenhamn?",o:["Brøndby IF","FC Midtjylland","FC København","AGF"],a:2,d:2},
  {q:"Vilket år grundades Premier League?",o:["1990","1992","1994","1996"],a:1,d:2},
  {q:"Vem vann Ballon d'Or 2021?",o:["Robert Lewandowski","Lionel Messi","Cristiano Ronaldo","Karim Benzema"],a:1,d:2},
  {q:"Vilket land vann Copa America 2021?",o:["Brasilien","Colombia","Argentina","Uruguay"],a:2,d:2},
  {q:"Vilket lag spelar hemma på Ullevi i Göteborg?",o:["IFK Göteborg & GAIS","IFK Göteborg","GAIS","Örgryte IS"],a:0,d:3},
],

"🏒 Ishockey": [
  {q:"Vilket lag spelar i Örebro SHL?",o:["Örebro HK","Leksands IF","BIK Karlskoga","Linköping HC"],a:0,d:1},
  {q:"Vad heter NHL-laget i Denver?",o:["Denver Avalanche","Colorado Rockies","Colorado Avalanche","Denver Blizzard"],a:2,d:1},
  {q:"Vilket år vann Colorado Avalanche Stanley Cup senast (före 2022)?",o:["1996","1999","2001","2004"],a:2,d:2},
  {q:"Vilket lag spelar hemma på Bell Centre?",o:["Toronto Maple Leafs","Ottawa Senators","Montreal Canadiens","Quebec Nordiques"],a:2,d:2},
  {q:"Vem håller rekord för flest mål i NHL-historia?",o:["Gordie Howe","Wayne Gretzky","Jaromir Jagr","Brett Hull"],a:1,d:2},
  {q:"Vilket år vann Pittsburgh Penguins Stanley Cup senast?",o:["2014","2016","2017","2018"],a:2,d:2},
  {q:"Vilket lag spelar hemma på TD Garden?",o:["New York Rangers","Philadelphia Flyers","Boston Bruins","Detroit Red Wings"],a:2,d:2},
  {q:"Vem är NHL:s alltime poänggörare per match?",o:["Mario Lemieux","Wayne Gretzky","Mike Bossy","Brett Hull"],a:0,d:3},
  {q:"Vilket lag spelar hemma på Madison Square Garden?",o:["New York Rangers","New York Islanders","New Jersey Devils","Philadelphia Flyers"],a:0,d:2},
  {q:"Vilket år kom Mats Sundin till NHL?",o:["1988","1990","1992","1994"],a:1,d:3},
  {q:"Vilket lag spelar i Linköping i SHL?",o:["Linköping HC","Djurgårdens IF","Frölunda HC","HV71"],a:0,d:2},
  {q:"Vad heter NHL-laget i Washington DC?",o:["Washington Capitals","DC Knights","Capital City Bears","Potomac Ice"],a:0,d:1},
],

"🏅 Sport (allmänt)": [
  {q:"Vem vann US Open tennis herrar 2023?",o:["Carlos Alcaraz","Novak Djokovic","Jannik Sinner","Daniil Medvedev"],a:0,d:2},
  {q:"Vilket land vann Rugby World Cup 2023?",o:["Nya Zeeland","Sydafrika","England","Frankrike"],a:1,d:2},
  {q:"Vem vann French Open herrar 2023?",o:["Novak Djokovic","Carlos Alcaraz","Casper Ruud","Holger Rune"],a:0,d:2},
  {q:"Vilket år kom Formel E (elektrisk racing) igång?",o:["2012","2014","2016","2018"],a:1,d:2},
  {q:"Vem vann Australian Open damer 2024?",o:["Aryna Sabalenka","Iga Swiatek","Coco Gauff","Elena Rybakina"],a:0,d:3},
  {q:"Vilket land vann VM i handboll herrar 2023?",o:["Frankrike","Danmark","Sverige","Spanien"],a:1,d:2},
  {q:"Vem vann Formel 1-VM 2022?",o:["Lewis Hamilton","Sergio Perez","Max Verstappen","Charles Leclerc"],a:2,d:2},
  {q:"Vilket år hölls de första vinter-OS?",o:["1920","1924","1928","1932"],a:1,d:3},
  {q:"Vilket land vann VM i volleyboll herrar 2022?",o:["Brasil","Frankrike","Polen","Ryssland"],a:2,d:3},
  {q:"Vem satte marathon-världsrekordet som bröt 2 timmar?",o:["Eliud Kipchoge","Kenenisa Bekele","Kelvin Kiptum","Geoffrey Kamworor"],a:0,d:2},
  {q:"Vilket år hölls OS i Peking (sommar)?",o:["2006","2008","2010","2012"],a:1,d:1},
  {q:"Vilket år kom Bryson DeChambeau på LIV Golf?",o:["2021","2022","2023","2024"],a:1,d:3},
],

"💻 Teknik & IT": [
  {q:"Vilket år grundades Instagram?",o:["2008","2010","2012","2014"],a:1,d:1},
  {q:"Vilket år köpte Meta Instagram?",o:["2010","2012","2014","2016"],a:1,d:2},
  {q:"Vilket år grundades Zoom?",o:["2009","2011","2013","2015"],a:2,d:2},
  {q:"Vilket år kom Python 3.0?",o:["2006","2008","2010","2012"],a:1,d:3},
  {q:"Vilket år grundades GitHub?",o:["2006","2008","2010","2012"],a:1,d:2},
  {q:"Vilket år köpte Microsoft GitHub?",o:["2014","2016","2018","2020"],a:2,d:2},
  {q:"Vilket år kom Docker?",o:["2011","2013","2015","2017"],a:1,d:3},
  {q:"Vilket år lanserades React (Facebook)?",o:["2011","2013","2015","2017"],a:1,d:3},
  {q:"Vilket år kom Kubernetes?",o:["2012","2014","2016","2018"],a:1,d:3},
  {q:"Vilket år grundades Slack?",o:["2011","2013","2015","2017"],a:1,d:2},
  {q:"Vilket år lanserades iPhone SE första versionen?",o:["2014","2016","2018","2020"],a:1,d:2},
  {q:"Vilket år kom Apple Silicon M2?",o:["2020","2022","2023","2024"],a:1,d:2},
  {q:"Vad heter Googles programmeringsspråk (2009)?",o:["Rust","Go","Swift","Kotlin"],a:1,d:3},
  {q:"Vilket år lanserades Swift (Apple)?",o:["2012","2014","2016","2018"],a:1,d:3},
  {q:"Vilket år grundades Vercel?",o:["2015","2017","2019","2021"],a:1,d:3},
],

"🔬 Vetenskap & Natur": [
  {q:"Vilket år kom CRISPR-Cas9 teknologin?",o:["2009","2012","2015","2018"],a:1,d:3},
  {q:"Vem fick Nobelpriset i fysik för att ha hittat svarta hål?",o:["Stephen Hawking","Roger Penrose","Kip Thorne","Andrea Ghez"],a:1,d:3},
  {q:"Vilket grundämne har flest kända strikta isotopper?",o:["Cesium","Xenon","Tin/Tenn","Tellurium"],a:2,d:3},
  {q:"Hur många naturliga element finns i periodiska systemet?",o:["92","94","98","118"],a:0,d:2},
  {q:"Vad heter den kemiska formeln för glukos?",o:["C5H10O5","C6H12O6","C6H10O5","C12H22O11"],a:1,d:2},
  {q:"Vilket år slutade Douglas Adams 'Liftarens guide' med 42 som svaret?",o:["1978","1979","1980","1981"],a:1,d:3},
  {q:"Hur lång tid tar det för ljuset att resa från Proxima Centauri till Jorden?",o:["1 år","2.5 år","4.2 år","10 år"],a:2,d:3},
  {q:"Vad heter den kemiska formeln för etanol?",o:["CH3OH","C2H5OH","C3H7OH","C4H9OH"],a:1,d:2},
  {q:"Vilket år formulerades Darwins evolutionsteori?",o:["1849","1859","1869","1879"],a:1,d:2},
  {q:"Vad är den kemiska beteckningen för natriumklorid (salt)?",o:["NaCl","NaK","NaCO3","NaSO4"],a:0,d:1},
  {q:"Vilket år dog Marie Curie?",o:["1930","1932","1934","1936"],a:2,d:2},
  {q:"Vad heter teorin om att universum expanderar?",o:["Steady State","Inflation","Den expanderande universum","Hubbles lag"],a:3,d:2},
],

"🌍 Geografi & Historia": [
  {q:"Vilket år förenades Öst- och Västtyskland?",o:["1988","1990","1992","1994"],a:1,d:1},
  {q:"Vilket land har flest grannar?",o:["Kina","Ryssland","Brasilien","USA"],a:0,d:2},
  {q:"Vilket år grundades Romfördraget (EEG)?",o:["1955","1957","1959","1961"],a:1,d:3},
  {q:"Vilket land var det sista att gå med i EU?",o:["Bulgarien","Rumänien","Kroatien","Nordmakedonien"],a:2,d:2},
  {q:"Vilket år inträffade folkmordet i Rwanda?",o:["1990","1992","1994","1996"],a:2,d:2},
  {q:"Vilket år byggdes Berlinmuren?",o:["1959","1961","1963","1965"],a:1,d:2},
  {q:"Vilket land kallades Ceylon?",o:["Indien","Bangladesh","Myanmar","Sri Lanka"],a:3,d:2},
  {q:"Vilket år fick Sydafrika demokrati?",o:["1990","1992","1994","1996"],a:2,d:2},
  {q:"Vilket land kom Kopernikusteorin ifrån?",o:["Tjeckien","Polen","Ungern","Österrike"],a:1,d:3},
  {q:"Vilket år inträffade Tjernobylolyckan?",o:["1984","1986","1988","1990"],a:1,d:2},
  {q:"Vilket år grundades Folkförbundet (League of Nations)?",o:["1917","1919","1921","1923"],a:1,d:3},
  {q:"Vilket land var det sista att avskaffa slaveriet?",o:["USA","Brasilien","Saudi-Arabien","Mauretanien"],a:3,d:3},
],

"🍕 Mat & Dryck": [
  {q:"Vilket land kom Croissant ursprungligen ifrån?",o:["Frankrike","Österrike","Schweiz","Belgien"],a:1,d:2},
  {q:"Vad heter den mexikanska rätten gjord på majsgryn?",o:["Tamale","Pozole","Atole","Champurrado"],a:1,d:3},
  {q:"Vilket år grundades McDonalds som franchise?",o:["1948","1954","1960","1965"],a:1,d:2},
  {q:"Vad heter den koreanska BBQ-rätten?",o:["Bibimbap","Bulgogi","Japchae","Gamjatang"],a:1,d:2},
  {q:"Vilket land uppfann ölen?",o:["England","Tyskland","Belgien","Mesopotamien/Irak"],a:3,d:3},
  {q:"Vad heter den peruanska rätten med citrusmarinerad fisk?",o:["Ceviche","Tiradito","Leche de tigre","Anticucho"],a:0,d:2},
  {q:"Vilket land uppfann curryrätterna?",o:["Indien","Thailand","Sri Lanka","Nepal"],a:0,d:1},
  {q:"Vad heter den franska bistro-rätten 'köttgryta med rödvin'?",o:["Coq au vin","Boeuf bourguignon","Pot-au-feu","Blanquette de veau"],a:1,d:2},
  {q:"Vilket land är känt för 'smørrebrød'?",o:["Norge","Sverige","Finland","Danmark"],a:3,d:1},
  {q:"Vad heter den vietnamesiska banh mi?",o:["En nudelsoppa","En baguettesmörgås","En risrätt","En sallad"],a:1,d:1},
  {q:"Vilket land producerar mest kaffe?",o:["Colombia","Etiopien","Brasilien","Vietnam"],a:2,d:2},
  {q:"Vad heter den argentinska grillen?",o:["Churrasco","Asado","Parrilla","Gaucho"],a:1,d:2},
],

"🏙️ Umeå & Norrland": [
  {q:"Vad heter Umeås största park?",o:["Gammlia","Stadsparken","Vasaparken","Sofiehem"],a:1,d:2},
  {q:"Vilket år grundades Västernorrlands läns museum?",o:["1899","1909","1919","1929"],a:0,d:3},
  {q:"Vad heter havsbaden nära Umeå?",o:["Umeå Havsbad","Norrlandsstranden","Boviken","Bölestranden"],a:0,d:2},
  {q:"Vilket landskap gränsar Västerbotten mot söder?",o:["Ångermanland","Medelpad","Hälsingland","Gästrikland"],a:0,d:2},
  {q:"Vad heter den största insjön i Västerbotten?",o:["Storuman","Kultsjön","Storsjön","Hotingsjön"],a:0,d:3},
  {q:"Vilket år grundades Skellefteå tekniska gymnasium?",o:["1945","1955","1963","1971"],a:2,d:3},
  {q:"Vad heter berget utanför Umeå?",o:["Rödklitten","Umeberget","Nydalaberget","Mullberget"],a:3,d:3},
  {q:"Vilket år kom Uminova Science Park?",o:["1990","1995","2002","2008"],a:2,d:3},
  {q:"Vilket år grundades Västerbottens läns landsting?",o:["1864","1887","1912","1944"],a:0,d:3},
  {q:"Vad heter Umeås välkända restauranggata?",o:["Kungsgatan","Rådhustorget","Avenyn","Storgatan"],a:3,d:2},
  {q:"Vilket år invigdes Umeå Energiarena?",o:["2010","2012","2014","2016"],a:2,d:2},
  {q:"Vad heter Västerbottens landshövding (2024)?",o:["Helene Hellmark Knutsson","Anders Flanking","Björn Eriksson","Stina Mattsson"],a:0,d:3},
],

"🎭 Allmänkultur & Käpphäst": [
  // ALLMÄNKULTUR
  {q:"Vem skrev 'Faust'?",o:["Friedrich Schiller","Johann Wolfgang von Goethe","Thomas Mann","Hermann Hesse"],a:1,d:2},
  {q:"Vilket år dog Leonardo da Vinci?",o:["1513","1519","1525","1531"],a:1,d:2},
  {q:"Vem målade 'Sistinska kapellet'?",o:["Raphael","Leonardo da Vinci","Michelangelo","Botticelli"],a:2,d:1},
  {q:"Vilket år kom Kafkas 'Förvandlingen'?",o:["1910","1912","1914","1916"],a:2,d:3},
  {q:"Vem skrev 'Brott och straff'?",o:["Leo Tolstoj","Anton Tjechov","Fjodor Dostojevskij","Ivan Turgenev"],a:2,d:2},
  {q:"Vilket år kom Proust 'På spaning efter den tid som flytt'?",o:["1909","1913","1917","1921"],a:1,d:3},
  {q:"Vem komponerade 'Midsommarnatts dröm'?",o:["Grieg","Mendelssohn","Brahms","Schumann"],a:1,d:2},
  {q:"Vilket år dog René Descartes?",o:["1645","1650","1655","1660"],a:1,d:3},
  {q:"Vem skriver 'Ulysses'?",o:["Virginia Woolf","D.H. Lawrence","James Joyce","T.S. Eliot"],a:2,d:2},
  {q:"Vilket år kom Ibsens 'Et dukkehjem'?",o:["1875","1879","1883","1887"],a:1,d:3},
  // KÄPPHÄSTAR – breda intressen som 25%+ av frågorna
  {q:"Vad heter det populäraste brädspelet i världen?",o:["Schack","Monopol","Scrabble","Cluedo"],a:1,d:1},
  {q:"Vilket är det mest spelade TV-spelet någonsin?",o:["Minecraft","Tetris","Grand Theft Auto V","PUBG"],a:1,d:1},
  {q:"Vad heter den populäraste podcasten i världen (2024)?",o:["Joe Rogan Experience","Serial","This American Life","TED Talks"],a:0,d:2},
  {q:"Vilket år kom Dungeons & Dragons?",o:["1970","1972","1974","1976"],a:2,d:2},
  {q:"Vad heter den äldsta aktiva ölstilen?",o:["Pilsner","Porter","Lambic","Sahti"],a:3,d:3},
  {q:"Vilket år kom Magic: the Gathering?",o:["1989","1991","1993","1995"],a:2,d:2},
  {q:"Vad heter den populäraste escape room-kedjän i världen?",o:["The Escape Game","Fox in a Box","Breakout","Det finns ingen tydlig ledare"],a:3,d:3},
  {q:"Vilket år lanserades Twitch?",o:["2009","2011","2013","2015"],a:1,d:2},
  {q:"Vad heter världens äldsta whisky-destilleri?",o:["Glenfarclas","Bowmore","Glenturret","Bushmills"],a:2,d:3},
  {q:"Vilket år kom det första moderna brädspelet Catan?",o:["1991","1993","1995","1997"],a:2,d:2},
  {q:"Vad heter världens mest sålda singel?",o:["White Christmas","Something","Yesterday","Candle in the Wind"],a:0,d:2},
  {q:"Vilket år startade TED Talks?",o:["1982","1984","1986","1988"],a:2,d:2},
  {q:"Vad heter det mest populära havet-kortspelet?",o:["Magic the Gathering","Pokémon TCG","Yu-Gi-Oh","Hearthstone"],a:1,d:1},
  {q:"Vilket år kom Netflix som streaming-tjänst?",o:["2005","2007","2009","2011"],a:1,d:1},
  {q:"Vad heter filosofen som sade 'Jag tänker alltså är jag'?",o:["John Locke","David Hume","Immanuel Kant","René Descartes"],a:3,d:1},
  {q:"Vilket år grundades Nobel-priset?",o:["1893","1895","1897","1901"],a:1,d:2},
  {q:"Vad heter den mest populära träningsformen i världen?",o:["Yoga","Löpning","Simning","Cykling"],a:1,d:1},
  {q:"Vilket år fick Sverige sin nuvarande flagga officiellt?",o:["1906","1916","1926","1936"],a:0,d:3},
  {q:"Vad heter världens äldsta parlament?",o:["Storbritanniens","Islands Alltinget","Norges Stortinget","Schweiz"],a:1,d:2},
  {q:"Vilket år kom den första Wikipedia-artikeln?",o:["1999","2001","2003","2005"],a:1,d:2},
],

"🌈 Blandat / Mix": [
  {q:"Vilket år dog Freddie Mercury?",o:["1989","1991","1993","1995"],a:1,d:1},
  {q:"Vilket land uppfann papperet?",o:["Japan","Indien","Kina","Egypten"],a:2,d:1},
  {q:"Vem målade 'Guernica'?",o:["Salvador Dalí","Joan Miró","Pablo Picasso","Francis Bacon"],a:2,d:1},
  {q:"Vilket år kom smartphones med touch-skärm?",o:["2005","2007","2009","2011"],a:1,d:1},
  {q:"Vem skapade Simpsons?",o:["Seth MacFarlane","Mike Judge","Matt Groening","Trey Parker"],a:2,d:1},
  {q:"Vilket år kom 'South Park'?",o:["1995","1997","1999","2001"],a:1,d:1},
  {q:"Vad heter det minsta benet i människokroppen?",o:["Stapes (stigbygeln)","Hammer","Amboss","Radius"],a:0,d:2},
  {q:"Vilket land uppfann gunpowder (krut)?",o:["Indien","Arabien","Japan","Kina"],a:3,d:1},
  {q:"Vilket år kom flygplanet (Wright Brothers)?",o:["1899","1901","1903","1905"],a:2,d:1},
  {q:"Vad heter den snabbaste fågeln?",o:["Örn","Falk (vandringsfalk)","Albatross","Swift"],a:1,d:2},
  {q:"Vilket år dog Alan Turing?",o:["1950","1952","1954","1956"],a:2,d:2},
  {q:"Vilket land uppfann glassen?",o:["Italien","Frankrike","Kina","USA"],a:2,d:2},
  {q:"Vad heter det land som har flest tidszoner?",o:["Ryssland","USA","Kina","Frankrike"],a:3,d:2},
  {q:"Vilket år kom Darwin's 'On the Origin of Species'?",o:["1849","1859","1869","1879"],a:1,d:2},
  {q:"Vad heter Amazons AI-assistent?",o:["Siri","Cortana","Alexa","Google"],a:2,d:1},
  {q:"Vilket år vann Sverige EM-guld i fotboll för damer?",o:["Sverige har aldrig vunnit","1992","2001","2004"],a:0,d:2},
],
};

(function() {
  if (typeof QUESTION_DB === 'undefined') return;
  const existing = new Set();
  Object.values(QUESTION_DB).forEach(qs => {
    qs.forEach(q => existing.add(q.q.toLowerCase().trim()));
  });
  let added = 0, skipped = 0;
  Object.keys(QUESTION_DB8).forEach(cat => {
    const newQs = QUESTION_DB8[cat].filter(q => {
      if (existing.has(q.q.toLowerCase().trim())) { skipped++; return false; }
      existing.add(q.q.toLowerCase().trim());
      return true;
    });
    if (QUESTION_DB[cat]) {
      QUESTION_DB[cat] = QUESTION_DB[cat].concat(newQs);
    } else {
      QUESTION_DB[cat] = newQs;
    }
    added += newQs.length;
  });
  console.log('questions8.js: ' + added + ' added, ' + skipped + ' duplicates skipped');
})();
