// questions12.js – Massiv utökning, ~1200 frågor, noggrann svårighetsgradering
// d:1=LÄTT (alla vet), d:2=MEDEL (intresserade vet), d:3=SVÅRT (nördar)
const QUESTION_DB12 = {

"🎵 80-tals musik": [
  // ── LÄTT – välkända hits ──
  {q:"Vilket band sjöng 'Pour Some Sugar on Me'?",o:["Mötley Crüe","Guns N' Roses","Bon Jovi","Def Leppard"],a:3,d:1},
  {q:"Vem sjunger 'Like a Prayer'?",o:["Cyndi Lauper","Pat Benatar","Madonna","Kim Wilde"],a:2,d:1},
  {q:"Vilket band sjöng 'Don't Stop Believin''?",o:["Bon Jovi","Journey","Foreigner","REO Speedwagon"],a:1,d:1},
  {q:"Vem sjunger 'Billie Jean'?",o:["Prince","James Brown","Michael Jackson","Stevie Wonder"],a:2,d:1},
  {q:"Vilket band sjöng 'Here I Go Again'?",o:["Foreigner","Whitesnake","Scorpions","Dokken"],a:1,d:1},
  {q:"Vem sjunger 'Private Dancer'?",o:["Pat Benatar","Tina Turner","Donna Summer","Debbie Harry"],a:1,d:1},
  {q:"Vilket band sjöng 'Should I Stay or Should I Go'?",o:["The Jam","The Police","The Clash","Elvis Costello"],a:2,d:1},
  {q:"Vem sjunger 'I Just Called to Say I Love You'?",o:["Elton John","Stevie Wonder","Barry White","Lionel Richie"],a:1,d:1},
  {q:"Vilket band sjöng 'Uptown Girl'?",o:["Hall & Oates","Billy Joel","Elton John","Paul Simon"],a:1,d:1},
  {q:"Vem sjunger 'Tell Her About It'?",o:["Billy Joel","Elton John","Paul Simon","Paul McCartney"],a:0,d:1},
  {q:"Vilket band sjöng 'Manic Monday'?",o:["Go-Go's","The Bangles","Wilson Phillips","The Pretenders"],a:1,d:1},
  {q:"Vem sjunger 'Separate Ways' (1983)?",o:["Bon Jovi","Journey","Foreigner","REO Speedwagon"],a:1,d:1},
  // ── MEDEL ──
  {q:"Vilket år kom a-has 'Take On Me'?",o:["1983","1985","1987","1989"],a:1,d:2},
  {q:"Vilket band sjöng 'Personal Jesus'?",o:["The Cure","New Order","Depeche Mode","Bauhaus"],a:2,d:2},
  {q:"Vem producerade Madonnas 'Like a Prayer'?",o:["Nile Rodgers","Patrick Leonard","Jellybean Benitez","Steve Bray"],a:1,d:2},
  {q:"Vilket band sjöng 'Don't You Want Me Baby'?",o:["Erasure","Pet Shop Boys","Human League","Yazoo"],a:2,d:2},
  {q:"Vilket år kom Princes 'Sign O the Times'?",o:["1985","1987","1989","1991"],a:1,d:2},
  {q:"Vilket band sjöng 'Tainted Love'?",o:["Depeche Mode","New Order","Soft Cell","Human League"],a:2,d:2},
  {q:"Vilket år kom Cyndi Laupers debut 'She's So Unusual'?",o:["1981","1983","1985","1987"],a:1,d:2},
  {q:"Vilket band sjöng 'Situation' (1982)?",o:["Visage","Yazoo","ABC","Heaven 17"],a:1,d:2},
  {q:"Vem sjunger 'What's Love Got to Do with It' (1984)?",o:["Pat Benatar","Tina Turner","Donna Summer","Diana Ross"],a:1,d:2},
  {q:"Vilket band sjöng 'Red Red Wine' (1983)?",o:["The Specials","Madness","UB40","Toots and the Maytals"],a:2,d:2},
  {q:"Vilket år kom U2s 'War'?",o:["1981","1983","1985","1987"],a:1,d:2},
  {q:"Vem sjunger 'Straight Up' (1988)?",o:["Whitney Houston","Mariah Carey","Paula Abdul","Janet Jackson"],a:2,d:2},
  // ── SVÅRT ──
  {q:"Vilket skivbolag gav ut The Smiths 'The Queen Is Dead'?",o:["Factory","Rough Trade","4AD","Mute"],a:1,d:3},
  {q:"Vilket år kom Depeche Modes 'Black Celebration'?",o:["1984","1986","1988","1990"],a:1,d:3},
  {q:"Vem producerade New Orders 'Blue Monday'?",o:["Martin Hannett","Bernard Sumner","Peter Saville","Michael Johnson"],a:2,d:3},
  {q:"Vilket år kom The Cure 'Disintegration'?",o:["1987","1989","1991","1993"],a:1,d:3},
  {q:"Vilket band sjöng 'This Charming Man'?",o:["The Cure","Echo and the Bunnymen","The Smiths","Bauhaus"],a:2,d:3},
  {q:"Vilket år kom Echo and the Bunnymen 'Ocean Rain'?",o:["1982","1984","1986","1988"],a:1,d:3},
  {q:"Vem är gitarrist i The Smiths?",o:["Bernard Sumner","Mick Jones","Johnny Marr","Billy Duffy"],a:2,d:3},
  {q:"Vilket år kom Talk Talk 'The Colour of Spring'?",o:["1984","1986","1988","1990"],a:1,d:3},
],

"🎶 90-tals musik": [
  // ── LÄTT ──
  {q:"Vilket band sjöng 'Losing My Religion'?",o:["U2","REM","Radiohead","Pearl Jam"],a:1,d:1},
  {q:"Vem sjunger 'My Heart Will Go On'?",o:["Whitney Houston","Mariah Carey","Celine Dion","Shania Twain"],a:2,d:1},
  {q:"Vilket band sjöng 'Black Hole Sun'?",o:["Pearl Jam","Alice in Chains","Soundgarden","Stone Temple Pilots"],a:2,d:1},
  {q:"Vem sjunger 'Creep' (Radiohead)?",o:["Oasis","Blur","Radiohead","Suede"],a:2,d:1},
  {q:"Vilket band sjöng 'Basket Case'?",o:["The Offspring","Rancid","Green Day","Blink-182"],a:2,d:1},
  {q:"Vem sjunger 'Baby One More Time'?",o:["Christina Aguilera","Britney Spears","Madonna","Mariah Carey"],a:1,d:1},
  {q:"Vilket band sjöng 'Smells Like Teen Spirit'?",o:["Pearl Jam","Soundgarden","Nirvana","Alice in Chains"],a:2,d:1},
  {q:"Vem sjunger 'No Scrubs'?",o:["Destiny's Child","En Vogue","TLC","SWV"],a:2,d:1},
  {q:"Vilket band sjöng 'Everybody (Backstreet's Back)'?",o:["NSYNC","New Kids on the Block","Backstreet Boys","Boyz II Men"],a:2,d:1},
  {q:"Vem sjunger 'Adia' (Sarah McLachlan)?",o:["Jewel","Sarah McLachlan","Alanis Morissette","Sheryl Crow"],a:1,d:1},
  {q:"Vilket band sjöng 'Waterfalls' (TLC)?",o:["Destiny's Child","En Vogue","TLC","Brandy"],a:2,d:1},
  {q:"Vem sjunger 'U Remind Me' (Usher)?",o:["R Kelly","Usher","Boyz II Men","Brian McKnight"],a:1,d:1},
  // ── MEDEL ──
  {q:"Vilket år kom Alanis Morissettes 'Jagged Little Pill'?",o:["1993","1995","1997","1999"],a:1,d:2},
  {q:"Vilket band sjöng 'Connection' (Elastica)?",o:["Garbage","PJ Harvey","Elastica","Echobelly"],a:2,d:2},
  {q:"Vilket år kom Weezer's blå album?",o:["1992","1994","1996","1998"],a:1,d:2},
  {q:"Vilket band sjöng 'When I Come Around'?",o:["Offspring","Green Day","Blink-182","Bad Religion"],a:1,d:2},
  {q:"Vilket år kom Jay-Zs 'Reasonable Doubt'?",o:["1994","1996","1998","2000"],a:1,d:2},
  {q:"Vilket band sjöng 'Lovefool'?",o:["Roxette","The Cardigans","Ace of Base","Sahara Hotnights"],a:1,d:2},
  {q:"Vilket år kom Oasis 'Be Here Now'?",o:["1995","1997","1999","2001"],a:1,d:2},
  {q:"Vilket band sjöng 'Loser' (Beck)?",o:["Pavement","Beck","Sebadoh","Guided by Voices"],a:1,d:2},
  {q:"Vilket år kom Lauryn Hills 'The Miseducation of Lauryn Hill'?",o:["1996","1998","2000","2002"],a:1,d:2},
  {q:"Vilket band sjöng 'The Freshmen'?",o:["Verve Pipe","Toad the Wet Sprocket","Gin Blossoms","Barenaked Ladies"],a:0,d:2},
  {q:"Vilket år kom Eminem 'The Slim Shady LP'?",o:["1997","1999","2001","2003"],a:1,d:2},
  {q:"Vilket band sjöng 'Karma Police' (Radiohead)?",o:["Oasis","Blur","Radiohead","Suede"],a:2,d:2},
  // ── SVÅRT ──
  {q:"Vilket år kom Sonic Youth 'Dirty'?",o:["1990","1992","1994","1996"],a:1,d:3},
  {q:"Vilket skivbolag var Nirvana på när 'Nevermind' kom?",o:["Sub Pop","DGC Records","Geffen","Epitaph"],a:1,d:3},
  {q:"Vem producerade Portisheads 'Dummy'?",o:["Geoff Barrow","Tricky","Massive Attack","Adrian Utley"],a:0,d:3},
  {q:"Vilket år kom PJ Harveys 'Rid of Me'?",o:["1991","1993","1995","1997"],a:1,d:3},
  {q:"Vilket band sjöng 'Come Undone' (Duran Duran 1993)?",o:["Spandau Ballet","Duran Duran","Culture Club","ABC"],a:1,d:3},
  {q:"Vilket år kom Björks 'Debut'?",o:["1991","1993","1995","1997"],a:1,d:3},
  {q:"Vilket band sjöng 'Cannonball' (The Breeders)?",o:["Pixies","The Breeders","Throwing Muses","Belly"],a:1,d:3},
  {q:"Vilket år kom Daft Punks 'Da Funk'?",o:["1993","1995","1997","1999"],a:1,d:3},
],

"🎤 Ny musik (2010-idag)": [
  // ── LÄTT ──
  {q:"Vem sjunger 'Uptown Funk'?",o:["Bruno Mars","Mark Ronson ft Bruno Mars","Pharrell","Justin Timberlake"],a:1,d:1},
  {q:"Vem sjunger 'Happy' (Pharrell Williams)?",o:["Bruno Mars","Justin Timberlake","Pharrell Williams","Jason Derulo"],a:2,d:1},
  {q:"Vem sjunger 'Shake It Off' (Taylor Swift)?",o:["Katy Perry","Ariana Grande","Taylor Swift","Selena Gomez"],a:2,d:1},
  {q:"Vem sjunger 'Old Town Road'?",o:["Cardi B","Lil Nas X","Travis Scott","Post Malone"],a:1,d:1},
  {q:"Vem sjunger 'Blinding Lights' (The Weeknd)?",o:["Drake","The Weeknd","Post Malone","Travis Scott"],a:1,d:1},
  {q:"Vem sjunger 'Stay With Me' (Sam Smith)?",o:["Ed Sheeran","Sam Smith","James Arthur","Olly Murs"],a:1,d:1},
  {q:"Vem sjunger 'Shape of You' (Ed Sheeran)?",o:["Justin Bieber","Ed Sheeran","Sam Smith","Harry Styles"],a:1,d:1},
  {q:"Vem sjunger 'Royals' (Lorde)?",o:["Lorde","Lana Del Rey","Halsey","Billie Eilish"],a:0,d:1},
  {q:"Vem sjunger 'Levitating' (Dua Lipa)?",o:["Dua Lipa","Doja Cat","Olivia Rodrigo","Ariana Grande"],a:0,d:1},
  {q:"Vem sjunger 'drivers license' (Olivia Rodrigo)?",o:["Billie Eilish","Dua Lipa","Olivia Rodrigo","Ariana Grande"],a:2,d:1},
  {q:"Vem sjunger 'Anti-Hero' (Taylor Swift)?",o:["Billie Eilish","Olivia Rodrigo","Taylor Swift","Sabrina Carpenter"],a:2,d:1},
  {q:"Vem sjunger 'As It Was' (Harry Styles)?",o:["Ed Sheeran","Harry Styles","Niall Horan","Louis Tomlinson"],a:1,d:1},
  // ── MEDEL ──
  {q:"Vilket år kom Taylor Swifts 'Red (Taylor's Version)'?",o:["2019","2021","2022","2023"],a:1,d:2},
  {q:"Vem sjunger 'God's Plan' (Drake)?",o:["Travis Scott","Post Malone","Drake","The Weeknd"],a:2,d:2},
  {q:"Vilket år kom Billie Eilish 'Happier Than Ever'?",o:["2019","2021","2022","2023"],a:1,d:2},
  {q:"Vem sjunger 'Montero Call Me by Your Name'?",o:["Tyler the Creator","Lil Nas X","Frank Ocean","ASAP Rocky"],a:1,d:2},
  {q:"Vilket år kom Doja Cats 'Planet Her'?",o:["2019","2021","2022","2023"],a:1,d:2},
  {q:"Vem sjunger 'Easy on Me' (Adele 2021)?",o:["Adele","Dua Lipa","Olivia Rodrigo","Taylor Swift"],a:0,d:2},
  {q:"Vilket år kom The Weeknds 'Starboy'?",o:["2014","2016","2018","2020"],a:1,d:2},
  {q:"Vem sjunger 'Shivers' (Ed Sheeran 2021)?",o:["Harry Styles","Ed Sheeran","Sam Smith","Lewis Capaldi"],a:1,d:2},
  {q:"Vilket år kom Lizzo 'Juice'?",o:["2017","2019","2021","2023"],a:1,d:2},
  {q:"Vem sjunger 'Bad Habits' (Ed Sheeran 2021)?",o:["Justin Bieber","Ed Sheeran","Harry Styles","Lewis Capaldi"],a:1,d:2},
  {q:"Vilket år kom Post Malones 'Stoney'?",o:["2014","2016","2018","2020"],a:1,d:2},
  {q:"Vem sjunger 'Heather' (2020)?",o:["Phoebe Bridgers","Gracie Abrams","Conan Gray","Noah Kahan"],a:2,d:2},
  // ── SVÅRT ──
  {q:"Vilket år kom Kendrick Lamars 'Section.80'?",o:["2009","2011","2013","2015"],a:1,d:3},
  {q:"Vem producerade Drakes 'Take Care'?",o:["Noah Shebib 40","Boi-1da","T-Minus","Nineteen85"],a:0,d:3},
  {q:"Vilket år kom Frank Oceans 'Channel Orange'?",o:["2010","2012","2014","2016"],a:1,d:3},
  {q:"Vilket år kom Solange 'A Seat at the Table'?",o:["2014","2016","2018","2020"],a:1,d:3},
  {q:"Vem producerade Beyoncés 'Lemonade'?",o:["Jack Antonoff","Mark Ronson","Diplo och Jack White bland andra","Ryan Tedder"],a:2,d:3},
  {q:"Vilket år kom Thundercat 'Drunk'?",o:["2015","2017","2019","2021"],a:1,d:3},
  {q:"Vem sjunger 'Motion Picture Soundtrack' (Kanye feat)?",o:["Kid Cudi","Drake","Jay-Z","Pusha T"],a:0,d:3},
  {q:"Vilket år kom Caroline Polacheks 'Desire I Want to Turn Into You'?",o:["2019","2021","2023","2024"],a:2,d:3},
],

"🎵 Popmusik (allmänt)": [
  // ── LÄTT ──
  {q:"Vilket band sjöng 'Bohemian Rhapsody'?",o:["Led Zeppelin","The Beatles","Queen","Rolling Stones"],a:2,d:1},
  {q:"Vem sjunger 'Hello' (Adele 2015)?",o:["Beyoncé","Rihanna","Adele","Lady Gaga"],a:2,d:1},
  {q:"Vilket land kommer ABBA ifrån?",o:["Norge","Danmark","Sverige","Finland"],a:2,d:1},
  {q:"Vem sjunger 'Toxic' (Britney Spears)?",o:["Christina Aguilera","Britney Spears","Kylie Minogue","Pink"],a:1,d:1},
  {q:"Vilket band sjöng 'Mr. Brightside'?",o:["The Strokes","The Killers","Interpol","Franz Ferdinand"],a:1,d:1},
  {q:"Vem sjunger 'Rolling in the Deep'?",o:["Amy Winehouse","Adele","Duffy","Paloma Faith"],a:1,d:1},
  {q:"Vilket år vann ABBA Eurovision med 'Waterloo'?",o:["1972","1974","1976","1978"],a:1,d:1},
  {q:"Vem sjunger 'Poker Face' (Lady Gaga)?",o:["Katy Perry","Rihanna","Lady Gaga","Pink"],a:2,d:1},
  {q:"Vem sjunger 'Beautiful' (Christina Aguilera 2002)?",o:["Alicia Keys","Nelly Furtado","Christina Aguilera","Beyoncé"],a:2,d:1},
  {q:"Vilket band sjöng 'Livin' La Vida Loca'?",o:["Marc Anthony","Ricky Martin","Enrique Iglesias","Shakira"],a:1,d:1},
  {q:"Vem sjunger 'Since U Been Gone' (Kelly Clarkson)?",o:["Pink","Kelly Clarkson","Avril Lavigne","Alanis Morissette"],a:1,d:1},
  {q:"Vem sjunger 'Halo' (Beyoncé)?",o:["Alicia Keys","Rihanna","Beyoncé","Mariah Carey"],a:2,d:1},
  // ── MEDEL ──
  {q:"Vilket år kom Lady Gagas 'Born This Way' album?",o:["2009","2011","2013","2015"],a:1,d:2},
  {q:"Vem sjunger 'Gold Digger' (Kanye West 2005)?",o:["Jay-Z","Kanye West","Ludacris","T.I."],a:1,d:2},
  {q:"Vilket år kom Destiny's Child 'Survivor'?",o:["1999","2001","2003","2005"],a:1,d:2},
  {q:"Vem sjunger 'Crazy' (Gnarls Barkley 2006)?",o:["Cee Lo Green","Bruno Mars","John Legend","Common"],a:0,d:2},
  {q:"Vilket år kom Amy Winehouse 'Back to Black'?",o:["2004","2006","2008","2010"],a:1,d:2},
  {q:"Vem sjunger 'Beautiful' (Snoop Dogg 2003)?",o:["R Kelly","50 Cent","Snoop Dogg","Pharrell Williams"],a:2,d:2},
  {q:"Vilket år kom Usher 'Yeah!'?",o:["2002","2004","2006","2008"],a:1,d:2},
  {q:"Vem sjunger 'Irreplaceable' (Beyoncé 2006)?",o:["Rihanna","Alicia Keys","Beyoncé","Mary J Blige"],a:2,d:2},
  {q:"Vilket år kom Nelly Furtado 'Maneater'?",o:["2004","2006","2008","2010"],a:1,d:2},
  {q:"Vem sjunger 'Rehab' (Amy Winehouse 2006)?",o:["Amy Winehouse","Duffy","Adele","Paloma Faith"],a:0,d:2},
  {q:"Vilket år kom Keane 'Somewhere Only We Know'?",o:["2002","2004","2006","2008"],a:1,d:2},
  {q:"Vem sjunger 'Stronger' (What Doesn't Kill You, Kelly Clarkson)?",o:["Katy Perry","Kelly Clarkson","Pink","Rihanna"],a:1,d:2},
  // ── SVÅRT ──
  {q:"Vilket skivbolag gav ut Madonnas debutalbum?",o:["Columbia","Sire Records","Warner","Atlantic"],a:1,d:3},
  {q:"Vem producerade Rihannas 'Umbrella'?",o:["Timbaland","Tricky Stewart och The-Dream","Stargate","Rodney Jerkins"],a:1,d:3},
  {q:"Vilket år kom Aaliyahs 'Are You That Somebody'?",o:["1996","1998","2000","2002"],a:1,d:3},
  {q:"Vad heter Beyoncés skivbolag hon grundade?",o:["Parkwood Entertainment","Ivy Park Records","Lemonade Records","Lion Babe"],a:0,d:3},
  {q:"Vilket år kom Destinys Childs 'Say My Name'?",o:["1997","1999","2001","2003"],a:1,d:3},
  {q:"Vem producerade P!nks 'Get the Party Started'?",o:["Max Martin","Linda Perry","Dallas Austin","Babyface"],a:1,d:3},
  {q:"Vilket år kom Kylie Minogues 'Can't Get You Out of My Head'?",o:["1999","2001","2003","2005"],a:1,d:3},
  {q:"Vad heter Lady Gagas riktiga namn?",o:["Stefani Germanotta","Joanne Germanotta","Stefani Joanne Angelina Germanotta","Bella Germanotta"],a:2,d:3},
],

"🎸 Rock & Metal": [
  // ── LÄTT ──
  {q:"Vilket band sjöng 'Smells Like Teen Spirit'?",o:["Pearl Jam","Soundgarden","Nirvana","Alice in Chains"],a:2,d:1},
  {q:"Vilket band sjöng 'Back in Black'?",o:["AC/DC","Aerosmith","Kiss","Motörhead"],a:0,d:1},
  {q:"Vem sjunger i Guns N' Roses?",o:["Sebastian Bach","Steven Tyler","Axl Rose","David Coverdale"],a:2,d:1},
  {q:"Vilket band sjöng 'Yellow' (Coldplay)?",o:["Travis","Keane","Coldplay","Snow Patrol"],a:2,d:1},
  {q:"Vilket band sjöng 'Seven Nation Army' (White Stripes)?",o:["The Strokes","The White Stripes","The Black Keys","The Raconteurs"],a:1,d:1},
  {q:"Vem sjunger i Foo Fighters?",o:["Eddie Vedder","Chris Cornell","Dave Grohl","Scott Weiland"],a:2,d:1},
  {q:"Vilket band sjöng 'Come As You Are' (Nirvana)?",o:["Pearl Jam","Soundgarden","Nirvana","Alice in Chains"],a:2,d:1},
  {q:"Vilket band sjöng 'Dream On' (Aerosmith)?",o:["Bon Jovi","Aerosmith","Kiss","Twisted Sister"],a:1,d:1},
  {q:"Vilket band sjöng 'Roxanne' (The Police)?",o:["The Clash","The Police","Elvis Costello","Joe Jackson"],a:1,d:1},
  {q:"Vem sjunger i Led Zeppelin?",o:["Roger Plant","Robert Plant","Richard Plant","Ronald Plant"],a:1,d:1},
  {q:"Vilket band sjöng 'More Than a Feeling' (Boston)?",o:["Journey","Foreigner","Boston","REO Speedwagon"],a:2,d:1},
  {q:"Vilket band sjöng 'Killing in the Name' (RATM)?",o:["Rage Against the Machine","Soundgarden","Tool","System of a Down"],a:0,d:1},
  // ── MEDEL ──
  {q:"Vilket år kom Foo Fighters 'The Colour and the Shape'?",o:["1995","1997","1999","2001"],a:1,d:2},
  {q:"Vilket band sjöng 'Everlong' (Foo Fighters)?",o:["Pearl Jam","Foo Fighters","Green Day","The Offspring"],a:1,d:2},
  {q:"Vilket år kom Green Days 'American Idiot'?",o:["2002","2004","2006","2008"],a:1,d:2},
  {q:"Vilket band sjöng 'Numb' (Linkin Park)?",o:["Korn","Slipknot","Linkin Park","Papa Roach"],a:2,d:2},
  {q:"Vilket år kom The White Stripes 'Elephant'?",o:["2001","2003","2005","2007"],a:1,d:2},
  {q:"Vilket band sjöng 'Knights of Cydonia' (Muse)?",o:["Radiohead","Muse","Placebo","Biffy Clyro"],a:1,d:2},
  {q:"Vilket år kom Arctic Monkeys 'Whatever People Say I Am'?",o:["2004","2006","2008","2010"],a:1,d:2},
  {q:"Vilket band sjöng 'Do I Wanna Know' (Arctic Monkeys)?",o:["The Black Keys","Arctic Monkeys","The Strokes","Interpol"],a:1,d:2},
  {q:"Vilket år kom Radioheads 'OK Computer'?",o:["1995","1997","1999","2001"],a:1,d:2},
  {q:"Vilket band sjöng 'Maps' (Yeah Yeah Yeahs)?",o:["The Strokes","Interpol","Yeah Yeah Yeahs","Franz Ferdinand"],a:2,d:2},
  {q:"Vilket år kom Queens of the Stone Age 'Songs for the Deaf'?",o:["2000","2002","2004","2006"],a:1,d:2},
  {q:"Vilket band sjöng 'Schism' (Tool)?",o:["Rage Against the Machine","Tool","System of a Down","Mastodon"],a:1,d:2},
  // ── SVÅRT ──
  {q:"Vilket år kom Pixies 'Surfer Rosa'?",o:["1986","1988","1990","1992"],a:1,d:3},
  {q:"Vilket år kom My Bloody Valentine 'Isn't Anything'?",o:["1986","1988","1990","1992"],a:1,d:3},
  {q:"Vem producerade Nirvanas 'In Utero'?",o:["Butch Vig","Steve Albini","Jack Endino","Brendan O'Brien"],a:1,d:3},
  {q:"Vilket år kom Sonic Youth 'Goo'?",o:["1988","1990","1992","1994"],a:1,d:3},
  {q:"Vad heter The Edges riktiga namn i U2?",o:["Dave Evans","David Howell Evans","Paul Hewson","Adam Clayton"],a:1,d:3},
  {q:"Vilket år kom Nick Cave 'Murder Ballads'?",o:["1994","1996","1998","2000"],a:1,d:3},
  {q:"Vem spelar bas i Red Hot Chili Peppers?",o:["Dave Navarro","John Frusciante","Flea","Chad Smith"],a:2,d:3},
  {q:"Vilket år kom The National 'Alligator'?",o:["2003","2005","2007","2009"],a:1,d:3},
],

"🔥 Heavy Metal": [
  // ── LÄTT ──
  {q:"Vilket band sjöng 'Enter Sandman' (Metallica)?",o:["Slayer","Metallica","Megadeth","Anthrax"],a:1,d:1},
  {q:"Vem är sångare i Iron Maiden?",o:["Rob Halford","Ozzy Osbourne","Bruce Dickinson","Dio"],a:2,d:1},
  {q:"Vilket band sjöng 'Paranoid' (Black Sabbath)?",o:["Deep Purple","Black Sabbath","Judas Priest","Ozzy Osbourne"],a:1,d:1},
  {q:"Vilket band sjöng 'Welcome to the Jungle' (Guns N' Roses)?",o:["Mötley Crüe","Def Leppard","Guns N' Roses","Poison"],a:2,d:1},
  {q:"Vilket band sjöng 'Master of Puppets' (Metallica)?",o:["Slayer","Megadeth","Metallica","Anthrax"],a:2,d:1},
  {q:"Vem är sångare i Judas Priest?",o:["Ozzy Osbourne","Rob Halford","Bruce Dickinson","Ronnie James Dio"],a:1,d:1},
  {q:"Vilket band sjöng 'Ace of Spades' (Motörhead)?",o:["Black Sabbath","Deep Purple","Motörhead","Venom"],a:2,d:1},
  {q:"Vilket band sjöng 'Raining Blood' (Slayer)?",o:["Metallica","Megadeth","Slayer","Anthrax"],a:2,d:1},
  {q:"Vilket band sjöng 'War Pigs' (Black Sabbath)?",o:["Deep Purple","Black Sabbath","Judas Priest","Led Zeppelin"],a:1,d:1},
  {q:"Vilket band sjöng 'Breaking the Law' (Judas Priest)?",o:["Black Sabbath","Iron Maiden","Judas Priest","Motörhead"],a:2,d:1},
  {q:"Vilket band sjöng 'Chop Suey!' (System of a Down)?",o:["Slipknot","Korn","System of a Down","Linkin Park"],a:2,d:1},
  {q:"Vilket band sjöng 'Toxicity' (System of a Down)?",o:["Slipknot","Korn","System of a Down","Linkin Park"],a:2,d:1},
  // ── MEDEL ──
  {q:"Vilket år kom Metallicas 'Kill 'Em All'?",o:["1981","1983","1985","1987"],a:1,d:2},
  {q:"Vem grundade Megadeth efter att ha lämnat Metallica?",o:["Lars Ulrich","Kirk Hammett","Dave Mustaine","Jason Newsted"],a:2,d:2},
  {q:"Vilket band sjöng 'Cowboys from Hell' (Pantera)?",o:["Slayer","Pantera","Sepultura","Machine Head"],a:1,d:2},
  {q:"Vilket år kom Iron Maidens 'Number of the Beast'?",o:["1980","1982","1984","1986"],a:1,d:2},
  {q:"Vilket band sjöng 'Before I Forget' (Slipknot)?",o:["Korn","Slipknot","Disturbed","Drowning Pool"],a:1,d:2},
  {q:"Vilket år kom Slipknots debutalbum?",o:["1997","1999","2001","2003"],a:1,d:2},
  {q:"Vilket band sjöng 'Down with the Sickness' (Disturbed)?",o:["Slipknot","Disturbed","Drowning Pool","Papa Roach"],a:1,d:2},
  {q:"Vilket band sjöng 'Holy Wars' (Megadeth)?",o:["Slayer","Megadeth","Metallica","Anthrax"],a:1,d:2},
  {q:"Vilket år kom Pantera 'Far Beyond Driven'?",o:["1992","1994","1996","1998"],a:1,d:2},
  {q:"Vilket band sjöng 'The Pot' (Tool)?",o:["Rage Against the Machine","Tool","System of a Down","Mastodon"],a:1,d:2},
  {q:"Vilket band sjöng 'Laid to Rest' (Lamb of God)?",o:["Slipknot","Trivium","Lamb of God","Machine Head"],a:2,d:2},
  {q:"Vilket år kom Black Sabbaths debutalbum?",o:["1968","1970","1972","1974"],a:1,d:2},
  // ── SVÅRT ──
  {q:"Vilket år kom Slayers 'South of Heaven'?",o:["1986","1988","1990","1992"],a:1,d:3},
  {q:"Vad heter basisten i Metallica som dog 1986?",o:["Jason Newsted","Robert Trujillo","Ron McGovney","Cliff Burton"],a:3,d:3},
  {q:"Vilket år kom Bathory 'Under the Sign of the Black Mark'?",o:["1985","1987","1989","1991"],a:1,d:3},
  {q:"Vilket band sjöng 'Det Som En Gang Var' (Burzum)?",o:["Mayhem","Emperor","Burzum","Darkthrone"],a:2,d:3},
  {q:"Vilket år kom Entombed 'Left Hand Path'?",o:["1988","1990","1992","1994"],a:1,d:3},
  {q:"Vem producerade Metallicas 'Master of Puppets'?",o:["Rick Rubin","Flemming Rasmussen","Bob Rock","James Hetfield"],a:1,d:3},
  {q:"Vilket år kom Neurosis 'Through Silver in Blood'?",o:["1994","1996","1998","2000"],a:1,d:3},
  {q:"Vilket band sjöng 'Freezing Moon' (Mayhem)?",o:["Mayhem","Emperor","Burzum","Darkthrone"],a:0,d:3},
],

"🇸🇪 Svensk musik": [
  // ── LÄTT ──
  {q:"Vilket band sjöng 'The Sign' (Ace of Base)?",o:["Roxette","ABBA","Ace of Base","Robyn"],a:2,d:1},
  {q:"Vad heter Aviciis riktiga namn?",o:["Tim Bergling","Tim Svensson","Tim Lindqvist","Tim Berg"],a:0,d:1},
  {q:"Vilket band sjöng 'It Must Have Been Love' (Roxette)?",o:["ABBA","Ace of Base","Roxette","Carola"],a:2,d:1},
  {q:"Var är Håkan Hellström uppvuxen?",o:["Stockholm","Malmö","Göteborg","Uppsala"],a:2,d:1},
  {q:"Vilket band sjöng 'Lovefool' (The Cardigans)?",o:["Roxette","The Cardigans","Ace of Base","Sahara Hotnights"],a:1,d:1},
  {q:"Vem sjunger 'Euphoria' (Eurovision 2012)?",o:["Carola","Charlotte Perrelli","Loreen","Petra Mede"],a:2,d:1},
  {q:"Vilket band är Per Gessle med i?",o:["ABBA","Ace of Base","Roxette","The Hellacopters"],a:2,d:1},
  {q:"Vem sjunger 'Dancing on My Own' (Robyn)?",o:["Zara Larsson","Robyn","Tove Lo","MØ"],a:1,d:1},
  {q:"Vilket band sjöng 'Hate to Say I Told You So' (The Hives)?",o:["The Hellacopters","The Hives","Refused","Soundtrack of Our Lives"],a:1,d:1},
  {q:"Vem sjunger 'Karolina' (Håkan Hellström)?",o:["Håkan Hellström","Lars Winnerbäck","Bob Hund","Ulf Lundell"],a:0,d:1},
  {q:"Vem sjunger 'Sommartider' (Gyllene Tider)?",o:["Gyllene Tider","Roxette","Per Gessle solo","Bob Hund"],a:0,d:1},
  {q:"Vem sjunger 'Habits (Stay High)' (Tove Lo)?",o:["Zara Larsson","Robyn","Tove Lo","MØ"],a:2,d:1},
  // ── MEDEL ──
  {q:"Vad heter Max Martins riktiga namn?",o:["Martin Sandberg","Max Sandberg","Martin Carlsson","Max Karlsson"],a:0,d:2},
  {q:"Vilket år kom Robyn 'Body Talk'?",o:["2008","2010","2012","2014"],a:1,d:2},
  {q:"Vilket år kom Aviciis 'True'?",o:["2011","2013","2015","2017"],a:1,d:2},
  {q:"Vilken stad kommer The Hives ifrån?",o:["Stockholm","Göteborg","Fagersta","Örebro"],a:2,d:2},
  {q:"Vilket år debuterade Robyn?",o:["1993","1995","1997","1999"],a:1,d:2},
  {q:"Vilket år vann Loreen Eurovision andra gången?",o:["2021","2022","2023","2024"],a:2,d:2},
  {q:"Vilket år kom The Hives 'Veni Vidi Vicious'?",o:["1998","2000","2002","2004"],a:1,d:2},
  {q:"Vem sjunger 'I Follow Rivers' (Lykke Li)?",o:["Lykke Li","Robyn","Fever Ray","Little Dragon"],a:0,d:2},
  {q:"Vilket år kom Lykke Lis debutalbum 'Youth Novels'?",o:["2006","2008","2010","2012"],a:1,d:2},
  {q:"Vilket år grundades Swedish House Mafia?",o:["2002","2004","2006","2008"],a:2,d:2},
  {q:"Vem sjunger 'Glömde att du inte längre bodde här' (Lars Winnerbäck)?",o:["Lars Winnerbäck","Håkan Hellström","Bob Hund","Ulf Lundell"],a:0,d:2},
  {q:"Vilket år kom Refused 'The Shape of Punk to Come'?",o:["1996","1998","2000","2002"],a:1,d:2},
  // ── SVÅRT ──
  {q:"Vad heter The Cardigans sångerskas fullständiga namn?",o:["Nina Persson","Nina Carlsson","Nina Lindqvist","Nina Svensson"],a:0,d:3},
  {q:"Vilket år kom Kents debutalbum?",o:["1993","1995","1997","1999"],a:1,d:3},
  {q:"Vem är sångare i Soundtrack of Our Lives?",o:["Björn Olsson","Ebbot Lundberg","Martin Hederos","Ian Person"],a:1,d:3},
  {q:"Vilket år kom Lakehouse Brorby 'Brorby'?",o:["1999","2001","2003","2005"],a:1,d:3},
  {q:"Vilket år grundades ABBA?",o:["1970","1972","1974","1976"],a:1,d:3},
  {q:"Vad heter Björn Ulvaeus och Agnetha Fältskogs dotter?",o:["Linda Ulvaeus","Emma Ulvaeus","Lena Ulvaeus","Anna Ulvaeus"],a:0,d:3},
  {q:"Vilket år kom Zara Larssons debut-EP 'Introducing Zara Larsson'?",o:["2011","2012","2013","2014"],a:1,d:3},
  {q:"Vem sjunger 'Den vassa eggen' (kent)?",o:["Joakim Berg","Martin Rindell","Sami Sirviö","Markus Mustonen"],a:0,d:3},
],

"🎬 Movie Quiz": [
  // ── LÄTT ──
  {q:"Vem spelar Iron Man i MCU?",o:["Chris Evans","Robert Downey Jr.","Chris Hemsworth","Mark Ruffalo"],a:1,d:1},
  {q:"Vilket år kom Titanic?",o:["1995","1996","1997","1998"],a:2,d:1},
  {q:"Vem regisserade Jurassic Park?",o:["James Cameron","Steven Spielberg","George Lucas","Ridley Scott"],a:1,d:1},
  {q:"Vem spelar Forrest Gump?",o:["Tom Cruise","Tom Hanks","Tom Selleck","Tom Hardy"],a:1,d:1},
  {q:"Vilket år kom The Matrix?",o:["1997","1999","2001","2003"],a:1,d:1},
  {q:"Vem spelar Neo i Matrix?",o:["Brad Pitt","Keanu Reeves","Tom Cruise","Will Smith"],a:1,d:1},
  {q:"Vilket år kom The Dark Knight?",o:["2006","2008","2010","2012"],a:1,d:1},
  {q:"Vem regisserade Goodfellas?",o:["Francis Ford Coppola","Brian De Palma","Martin Scorsese","Quentin Tarantino"],a:2,d:1},
  {q:"Vem spelar Joker i Joker (2019)?",o:["Heath Ledger","Jared Leto","Joaquin Phoenix","Jack Nicholson"],a:2,d:1},
  {q:"Vilket år kom Avengers Endgame?",o:["2017","2019","2021","2023"],a:1,d:1},
  {q:"Vem spelar Thanos i MCU?",o:["Idris Elba","Tom Hiddleston","Josh Brolin","Michael Shannon"],a:2,d:1},
  {q:"Vem spelar i Barbie (2023)?",o:["Margot Robbie","Scarlett Johansson","Emma Stone","Jennifer Lawrence"],a:0,d:1},
  // ── MEDEL ──
  {q:"Vem regisserade The Dark Knight?",o:["Tim Burton","Joel Schumacher","Christopher Nolan","Zack Snyder"],a:2,d:2},
  {q:"Vem regisserade Pulp Fiction?",o:["Martin Scorsese","Quentin Tarantino","Coen Brothers","David Fincher"],a:1,d:2},
  {q:"Vilket år kom Fight Club?",o:["1997","1999","2001","2003"],a:1,d:2},
  {q:"Vem regisserade Fight Club?",o:["Quentin Tarantino","David Fincher","Christopher Nolan","Darren Aronofsky"],a:1,d:2},
  {q:"Vilket år vann Parasite Oscar för bästa film?",o:["2018","2019","2020","2021"],a:2,d:2},
  {q:"Vilket år kom Nolans Inception?",o:["2008","2010","2012","2014"],a:1,d:2},
  {q:"Vem regisserade Arrival (2016)?",o:["Christopher Nolan","Denis Villeneuve","Ridley Scott","David Fincher"],a:1,d:2},
  {q:"Vilket år kom Jordan Peeles Get Out?",o:["2015","2017","2019","2021"],a:1,d:2},
  {q:"Vem spelar i Dune (2021) som Paul Atreides?",o:["Tom Holland","Timothée Chalamet","Ansel Elgort","Lucas Hedges"],a:1,d:2},
  {q:"Vilket år kom Scorseses The Departed?",o:["2004","2006","2008","2010"],a:1,d:2},
  {q:"Vem regisserade Mad Max Fury Road?",o:["Michael Bay","George Miller","Ridley Scott","James Cameron"],a:1,d:2},
  {q:"Vilket år kom Nolans Oppenheimer?",o:["2021","2022","2023","2024"],a:2,d:2},
  // ── SVÅRT ──
  {q:"Vilket år kom Bergmans 'Det sjunde inseglet'?",o:["1955","1957","1959","1961"],a:1,d:3},
  {q:"Vem regisserade '2001: A Space Odyssey'?",o:["Steven Spielberg","Stanley Kubrick","Ridley Scott","Francis Ford Coppola"],a:1,d:3},
  {q:"Vilket år kom Andrei Tarkovskijs 'Solaris'?",o:["1970","1972","1974","1976"],a:1,d:3},
  {q:"Vem komponerade musiken till 'Psycho' (1960)?",o:["Bernard Herrmann","Ennio Morricone","Henry Mancini","John Williams"],a:0,d:3},
  {q:"Vilket år kom John Cassavetes 'A Woman Under the Influence'?",o:["1972","1974","1976","1978"],a:1,d:3},
  {q:"Vilket år kom Terrence Malicks 'Badlands'?",o:["1971","1973","1975","1977"],a:1,d:3},
  {q:"Vem regisserade 'The Conversation' (1974)?",o:["Martin Scorsese","Francis Ford Coppola","Brian De Palma","Sidney Lumet"],a:1,d:3},
  {q:"Vilket år kom Robert Altmans 'Nashville'?",o:["1973","1975","1977","1979"],a:1,d:3},
],

"📺 TV-serier": [
  // ── LÄTT ──
  {q:"Vilket TV-program handlade om vänner i New York?",o:["Seinfeld","Friends","Frasier","Will & Grace"],a:1,d:1},
  {q:"Vem spelar Walter White i Breaking Bad?",o:["Bryan Cranston","Aaron Paul","Bob Odenkirk","Dean Norris"],a:0,d:1},
  {q:"Vilket år kom Game of Thrones?",o:["2009","2011","2013","2015"],a:1,d:1},
  {q:"Vem spelar Tony Soprano i The Sopranos?",o:["Joe Pesci","Robert De Niro","James Gandolfini","Al Pacino"],a:2,d:1},
  {q:"Vilket år kom Stranger Things?",o:["2014","2016","2018","2020"],a:1,d:1},
  {q:"Vem spelar Daenerys Targaryen i Game of Thrones?",o:["Sophie Turner","Natalie Dormer","Emilia Clarke","Kit Harington"],a:2,d:1},
  {q:"Vem spelar Tommy Shelby i Peaky Blinders?",o:["Tom Hardy","Cillian Murphy","Idris Elba","James McAvoy"],a:1,d:1},
  {q:"Vilket år kom Squid Game?",o:["2019","2021","2022","2023"],a:1,d:1},
  {q:"Vem spelar Logan Roy i Succession?",o:["Brian Cox","Jeff Bridges","Anthony Hopkins","Gary Oldman"],a:0,d:1},
  {q:"Vilket år kom Breaking Bad?",o:["2006","2008","2010","2012"],a:1,d:1},
  {q:"Vem spelar Sheldon Cooper i The Big Bang Theory?",o:["Johnny Galecki","Jim Parsons","Kunal Nayyar","Simon Helberg"],a:1,d:1},
  {q:"Vilket år kom The Office USA?",o:["2003","2005","2007","2009"],a:1,d:1},
  // ── MEDEL ──
  {q:"Vilket år kom Succession?",o:["2016","2018","2020","2022"],a:1,d:2},
  {q:"Vilket år kom Better Call Saul?",o:["2013","2015","2017","2019"],a:1,d:2},
  {q:"Vilket år kom Twin Peaks?",o:["1988","1990","1992","1994"],a:1,d:2},
  {q:"Vem skapade Twin Peaks?",o:["Steven Spielberg","David Lynch och Mark Frost","Ridley Scott","Jim Jarmusch"],a:1,d:2},
  {q:"Vilket år kom Mad Men?",o:["2005","2007","2009","2011"],a:1,d:2},
  {q:"Vem skapade Mad Men?",o:["David Chase","David Simon","Vince Gilligan","Matthew Weiner"],a:3,d:2},
  {q:"Vilket år kom The Bear?",o:["2020","2022","2023","2024"],a:1,d:2},
  {q:"Vilket år kom Dark (tysk Netflix)?",o:["2015","2017","2019","2021"],a:1,d:2},
  {q:"Vem spelar Kendall Roy i Succession?",o:["Matthew Macfadyen","Jeremy Strong","Kieran Culkin","Nicholas Braun"],a:1,d:2},
  {q:"Vilket år kom Six Feet Under?",o:["1999","2001","2003","2005"],a:1,d:2},
  {q:"Vilket år kom Severance?",o:["2020","2022","2023","2024"],a:1,d:2},
  {q:"Vem skapade och spelar i Fleabag?",o:["Sharon Horgan","Phoebe Waller-Bridge","Lena Dunham","Mindy Kaling"],a:1,d:2},
  // ── SVÅRT ──
  {q:"Vem skapade Breaking Bad?",o:["David Chase","David Simon","Vince Gilligan","Matthew Weiner"],a:2,d:3},
  {q:"Vem skapade The Wire?",o:["David Chase","David Simon","Vince Gilligan","Ed Burns"],a:1,d:3},
  {q:"Vem skapade The Sopranos?",o:["David Chase","David Simon","Vince Gilligan","Matthew Weiner"],a:0,d:3},
  {q:"Vilket år kom Deadwood (HBO)?",o:["2002","2004","2006","2008"],a:1,d:3},
  {q:"Vem skapade Succession?",o:["David Chase","Jesse Armstrong","Vince Gilligan","Alan Ball"],a:1,d:3},
  {q:"Vilket år kom Mr Robot?",o:["2013","2015","2017","2019"],a:1,d:3},
  {q:"Vem skapade The Bear?",o:["Lena Waithe","Christopher Storer","Aziz Ansari","Donald Glover"],a:1,d:3},
  {q:"Vilket år kom Treme (HBO)?",o:["2008","2010","2012","2014"],a:1,d:3},
],

"🏰 Disney Klassiker": [
  // ── LÄTT ──
  {q:"Vad heter lejonungen i Lejonkungen?",o:["Simba","Nala","Mufasa","Pumba"],a:0,d:1},
  {q:"Vad heter fiskens pappa i Hitta Nemo?",o:["Martin","Marlin","Marcel","Marco"],a:1,d:1},
  {q:"Vad heter cowboyen i Toy Story?",o:["Buzz","Woody","Rex","Hamm"],a:1,d:1},
  {q:"Vad heter prinsessan i Törnrosa?",o:["Aurora","Ariel","Belle","Jasmine"],a:0,d:1},
  {q:"Vilket djur är Dumbo?",o:["Häst","Giraff","Elefant","Noshörning"],a:2,d:1},
  {q:"Vad heter rymdkommandot i Toy Story?",o:["Woody","Buzz Lightyear","Rex","Hamm"],a:1,d:1},
  {q:"Vad heter musen i Ratatouille?",o:["Emile","Gusteau","Remy","Anton"],a:2,d:1},
  {q:"Vad heter häxan i Den lilla sjöjungfrun?",o:["Maleficent","Ursula","Gothel","The Evil Queen"],a:1,d:1},
  {q:"Vad heter Timons kompis i Lejonkungen?",o:["Simba","Nala","Pumba","Rafiki"],a:2,d:1},
  {q:"Vilket år kom Lejonkungen?",o:["1990","1992","1994","1996"],a:2,d:1},
  {q:"Vad heter björnen i Djungelboken?",o:["Shere Khan","King Louie","Baloo","Akela"],a:2,d:1},
  {q:"Vad heter prinsessan i Törnrosa på engelska?",o:["Aurora","Ariel","Belle","Jasmine"],a:0,d:1},
  // ── MEDEL ──
  {q:"Vilket år kom Toy Story?",o:["1993","1995","1997","1999"],a:1,d:2},
  {q:"Vilket år kom Den lilla sjöjungfrun?",o:["1987","1989","1991","1993"],a:1,d:2},
  {q:"Vem röstade Woody i Toy Story?",o:["Tom Hanks","Tim Allen","Billy Crystal","John Goodman"],a:0,d:2},
  {q:"Vilket år kom Aladdin?",o:["1990","1992","1994","1996"],a:1,d:2},
  {q:"Vilket år kom Beauty and the Beast?",o:["1989","1991","1993","1995"],a:1,d:2},
  {q:"Vem röstade Scar i Lejonkungen?",o:["Tim Curry","Jeremy Irons","Ian McKellen","Alan Rickman"],a:1,d:2},
  {q:"Vem röstade Genie i Aladdin?",o:["Jim Carrey","Steve Martin","Robin Williams","Billy Crystal"],a:2,d:2},
  {q:"Vilket år kom Hitta Nemo?",o:["2001","2003","2005","2007"],a:1,d:2},
  {q:"Vem röstade Mufasa i Lejonkungen?",o:["Morgan Freeman","James Earl Jones","Samuel L Jackson","Denzel Washington"],a:1,d:2},
  {q:"Vilket år kom Mulan?",o:["1994","1996","1998","2000"],a:2,d:2},
  {q:"Vad heter Ariels pappa i Sjöjungfrun?",o:["Triton","Poseidon","Neptune","Aquaman"],a:0,d:2},
  {q:"Vilket år kom Hercules (Disney)?",o:["1995","1997","1999","2001"],a:1,d:2},
  // ── SVÅRT ──
  {q:"Vilket år kom Disneys 'Sleeping Beauty'?",o:["1957","1959","1961","1963"],a:1,d:3},
  {q:"Vilket år kom Disneys allra första film Snövit?",o:["1934","1937","1940","1943"],a:1,d:3},
  {q:"Vilket år kom Fantasia?",o:["1938","1940","1942","1944"],a:1,d:3},
  {q:"Vem komponerade musiken till Lejonkungen?",o:["Alan Menken","Howard Ashman","Hans Zimmer","Elton John"],a:2,d:3},
  {q:"Vem röstade Ursula i Sjöjungfrun?",o:["Cloris Leachman","Bette Midler","Pat Carroll","Rosie O'Donnell"],a:2,d:3},
  {q:"Vilket år kom Lady and the Tramp?",o:["1953","1955","1957","1959"],a:1,d:3},
  {q:"Vad heter kaninen i Bambi?",o:["Peter","Thumper","Flower","Faline"],a:1,d:3},
  {q:"Vilket år kom 101 Dalmatiner?",o:["1959","1961","1963","1965"],a:1,d:3},
],

"❄️ Frost & Moderna Disney": [
  // ── LÄTT ──
  {q:"Vad heter prinsessorna i Frost?",o:["Anna och Bella","Elsa och Anna","Elsa och Sofia","Anna och Kristina"],a:1,d:1},
  {q:"Vilket år kom Frost?",o:["2011","2013","2015","2017"],a:1,d:1},
  {q:"Vad heter snögubben i Frost?",o:["Olaf","Sven","Kristoff","Hans"],a:0,d:1},
  {q:"Vad heter rendjuret i Frost?",o:["Olaf","Kristoff","Sven","Hans"],a:2,d:1},
  {q:"Vad heter antagonisten i Frost?",o:["Kristoff","Hans","Duke of Weselton","Marshmallow"],a:1,d:1},
  {q:"Vilket år kom Encanto?",o:["2019","2021","2022","2023"],a:1,d:1},
  {q:"Vad heter halvguden i Vaiana?",o:["Tamatoa","Maui","Hei Hei","Te Ka"],a:1,d:1},
  {q:"Vilket år kom Zootopia?",o:["2014","2016","2018","2020"],a:1,d:1},
  {q:"Vilket år kom Coco (Pixar)?",o:["2015","2017","2019","2021"],a:1,d:1},
  {q:"Vilket år kom Inside Out?",o:["2013","2015","2017","2019"],a:1,d:1},
  {q:"Vad heter prinsessan i Brave?",o:["Raya","Moana","Merida","Vaiana"],a:2,d:1},
  {q:"Vad heter roboten i Big Hero 6?",o:["Baymax","Hiro","Tadashi","Go Go"],a:0,d:1},
  // ── MEDEL ──
  {q:"Vem sjunger Let It Go i Frost?",o:["Idina Menzel","Kristen Bell","Anna Kendrick","Lea Michele"],a:0,d:2},
  {q:"Vad heter Elsas och Annas mamma?",o:["Elsa","Iduna","Gerda","Ingrid"],a:1,d:2},
  {q:"Vilket år kom Frost 2?",o:["2017","2019","2021","2023"],a:1,d:2},
  {q:"Vilket år kom Vaiana/Moana?",o:["2014","2016","2018","2020"],a:1,d:2},
  {q:"Vilket år kom Inside Out 2?",o:["2022","2023","2024","2025"],a:2,d:2},
  {q:"Vilket år kom Raya and the Last Dragon?",o:["2019","2021","2022","2023"],a:1,d:2},
  {q:"Vad heter det nya känslot i Inside Out 2?",o:["Stress","Anxiety","Embarrassment","Envy"],a:1,d:2},
  {q:"Vilket år kom Pixars Luca?",o:["2019","2021","2022","2023"],a:1,d:2},
  {q:"Vad heter Flynn Rider egentligen i Tangled?",o:["Hans","Eugene Fitzherbert","Kristoff","Jack"],a:1,d:2},
  {q:"Vilket år kom Pixars Turning Red?",o:["2020","2022","2023","2024"],a:1,d:2},
  {q:"Vad heter räven i Zootopia?",o:["Jack","Nick","Fin","Rex"],a:1,d:2},
  {q:"Vilket år kom Big Hero 6?",o:["2012","2014","2016","2018"],a:1,d:2},
  // ── SVÅRT ──
  {q:"Vem regisserade Frost?",o:["John Lasseter","Pete Docter","Chris Buck och Jennifer Lee","Andrew Stanton"],a:2,d:3},
  {q:"Vad heter byn i Encanto?",o:["Casita","Colombia","La Familia","Madrigal"],a:0,d:3},
  {q:"Vad heter hästen i Tangled?",o:["Maximus","Samson","Angus","Achilles"],a:0,d:3},
  {q:"Vilket år kom Pixars Soul?",o:["2018","2020","2022","2024"],a:1,d:3},
  {q:"Vilket år kom Pixars Brave?",o:["2010","2012","2014","2016"],a:1,d:3},
  {q:"Vem sjunger Surface Pressure i Encanto?",o:["Luisa","Mirabel","Isabela","Dolores"],a:0,d:3},
  {q:"Vilket år kom Pixar Elemental?",o:["2021","2022","2023","2024"],a:2,d:3},
  {q:"Vilket år kom Disney Wish?",o:["2021","2022","2023","2024"],a:2,d:3},
],

"🎠 Barnfilmer & Ungdomsfilmer": [
  // ── LÄTT ──
  {q:"Vem spelar Harry Potter?",o:["Rupert Grint","Daniel Radcliffe","Tom Felton","Matthew Lewis"],a:1,d:1},
  {q:"Vilket år kom första Harry Potter-filmen?",o:["1999","2001","2003","2005"],a:1,d:1},
  {q:"Vad heter åsnan i Shrek?",o:["Donkey","Burro","Mule","Percy"],a:0,d:1},
  {q:"Vem spelar Katniss i Hunger Games?",o:["Emma Stone","Jennifer Lawrence","Shailene Woodley","Kristen Stewart"],a:1,d:1},
  {q:"Vem spelar Edward i Twilight?",o:["Taylor Lautner","Kellan Lutz","Robert Pattinson","Jackson Rathbone"],a:2,d:1},
  {q:"Vem spelar Bilbo i Hobbit?",o:["Ian McKellen","Martin Freeman","Benedict Cumberbatch","Richard Armitage"],a:1,d:1},
  {q:"Vilket år kom E.T.?",o:["1980","1982","1984","1986"],a:1,d:1},
  {q:"Vem spelar Kevin i Home Alone?",o:["Macaulay Culkin","Haley Joel Osment","Joseph Gordon-Levitt","Ryan Gosling"],a:0,d:1},
  {q:"Vem spelar Frodo i Sagan om Ringen?",o:["Sean Bean","Orlando Bloom","Elijah Wood","Dominic Monaghan"],a:2,d:1},
  {q:"Vilket år kom Shrek?",o:["1999","2001","2003","2005"],a:1,d:1},
  {q:"Vilket år kom Jumanji?",o:["1993","1995","1997","1999"],a:1,d:1},
  {q:"Vem skriver böckerna om Harry Potter?",o:["Roald Dahl","J.R.R. Tolkien","J.K. Rowling","C.S. Lewis"],a:2,d:1},
  // ── MEDEL ──
  {q:"Vilket år kom Sagan om Ringen del 1?",o:["1999","2001","2003","2005"],a:1,d:2},
  {q:"Vem spelar Dumbledore i HP ursprungligen?",o:["Richard Harris","Michael Gambon","Ian McKellen","Patrick Stewart"],a:0,d:2},
  {q:"Vilket år kom Home Alone?",o:["1988","1990","1992","1994"],a:1,d:2},
  {q:"Vilket år kom Narnia Häxan och lejonet?",o:["2003","2005","2007","2009"],a:1,d:2},
  {q:"Vilket år kom Twilight?",o:["2006","2008","2010","2012"],a:1,d:2},
  {q:"Vilket år kom Hobbit del 1?",o:["2010","2012","2014","2016"],a:1,d:2},
  {q:"Vilket år kom Divergent?",o:["2012","2014","2016","2018"],a:1,d:2},
  {q:"Vilket år kom The Maze Runner?",o:["2012","2014","2016","2018"],a:1,d:2},
  {q:"Vilket år kom Spirited Away?",o:["1999","2001","2003","2005"],a:1,d:2},
  {q:"Vem regisserade Spirited Away?",o:["Mamoru Oshii","Satoshi Kon","Isao Takahata","Hayao Miyazaki"],a:3,d:2},
  {q:"Vilket år kom My Neighbor Totoro?",o:["1986","1988","1990","1992"],a:1,d:2},
  {q:"Vilket år kom Coraline?",o:["2007","2009","2011","2013"],a:1,d:2},
  // ── SVÅRT ──
  {q:"Vem regisserade E.T.?",o:["George Lucas","Steven Spielberg","Robert Zemeckis","Ron Howard"],a:1,d:3},
  {q:"Vilket år kom The Neverending Story?",o:["1982","1984","1986","1988"],a:1,d:3},
  {q:"Vem spelar Jareth i Labyrinth (1986)?",o:["Sting","David Bowie","Roger Daltrey","Peter Gabriel"],a:1,d:3},
  {q:"Vilket år kom Princess Bride?",o:["1985","1987","1989","1991"],a:1,d:3},
  {q:"Vem regisserade Coraline?",o:["Tim Burton","Henry Selick","Pete Docter","Brad Bird"],a:1,d:3},
  {q:"Vilket år kom The Iron Giant?",o:["1997","1999","2001","2003"],a:1,d:3},
  {q:"Vem regisserade The Iron Giant?",o:["Brad Bird","Pete Docter","Andrew Stanton","Lee Unkrich"],a:0,d:3},
  {q:"Vilket år kom Howls Moving Castle?",o:["2002","2004","2006","2008"],a:1,d:3},
],

"⚽ Fotboll": [
  // ── LÄTT ──
  {q:"Vilket land vann fotbolls-VM 2022?",o:["Brasilien","Frankrike","Argentina","Portugal"],a:2,d:1},
  {q:"Vilket lag spelar hemma på Camp Nou?",o:["Real Madrid","Atletico Madrid","FC Barcelona","Valencia"],a:2,d:1},
  {q:"Vem vann Ballon d'Or flest gånger?",o:["Cristiano Ronaldo","Lionel Messi","Ronaldinho","Zidane"],a:1,d:1},
  {q:"Vilket land är Zlatan Ibrahimovic från?",o:["Danmark","Finland","Norge","Sverige"],a:3,d:1},
  {q:"Vilket lag spelar hemma på Anfield?",o:["Arsenal","Everton","Liverpool","Manchester City"],a:2,d:1},
  {q:"Vilket lag spelar hemma på Old Trafford?",o:["Arsenal","Liverpool","Manchester United","Chelsea"],a:2,d:1},
  {q:"Vilket lag vann Champions League 2023?",o:["Real Madrid","Manchester City","Bayern München","PSG"],a:1,d:1},
  {q:"Hur många spelare finns i ett fotbollslag?",o:["10","11","12","9"],a:1,d:1},
  {q:"Vilket land vann fotbolls-VM 2018?",o:["Tyskland","Brasilien","Frankrike","Argentina"],a:2,d:1},
  {q:"Vilket land vann fotbolls-VM 2014?",o:["Brasilien","Argentina","Frankrike","Tyskland"],a:3,d:1},
  {q:"Vilket land har vunnit flest VM-guld?",o:["Argentina","Tyskland","Italien","Brasilien"],a:3,d:1},
  {q:"Vem vann Ballon d'Or 2023?",o:["Erling Haaland","Kylian Mbappe","Lionel Messi","Vinicius Jr."],a:2,d:1},
  // ── MEDEL ──
  {q:"Vilket år vann Sverige VM-brons i fotboll?",o:["1950","1958","1966","1974"],a:1,d:2},
  {q:"Vilket år grundades Premier League?",o:["1988","1990","1992","1994"],a:2,d:2},
  {q:"Vilket lag vann Champions League flest gånger?",o:["Barcelona","Bayern München","Real Madrid","AC Milan"],a:2,d:2},
  {q:"Hur många VM har Brasilien vunnit?",o:["3","4","5","6"],a:2,d:2},
  {q:"Vem var toppscorar VM 2022?",o:["Messi","Mbappe","Benzema","Neymar"],a:1,d:2},
  {q:"Vilket lag spelar hemma på Allianz Arena?",o:["Borussia Dortmund","Bayern München","RB Leipzig","Bayer Leverkusen"],a:1,d:2},
  {q:"Vilket land vann EM 2021?",o:["Frankrike","England","Portugal","Italien"],a:3,d:2},
  {q:"Vilket land vann damernas VM 2023?",o:["USA","Australien","England","Spanien"],a:3,d:2},
  {q:"Vilket lag vann Champions League 2024?",o:["Liverpool","PSG","Bayern München","Real Madrid"],a:3,d:2},
  {q:"Vilket år kom VAR till Premier League?",o:["2017","2019","2021","2023"],a:1,d:2},
  {q:"Vilket år vann Frankrike sitt andra VM?",o:["2014","2016","2018","2020"],a:2,d:2},
  {q:"Vem vann Ballon d'Or 2022?",o:["Erling Haaland","Kylian Mbappe","Karim Benzema","Vinicius Jr."],a:2,d:2},
  // ── SVÅRT ──
  {q:"Vilket år spelades det allra första VM i fotboll?",o:["1926","1930","1934","1938"],a:1,d:3},
  {q:"Vilket år grundades FIFA?",o:["1900","1904","1908","1912"],a:1,d:3},
  {q:"Vad heter rekordet för flest mål i ett VM?",o:["Just Fontaine 1958","Pele 1970","Gerd Muller 1970","Ronaldo 2002"],a:0,d:3},
  {q:"Vilket lag vann Champions League 2012?",o:["Barcelona","Bayern München","Chelsea","Real Madrid"],a:2,d:3},
  {q:"Vilket år vann Grekland EM i fotboll?",o:["2000","2002","2004","2006"],a:2,d:3},
  {q:"Vilket år kom offside-regeln i fotboll?",o:["1863","1878","1896","1925"],a:3,d:3},
  {q:"Vilket år spelades Sverige sin första VM-match?",o:["1930","1934","1938","1950"],a:1,d:3},
  {q:"Vem är historiens mestmålsgörare i Champions League?",o:["Lionel Messi","Raul","Cristiano Ronaldo","Karim Benzema"],a:2,d:3},
],

"🏒 Ishockey": [
  // ── LÄTT ──
  {q:"Vad heter NHL:s mästarskapstrofe?",o:["Presidents Trophy","Hart Trophy","Stanley Cup","Conn Smythe"],a:2,d:1},
  {q:"Vad kallas Wayne Gretzky?",o:["The Boss","The Great One","The Rocket","Mr Hockey"],a:1,d:1},
  {q:"Hur många perioder spelas i ishockey?",o:["2","3","4","5"],a:1,d:1},
  {q:"Vilket lag spelar hemma på Scandinavium?",o:["Brynas IF","Frolunda","Djurgardens IF","MODO"],a:1,d:1},
  {q:"Vem håller rekord för flest NHL-poäng?",o:["Mario Lemieux","Mark Messier","Wayne Gretzky","Gordie Howe"],a:2,d:1},
  {q:"Hur många lag finns i NHL?",o:["28","30","32","34"],a:2,d:1},
  {q:"Vilket år vann Sverige OS-guld i ishockey?",o:["1994","2002","2006","2018"],a:0,d:1},
  {q:"Vilket land har vunnit flest VM i ishockey?",o:["Sverige","Finland","Kanada","Sovjet/Ryssland"],a:2,d:1},
  {q:"Vilket lag spelar i Gavle i SHL?",o:["Brynas IF","Frolunda","Djurgardens IF","HV71"],a:0,d:1},
  {q:"Vilket lag spelar i Jonkoping i SHL?",o:["Brynas IF","Frolunda","Djurgardens IF","HV71"],a:3,d:1},
  {q:"Hur lång är en NHL-period?",o:["15 min","20 min","25 min","30 min"],a:1,d:1},
  {q:"Vad heter trofén för bäste målvakt i NHL?",o:["Vezina Trophy","Hart Trophy","Norris Trophy","Calder Trophy"],a:0,d:1},
  // ── MEDEL ──
  {q:"Vilket lag vann Stanley Cup 2024?",o:["Colorado Avalanche","Florida Panthers","Edmonton Oilers","Rangers"],a:1,d:2},
  {q:"Vilket lag vann Stanley Cup 2022?",o:["Colorado Avalanche","Tampa Bay Lightning","Vegas Golden Knights","Florida Panthers"],a:0,d:2},
  {q:"Vilket lag vann Stanley Cup 2021?",o:["Colorado Avalanche","Tampa Bay Lightning","Vegas Golden Knights","Montreal"],a:1,d:2},
  {q:"Vilket år grundades NHL?",o:["1910","1917","1924","1930"],a:1,d:2},
  {q:"Vilket år kom Peter Forsberg till NHL?",o:["1993","1995","1997","1999"],a:1,d:2},
  {q:"Vilket år kom Nicklas Backstrom till NHL?",o:["2005","2007","2009","2011"],a:1,d:2},
  {q:"Vilket år kom William Nylander till NHL?",o:["2014","2016","2018","2020"],a:1,d:2},
  {q:"Vilket land vann OS-guld damernas ishockey 2022?",o:["Sverige","USA","Kanada","Finland"],a:1,d:2},
  {q:"Vilket år vann Sverige VM i ishockey senast?",o:["2016","2017","2018","2019"],a:1,d:2},
  {q:"Vilket lag spelar hemma på Bell Centre?",o:["Toronto Maple Leafs","Ottawa Senators","Montreal Canadiens","Quebec Nordiques"],a:2,d:2},
  {q:"Vilket år kom Elias Pettersson till NHL?",o:["2016","2018","2020","2022"],a:1,d:2},
  {q:"Vilket lag spelar hemma på Madison Square Garden?",o:["New York Rangers","New York Islanders","New Jersey Devils","Philadelphia Flyers"],a:0,d:2},
  // ── SVÅRT ──
  {q:"Vem scores mest poäng i NHL-historia en säsong?",o:["Mario Lemieux","Brett Hull","Wayne Gretzky 215p","Jari Kurri"],a:2,d:3},
  {q:"Vad heter trofén för mest poäng i NHL-säsong?",o:["Vezina Trophy","Hart Trophy","Art Ross Trophy","Maurice Richard Trophy"],a:2,d:3},
  {q:"Vad heter trofén för MVP i NHL playoffs?",o:["Vezina Trophy","Hart Trophy","Conn Smythe Trophy","Norris Trophy"],a:2,d:3},
  {q:"Vilket år grundades Brynas IF?",o:["1908","1920","1930","1940"],a:2,d:3},
  {q:"Vilket år grundades Djurgardens IF hockey?",o:["1912","1921","1930","1945"],a:1,d:3},
  {q:"Vilket år kom Viktor Hedman till NHL?",o:["2007","2009","2011","2013"],a:1,d:3},
  {q:"Vem är NHL:s all-time points-leader per match?",o:["Mario Lemieux","Wayne Gretzky","Mike Bossy","Brett Hull"],a:0,d:3},
  {q:"Vilket lag spelar hemma på TD Garden?",o:["New York Rangers","Philadelphia Flyers","Boston Bruins","Detroit Red Wings"],a:2,d:3},
],

"🏅 Sport (allmänt)": [
  // ── LÄTT ──
  {q:"Vem satte 100m-rekordet på 9.58 sek?",o:["Carl Lewis","Maurice Greene","Usain Bolt","Justin Gatlin"],a:2,d:1},
  {q:"Hur långt är ett marathonlopp?",o:["40 km","42.195 km","45 km","50 km"],a:1,d:1},
  {q:"Vilket land har flest OS-guld totalt?",o:["Ryssland","Kina","USA","Tyskland"],a:2,d:1},
  {q:"Vilken sport spelas i Wimbledon?",o:["Badminton","Squash","Tennis","Padel"],a:2,d:1},
  {q:"Vem vann Formel 1-VM 2021?",o:["Lewis Hamilton","Max Verstappen","Valtteri Bottas","Sebastian Vettel"],a:1,d:1},
  {q:"I vilken sport tävlar man i Tour de France?",o:["Triathlon","Löpning","Cykling","Simning"],a:2,d:1},
  {q:"Hur många Grand Slam finns det i tennis?",o:["2","3","4","5"],a:2,d:1},
  {q:"Vilket år hölls OS i Rio de Janeiro?",o:["2012","2014","2016","2018"],a:2,d:1},
  {q:"Vem vann Wimbledon damer 2023?",o:["Iga Swiatek","Coco Gauff","Marketa Vondrousova","Aryna Sabalenka"],a:2,d:1},
  {q:"Vilket år hölls OS i Tokyo?",o:["2018","2020","2021","2022"],a:2,d:1},
  {q:"Vem vann Formel 1-VM 2023?",o:["Lewis Hamilton","Max Verstappen","Charles Leclerc","Sergio Perez"],a:1,d:1},
  {q:"Vem vann Formel 1-VM 2024?",o:["Lewis Hamilton","Max Verstappen","Charles Leclerc","Lando Norris"],a:1,d:1},
  // ── MEDEL ──
  {q:"Hur många Grand Slam har Roger Federer vunnit?",o:["18","20","22","24"],a:1,d:2},
  {q:"Vem vann Formel 1-VM flest gånger?",o:["Ayrton Senna","Michael Schumacher","Lewis Hamilton","Sebastian Vettel"],a:1,d:2},
  {q:"Vilket land har flest Tour de France-segrar?",o:["Frankrike","Belgien","Spanien","USA"],a:2,d:2},
  {q:"Vem vann Tour de France 2024?",o:["Tadej Pogacar","Jonas Vingegaard","Egan Bernal","Primoz Roglic"],a:0,d:2},
  {q:"Vilket år hölls OS i Barcelona?",o:["1988","1992","1996","2000"],a:1,d:2},
  {q:"Vem vann Wimbledon herrar 2023?",o:["Novak Djokovic","Carlos Alcaraz","Jannik Sinner","Daniil Medvedev"],a:1,d:2},
  {q:"Vilket år hölls OS i Seoul?",o:["1984","1988","1992","1996"],a:1,d:2},
  {q:"Vilket land vann Rugby World Cup 2023?",o:["Nya Zeeland","Sydafrika","England","Frankrike"],a:1,d:2},
  {q:"Vem vann US Open tennis herrar 2023?",o:["Carlos Alcaraz","Novak Djokovic","Jannik Sinner","Daniil Medvedev"],a:0,d:2},
  {q:"Hur många set spelas i herrtennismatch på Grand Slam?",o:["3","5","4","2"],a:1,d:2},
  {q:"Vilket år vann Bjorn Borg sitt sista Wimbledon?",o:["1978","1980","1981","1983"],a:1,d:2},
  {q:"Vem satte maratonrekordet som bröt 2 timmar?",o:["Eliud Kipchoge","Kenenisa Bekele","Kelvin Kiptum","Geoffrey Kamworor"],a:0,d:2},
  // ── SVÅRT ──
  {q:"Vilket år hölls de allra första moderna OS?",o:["1894","1896","1900","1904"],a:1,d:3},
  {q:"Vilket år hölls OS i München där terrordådet skedde?",o:["1968","1972","1976","1980"],a:1,d:3},
  {q:"Vilket land har vunnit flest Formel 1-VM konstruktörer?",o:["Ferrari","McLaren","Mercedes","Williams"],a:0,d:3},
  {q:"Vilket år hölls de första vinter-OS?",o:["1920","1924","1928","1932"],a:1,d:3},
  {q:"Vem vann French Open herrar 2023?",o:["Novak Djokovic","Carlos Alcaraz","Casper Ruud","Holger Rune"],a:0,d:3},
  {q:"Vad heter Formel 1-banan i Monaco?",o:["Circuit de Monaco","Monte Carlo Circuit","Monaco GP Circuit","Circuit des Princes"],a:0,d:3},
  {q:"Vilket år grundades FIFA?",o:["1900","1904","1908","1912"],a:1,d:3},
  {q:"Vilket år vann Sverige damernas VM i fotboll?",o:["Sverige har aldrig vunnit","1991","1995","2003"],a:0,d:3},
],

"💻 Teknik & IT": [
  // ── LÄTT ──
  {q:"Vilket företag tillverkar PlayStation?",o:["Microsoft","Nintendo","Sony","Sega"],a:2,d:1},
  {q:"Vilket år lanserades första iPhone?",o:["2005","2007","2009","2011"],a:1,d:1},
  {q:"Vilket företag grundade Bill Gates?",o:["Apple","Amazon","Microsoft","Google"],a:2,d:1},
  {q:"Vilket år grundades Google?",o:["1996","1998","2000","2002"],a:1,d:1},
  {q:"Vad heter Apples smarta assistent?",o:["Cortana","Alexa","Google","Siri"],a:3,d:1},
  {q:"Vilket år grundades Apple?",o:["1974","1976","1978","1980"],a:1,d:1},
  {q:"Vad heter Googles mobiloperativsystem?",o:["iOS","Windows Mobile","Android","HarmonyOS"],a:2,d:1},
  {q:"Vilket år grundades Facebook?",o:["2002","2004","2006","2008"],a:1,d:1},
  {q:"Vad heter Amazons smarta assistent?",o:["Siri","Cortana","Alexa","Google"],a:2,d:1},
  {q:"Vilket år kom YouTube?",o:["2003","2005","2007","2009"],a:1,d:1},
  {q:"Vad heter Microsofts molntjänst?",o:["AWS","Google Cloud","Azure","IBM Cloud"],a:2,d:1},
  {q:"Vilket år köpte Elon Musk Twitter?",o:["2020","2021","2022","2023"],a:2,d:1},
  // ── MEDEL ──
  {q:"Vilket år kom Instagram?",o:["2008","2010","2012","2014"],a:1,d:2},
  {q:"Vilket år lanserades ChatGPT?",o:["2020","2021","2022","2023"],a:2,d:2},
  {q:"Vad heter Metas VR-headset?",o:["HoloLens","Vision Pro","Quest","Vive"],a:2,d:2},
  {q:"Vilket år kom TikTok globalt?",o:["2014","2016","2018","2020"],a:2,d:2},
  {q:"Vem grundade LinkedIn?",o:["Bill Gates","Reid Hoffman","Mark Zuckerberg","Jack Dorsey"],a:1,d:2},
  {q:"Vilket år grundades OpenAI?",o:["2013","2015","2017","2019"],a:1,d:2},
  {q:"Vem grundade SpaceX?",o:["Jeff Bezos","Richard Branson","Elon Musk","Larry Page"],a:2,d:2},
  {q:"Vilket år lanserades Apples M1-chip?",o:["2018","2020","2022","2024"],a:1,d:2},
  {q:"Vilket år grundades Netflix?",o:["1995","1997","1999","2001"],a:1,d:2},
  {q:"Vilket år grundades Uber?",o:["2007","2009","2011","2013"],a:1,d:2},
  {q:"Vilket år grundades NVIDIA?",o:["1989","1991","1993","1995"],a:2,d:2},
  {q:"Vilket år kom WhatsApp?",o:["2007","2009","2011","2013"],a:1,d:2},
  // ── SVÅRT ──
  {q:"Vem uppfann World Wide Web?",o:["Bill Gates","Steve Jobs","Tim Berners-Lee","Vint Cerf"],a:2,d:3},
  {q:"Vilket år kom första versionen av Linux?",o:["1989","1991","1993","1995"],a:1,d:3},
  {q:"Vad heter protokollet bakom internet?",o:["HTTP","TCP/IP","FTP","SMTP"],a:1,d:3},
  {q:"Vilket år grundades Intel?",o:["1964","1966","1968","1970"],a:2,d:3},
  {q:"Vad heter Alan Turings test för AI?",o:["Turing Test","Intelligence Test","Machine Test","Imitation Game"],a:0,d:3},
  {q:"Vilket år kom Python 3.0?",o:["2006","2008","2010","2012"],a:1,d:3},
  {q:"Vilket år grundades GitHub?",o:["2006","2008","2010","2012"],a:1,d:3},
  {q:"Vilket år kom Docker?",o:["2011","2013","2015","2017"],a:1,d:3},
],

"🔬 Vetenskap & Natur": [
  // ── LÄTT ──
  {q:"Vilket är det hårdaste naturliga materialet?",o:["Guld","Granit","Diamant","Järn"],a:2,d:1},
  {q:"Hur många planeter finns i solsystemet?",o:["7","8","9","10"],a:1,d:1},
  {q:"Vad är den kemiska formeln för vatten?",o:["HO","H2O","H2O2","HO2"],a:1,d:1},
  {q:"Vilket grundämne har kemisk symbol Au?",o:["Silver","Aluminium","Guld","Koppar"],a:2,d:1},
  {q:"Vad är DNA förkortning för?",o:["Proteinkomplex","Ribosomalt RNA","Deoxiribonukleinsyra","Adenosintrifosfat"],a:2,d:1},
  {q:"Hur många kromosompar har en människa?",o:["21","23","25","46"],a:1,d:1},
  {q:"Vad är ljusets hastighet?",o:["200000 km/s","300000 km/s","400000 km/s","500000 km/s"],a:1,d:1},
  {q:"Vilket grundämne har kemisk symbol Fe?",o:["Fluor","Fosfor","Järn","Francium"],a:2,d:1},
  {q:"Vad är den stora planeten i solsystemet?",o:["Saturn","Uranus","Jupiter","Neptunus"],a:2,d:1},
  {q:"Hur många grundämnen finns i periodiska systemet?",o:["98","108","118","128"],a:2,d:1},
  {q:"Vad är den kemiska formeln för koldioxid?",o:["CO","CO2","C2O","C2O2"],a:1,d:1},
  {q:"Vilket grundämne är flytande vid rumstemperatur (ej kvicksilver)?",o:["Brom","Jod","Fosfor","Selen"],a:0,d:1},
  // ── MEDEL ──
  {q:"Vilket år publicerade Darwin Arternas uppkomst?",o:["1849","1859","1869","1879"],a:1,d:2},
  {q:"Hur gammal är universum?",o:["8 miljarder år","10 miljarder år","13.8 miljarder år","20 miljarder år"],a:2,d:2},
  {q:"Vad är teorin om universums ursprung?",o:["Steady State","Big Crunch","Big Bang","Inflation"],a:2,d:2},
  {q:"Vilket år sände James Webb-teleskopet sina första bilder?",o:["2020","2021","2022","2023"],a:2,d:2},
  {q:"Hur djup är Marianergraven?",o:["7 km","9 km","11 km","13 km"],a:2,d:2},
  {q:"Vilket år publicerade Einstein sin relativitetsteori?",o:["1900","1905","1910","1915"],a:1,d:2},
  {q:"Vad är den kemiska formeln för glukos?",o:["C5H10O5","C6H12O6","C6H10O5","C12H22O11"],a:1,d:2},
  {q:"Vilket år togs det första fotot av ett svart hål?",o:["2015","2017","2019","2021"],a:2,d:2},
  {q:"Vad heter den process där atomer klyvs?",o:["Fusion","Fission","Klyvning","Radioaktivitet"],a:1,d:2},
  {q:"Vad är absolut nollpunkt i Kelvin?",o:["0 K","minus 100 K","100 K","273 K"],a:0,d:2},
  {q:"Hur lång tid tar ljuset att nå oss från solen?",o:["Ca 4 min","Ca 8 min","Ca 16 min","Ca 30 min"],a:1,d:2},
  {q:"Vilket grundämne har atomnummer 79?",o:["Platina","Silver","Guld","Koppar"],a:2,d:2},
  // ── SVÅRT ──
  {q:"Vad är Heisenbergs osäkerhetsprincip?",o:["Man kan inte mäta läge och hastighet exakt samtidigt","Ljusets hastighet är konstant","Energi kan inte skapas eller förstöras","Materia och energi är ekvivalenta"],a:0,d:3},
  {q:"Vilket år kom CRISPR-Cas9 teknologin?",o:["2009","2012","2015","2018"],a:1,d:3},
  {q:"Vad heter den svagaste av de fyra naturkrafterna?",o:["Stark kärnkraft","Svag kärnkraft","Elektromagnetism","Gravitation"],a:3,d:3},
  {q:"Vilket år fick Marie Curie sitt andra Nobelpris?",o:["1903","1907","1911","1915"],a:2,d:3},
  {q:"Vad är Schrödingers katt?",o:["En verklig katt","Ett tankeexperiment om kvantöverlagring","En matematisk formel","En typ av subatomär partikel"],a:1,d:3},
  {q:"Vilket år sände Voyager 1 ut?",o:["1973","1975","1977","1979"],a:2,d:3},
  {q:"Vad heter Jupiters störst måne?",o:["Europa","Ganymedes","Callisto","Io"],a:1,d:3},
  {q:"Hur lång tid tar Neptunus att kretsa runt solen?",o:["84 år","100 år","165 år","248 år"],a:2,d:3},
],

"🌍 Geografi & Historia": [
  // ── LÄTT ──
  {q:"Vad är Frankrikes huvudstad?",o:["Lyon","Marseille","Paris","Bordeaux"],a:2,d:1},
  {q:"Vilket land är störst till ytan?",o:["USA","Kanada","Kina","Ryssland"],a:3,d:1},
  {q:"Vad är Australiens huvudstad?",o:["Sydney","Melbourne","Canberra","Brisbane"],a:2,d:1},
  {q:"Vilket år föll Berlinmuren?",o:["1987","1989","1991","1993"],a:1,d:1},
  {q:"Vilket land har flest invånare?",o:["Indien","Kina","USA","Indonesien"],a:0,d:1},
  {q:"Vad är Japans huvudstad?",o:["Osaka","Kyoto","Tokyo","Hiroshima"],a:2,d:1},
  {q:"Vad är Kanadas huvudstad?",o:["Toronto","Montreal","Vancouver","Ottawa"],a:3,d:1},
  {q:"Vilket år landade människan på månen?",o:["1967","1969","1971","1973"],a:1,d:1},
  {q:"Vilket år började andra världskriget?",o:["1937","1939","1941","1943"],a:1,d:1},
  {q:"Vilket land var tidigare känt som Persien?",o:["Irak","Iran","Turkiet","Syrien"],a:1,d:1},
  {q:"Vilket är världens högsta berg?",o:["K2","Mont Blanc","Mount Everest","Kilimanjaro"],a:2,d:1},
  {q:"Vilket är världens minsta land?",o:["Monaco","San Marino","Vatikanstaten","Liechtenstein"],a:2,d:1},
  // ── MEDEL ──
  {q:"Vilket år grundades FN?",o:["1943","1945","1947","1949"],a:1,d:2},
  {q:"Vilket år sprack Sovjet upp?",o:["1989","1991","1993","1995"],a:1,d:2},
  {q:"Vilket år skedde Franska revolutionen?",o:["1776","1789","1799","1815"],a:1,d:2},
  {q:"Vilken stad var Osmanska rikets huvudstad?",o:["Ankara","Bagdad","Konstantinopel","Kairo"],a:2,d:2},
  {q:"Vilket år förenades Öst- och Västtyskland?",o:["1988","1990","1992","1994"],a:1,d:2},
  {q:"Vilket år byggdes Berlinmuren?",o:["1959","1961","1963","1965"],a:1,d:2},
  {q:"Hur många länder finns i Afrika?",o:["44","54","64","74"],a:1,d:2},
  {q:"Vilket år inträffade Tjernobylolyckan?",o:["1984","1986","1988","1990"],a:1,d:2},
  {q:"Vilket land kallades Ceylon?",o:["Indien","Bangladesh","Myanmar","Sri Lanka"],a:3,d:2},
  {q:"Vilket är Afrikas längsta flod?",o:["Kongo","Niger","Zambezi","Nilen"],a:3,d:2},
  {q:"Vilket år grundades EU formellt i Maastricht?",o:["1989","1991","1993","1995"],a:2,d:2},
  {q:"Vilket år startade Koreakriget?",o:["1948","1950","1952","1954"],a:1,d:2},
  // ── SVÅRT ──
  {q:"Vilket år grundades Romerska riket som kejsardöme?",o:["753 f.Kr.","509 f.Kr.","264 f.Kr.","27 f.Kr."],a:3,d:3},
  {q:"Vilket år grundades NATO?",o:["1945","1947","1949","1951"],a:2,d:3},
  {q:"Vilket land var det sista att avskaffa slaveriet?",o:["USA","Brasilien","Saudi-Arabien","Mauretanien"],a:3,d:3},
  {q:"Vilket år kom Magna Carta?",o:["1204","1215","1228","1240"],a:1,d:3},
  {q:"Vilket år skedde den ryska revolutionen?",o:["1915","1917","1919","1921"],a:1,d:3},
  {q:"Vilket år grundades Kinas kommunistparti?",o:["1919","1921","1925","1930"],a:1,d:3},
  {q:"Vilket år startade Vietnamkriget?",o:["1953","1955","1957","1959"],a:1,d:3},
  {q:"Vilket år slöts Wienkongressen?",o:["1810","1815","1820","1825"],a:1,d:3},
],

"🍕 Mat & Dryck": [
  // ── LÄTT ──
  {q:"Vad är huvudingrediensen i guacamole?",o:["Tomat","Avokado","Lime","Koriander"],a:1,d:1},
  {q:"Vilket land kommer sushi ifrån?",o:["Kina","Korea","Japan","Thailand"],a:2,d:1},
  {q:"Vilket land kommer pizza ifrån?",o:["Frankrike","Spanien","Italien","Grekland"],a:2,d:1},
  {q:"Vad är en cappuccino?",o:["Bara mjölk","Espresso och ångad mjölk","Te och mjölk","Kaffe och grädde"],a:1,d:1},
  {q:"Vilket land kommer paella ifrån?",o:["Italien","Portugal","Frankrike","Spanien"],a:3,d:1},
  {q:"Vad är hummus gjort av?",o:["Linser","Kikärtor","Bönor","Ärtor"],a:1,d:1},
  {q:"Vilket land producerar mest olivolja?",o:["Italien","Spanien","Grekland","Turkiet"],a:1,d:1},
  {q:"Vad är umami?",o:["Sött","Surt","Salt","Den femte grundsmaken"],a:3,d:1},
  {q:"Vilket land är känt för Moules-frites?",o:["Frankrike","Holland","Belgien","Luxemburg"],a:2,d:1},
  {q:"Vad heter den japanska rätten med nudlar i buljong?",o:["Udon","Soba","Ramen","Somen"],a:2,d:1},
  {q:"Vilket land producerar mest vin?",o:["Frankrike","Spanien","Italien","USA"],a:2,d:1},
  {q:"Vad kallas den japanska rätten med rå fisk?",o:["Sushi","Sashimi","Ramen","Udon"],a:1,d:1},
  // ── MEDEL ──
  {q:"Vad heter den franska rätten med sniglar?",o:["Foie gras","Bouillabaisse","Escargot","Soufflé"],a:2,d:2},
  {q:"Vilket land kom kebab ifrån?",o:["Libanon","Turkiet","Irak","Iran"],a:1,d:2},
  {q:"Vad är en Old Fashioned gjord på?",o:["Vodka angostura och socker","Bourbon eller rye angostura och socker","Rum angostura och socker","Gin angostura och socker"],a:1,d:2},
  {q:"Vilket land kom kimchi ifrån?",o:["Japan","Kina","Korea","Vietnam"],a:2,d:2},
  {q:"Vad heter det peruanska rätten med citrusmarinerad fisk?",o:["Ceviche","Tiradito","Leche de tigre","Anticucho"],a:0,d:2},
  {q:"Vilket land uppfann champagnen?",o:["Spanien","Italien","Frankrike","Belgien"],a:2,d:2},
  {q:"Vilket år grundades McDonalds?",o:["1940","1948","1955","1960"],a:0,d:2},
  {q:"Vad heter den mexicanska rätten fylld tortilla?",o:["Burrito","Taco","Quesadilla","Enchilada"],a:2,d:2},
  {q:"Vad är Cointreau?",o:["En rom","En apelsinlikör","En vodka","En gin"],a:1,d:2},
  {q:"Vad heter den koreanska BBQ-rätten?",o:["Bibimbap","Bulgogi","Japchae","Gamjatang"],a:1,d:2},
  {q:"Vilket land uppfann ölet historiskt?",o:["England","Mesopotamien","Egypten","Kina"],a:1,d:2},
  {q:"Vad heter den schweiziska rätten av smält ost?",o:["Raclette","Fondue","Rösti","Schnitzel"],a:1,d:2},
  // ── SVÅRT ──
  {q:"Vad är en Maillard-reaktion?",o:["Kemisk reaktion vid jäsning","Brunningsreaktion vid upphettning","Saltningsprocess","Konserveringsmetod"],a:1,d:3},
  {q:"Vilket land producerar Grand Cru-viner?",o:["Italien","Spanien","Frankrike","Portugal"],a:2,d:3},
  {q:"Vilket år grundades Michelin-guiden?",o:["1895","1900","1910","1920"],a:1,d:3},
  {q:"Vad är koji i japansk matlagning?",o:["En fisk","En svamp och mögel","En sås","En ristyp"],a:1,d:3},
  {q:"Vad heter den japanska metoden att slakta fisk humant?",o:["Ikejime","Sashimi","Katsu","Mirin"],a:0,d:3},
  {q:"Vilket år grundades Guinness?",o:["1749","1759","1769","1779"],a:1,d:3},
  {q:"Vad heter Burgundys finaste rödvinsdruva?",o:["Cabernet Sauvignon","Pinot Noir","Merlot","Syrah"],a:1,d:3},
  {q:"Vad heter den katalanska desserten med bränt socker?",o:["Creme brulee","Crema catalana","Flan","Panna cotta"],a:1,d:3},
],

"🎭 Allmänkultur & Käpphäst": [
  // ── LÄTT – Allmänkultur ──
  {q:"Vem målade Mona Lisa?",o:["Michelangelo","Raphael","Leonardo da Vinci","Botticelli"],a:2,d:1},
  {q:"Vem skrev Romeo och Julia?",o:["Charles Dickens","Jane Austen","William Shakespeare","Homer"],a:2,d:1},
  {q:"Vem var den första att gå på månen?",o:["Buzz Aldrin","Neil Armstrong","Yuri Gagarin","John Glenn"],a:1,d:1},
  {q:"Vem är känd för teorin om relativitet?",o:["Isaac Newton","Niels Bohr","Albert Einstein","Max Planck"],a:2,d:1},
  {q:"Vem skapade Sherlock Holmes?",o:["Agatha Christie","Arthur Conan Doyle","Edgar Allan Poe","Wilkie Collins"],a:1,d:1},
  {q:"Vem skulpterade Davidskulpturen (renässansen)?",o:["Raphael","Leonardo da Vinci","Michelangelo","Donatello"],a:2,d:1},
  {q:"Vem målade Skrik?",o:["Vincent van Gogh","Paul Gauguin","Edvard Munch","Gustav Klimt"],a:2,d:1},
  // ── LÄTT – Käpphästar ──
  {q:"Vilket år kom brädspelet Catan?",o:["1991","1993","1995","1997"],a:2,d:1},
  {q:"Vilket är det mest sålda brädspelet i världen?",o:["Schack","Monopol","Scrabble","Cluedo"],a:1,d:1},
  {q:"Vilket år lanserades Twitch?",o:["2009","2011","2013","2015"],a:1,d:1},
  {q:"Vem skapade Simpsons?",o:["Seth MacFarlane","Mike Judge","Matt Groening","Trey Parker"],a:2,d:1},
  {q:"Vilket år kom Netflix som streamingtjänst?",o:["2005","2007","2009","2011"],a:1,d:1},
  // ── MEDEL – Allmänkultur ──
  {q:"Vem komponerade Symfoni nr 9?",o:["Mozart","Brahms","Beethoven","Schubert"],a:2,d:2},
  {q:"Vilket år dog Beethoven?",o:["1820","1823","1827","1831"],a:2,d:2},
  {q:"Vem skulpterade Tänkaren?",o:["Michelangelo","Bernini","Auguste Rodin","Donatello"],a:2,d:2},
  {q:"Vem målade Nattvakten?",o:["Vermeer","Rembrandt","Frans Hals","Jan van Eyck"],a:1,d:2},
  {q:"Vem skrev Brott och straff?",o:["Leo Tolstoj","Anton Tjechov","Fjodor Dostojevskij","Ivan Turgenev"],a:2,d:2},
  {q:"Vilket år dog Mozart?",o:["1787","1789","1791","1793"],a:2,d:2},
  {q:"Vilket år dog Shakespeare?",o:["1610","1613","1616","1619"],a:2,d:2},
  // ── MEDEL – Käpphästar ──
  {q:"Vilket år kom Dungeons and Dragons?",o:["1970","1972","1974","1976"],a:2,d:2},
  {q:"Vilket år lanserades Magic the Gathering?",o:["1989","1991","1993","1995"],a:2,d:2},
  {q:"Vilket år kom Pokemon Go?",o:["2014","2016","2018","2020"],a:1,d:2},
  {q:"Vilket år grundades Reddit?",o:["2003","2005","2007","2009"],a:1,d:2},
  {q:"Vilket år kom Minecraft?",o:["2007","2009","2011","2013"],a:1,d:2},
  // ── SVÅRT – Allmänkultur ──
  {q:"Vilket år kom Prousts 'På spaning efter den tid som flytt'?",o:["1909","1913","1917","1921"],a:1,d:3},
  {q:"Vilket år kom Kafkas 'Processen'?",o:["1915","1920","1925","1930"],a:2,d:3},
  {q:"Vem komponerade 'Rite of Spring'?",o:["Debussy","Ravel","Stravinsky","Prokofiev"],a:2,d:3},
  {q:"Vilket år dog Leonardo da Vinci?",o:["1513","1519","1525","1531"],a:1,d:3},
  {q:"Vem skrev 'Ulysses' (James Joyce)?",o:["Virginia Woolf","D.H. Lawrence","James Joyce","T.S. Eliot"],a:2,d:3},
  // ── SVÅRT – Käpphästar ──
  {q:"Vilket år kom det första moderna World of Warcraft?",o:["2002","2004","2006","2008"],a:1,d:3},
  {q:"Vad heter världens äldsta aktiva destilleri (whisky)?",o:["Glenfarclas","Bowmore","Glenturret","Bushmills"],a:2,d:3},
  {q:"Vilket år lanserades Discord?",o:["2013","2015","2017","2019"],a:1,d:3},
],

"🌈 Blandat / Mix": [
  // ── LÄTT ──
  {q:"Vilket land kom Ikea ifrån?",o:["Danmark","Norge","Finland","Sverige"],a:3,d:1},
  {q:"Vad är PI ungefär?",o:["2.14","3.14","3.41","4.14"],a:1,d:1},
  {q:"Vilket år dog Elvis Presley?",o:["1975","1977","1979","1981"],a:1,d:1},
  {q:"Vem målade Guernica?",o:["Salvador Dalí","Joan Miró","Pablo Picasso","Francis Bacon"],a:2,d:1},
  {q:"Vilket land uppfann papperet?",o:["Japan","Indien","Kina","Egypten"],a:2,d:1},
  {q:"Vem skapade Simpsons?",o:["Seth MacFarlane","Mike Judge","Matt Groening","Trey Parker"],a:2,d:1},
  {q:"Vilket år dog Freddie Mercury?",o:["1989","1991","1993","1995"],a:1,d:1},
  {q:"Vilket land vann fotbolls-VM 2022?",o:["Brasilien","Frankrike","Argentina","Portugal"],a:2,d:1},
  {q:"Vem sjunger Bad Guy (Billie Eilish)?",o:["Ariana Grande","Billie Eilish","Dua Lipa","Olivia Rodrigo"],a:1,d:1},
  {q:"Vilket år kom första iPhone?",o:["2005","2007","2009","2011"],a:1,d:1},
  {q:"Vilket år landade människan på månen?",o:["1967","1969","1971","1973"],a:1,d:1},
  {q:"Vad heter det minsta landet i världen?",o:["Monaco","San Marino","Vatikanstaten","Liechtenstein"],a:2,d:1},
  // ── MEDEL ──
  {q:"Vilket år grundades Google?",o:["1996","1998","2000","2002"],a:1,d:2},
  {q:"Vilket år kom Breaking Bad?",o:["2006","2008","2010","2012"],a:1,d:2},
  {q:"Vilket land vann EM 2024?",o:["Frankrike","England","Spanien","Portugal"],a:2,d:2},
  {q:"Vilket grundämne har kemisk symbol H?",o:["Helium","Väte","Hafnium","Holmium"],a:1,d:2},
  {q:"Vem vann Formel 1-VM 2021?",o:["Lewis Hamilton","Max Verstappen","Valtteri Bottas","Sebastian Vettel"],a:1,d:2},
  {q:"Hur många bitar ingår i en byte?",o:["4","6","8","10"],a:2,d:2},
  {q:"Vilket år kom Squid Game?",o:["2019","2021","2022","2023"],a:1,d:2},
  {q:"Vad heter den snabbaste fågeln (vandringsfalk)?",o:["Örn","Vandringsfalk","Albatross","Swift"],a:1,d:2},
  {q:"Vilket år kom Spotify?",o:["2004","2006","2008","2010"],a:2,d:2},
  {q:"Vilket år dog Alan Turing?",o:["1950","1952","1954","1956"],a:2,d:2},
  {q:"Vad heter det minsta benet i kroppen?",o:["Stapes stigbygeln","Hammer","Amboss","Radius"],a:0,d:2},
  {q:"Vilket år kom flygplanet Wright Brothers?",o:["1899","1901","1903","1905"],a:2,d:2},
  // ── SVÅRT ──
  {q:"Vilket land har flest tidszoner?",o:["Ryssland","USA","Kina","Frankrike"],a:3,d:3},
  {q:"Vilket år kom Darwin's On the Origin of Species?",o:["1849","1859","1869","1879"],a:1,d:3},
  {q:"Vad heter kvantfysikens osäkerhetsprincip?",o:["Einsteins princip","Heisenbergs osäkerhetsprincip","Bohrs princip","Plancks kvantum"],a:1,d:3},
  {q:"Vilket år grundades Anthropic som skapade Claude?",o:["2019","2021","2022","2023"],a:1,d:3},
  {q:"Vilket år kom Citizen Kane?",o:["1938","1941","1944","1947"],a:1,d:3},
  {q:"Vad är Schrödingers katt ett tankeexperiment om?",o:["Kvantöverlagring","Relativitetsteori","Gravitation","Elektromagnetism"],a:0,d:3},
  {q:"Vilket år uppfann Wright Brothers flygplanet?",o:["1899","1901","1903","1905"],a:2,d:3},
  {q:"Vem uppfann World Wide Web?",o:["Bill Gates","Steve Jobs","Tim Berners-Lee","Vint Cerf"],a:2,d:3},
],

"🏙️ Umeå & Norrland": [
  // ── LÄTT ──
  {q:"Umeå är beläget vid vilken älv?",o:["Luleälven","Ångermanälven","Umeälven","Skellefteälven"],a:2,d:1},
  {q:"Vilket år utsågs Umeå till Europas kulturhuvudstad?",o:["2010","2012","2014","2016"],a:2,d:1},
  {q:"Vilket universitet finns i Umeå?",o:["Luleå tekniska","Uppsala","Umeå universitet","Mittuniversitetet"],a:2,d:1},
  {q:"Vad kallas Umeå ibland på grund av sina björkar?",o:["Björkstaden","Trädstaden","Norrlandsstaden","Älvstaden"],a:0,d:1},
  {q:"I vilket landskap ligger Umeå?",o:["Ångermanland","Lappland","Västerbotten","Norrbotten"],a:2,d:1},
  {q:"Vad heter Umeås konstmuseum?",o:["Bildmuseet","Umeå konstmuseum","Norrlandsmuseet","Västerbottensmuseet"],a:0,d:1},
  {q:"Hur många invånare har Umeå ungefär?",o:["60000","80000","130000","200000"],a:2,d:1},
  {q:"Vilket landskap gränsar Västerbotten mot väster?",o:["Lappland","Norrbotten","Ångermanland","Finland"],a:0,d:1},
  {q:"Vilket år grundades Umeå universitet?",o:["1945","1955","1963","1971"],a:2,d:1},
  {q:"Vad heter Umeås stora köpcentrum?",o:["Mitt i City","Syd","A6","Utopia"],a:3,d:1},
  {q:"Vilket lag spelar i Skelleftea i SHL?",o:["Lulea HF","Skelleftea AIK","MODO","Timra IK"],a:1,d:1},
  {q:"Vilken E-väg går genom Umeå?",o:["E4","E6","E10","E12"],a:0,d:1},
  // ── MEDEL ──
  {q:"Vilken kändis från Umeå är känd inom höjdhopp?",o:["Stefan Holm","Patrik Sjöberg","Kajsa Bergqvist","Carolina Klüft"],a:0,d:2},
  {q:"Vilket år fick Umeå stadsrättigheter?",o:["1588","1622","1640","1700"],a:1,d:2},
  {q:"Vad heter Umeås lokaltidning?",o:["Västerbottens-Kuriren","Norrländska Socialdemokraten","Umeå Tidning","Norran"],a:0,d:2},
  {q:"Vilket år brann Umeå ned och byggdes upp?",o:["1798","1888","1902","1920"],a:1,d:2},
  {q:"Hur långt är det från Umeå till Stockholm?",o:["Ca 400 km","Ca 600 km","Ca 700 km","Ca 900 km"],a:3,d:2},
  {q:"Vilket år öppnade Northvolt-fabriken i Skellefteå?",o:["2019","2021","2022","2023"],a:1,d:2},
  {q:"Vad heter konstinstallationsparken nära Umeå?",o:["Bildmuseet utomhus","Umedalen Skulptur","Konst i det fria","Skulpturparken"],a:1,d:2},
  {q:"Vilket år invigdes Umeå Arena?",o:["2010","2012","2014","2016"],a:2,d:2},
  {q:"Vilket år grundades Skellefteå stad?",o:["1845","1901","1912","1929"],a:1,d:2},
  {q:"Vad heter Umeås stadsdel med sjukhuset?",o:["Ersboda","Ålidhem","Tomtebo","NUS-området"],a:3,d:2},
  {q:"Hur lång är älvbron i centrala Umeå ungefär?",o:["200 m","400 m","600 m","800 m"],a:1,d:2},
  {q:"Vilket landskap gränsar Västerbotten mot söder?",o:["Ångermanland","Medelpad","Hälsingland","Gästrikland"],a:0,d:2},
  // ── SVÅRT ──
  {q:"Vilket år grundades Västerbottens museum?",o:["1886","1900","1921","1945"],a:0,d:3},
  {q:"Vilket år öppnade Umeå flygplats?",o:["1935","1944","1952","1960"],a:1,d:3},
  {q:"Vilket år grundades Umeå som stad?",o:["1588","1621","1650","1700"],a:1,d:3},
  {q:"Vad heter kullen i centrala Umeå?",o:["Röbäckskullen","Umedalen","Backenkullen","Tomtebo"],a:0,d:3},
  {q:"Vilket år grundades Luleå tekniska universitet?",o:["1961","1966","1971","1976"],a:2,d:3},
  {q:"Vad heter den stora insjön i Lycksele-området?",o:["Storuman","Kultsjön","Storsjön","Hotingsjön"],a:0,d:3},
  {q:"Vilket år startade Umeå Open (tennis)?",o:["1980","1985","1990","1995"],a:2,d:3},
  {q:"Hur många kommuner finns det i Västerbottens län?",o:["10","15","20","25"],a:1,d:3},
],

"🕺 70-tals musik": [
  // ── LÄTT ──
  {q:"Vilket band sjöng 'Bohemian Rhapsody'?",o:["Led Zeppelin","The Beatles","Queen","Rolling Stones"],a:2,d:1},
  {q:"Vem sjunger 'Rocket Man' (Elton John)?",o:["David Bowie","Rod Stewart","Elton John","Billy Joel"],a:2,d:1},
  {q:"Vem sjunger 'I Will Survive' (Gloria Gaynor)?",o:["Donna Summer","Gloria Gaynor","Diana Ross","Tina Turner"],a:1,d:1},
  {q:"Vilket band sjöng 'Stayin Alive' (Bee Gees)?",o:["Earth Wind & Fire","KC and the Sunshine Band","Bee Gees","Chic"],a:2,d:1},
  {q:"Vem sjunger 'Piano Man' (Billy Joel)?",o:["Elton John","Billy Joel","James Taylor","Carole King"],a:1,d:1},
  {q:"Vilket band sjöng 'Le Freak' (Chic)?",o:["Earth Wind & Fire","Chic","Kool & the Gang","Parliament"],a:1,d:1},
  {q:"Vem sjunger 'Jolene' (Dolly Parton)?",o:["Loretta Lynn","Tammy Wynette","Dolly Parton","Emmylou Harris"],a:2,d:1},
  {q:"Vilket band sjöng 'Hotel California' (Eagles)?",o:["Fleetwood Mac","Eagles","Dire Straits","The Doors"],a:1,d:1},
  {q:"Vem sjunger 'Superstition' (Stevie Wonder)?",o:["Earth Wind & Fire","Stevie Wonder","Marvin Gaye","Curtis Mayfield"],a:1,d:1},
  {q:"Vem sjunger 'Dancing Queen' (ABBA)?",o:["Donna Summer","Diana Ross","ABBA","Gloria Gaynor"],a:2,d:1},
  {q:"Vilket band sjöng 'Smoke on the Water' (Deep Purple)?",o:["Led Zeppelin","Black Sabbath","Deep Purple","Uriah Heep"],a:2,d:1},
  {q:"Vem sjunger 'Maggie May' (Rod Stewart)?",o:["Mick Jagger","Rod Stewart","Joe Cocker","Eric Clapton"],a:1,d:1},
  // ── MEDEL ──
  {q:"Vilket år kom Pink Floyds 'Dark Side of the Moon'?",o:["1971","1973","1975","1977"],a:1,d:2},
  {q:"Vilket år kom Fleetwood Macs 'Rumours'?",o:["1975","1977","1979","1981"],a:1,d:2},
  {q:"Vilket år kom David Bowies 'Heroes'?",o:["1975","1977","1979","1981"],a:1,d:2},
  {q:"Vilket band sjöng 'Night Fever' (Bee Gees)?",o:["Earth Wind & Fire","Bee Gees","Chic","Kool & the Gang"],a:1,d:2},
  {q:"Vilket band sjöng 'Fortunate Son' (CCR)?",o:["Creedence Clearwater Revival","The Eagles","Lynyrd Skynyrd","ZZ Top"],a:0,d:2},
  {q:"Vilket band sjöng 'Free Bird' (Lynyrd Skynyrd)?",o:["The Allman Brothers","Lynyrd Skynyrd","ZZ Top","38 Special"],a:1,d:2},
  {q:"Vilket band sjöng 'More Than a Feeling' (Boston)?",o:["Journey","Foreigner","Boston","REO Speedwagon"],a:2,d:2},
  {q:"Vilket år kom David Bowies 'Ziggy Stardust'?",o:["1970","1972","1974","1976"],a:1,d:2},
  {q:"Vilket band sjöng 'Born to Run' (Springsteen)?",o:["Tom Petty","Bruce Springsteen","John Mellencamp","Bob Seger"],a:1,d:2},
  {q:"Vilket år kom Led Zeppelins 'Physical Graffiti'?",o:["1973","1975","1977","1979"],a:1,d:2},
  {q:"Vilket band sjöng 'Roxanne' (The Police 1978)?",o:["The Clash","The Police","Elvis Costello","Joe Jackson"],a:1,d:2},
  {q:"Vilket år kom T-Rex 'Electric Warrior'?",o:["1969","1971","1973","1975"],a:1,d:2},
  // ── SVÅRT ──
  {q:"Vilket år kom The Clash 'London Calling'?",o:["1977","1979","1981","1983"],a:1,d:3},
  {q:"Vem producerade Chics 'Good Times' (1979)?",o:["Barry White","Quincy Jones","Nile Rodgers","Giorgio Moroder"],a:2,d:3},
  {q:"Vilket år kom Talking Heads 'Remain in Light'?",o:["1978","1980","1982","1984"],a:1,d:3},
  {q:"Vem sjunger 'Killing Me Softly' original (1973)?",o:["Carly Simon","Roberta Flack","Nina Simone","Phoebe Snow"],a:1,d:3},
  {q:"Vilket år kom Can 'Ege Bamyasi'?",o:["1970","1972","1974","1976"],a:1,d:3},
  {q:"Vilket band sjöng 'The Jean Genie' (David Bowie)?",o:["T.Rex","David Bowie","Roxy Music","Gary Glitter"],a:1,d:3},
  {q:"Vilket år kom Public Image Ltd debutalbum?",o:["1976","1978","1980","1982"],a:1,d:3},
  {q:"Vem producerade Donna Summers disco-hits?",o:["Barry White","Giorgio Moroder","Nile Rodgers","Quincy Jones"],a:1,d:3},
],

"🎤 K-pop & Asiatisk musik": [
  // ── LÄTT ──
  {q:"Vilket K-pop band sjöng 'Dynamite'?",o:["EXO","BLACKPINK","BTS","TWICE"],a:2,d:1},
  {q:"Vilket K-pop band sjöng 'How You Like That'?",o:["EXO","BLACKPINK","BTS","aespa"],a:1,d:1},
  {q:"Vem sjunger 'Gangnam Style'?",o:["Rain","G-Dragon","PSY","Taeyang"],a:2,d:1},
  {q:"Vad heter BTS fansen officiellt?",o:["Blinks","Stays","Army","Carats"],a:2,d:1},
  {q:"Vilket K-pop band sjöng 'Kill This Love'?",o:["EXO","BLACKPINK","BTS","MAMAMOO"],a:1,d:1},
  {q:"Vilket K-pop band sjöng 'Fancy' (TWICE)?",o:["TWICE","BLACKPINK","Red Velvet","ITZY"],a:0,d:1},
  {q:"Vad heter BLACKPINK fansen?",o:["Army","Blinks","Stays","Reveluvs"],a:1,d:1},
  {q:"Vilket land kommer K-pop ifrån?",o:["Japan","Kina","Sydkorea","Thailand"],a:2,d:1},
  {q:"Vilket K-pop band sjöng 'Butter' (BTS)?",o:["EXO","BLACKPINK","BTS","TXT"],a:2,d:1},
  {q:"Vad heter TWICE fansen?",o:["Army","Blinks","Stays","Once"],a:3,d:1},
  {q:"Vilket K-pop band sjöng 'Ditto' (NewJeans)?",o:["aespa","IVE","NMIXX","NewJeans"],a:3,d:1},
  {q:"Vem sjunger 'Celebrity' (IU)?",o:["TWICE","IU","aespa","MAMAMOO"],a:1,d:1},
  // ── MEDEL ──
  {q:"Vilket år debuterade BTS?",o:["2011","2013","2015","2017"],a:1,d:2},
  {q:"Vilket år debuterade BLACKPINK?",o:["2014","2016","2018","2020"],a:1,d:2},
  {q:"Vilket K-pop band sjöng 'Next Level' (aespa)?",o:["TWICE","BLACKPINK","Red Velvet","aespa"],a:3,d:2},
  {q:"Vilket K-pop band sjöng 'Cupid' (FIFTY FIFTY)?",o:["aespa","IVE","FIFTY FIFTY","NewJeans"],a:2,d:2},
  {q:"Vilket år debuterade TWICE?",o:["2013","2015","2017","2019"],a:1,d:2},
  {q:"Vilket K-pop band sjöng 'ELEVEN' (IVE)?",o:["aespa","IVE","NMIXX","NewJeans"],a:1,d:2},
  {q:"Vilket K-pop band sjöng 'Miroh' (Stray Kids)?",o:["Stray Kids","ATEEZ","MONSTA X","VICTON"],a:0,d:2},
  {q:"Vilket K-pop band sjöng 'NOT OKAY' (LE SSERAFIM)?",o:["IVE","LE SSERAFIM","NMIXX","NewJeans"],a:1,d:2},
  {q:"Vilket år kom NewJeans debutalbum?",o:["2020","2021","2022","2023"],a:2,d:2},
  {q:"Vilket K-pop band sjöng 'TOMBOY' (G I-DLE)?",o:["G I-DLE","aespa","IVE","NMIXX"],a:0,d:2},
  {q:"Vilket K-pop band sjöng 'Fearless' (LE SSERAFIM)?",o:["IVE","LE SSERAFIM","NMIXX","NewJeans"],a:1,d:2},
  {q:"Vad heter Stray Kids fansen?",o:["Army","Blinks","Stays","Once"],a:2,d:2},
  // ── SVÅRT ──
  {q:"Vad heter BTS-memberens soloalbum 'Jack In the Box'?",o:["Jin","V","J-Hope","Jungkook"],a:2,d:3},
  {q:"Vilket K-pop band sjöng 'Beautiful' (Monsta X)?",o:["Stray Kids","ATEEZ","MONSTA X","VICTON"],a:2,d:3},
  {q:"Vilket år grundades HYBE (BTS skivbolag)?",o:["2003","2005","2007","2009"],a:2,d:3},
  {q:"Vilket K-pop band sjöng 'Thunder' (EXO)?",o:["EXO","SHINee","Super Junior","GOT7"],a:0,d:3},
  {q:"Vilket K-pop band sjöng 'Not Shy' (ITZY)?",o:["ITZY","IVE","aespa","NMIXX"],a:0,d:3},
  {q:"Vad heter SM Entertainment artisten känd som 'Queen of K-pop'?",o:["BoA","Taeyeon","IU","Lee Hyori"],a:0,d:3},
  {q:"Vilket år debuterade EXO?",o:["2010","2012","2014","2016"],a:1,d:3},
  {q:"Vilket K-pop band sjöng 'Growl' (EXO)?",o:["EXO","SHINee","Super Junior","2PM"],a:0,d:3},
],

"🌌 Astronomi & Rymden": [
  // ── LÄTT ──
  {q:"Vilket är solsystemets störst planet?",o:["Saturn","Uranus","Jupiter","Neptunus"],a:2,d:1},
  {q:"Vad heter vår galax?",o:["Andromeda","Vintergatan","Triangeln","Magellanska molnet"],a:1,d:1},
  {q:"Hur lång tid tar ljuset från solen till jorden?",o:["4 min","8 min","20 min","1 timme"],a:1,d:1},
  {q:"Hur många månader har Mars?",o:["0","1","2","3"],a:2,d:1},
  {q:"Vad heter den röda planeten?",o:["Venus","Jupiter","Mars","Saturn"],a:2,d:1},
  {q:"Vad är ett svart hål?",o:["En kollapsad stjärna med extrem gravitation","En nebulosa","En kvasar","En pulsar"],a:0,d:1},
  {q:"Hur många planeter finns i solsystemet?",o:["7","8","9","10"],a:1,d:1},
  {q:"Vad heter teorin om universums ursprung?",o:["Steady State","Big Crunch","Big Bang","Inflation"],a:2,d:1},
  {q:"Vad är ljusets hastighet?",o:["200000 km/s","300000 km/s","400000 km/s","500000 km/s"],a:1,d:1},
  {q:"Vad heter den närmaste stjärnan till solen?",o:["Sirius","Vega","Proxima Centauri","Betelgeuse"],a:2,d:1},
  {q:"Vilket år landade Neil Armstrong på månen?",o:["1967","1969","1971","1973"],a:1,d:1},
  {q:"Vad heter Saturnus ringar gjorda av?",o:["Gas","Is och sten","Metall","Damm"],a:1,d:1},
  // ── MEDEL ──
  {q:"Vilket år togs det första fotot av ett svart hål?",o:["2015","2017","2019","2021"],a:2,d:2},
  {q:"Vad heter det svarta hålet i centrum av Vintergatan?",o:["Sagittarius A*","Cygnus X-1","TON 618","M87*"],a:0,d:2},
  {q:"Hur gammal är universum?",o:["8 miljarder år","10 miljarder år","13.8 miljarder år","20 miljarder år"],a:2,d:2},
  {q:"Vilket år sände James Webb-teleskopet sina första bilder?",o:["2020","2021","2022","2023"],a:2,d:2},
  {q:"Vilket år landade Curiosity på Mars?",o:["2008","2010","2012","2014"],a:2,d:2},
  {q:"Vilket år sände Voyager 1 ut?",o:["1973","1975","1977","1979"],a:2,d:2},
  {q:"Hur lång tid tar det för ljuset från Proxima Centauri?",o:["1 år","2.5 år","4.2 år","10 år"],a:2,d:2},
  {q:"Vad heter Jupiters störst måne?",o:["Europa","Ganymedes","Callisto","Io"],a:1,d:2},
  {q:"Vilket år kom Perseverance-rovern till Mars?",o:["2019","2021","2022","2023"],a:1,d:2},
  {q:"Vad heter den närmaste galaxen till Vintergatan?",o:["Triangelgalaxen","Andromeda","Stora Magellanska molnet","Lilla Magellanska molnet"],a:1,d:2},
  {q:"Vilket år kom Hubble-teleskopet?",o:["1986","1988","1990","1992"],a:2,d:2},
  {q:"Vad kallas det när en stjärna exploderar?",o:["Nova","Supernova","Hypernova","Kilonova"],a:1,d:2},
  // ── SVÅRT ──
  {q:"Hur lång tid tar Neptunus att kretsa runt solen?",o:["84 år","100 år","165 år","248 år"],a:2,d:3},
  {q:"Vad är en pulsar?",o:["En roterande neutronsstjärna","En kollapsad vit dvärg","En quasar","En röd jätte"],a:0,d:3},
  {q:"Vad heter teorin om mörk materia?",o:["WIMP-teorin","Lambda-CDM","Inflation","Multiverse"],a:1,d:3},
  {q:"Hur lång är ett ljusår i kilometer?",o:["6 biljoner km","9.46 biljoner km","12 biljoner km","15 biljoner km"],a:1,d:3},
  {q:"Vad heter Saturnus störst måne?",o:["Titan","Enceladus","Rhea","Mimas"],a:0,d:3},
  {q:"Vilket år grundades NASA?",o:["1952","1954","1958","1960"],a:2,d:3},
  {q:"Vad heter den process där stjärnor föds?",o:["Fusion","Fission","Gravitationskollaps","Supernovaexplosion"],a:2,d:3},
  {q:"Vad är ett exoplanet?",o:["En planet utanför solsystemet","En planet utan atmosfär","En dvärgplanet","En asteroid"],a:0,d:3},
],

"🍹 Alkohol & Drinkar": [
  // ── LÄTT ──
  {q:"Vad är huvudingrediensen i en Margarita?",o:["Vodka","Rum","Tequila","Gin"],a:2,d:1},
  {q:"Vilket land kommer Scotch Whisky ifrån?",o:["Irland","Skottland","USA","Japan"],a:1,d:1},
  {q:"Vad är en Mojito gjord på?",o:["Vodka och lime","Rum mynta lime och socker","Gin och tonic","Tequila och citron"],a:1,d:1},
  {q:"Vilket land kommer Bourbon ifrån?",o:["Skottland","Irland","Kanada","USA"],a:3,d:1},
  {q:"Vad är en Aperol Spritz gjord på?",o:["Aperol Campari och soda","Aperol prosecco och soda","Aperol gin och tonic","Aperol vodka och lime"],a:1,d:1},
  {q:"Vad heter den irländska stout-ölen?",o:["Heineken","Guinness","Carlsberg","Stella Artois"],a:1,d:1},
  {q:"Vilket land producerar Rioja-vin?",o:["Frankrike","Italien","Spanien","Portugal"],a:2,d:1},
  {q:"Vad är en Negroni gjord på?",o:["Campari gin och vermut","Vodka triple sec och lime","Tequila triple sec och lime","Bourbon angostura och socker"],a:0,d:1},
  {q:"Vad kallas drycken gjord på druvor?",o:["Öl","Vin","Cider","Mjöd"],a:1,d:1},
  {q:"Vilket land är känt för Rioja-vin?",o:["Frankrike","Italien","Spanien","Portugal"],a:2,d:1},
  {q:"Vad är en Daiquiri gjord på?",o:["Vodka lime och socker","Rum lime och socker","Gin citron och socker","Tequila lime och socker"],a:1,d:1},
  {q:"Vilket land producerar mest champagne?",o:["Spanien","Italien","Frankrike","Belgien"],a:2,d:1},
  // ── MEDEL ──
  {q:"Vad är en Old Fashioned gjord på?",o:["Vodka angostura och socker","Bourbon eller rye angostura och socker","Rum angostura och socker","Gin angostura och socker"],a:1,d:2},
  {q:"Vilket land producerar mest vin i världen?",o:["Frankrike","Spanien","Italien","USA"],a:2,d:2},
  {q:"Vad är Cointreau?",o:["En rom","En apelsinlikör","En vodka","En gin"],a:1,d:2},
  {q:"Vad är en Espresso Martini gjord på?",o:["Vodka kaffelikör och espresso","Gin kaffelikör och espresso","Rum kaffelikör och espresso","Bourbon kaffelikör och espresso"],a:0,d:2},
  {q:"Vilket land producerar mest öl i världen?",o:["Tyskland","USA","Kina","Tjeckien"],a:2,d:2},
  {q:"Vad heter cocktailen med vodka lime och ginger beer?",o:["Paloma","Moscow Mule","Dark and Stormy","Gin Mule"],a:1,d:2},
  {q:"Vad är Campari?",o:["En italiensk bitter likör","En fransk vin-aperitif","En spansk sherry","En belgisk öl"],a:0,d:2},
  {q:"Vilket land uppfann ölet historiskt?",o:["England","Mesopotamien","Egypten","Kina"],a:1,d:2},
  {q:"Vad heter den mexicanska agavedrycken (ej tequila)?",o:["Pulque","Mezcal","Sotol","Raicilla"],a:1,d:2},
  {q:"Vilket land är känt för Prosecco?",o:["Frankrike","Spanien","Italien","Portugal"],a:2,d:2},
  {q:"Vad heter den klassiska whisky-sour cocktailen?",o:["Whisky Sour","Manhattan","Old Fashioned","Boulevardier"],a:0,d:2},
  {q:"Vad är Amaretto gjort på?",o:["Mandlar","Apelsinskal","Körsbär","Aprikos"],a:0,d:2},
  // ── SVÅRT ──
  {q:"Vilket år grundades Guinness?",o:["1749","1759","1769","1779"],a:1,d:3},
  {q:"Vad heter den klassiska New Orleans-cocktailen med rye och angostura?",o:["Hurricane","Sazerac","Ramos Gin Fizz","Vieux Carré"],a:1,d:3},
  {q:"Vilket år kom Baileys Irish Cream?",o:["1967","1972","1977","1982"],a:1,d:3},
  {q:"Vad heter Burgundys finaste vita vindruva?",o:["Riesling","Chardonnay","Sauvignon Blanc","Pinot Gris"],a:1,d:3},
  {q:"Vilket land uppfann destillation av sprit (historiskt)?",o:["Irland","Kina","Persien/Irak","Skottland"],a:2,d:3},
  {q:"Vad heter den japanska destilleringen Nikka grundades av?",o:["Masataka Taketsuru","Shinjiro Torii","Ichiro Akuto","Kenji Kitamoto"],a:0,d:3},
  {q:"Vilket år grundades Absolut Vodkas ursprungliga destilleri i Åhus?",o:["1879","1889","1899","1909"],a:0,d:3},
  {q:"Vad heter den argentinska bitterdrycken gjord på örter?",o:["Fernet-Branca","Amaro","Campari","Aperol"],a:0,d:3},
],

"🏈 Amerikansk fotboll": [
  // ── LÄTT ──
  {q:"Vad heter NFL:s mästerskapstrofe?",o:["Lombardi Trophy","Stanley Cup","Larry O'Brien Trophy","Commissioner's Trophy"],a:0,d:1},
  {q:"Hur många poäng ger en touchdown?",o:["3","4","6","7"],a:2,d:1},
  {q:"Hur många poäng ger en field goal?",o:["1","2","3","4"],a:2,d:1},
  {q:"Hur många spelare per lag är på planen?",o:["9","10","11","12"],a:2,d:1},
  {q:"Vem kallas 'GOAT' i NFL-historien?",o:["Aaron Rodgers","Peyton Manning","Tom Brady","Patrick Mahomes"],a:2,d:1},
  {q:"Hur många downs har ett lag på sig att ta 10 yards?",o:["3","4","5","6"],a:1,d:1},
  {q:"Vilket lag spelar hemma på Lambeau Field?",o:["Chicago Bears","Green Bay Packers","Minnesota Vikings","Detroit Lions"],a:1,d:1},
  {q:"Hur många Super Bowls vann Tom Brady totalt?",o:["5","6","7","8"],a:2,d:1},
  {q:"Hur lång är en NFL-plan i yards?",o:["80","100","110","120"],a:1,d:1},
  {q:"Vilket lag vann Super Bowl LVII 2023?",o:["Philadelphia Eagles","Kansas City Chiefs","San Francisco 49ers","Dallas Cowboys"],a:1,d:1},
  {q:"Vilket lag vann Super Bowl LVIII 2024?",o:["Kansas City Chiefs","San Francisco 49ers","Detroit Lions","Baltimore Ravens"],a:0,d:1},
  {q:"Vad heter positionen som kastar bollen i NFL?",o:["Running Back","Wide Receiver","Quarterback","Tight End"],a:2,d:1},
  // ── MEDEL ──
  {q:"Vilket lag vann Super Bowl LVI 2022?",o:["LA Rams","Cincinnati Bengals","San Francisco 49ers","Dallas Cowboys"],a:0,d:2},
  {q:"Vilket år spelades det första Super Bowl?",o:["1964","1967","1969","1971"],a:1,d:2},
  {q:"Vilket lag vann Super Bowl I?",o:["Green Bay Packers","Dallas Cowboys","NY Giants","SF 49ers"],a:0,d:2},
  {q:"Hur många lag deltar i NFL-playoffs?",o:["8","12","14","16"],a:2,d:2},
  {q:"Vilket år kom Patrick Mahomes till NFL?",o:["2015","2017","2019","2021"],a:1,d:2},
  {q:"Vem är NFL:s all-time rushing leader?",o:["Barry Sanders","Emmitt Smith","Walter Payton","Jim Brown"],a:1,d:2},
  {q:"Vilket lag spelar hemma på Arrowhead Stadium?",o:["Denver Broncos","Kansas City Chiefs","Las Vegas Raiders","LA Chargers"],a:1,d:2},
  {q:"Vilket lag spelar hemma på Gillette Stadium?",o:["New York Giants","New England Patriots","Buffalo Bills","Miami Dolphins"],a:1,d:2},
  {q:"Vad kallas en säkerhet (safety) i NFL?",o:["2 poäng till försvarslaget","1 poäng till anfallslaget","3 poäng","6 poäng"],a:0,d:2},
  {q:"Vilket lag vann Super Bowl LV 2021?",o:["Kansas City Chiefs","Tampa Bay Buccaneers","New England Patriots","Green Bay Packers"],a:1,d:2},
  {q:"Vilket NFL-lag kallas America's Team?",o:["Dallas Cowboys","New England Patriots","Green Bay Packers","NY Giants"],a:0,d:2},
  {q:"Vilket lag spelar hemma på SoFi Stadium?",o:["Seattle Seahawks","Las Vegas Raiders","LA Rams och Chargers","San Francisco 49ers"],a:2,d:2},
  // ── SVÅRT ──
  {q:"Vilket lag har flest förlorade Super Bowls?",o:["New England Patriots","Denver Broncos","Dallas Cowboys","Buffalo Bills"],a:3,d:3},
  {q:"Vilket år grundades NFL?",o:["1910","1920","1930","1940"],a:1,d:3},
  {q:"Hur många NFL-lag finns det?",o:["28","30","32","34"],a:2,d:3},
  {q:"Vad heter NFL-draften (fullt namn)?",o:["NFL Combine","NFL Annual Player Selection Meeting","NFL Draft","Selection Showcase"],a:2,d:3},
  {q:"Vem kallas 'The Refrigerator' i NFL-historien?",o:["William Perry","Refrigerator White","Lawrence Taylor","Mean Joe Greene"],a:0,d:3},
  {q:"Vilket år kom salary cap till NFL?",o:["1988","1990","1992","1994"],a:3,d:3},
  {q:"Vilket lag spelar hemma på AT&T Stadium?",o:["Houston Texans","Dallas Cowboys","Tennessee Titans","Arizona Cardinals"],a:1,d:3},
  {q:"Vad heter trofén som ges till Super Bowl MVP?",o:["Lombardi Trophy","Pete Rozelle Trophy","Dan Marino Trophy","Vince Lombardi Award"],a:1,d:3},
],
};

(function() {
  if (typeof QUESTION_DB === 'undefined') { console.error('QUESTION_DB missing!'); return; }
  const existing = new Set();
  Object.values(QUESTION_DB).forEach(qs => qs.forEach(q => existing.add(q.q.toLowerCase().trim())));
  let added = 0, skipped = 0;
  Object.keys(QUESTION_DB12).forEach(cat => {
    const newQs = QUESTION_DB12[cat].filter(q => {
      const key = q.q.toLowerCase().trim();
      if (existing.has(key)) { skipped++; return false; }
      existing.add(key);
      return true;
    });
    if (QUESTION_DB[cat]) { QUESTION_DB[cat] = QUESTION_DB[cat].concat(newQs); }
    else { QUESTION_DB[cat] = newQs; }
    added += newQs.length;
  });
  console.log('questions12.js: ' + added + ' added, ' + skipped + ' dupes skipped');
})();
