// ═══════════════════════════════════════════════════════
//  Combitech AW Quiz – Frågedatabas v3
//  Format: { q:"Fråga?", o:["A","B","C","D"], a:0, d:1 }
//  d = svårighetsgrad: 1=lätt, 2=medel, 3=svårt
// ═══════════════════════════════════════════════════════

const QUESTION_DB = {

  // ════════════════════════════════════
  //  MUSIK
  // ════════════════════════════════════

  "🎵 80-tals musik": [
    {q:"Vilket band sjöng 'Wake Me Up Before You Go-Go'?",o:["Duran Duran","Wham!","Culture Club","Spandau Ballet"],a:1,d:1},
    {q:"Vem sjunger 'Like a Virgin'?",o:["Cyndi Lauper","Pat Benatar","Madonna","Tina Turner"],a:2,d:1},
    {q:"Vilket band sjöng 'Don't You (Forget About Me)'?",o:["The Cure","Simple Minds","New Order","Depeche Mode"],a:1,d:1},
    {q:"Vem sjunger 'Girls Just Want to Have Fun'?",o:["Madonna","Pat Benatar","Cyndi Lauper","Blondie"],a:2,d:1},
    {q:"Vilket band sjöng 'Take On Me'?",o:["a-ha","Roxette","Europe","Ace of Base"],a:0,d:1},
    {q:"Vilket band sjöng 'Africa'?",o:["Foreigner","Toto","Journey","Boston"],a:1,d:1},
    {q:"Vem sjunger 'Sweet Dreams (Are Made of This)'?",o:["Siouxsie","Annie Lennox / Eurythmics","Kate Bush","Yazoo"],a:1,d:1},
    {q:"Vilket band sjöng 'Every Breath You Take'?",o:["The Police","U2","Dire Straits","Genesis"],a:0,d:1},
    {q:"Vem sjunger 'Jump' (1984)?",o:["David Lee Roth / Van Halen","Bon Jovi","Aerosmith","Def Leppard"],a:0,d:1},
    {q:"Vilket band sjöng 'Come On Eileen'?",o:["The Clash","Madness","Dexys Midnight Runners","The Specials"],a:2,d:1},
    {q:"Vilket år kom Michael Jacksons 'Thriller'?",o:["1980","1982","1984","1986"],a:1,d:1},
    {q:"Vem sjunger 'Purple Rain'?",o:["Michael Jackson","Prince","David Bowie","Stevie Wonder"],a:1,d:1},
    {q:"Vilket band sjöng 'Summer of '69'?",o:["Tom Petty","Bryan Adams","John Mellencamp","Bruce Springsteen"],a:1,d:1},
    {q:"Vem sjunger 'Total Eclipse of the Heart'?",o:["Celine Dion","Bonnie Tyler","Kim Carnes","Stevie Nicks"],a:1,d:1},
    {q:"Vilket band sjöng 'Living on a Prayer'?",o:["Aerosmith","Bon Jovi","Journey","Foreigner"],a:1,d:1},
    {q:"Vilket år kom a-has 'Take On Me'?",o:["1983","1985","1987","1989"],a:1,d:2},
    {q:"Vad heter Michael Jacksons album med 'Billie Jean'?",o:["Off the Wall","Bad","Thriller","Dangerous"],a:2,d:2},
    {q:"Vilket band sjöng 'Personal Jesus'?",o:["The Cure","New Order","Depeche Mode","Bauhaus"],a:2,d:2},
    {q:"Vem producerade många av 80-talets största hits inkl. Cyndi Lauper?",o:["Quincy Jones","Rick Rubin","Nile Rodgers","Giorgio Moroder"],a:2,d:2},
    {q:"Vilket band sjöng 'True' (1983)?",o:["Duran Duran","Spandau Ballet","ABC","Heaven 17"],a:1,d:2},
    {q:"Vilket år kom U2s album 'The Joshua Tree'?",o:["1985","1987","1989","1991"],a:1,d:2},
    {q:"Vem sjunger 'What's Love Got to Do with It'?",o:["Aretha Franklin","Diana Ross","Tina Turner","Whitney Houston"],a:2,d:2},
    {q:"Vilket band sjöng 'Love Will Tear Us Apart'?",o:["The Smiths","Joy Division","The Cure","Echo & the Bunnymen"],a:1,d:2},
    {q:"Vad heter Madonna's debutalbum?",o:["True Blue","Like a Virgin","Madonna","Immaculate Collection"],a:2,d:2},
    {q:"Vem sjunger 'Running Up That Hill'?",o:["Annie Lennox","Kate Bush","Siouxsie","Cocteau Twins"],a:1,d:3},
    {q:"Vilket skivbolag gav ut The Smiths tidiga skivor?",o:["Factory","Rough Trade","4AD","Creation"],a:1,d:3},
    {q:"Vad heter Depeche Modes genombrott salbum 1981?",o:["Some Great Reward","Black Celebration","Speak & Spell","A Broken Frame"],a:2,d:3},
    {q:"Vilket år kom New Orders 'Blue Monday'?",o:["1981","1983","1985","1987"],a:1,d:3},
    {q:"Vem producerade MJs 'Off the Wall'?",o:["Berry Gordy","Quincy Jones","Teddy Riley","L.A. Reid"],a:1,d:3},
    {q:"Vilket band bildade Morrissey och Johnny Marr?",o:["The Cure","Joy Division","The Smiths","Bauhaus"],a:2,d:3},
  ],

  "🎶 90-tals musik": [
    {q:"Vilket band sjöng 'Smells Like Teen Spirit'?",o:["Pearl Jam","Soundgarden","Nirvana","Alice in Chains"],a:2,d:1},
    {q:"Vilket band sjöng 'Wannabe'?",o:["TLC","Destiny's Child","Spice Girls","En Vogue"],a:2,d:1},
    {q:"Vem sjunger 'Baby One More Time'?",o:["Christina Aguilera","Britney Spears","Madonna","Mariah Carey"],a:1,d:1},
    {q:"Vilket band sjöng 'Ironic'?",o:["Sheryl Crow","Alanis Morissette","Shania Twain","Jewel"],a:1,d:1},
    {q:"Vilket band sjöng 'Losing My Religion'?",o:["U2","REM","Radiohead","Pearl Jam"],a:1,d:1},
    {q:"Vilket band sjöng 'Basket Case'?",o:["The Offspring","Rancid","Green Day","Blink-182"],a:2,d:1},
    {q:"Vem sjunger 'I Will Always Love You' (filmversion)?",o:["Dolly Parton","Celine Dion","Whitney Houston","Mariah Carey"],a:2,d:1},
    {q:"Vilket band sjöng 'Wonderwall'?",o:["Blur","Pulp","Oasis","Suede"],a:2,d:1},
    {q:"Vilket band sjöng 'No Scrubs'?",o:["Destiny's Child","En Vogue","TLC","SWV"],a:2,d:1},
    {q:"Vilket band sjöng 'MMMBop'?",o:["New Kids on the Block","Backstreet Boys","Hanson","NSYNC"],a:2,d:1},
    {q:"Vilket band sjöng 'Waterfalls'?",o:["Destiny's Child","En Vogue","TLC","Brandy"],a:2,d:1},
    {q:"Vem sjunger 'My Heart Will Go On'?",o:["Whitney Houston","Mariah Carey","Celine Dion","Shania Twain"],a:2,d:1},
    {q:"Vilket år kom Nirvanas 'Nevermind'?",o:["1989","1991","1993","1995"],a:1,d:2},
    {q:"Vilket band sjöng 'Black Hole Sun'?",o:["Pearl Jam","Alice in Chains","Soundgarden","Stone Temple Pilots"],a:2,d:2},
    {q:"Vem sjunger 'Creep'?",o:["Oasis","Blur","Radiohead","Suede"],a:2,d:2},
    {q:"Vilket band sjöng 'Semi-Charmed Life'?",o:["Matchbox Twenty","Third Eye Blind","Counting Crows","Spin Doctors"],a:1,d:2},
    {q:"Vilket band sjöng 'One Week'?",o:["Barenaked Ladies","The Tragically Hip","Our Lady Peace","Default"],a:0,d:2},
    {q:"Vad heter Radioheads genombrott salbum 1997?",o:["Pablo Honey","The Bends","OK Computer","Kid A"],a:2,d:2},
    {q:"Vilket band sjöng 'Bullet with Butterfly Wings'?",o:["Soundgarden","Alice in Chains","Smashing Pumpkins","Stone Temple Pilots"],a:2,d:2},
    {q:"Vilket år kom Backstreet Boys debutalbum?",o:["1994","1996","1998","2000"],a:1,d:2},
    {q:"Vem sjunger 'Killing Me Softly' (1996)?",o:["TLC","Destiny's Child","Fugees","En Vogue"],a:2,d:2},
    {q:"Vilket band sjöng 'What's Up'?",o:["Alanis Morissette","4 Non Blondes","Sheryl Crow","Melissa Etheridge"],a:1,d:2},
    {q:"På vilket skivbolag debuterade Nirvana?",o:["DGC Records","Sub Pop","Geffen","Epitaph"],a:1,d:3},
    {q:"Vem producerade Nevermind?",o:["Steve Albini","Rick Rubin","Butch Vig","Jack Endino"],a:2,d:3},
    {q:"Vilket år kom Radioheads 'OK Computer'?",o:["1995","1997","1999","2001"],a:1,d:3},
    {q:"Vilket band sjöng 'Champagne Supernova'?",o:["Blur","Pulp","Oasis","Suede"],a:2,d:3},
    {q:"Vad heter Alanis Morissettes genombrott salbum?",o:["Supposed Former Infatuation Junkie","So-Called Chaos","Jagged Little Pill","Under Rug Swept"],a:2,d:3},
    {q:"Vilket band bildade Chris Martin 1996?",o:["Travis","Keane","Coldplay","Snow Patrol"],a:2,d:3},
    {q:"Vem sjunger 'Ex-Factor'?",o:["Mary J. Blige","Lauryn Hill","Erykah Badu","Aaliyah"],a:1,d:3},
    {q:"Vilket år kom Fugees album 'The Score'?",o:["1994","1996","1998","2000"],a:1,d:3},
  ],

  "🎤 Ny musik (2010-idag)": [
    {q:"Vem sjunger 'Shape of You'?",o:["Justin Bieber","Ed Sheeran","Sam Smith","Harry Styles"],a:1,d:1},
    {q:"Vem sjunger 'Bad Guy'?",o:["Ariana Grande","Billie Eilish","Dua Lipa","Olivia Rodrigo"],a:1,d:1},
    {q:"Vilket band sjöng 'Uptown Funk'?",o:["Bruno Mars","Mark Ronson ft. Bruno Mars","Pharrell Williams","Justin Timberlake"],a:1,d:1},
    {q:"Vem sjunger 'Hello' (2015)?",o:["Beyoncé","Rihanna","Adele","Lady Gaga"],a:2,d:1},
    {q:"Vem sjunger 'Blinding Lights'?",o:["Drake","The Weeknd","Post Malone","Travis Scott"],a:1,d:1},
    {q:"Vem sjunger 'Old Town Road'?",o:["Cardi B","Lil Nas X","Travis Scott","Post Malone"],a:1,d:1},
    {q:"Vem sjunger 'Levitating'?",o:["Dua Lipa","Doja Cat","Olivia Rodrigo","Ariana Grande"],a:0,d:1},
    {q:"Vilket band sjöng 'Stressed Out'?",o:["Imagine Dragons","Twenty One Pilots","Fall Out Boy","Panic! At The Disco"],a:1,d:1},
    {q:"Vem sjunger 'drivers license'?",o:["Billie Eilish","Dua Lipa","Olivia Rodrigo","Ariana Grande"],a:2,d:1},
    {q:"Vem sjunger 'Stay' (2021)?",o:["The Kid LAROI & Justin Bieber","Lil Nas X","Polo G","Rod Wave"],a:0,d:1},
    {q:"Vem sjunger 'Anti-Hero'?",o:["Billie Eilish","Olivia Rodrigo","Taylor Swift","Sabrina Carpenter"],a:2,d:1},
    {q:"Vem sjunger 'As It Was'?",o:["Ed Sheeran","Harry Styles","Niall Horan","Louis Tomlinson"],a:1,d:1},
    {q:"Vilket år kom Billie Eilish's debutalbum?",o:["2017","2019","2021","2023"],a:1,d:2},
    {q:"Vem sjunger 'good 4 u'?",o:["Billie Eilish","Dua Lipa","Olivia Rodrigo","Ariana Grande"],a:2,d:2},
    {q:"Vilket år kom Adeles album '21'?",o:["2009","2011","2013","2015"],a:1,d:2},
    {q:"Vem sjunger 'Espresso'?",o:["Dua Lipa","Sabrina Carpenter","Olivia Rodrigo","Ariana Grande"],a:1,d:2},
    {q:"Vilket år vann Billie Eilish fyra Grammy?",o:["2019","2020","2021","2022"],a:1,d:2},
    {q:"Vem sjunger 'Montero (Call Me By Your Name)'?",o:["Tyler the Creator","Lil Nas X","Frank Ocean","ASAP Rocky"],a:1,d:2},
    {q:"Vilket år kom Taylor Swifts 'Folklore'?",o:["2018","2019","2020","2021"],a:2,d:2},
    {q:"Vem sjunger 'Flowers'?",o:["Dua Lipa","Miley Cyrus","Selena Gomez","Lizzo"],a:1,d:2},
    {q:"Vilket år kom Dua Lipas 'Future Nostalgia'?",o:["2018","2020","2022","2024"],a:1,d:2},
    {q:"Vem sjunger 'Heat Waves'?",o:["The 1975","Glass Animals","Tame Impala","Jungle"],a:1,d:2},
    {q:"Vad heter Billie Eilish's bror och producent?",o:["Ryan","Finneas","Declan","Ryder"],a:1,d:3},
    {q:"Vilket år kom Kendrick Lamars 'To Pimp a Butterfly'?",o:["2013","2015","2017","2019"],a:1,d:3},
    {q:"Vilket år kom Frank Oceans 'Blonde'?",o:["2014","2016","2018","2020"],a:1,d:3},
    {q:"Vem producerade Dua Lipas 'Future Nostalgia'?",o:["Max Martin","Stuart Price","Ian Kirkpatrick","Jeff Bhasker"],a:1,d:3},
    {q:"Vad heter Taylor Swifts Re-recordings-era?",o:["Taylor's Version","Redux","Reimagined","Revisited"],a:0,d:3},
    {q:"Vilket år kom The Weeknds 'After Hours'?",o:["2018","2020","2022","2024"],a:1,d:3},
    {q:"Vilket skivbolag är Olivia Rodrigo på?",o:["Republic","Geffen","Interscope","Geffen/Interscope"],a:3,d:3},
    {q:"Vem producerade Billie Eilish's 'When We All Fall Asleep'?",o:["Pharrell","Finneas O'Connell","Max Martin","No I.D."],a:1,d:3},
  ],

  "🎵 Popmusik (allmänt)": [
    {q:"Vilket land kommer ABBA ifrån?",o:["Norge","Danmark","Sverige","Finland"],a:2,d:1},
    {q:"Vem är känd som 'King of Pop'?",o:["Elvis Presley","Prince","Michael Jackson","David Bowie"],a:2,d:1},
    {q:"Vilket band sjöng 'Bohemian Rhapsody'?",o:["Led Zeppelin","The Beatles","Queen","Rolling Stones"],a:2,d:1},
    {q:"Vem sjunger 'Rolling in the Deep'?",o:["Amy Winehouse","Adele","Duffy","Paloma Faith"],a:1,d:1},
    {q:"Vem sjunger 'Someone Like You'?",o:["Adele","Amy Winehouse","Duffy","Ellie Goulding"],a:0,d:1},
    {q:"Vilket år vann ABBA Eurovision med 'Waterloo'?",o:["1972","1974","1976","1978"],a:1,d:1},
    {q:"Vem sjunger 'Toxic'?",o:["Christina Aguilera","Britney Spears","Kylie Minogue","Pink"],a:1,d:1},
    {q:"Vilket land vann Eurovision 2023?",o:["Sverige","Finland","Ukraina","Italien"],a:0,d:1},
    {q:"Vem sjunger 'Hotel California'?",o:["Fleetwood Mac","Eagles","Dire Straits","The Doors"],a:1,d:1},
    {q:"Vem sjunger 'chandelier'?",o:["Lorde","Lana Del Rey","Sia","Ellie Goulding"],a:2,d:1},
    {q:"Vem sjunger 'Thriller'?",o:["Prince","Michael Jackson","James Brown","Stevie Wonder"],a:1,d:1},
    {q:"Vilket band sjöng 'Mr. Brightside'?",o:["The Strokes","The Killers","Interpol","Franz Ferdinand"],a:1,d:1},
    {q:"Vad heter Madonnas debutalbum?",o:["True Blue","Like a Virgin","Madonna","Immaculate Collection"],a:2,d:2},
    {q:"Vilket år grundades Spice Girls?",o:["1992","1994","1996","1998"],a:1,d:2},
    {q:"Vad heter Beyoncés soloalbum från 2003?",o:["Lemonade","4","Dangerously in Love","B'Day"],a:2,d:2},
    {q:"Vem sjunger 'Poker Face'?",o:["Katy Perry","Rihanna","Lady Gaga","Pink"],a:2,d:2},
    {q:"Vilket år kom Rihannas 'Umbrella'?",o:["2005","2007","2009","2011"],a:1,d:2},
    {q:"Vad heter Lady Gagas riktiga namn?",o:["Stefani Germanotta","Stefani Joanne Germanotta","Joanne Germanotta","Stefani Angelina"],a:1,d:2},
    {q:"Vilket år vann Loreen Eurovision första gången?",o:["2010","2012","2014","2016"],a:1,d:2},
    {q:"Vilket år kom PSY's 'Gangnam Style'?",o:["2010","2012","2014","2016"],a:1,d:2},
    {q:"Vem sjunger 'Born This Way'?",o:["Katy Perry","Rihanna","Lady Gaga","Kesha"],a:2,d:2},
    {q:"Vilket år kom Adeles '21'?",o:["2009","2011","2013","2015"],a:1,d:2},
    {q:"På vilket skivbolag debuterade ABBA?",o:["Polar","Epic","CBS","Atlantic"],a:0,d:3},
    {q:"Vem producerade Michael Jacksons 'Thriller'?",o:["Berry Gordy","Quincy Jones","Teddy Riley","Babyface"],a:1,d:3},
    {q:"Vad heter ABBA-medlemmens Agnethas efternamn?",o:["Fältskog","Lindqvist","Andersson","Björk"],a:0,d:3},
    {q:"Vilket år bildades Queen?",o:["1968","1970","1972","1974"],a:1,d:3},
    {q:"Vem producerade Madonnas 'Like a Prayer'?",o:["Nile Rodgers","Patrick Leonard","Jellybean Benitez","Steve Bray"],a:1,d:3},
    {q:"Vad heter Beyoncés album från 2016?",o:["Renaissance","4","Lemonade","Self-titled"],a:2,d:3},
    {q:"Vilket skivbolag gav ut Lady Gagas debutalbum?",o:["Universal","Interscope","Atlantic","Columbia"],a:1,d:3},
    {q:"Vilket år kom Kylie Minogues genombrott salbum 'Fever'?",o:["1999","2001","2003","2005"],a:1,d:3},
  ],

  "🎸 Rock & Metal": [
    {q:"Vilket band sjöng 'Smells Like Teen Spirit'?",o:["Pearl Jam","Soundgarden","Nirvana","Alice in Chains"],a:2,d:1},
    {q:"Vilket band spelade 'Enter Sandman'?",o:["Slayer","Metallica","Megadeth","Anthrax"],a:1,d:1},
    {q:"Vem kallas 'The Boss' inom rock?",o:["Jon Bon Jovi","Bruce Springsteen","Mick Jagger","Tom Petty"],a:1,d:1},
    {q:"Vilket band sjöng 'Back in Black'?",o:["AC/DC","Aerosmith","Kiss","Motörhead"],a:0,d:1},
    {q:"Vem är sångare i Iron Maiden?",o:["Rob Halford","Ozzy Osbourne","Bruce Dickinson","Dio"],a:2,d:1},
    {q:"Vilket band sjöng 'Welcome to the Jungle'?",o:["Mötley Crüe","Def Leppard","Guns N' Roses","Poison"],a:2,d:1},
    {q:"Vilket band sjöng 'Paranoid'?",o:["Deep Purple","Black Sabbath","Judas Priest","Ozzy Osbourne"],a:1,d:1},
    {q:"Vem är gitarrist i Rolling Stones?",o:["Pete Townshend","Jimmy Page","Keith Richards","Eric Clapton"],a:2,d:1},
    {q:"Vilket band sjöng 'Livin' on a Prayer'?",o:["Aerosmith","Bon Jovi","Journey","Def Leppard"],a:1,d:1},
    {q:"Vilket band sjöng 'Eye of the Tiger'?",o:["Foreigner","Night Ranger","Survivor","Asia"],a:2,d:1},
    {q:"Vilket band sjöng 'Sweet Home Alabama'?",o:["The Allman Brothers","Lynyrd Skynyrd","ZZ Top","38 Special"],a:1,d:1},
    {q:"Vem sjunger i Led Zeppelin?",o:["Roger Plant","Robert Plant","Richard Plant","Ronald Plant"],a:1,d:1},
    {q:"Vilket år kom Metallicas svarta album?",o:["1989","1991","1993","1995"],a:1,d:2},
    {q:"Vad heter Nirvanas debutalbum?",o:["Nevermind","In Utero","Bleach","Incesticide"],a:2,d:2},
    {q:"Vilket år upplöstes The Beatles?",o:["1968","1970","1972","1974"],a:1,d:2},
    {q:"Vilket band sjöng 'Under the Bridge'?",o:["Pearl Jam","Red Hot Chili Peppers","Soundgarden","Stone Temple Pilots"],a:1,d:2},
    {q:"Vilket band sjöng 'Man in the Box'?",o:["Pearl Jam","Soundgarden","Alice in Chains","Temple of the Dog"],a:2,d:2},
    {q:"Vilket år bildades Metallica?",o:["1979","1981","1983","1985"],a:1,d:2},
    {q:"Vilket band sjöng 'Creep'?",o:["Oasis","Blur","Radiohead","Suede"],a:2,d:2},
    {q:"Vilket år kom Led Zeppelins debutalbum?",o:["1967","1969","1971","1973"],a:1,d:2},
    {q:"Vilket band sjöng 'Black Hole Sun'?",o:["Pearl Jam","Alice in Chains","Soundgarden","Stone Temple Pilots"],a:2,d:2},
    {q:"Vilket band sjöng 'Hotel California'?",o:["Fleetwood Mac","Eagles","Dire Straits","The Doors"],a:1,d:2},
    {q:"På vilket skivbolag debuterade Nirvana?",o:["DGC Records","Sub Pop","Geffen","Epitaph"],a:1,d:3},
    {q:"Vem producerade Nevermind?",o:["Steve Albini","Rick Rubin","Butch Vig","Jack Endino"],a:2,d:3},
    {q:"Vad heter Iron Maidens maskot?",o:["Vic","Eddie","Spike","Axe"],a:1,d:3},
    {q:"Vilket album innehåller Black Sabbaths 'Iron Man'?",o:["Black Sabbath","Paranoid","Master of Reality","Vol. 4"],a:1,d:3},
    {q:"Vad heter Ozzy Osbournes riktiga förnamn?",o:["Oscar","John","Ozzy","James"],a:1,d:3},
    {q:"Vilket år bildades Black Sabbath?",o:["1966","1968","1970","1972"],a:1,d:3},
    {q:"Vilket år spelade Led Zeppelin sista turnén?",o:["1975","1977","1979","1980"],a:3,d:3},
    {q:"Vem var originaltrummisen i AC/DC?",o:["Phil Rudd","Simon Wright","Chris Slade","Peter Clack"],a:0,d:3},
  ],

  "🔥 Heavy Metal": [
    {q:"Vilket band spelade 'Enter Sandman'?",o:["Slayer","Metallica","Megadeth","Anthrax"],a:1,d:1},
    {q:"Vem är sångare i Iron Maiden?",o:["Rob Halford","Ozzy Osbourne","Bruce Dickinson","Dio"],a:2,d:1},
    {q:"Vilket band sjöng 'Paranoid'?",o:["Deep Purple","Black Sabbath","Judas Priest","Ozzy Osbourne"],a:1,d:1},
    {q:"Vilket band sjöng 'Welcome to the Jungle'?",o:["Mötley Crüe","Def Leppard","Guns N' Roses","Poison"],a:2,d:1},
    {q:"Vem är sångare i Judas Priest?",o:["Ozzy Osbourne","Rob Halford","Bruce Dickinson","Ronnie James Dio"],a:1,d:1},
    {q:"Vilket band sjöng 'Ace of Spades'?",o:["Black Sabbath","Deep Purple","Motörhead","Venom"],a:2,d:1},
    {q:"Vilket band sjöng 'Master of Puppets'?",o:["Slayer","Megadeth","Metallica","Anthrax"],a:2,d:1},
    {q:"Vilket band sjöng 'War Pigs'?",o:["Deep Purple","Black Sabbath","Judas Priest","Led Zeppelin"],a:1,d:1},
    {q:"Vem är sångare i Ozzy Osbournes band?",o:["Rob Halford","Ozzy Osbourne","Glenn Hughes","David Coverdale"],a:1,d:1},
    {q:"Vilket band sjöng 'Raining Blood'?",o:["Metallica","Megadeth","Slayer","Anthrax"],a:2,d:1},
    {q:"Vilket band sjöng 'Holy Diver'?",o:["Black Sabbath","Rainbow","Dio","Ozzy Osbourne"],a:2,d:1},
    {q:"Vilket band sjöng 'Am I Evil?'?",o:["Iron Maiden","Diamond Head","Saxon","Judas Priest"],a:1,d:1},
    {q:"Vilket år bildades Black Sabbath?",o:["1966","1968","1970","1972"],a:1,d:2},
    {q:"Vilket år bildades Metallica?",o:["1979","1981","1983","1985"],a:1,d:2},
    {q:"Vad heter Iron Maidens maskot?",o:["Vic","Eddie","Spike","Axe"],a:1,d:2},
    {q:"Vilket album innehåller Metallicas 'One'?",o:["Ride the Lightning","Master of Puppets","...And Justice for All","Metallica"],a:2,d:2},
    {q:"Vilket band sjöng 'Cowboys from Hell'?",o:["Slayer","Pantera","Sepultura","Machine Head"],a:1,d:2},
    {q:"Vem spelade bas i Metallica tills 1986?",o:["Jason Newsted","Robert Trujillo","Ron McGovney","Cliff Burton"],a:3,d:2},
    {q:"Vilket band sjöng 'Down with the Sickness'?",o:["Slipknot","Disturbed","Drowning Pool","Papa Roach"],a:1,d:2},
    {q:"Vilket år kom Slipknots debutalbum?",o:["1997","1999","2001","2003"],a:1,d:2},
    {q:"Vilket band sjöng 'Chop Suey!'?",o:["Slipknot","Korn","System of a Down","Linkin Park"],a:2,d:2},
    {q:"Vilket år kom Pantera's 'Vulgar Display of Power'?",o:["1990","1992","1994","1996"],a:1,d:2},
    {q:"Vad heter Ozzy Osbournes riktiga förnamn?",o:["Oscar","John","Ozzy","James"],a:1,d:3},
    {q:"Vem producerade Metallicas 'Master of Puppets'?",o:["Rick Rubin","Flemming Rasmussen","Bob Rock","James Hetfield"],a:1,d:3},
    {q:"Vilket år kom Iron Maidens 'The Number of the Beast'?",o:["1980","1982","1984","1986"],a:1,d:3},
    {q:"Vad heter gitarristen i Black Sabbath (originalbandet)?",o:["Glenn Tipton","Tony Iommi","KK Downing","Dave Murray"],a:1,d:3},
    {q:"Vilket år kom Slayers 'Reign in Blood'?",o:["1984","1986","1988","1990"],a:1,d:3},
    {q:"Vilket skivbolag gav ut Metallicas tidiga album?",o:["Columbia","Megaforce/Elektra","Atlantic","Roadrunner"],a:1,d:3},
    {q:"Vem grundade Megadeth efter att ha lämnat Metallica?",o:["Lars Ulrich","Kirk Hammett","Dave Mustaine","Jason Newsted"],a:2,d:3},
    {q:"Vilket år kom Pantera's debut på major-label?",o:["1988","1990","1992","1994"],a:1,d:3},
  ],

  "🇸🇪 Svensk musik": [
    {q:"Vilket band sjöng 'The Sign'?",o:["Roxette","ABBA","Ace of Base","Robyn"],a:2,d:1},
    {q:"Vad heter Aviciis mest kända låt?",o:["Fade into Darkness","Levels","Wake Me Up","Hey Brother"],a:1,d:1},
    {q:"Vilket band sjöng 'It Must Have Been Love'?",o:["ABBA","Ace of Base","Roxette","Carola"],a:2,d:1},
    {q:"Var är Håkan Hellström uppvuxen?",o:["Stockholm","Malmö","Göteborg","Uppsala"],a:2,d:1},
    {q:"Vem sjunger 'Euphoria' (Eurovision 2012)?",o:["Carola","Charlotte Perrelli","Loreen","Petra Mede"],a:2,d:1},
    {q:"Vilket band sjöng 'Lovefool'?",o:["Roxette","The Cardigans","Ace of Base","Sahara Hotnights"],a:1,d:1},
    {q:"Vad heter Aviciis riktiga namn?",o:["Tim Bergling","Tim Svensson","Tim Lindqvist","Tim Berg"],a:0,d:1},
    {q:"Vilket band är Per Gessle med i?",o:["ABBA","Ace of Base","Roxette","The Hellacopters"],a:2,d:1},
    {q:"Vem sjunger 'Sommartider'?",o:["Gyllene Tider","Roxette","Per Gessle solo","Bob Hund"],a:0,d:1},
    {q:"Vad heter Robyn egentligen?",o:["Robin Carlsson","Robyn Andersson","Robin Miriam Carlsson","Robyn Lindqvist"],a:2,d:1},
    {q:"Vilket år vann ABBA Eurovision?",o:["1972","1974","1976","1978"],a:1,d:1},
    {q:"Vem sjunger 'En dag'?",o:["Lars Winnerbäck","Håkan Hellström","Magnus Uggla","Ulf Lundell"],a:0,d:1},
    {q:"Vad heter Max Martins riktiga namn?",o:["Martin Sandberg","Max Sandberg","Martin Carlsson","Max Karlsson"],a:0,d:2},
    {q:"Vilket år grundades Swedish House Mafia?",o:["2002","2004","2006","2008"],a:2,d:2},
    {q:"Vem vann Melodifestivalen 2012?",o:["Loreen","Eric Saade","Danny Saucedo","Sonja Aldén"],a:0,d:2},
    {q:"Vad heter Swedish House Mafias tre medlemmar?",o:["Axwell, Steve Angello, Sebastian Ingrosso","Axwell, Avicii, Alesso","Avicii, Alesso, Ingrosso","Axwell, Tiesto, Ingrosso"],a:0,d:2},
    {q:"Vilket band sjöng 'Omogen'?",o:["Gyllene Tider","Imperiet","Eldkvarn","Nationalteatern"],a:0,d:2},
    {q:"Vilken stad kommer The Hives ifrån?",o:["Stockholm","Göteborg","Fagersta","Örebro"],a:2,d:2},
    {q:"Vilket år bildades Gyllene Tider?",o:["1974","1976","1978","1980"],a:1,d:2},
    {q:"Vem producerade Ace of Base's 'The Sign'?",o:["Max Martin","Denniz Pop","Rolf Ellmer","Jonas Berggren"],a:1,d:2},
    {q:"Vilket år debuterade Robyn?",o:["1993","1995","1997","1999"],a:1,d:2},
    {q:"Vilket år vann Loreen Eurovision andra gången?",o:["2021","2022","2023","2024"],a:2,d:2},
    {q:"På vilket skivbolag debuterade ABBA?",o:["Polar","Epic","CBS","Atlantic"],a:0,d:3},
    {q:"Vem spelade trummor som session-musiker på ABBA-skivor?",o:["Ola Brunkert","Roger Palm","Christer Eklund","Malando Gassama"],a:0,d:3},
    {q:"Vilket år startade Denniz Pop sin karriär som producent?",o:["1983","1985","1987","1989"],a:2,d:3},
    {q:"Vad heter The Cardigans sångerskas fullständiga namn?",o:["Nina Persson","Nina Carlsson","Nina Lindqvist","Nina Svensson"],a:0,d:3},
    {q:"Vilket år bildades Roxette?",o:["1982","1984","1986","1988"],a:1,d:3},
    {q:"Vem var sångare i Imperiet?",o:["Håkan Hellström","Joakim Thåström","Thomas Eriksson","Ulf Lundell"],a:1,d:3},
    {q:"Vilket skivbolag är The Hives på?",o:["Burning Heart","Epitaph","Poptones","Atlantic"],a:0,d:3},
    {q:"Vilket år kom Aviciis debutalbum 'True'?",o:["2011","2013","2015","2017"],a:1,d:3},
  ],

  // ════════════════════════════════════
  //  FILM & TV
  // ════════════════════════════════════

  "🎬 Movie Quiz": [
    {q:"Vem spelar Iron Man i MCU?",o:["Chris Evans","Robert Downey Jr.","Chris Hemsworth","Mark Ruffalo"],a:1,d:1},
    {q:"Vilket år kom Titanic?",o:["1995","1996","1997","1998"],a:2,d:1},
    {q:"Vem regisserade Jurassic Park?",o:["James Cameron","Steven Spielberg","George Lucas","Ridley Scott"],a:1,d:1},
    {q:"Vilket år kom första Star Wars-filmen?",o:["1975","1977","1979","1981"],a:1,d:1},
    {q:"Vem spelar Jack i Titanic?",o:["Brad Pitt","Johnny Depp","Leonardo DiCaprio","Matt Damon"],a:2,d:1},
    {q:"Vem spelar Forrest Gump?",o:["Tom Cruise","Tom Hanks","Tom Selleck","Tom Hardy"],a:1,d:1},
    {q:"Vad heter Batmans alter ego?",o:["Clark Kent","Peter Parker","Bruce Wayne","Tony Stark"],a:2,d:1},
    {q:"Vilket land producerade Parasite?",o:["Japan","Kina","Sydkorea","Thailand"],a:2,d:1},
    {q:"Vem spelar Katniss i Hunger Games?",o:["Emma Stone","Jennifer Lawrence","Shailene Woodley","Kristen Stewart"],a:1,d:1},
    {q:"Vem spelar Hermione Granger i Harry Potter?",o:["Emma Roberts","Emma Stone","Emma Watson","Emily Blunt"],a:2,d:1},
    {q:"Vem spelar Neo i Matrix?",o:["Brad Pitt","Keanu Reeves","Tom Cruise","Will Smith"],a:1,d:1},
    {q:"Vilket år kom The Avengers?",o:["2010","2012","2014","2016"],a:1,d:1},
    {q:"Vem regisserade The Dark Knight?",o:["Tim Burton","Joel Schumacher","Christopher Nolan","Zack Snyder"],a:2,d:2},
    {q:"Vem regisserade Pulp Fiction?",o:["Martin Scorsese","Quentin Tarantino","Coen Brothers","David Fincher"],a:1,d:2},
    {q:"Vilket år kom The Shawshank Redemption?",o:["1992","1994","1996","1998"],a:1,d:2},
    {q:"Vem spelar Don Corleone i The Godfather?",o:["Al Pacino","Robert De Niro","Marlon Brando","Jack Nicholson"],a:2,d:2},
    {q:"Vem regisserade Inception?",o:["Ridley Scott","Christopher Nolan","David Fincher","Darren Aronofsky"],a:1,d:2},
    {q:"Vilket år vann Parasite Oscar för bästa film?",o:["2018","2019","2020","2021"],a:2,d:2},
    {q:"Vem spelar Wolverine i X-Men?",o:["Chris Evans","Hugh Jackman","Ryan Reynolds","Ben Affleck"],a:1,d:2},
    {q:"Vilket år kom Gladiator?",o:["1998","2000","2002","2004"],a:1,d:2},
    {q:"Vem regisserade Schindler's List?",o:["Martin Scorsese","Francis Ford Coppola","Steven Spielberg","Clint Eastwood"],a:2,d:2},
    {q:"Vilket år kom första Transformers-filmen?",o:["2005","2007","2009","2011"],a:1,d:2},
    {q:"Vem komponerade musiken till Star Wars?",o:["Hans Zimmer","Danny Elfman","John Williams","Ennio Morricone"],a:2,d:3},
    {q:"Vilket år kom Citizen Kane?",o:["1938","1941","1944","1947"],a:1,d:3},
    {q:"Vem regisserade 2001: A Space Odyssey?",o:["Steven Spielberg","Stanley Kubrick","Ridley Scott","Francis Ford Coppola"],a:1,d:3},
    {q:"Vem regisserade Apocalypse Now?",o:["Martin Scorsese","Francis Ford Coppola","Stanley Kubrick","Brian De Palma"],a:1,d:3},
    {q:"Vilket år vann 'Everything Everywhere All At Once' Oscar?",o:["2021","2022","2023","2024"],a:2,d:3},
    {q:"Vem spelade Hannibal Lecter i Silence of the Lambs?",o:["Gary Oldman","Anthony Hopkins","Jeremy Irons","Ian McKellen"],a:1,d:3},
    {q:"Vilket år kom The Godfather?",o:["1970","1972","1974","1976"],a:1,d:3},
    {q:"Vem regisserade Blade Runner (1982)?",o:["James Cameron","Steven Spielberg","Ridley Scott","David Lynch"],a:2,d:3},
  ],

  "📺 TV-serier": [
    {q:"Vilket TV-program handlade om vänner i New York?",o:["Seinfeld","Friends","Frasier","Will & Grace"],a:1,d:1},
    {q:"Vem spelar Walter White i Breaking Bad?",o:["Bryan Cranston","Aaron Paul","Bob Odenkirk","Dean Norris"],a:0,d:1},
    {q:"Vilket år kom Game of Thrones?",o:["2009","2011","2013","2015"],a:1,d:1},
    {q:"Vilket år kom Breaking Bad?",o:["2006","2008","2010","2012"],a:1,d:1},
    {q:"Vem spelar Tony Soprano i The Sopranos?",o:["Joe Pesci","Robert De Niro","James Gandolfini","Al Pacino"],a:2,d:1},
    {q:"Vilket år kom Stranger Things?",o:["2014","2016","2018","2020"],a:1,d:1},
    {q:"Vem spelar Daenerys Targaryen i Game of Thrones?",o:["Sophie Turner","Natalie Dormer","Emilia Clarke","Kit Harington"],a:2,d:1},
    {q:"Vilket år kom första säsongen av Friends?",o:["1992","1994","1996","1998"],a:1,d:1},
    {q:"Vem spelar Sheldon Cooper i The Big Bang Theory?",o:["Johnny Galecki","Jim Parsons","Kunal Nayyar","Simon Helberg"],a:1,d:1},
    {q:"Vilket år kom The Office (USA)?",o:["2003","2005","2007","2009"],a:1,d:1},
    {q:"Vilket år kom The Mandalorian?",o:["2017","2019","2021","2023"],a:1,d:1},
    {q:"Vem skapar kaos i Black Mirror?",o:["Framtida AI","Framtida teknologi","Nutida människor","Utomjordingar"],a:1,d:1},
    {q:"Vilket år kom The Sopranos?",o:["1997","1999","2001","2003"],a:1,d:2},
    {q:"Vilket år kom The Wire?",o:["2000","2002","2004","2006"],a:1,d:2},
    {q:"Vem skapar och spelar i Succession?",o:["David Chase","Vince Gilligan","Jesse Armstrong","Matthew Weiner"],a:2,d:2},
    {q:"Vilket år kom Black Mirror?",o:["2009","2011","2013","2015"],a:1,d:2},
    {q:"Vem skapar 'Fleabag'?",o:["Sharon Horgan","Phoebe Waller-Bridge","Lena Dunham","Mindy Kaling"],a:1,d:2},
    {q:"Vilket år kom Seinfeld?",o:["1987","1989","1991","1993"],a:1,d:2},
    {q:"Vilket år kom Mad Men?",o:["2005","2007","2009","2011"],a:1,d:2},
    {q:"Vem spelar protagonisten i Fleabag?",o:["Sharon Horgan","Phoebe Waller-Bridge","Claire Foy","Olivia Colman"],a:1,d:2},
    {q:"Vilket år kom Miniseries Chernobyl?",o:["2017","2019","2021","2023"],a:1,d:2},
    {q:"Vilket år kom Severance?",o:["2020","2022","2023","2024"],a:1,d:2},
    {q:"Vem skapade Breaking Bad?",o:["David Chase","David Simon","Vince Gilligan","Matthew Weiner"],a:2,d:3},
    {q:"Vilket år kom The Wire?",o:["2000","2002","2004","2006"],a:1,d:3},
    {q:"Vad heter karaktären Jack Bauer i?",o:["The Shield","24","Alias","Prison Break"],a:1,d:3},
    {q:"Vilket år kom Deadwood?",o:["2002","2004","2006","2008"],a:1,d:3},
    {q:"Vem skapade Mad Men?",o:["David Chase","David Simon","Vince Gilligan","Matthew Weiner"],a:3,d:3},
    {q:"Hur många säsonger hade The Wire?",o:["3","4","5","6"],a:2,d:3},
    {q:"Vilket år kom Battlestar Galactica (nya versionen)?",o:["2001","2003","2005","2007"],a:1,d:3},
    {q:"Vem spelar huvudrollen i Mr. Robot?",o:["Christian Slater","Rami Malek","B.D. Wong","Martin Wallström"],a:1,d:3},
  ],

  // ════════════════════════════════════
  //  DISNEY & BARN
  // ════════════════════════════════════

  "🏰 Disney Klassiker": [
    {q:"Vad heter lejonungen i Lejonkungen?",o:["Simba","Nala","Mufasa","Pumba"],a:0,d:1},
    {q:"Vad heter fiskens pappa i Hitta Nemo?",o:["Martin","Marlin","Marcel","Marco"],a:1,d:1},
    {q:"Vad heter cowboyen i Toy Story?",o:["Buzz","Woody","Rex","Hamm"],a:1,d:1},
    {q:"Vad heter prinsessan i Törnrosa?",o:["Aurora","Ariel","Belle","Jasmine"],a:0,d:1},
    {q:"Vilket djur är Dumbo?",o:["Häst","Giraff","Elefant","Noshörning"],a:2,d:1},
    {q:"Vilket år kom Lejonkungen?",o:["1990","1992","1994","1996"],a:2,d:1},
    {q:"Vad heter häxan i Snövit?",o:["Ursula","Maleficent","Den onda drottningen","Gothel"],a:2,d:1},
    {q:"Vad heter rymdkommandot i Toy Story?",o:["Woody","Buzz Lightyear","Rex","Hamm"],a:1,d:1},
    {q:"Vad heter musen i Ratatouille?",o:["Emile","Gusteau","Remy","Anton"],a:2,d:1},
    {q:"Vad heter Ariels bästa fiskekompis i Den lilla sjöjungfrun?",o:["Sebastian","Flounder","Scuttle","Louis"],a:1,d:1},
    {q:"Vad heter häxan i Den lilla sjöjungfrun?",o:["Maleficent","Ursula","Gothel","The Evil Queen"],a:1,d:1},
    {q:"Vad heter Mulans drake?",o:["Shang","Mushu","Cri-Kee","Khan"],a:1,d:1},
    {q:"Vilket år kom Toy Story?",o:["1993","1995","1997","1999"],a:1,d:2},
    {q:"Vilket år kom Hitta Nemo?",o:["2001","2003","2005","2007"],a:1,d:2},
    {q:"Vem röstade Woody i Toy Story originalet?",o:["Tom Hanks","Tim Allen","Billy Crystal","John Goodman"],a:0,d:2},
    {q:"Vilket år kom Aladdin?",o:["1990","1992","1994","1996"],a:1,d:2},
    {q:"Vilket år kom Beauty and the Beast?",o:["1989","1991","1993","1995"],a:1,d:2},
    {q:"Vilket år kom Mulan?",o:["1994","1996","1998","2000"],a:2,d:2},
    {q:"Vad heter prinsessan i Vaiana/Moana?",o:["Tamatoa","Moana","Raya","Merida"],a:1,d:2},
    {q:"Vilket år kom The Incredibles?",o:["2002","2004","2006","2008"],a:1,d:2},
    {q:"Vad heter restaurangen i Ratatouille?",o:["La Maison","Gusteau's","Le Cordon","Chez Gustave"],a:1,d:2},
    {q:"Vilket år kom Up?",o:["2007","2009","2011","2013"],a:1,d:2},
    {q:"Vilket år kom Disneys första film Snövit?",o:["1934","1937","1940","1943"],a:1,d:3},
    {q:"Vem komponerade musiken till Lejonkungen?",o:["Alan Menken","Howard Ashman","Hans Zimmer","Elton John"],a:2,d:3},
    {q:"Vem röstade Scar i Lejonkungen originalet?",o:["Tim Curry","Jeremy Irons","Ian McKellen","Alan Rickman"],a:1,d:3},
    {q:"Vilket Pixar-film kom allra först?",o:["A Bug's Life","Toy Story","Monsters Inc","Finding Nemo"],a:1,d:3},
    {q:"Vilket år kom Fantasia?",o:["1938","1940","1942","1944"],a:1,d:3},
    {q:"Vem komponerade musiken till Den lilla sjöjungfrun?",o:["Elton John","Alan Menken","Phil Collins","Randy Newman"],a:1,d:3},
    {q:"Vilket år kom Pixars 'Brave'?",o:["2010","2012","2014","2016"],a:1,d:3},
    {q:"Vem röstade Genie i Aladdin?",o:["Jim Carrey","Steve Martin","Robin Williams","Billy Crystal"],a:2,d:3},
  ],

  "❄️ Frost & Moderna Disney": [
    {q:"Vad heter prinsessorna i Frost?",o:["Anna och Bella","Elsa och Anna","Elsa och Sofia","Anna och Kristina"],a:1,d:1},
    {q:"Vilket år kom Frost?",o:["2011","2013","2015","2017"],a:1,d:1},
    {q:"Vad heter rendjuret i Frost?",o:["Olaf","Kristoff","Sven","Hans"],a:2,d:1},
    {q:"Vad heter snögubben i Frost?",o:["Olaf","Sven","Kristoff","Hans"],a:0,d:1},
    {q:"Vilket år kom Frost 2?",o:["2017","2019","2021","2023"],a:1,d:1},
    {q:"Vad heter Moanas höna?",o:["Tamatoa","Maui","Hei Hei","Te Kā"],a:2,d:1},
    {q:"Vilket år kom Encanto?",o:["2019","2021","2022","2023"],a:1,d:1},
    {q:"Vad heter Miraculos superhjälte?",o:["Marinette","Ladybug","Adrien","Chat Noir"],a:1,d:1},
    {q:"Vilket år kom Zootopia?",o:["2014","2016","2018","2020"],a:1,d:1},
    {q:"Vad heter prinsessan i Tangled (Trassel)?",o:["Ariel","Rapunzel","Belle","Aurora"],a:1,d:1},
    {q:"Vad heter antagonisten i Frost?",o:["Kristoff","Hans","Duke","Marshmallow"],a:1,d:1},
    {q:"Vilket år kom Coco (Pixar)?",o:["2015","2017","2019","2021"],a:1,d:1},
    {q:"Vem sjunger 'Let It Go' på svenska?",o:["Helen Sjöholm","Charlotte Perrelli","Melodikrysset","Katarina Ewerlöf"],a:0,d:2},
    {q:"Vilket år kom Moana/Vaiana?",o:["2014","2016","2018","2020"],a:1,d:2},
    {q:"Vad heter halvguden i Moana?",o:["Tamatoa","Maui","Hei Hei","Te Fiti"],a:1,d:2},
    {q:"Vilket år kom Big Hero 6?",o:["2012","2014","2016","2018"],a:1,d:2},
    {q:"Vad heter roboten i Big Hero 6?",o:["Baymax","Hiro","Tadashi","Go Go"],a:0,d:2},
    {q:"Vilket år kom Turning Red?",o:["2020","2022","2023","2024"],a:1,d:2},
    {q:"Vilket år kom Raya and the Last Dragon?",o:["2019","2021","2022","2023"],a:1,d:2},
    {q:"Vem sjunger 'Surface Pressure' i Encanto?",o:["Luisa","Mirabel","Isabela","Dolores"],a:0,d:2},
    {q:"Vilket år kom Brave (Vild)?",o:["2010","2012","2014","2016"],a:1,d:2},
    {q:"Vad heter hästen i Tangled?",o:["Maximus","Samson","Angus","Achilles"],a:0,d:2},
    {q:"Vem regisserade Frost?",o:["John Lasseter","Pete Docter","Chris Buck & Jennifer Lee","Andrew Stanton"],a:2,d:3},
    {q:"Vilket år kom Inside Out 2?",o:["2022","2023","2024","2025"],a:2,d:3},
    {q:"Vad heter Elsas och Annas mamma?",o:["Elsa","Iduna","Gerda","Ingrid"],a:1,d:3},
    {q:"Vilket år kom Lightyear (Pixar)?",o:["2020","2022","2023","2024"],a:1,d:3},
    {q:"Vad heter byn i Encanto?",o:["Casita","Colombia","La Familia","Madrigal"],a:0,d:3},
    {q:"Vilket år kom Strange World (Disney)?",o:["2020","2022","2023","2024"],a:1,d:3},
    {q:"Vem sjunger 'We Don't Talk About Bruno'?",o:["Mirabel","Dolores","Camilo","Flera karaktärer"],a:3,d:3},
    {q:"Vilket år kom Pixars 'Soul'?",o:["2018","2020","2022","2024"],a:1,d:3},
  ],

  "🎠 Barnfilmer & Ungdomsfilmer": [
    {q:"Vad heter Pippi Långstrumps häst?",o:["Lansen","Lansen","Lansen","Lansen"],a:0,d:1},
    {q:"Vem spelar Harry Potter?",o:["Rupert Grint","Daniel Radcliffe","Tom Felton","Matthew Lewis"],a:1,d:1},
    {q:"Vilket år kom första Harry Potter-filmen?",o:["1999","2001","2003","2005"],a:1,d:1},
    {q:"Vad heter Hagrids hund i Harry Potter?",o:["Fang","Fluffy","Buckbeak","Nox"],a:0,d:1},
    {q:"Vilket år kom Shrek?",o:["1999","2001","2003","2005"],a:1,d:1},
    {q:"Vad heter åsnan i Shrek?",o:["Donkey","Burro","Mule","Percy"],a:0,d:1},
    {q:"Vilket år kom Narnia: Häxan och lejonet?",o:["2003","2005","2007","2009"],a:1,d:1},
    {q:"Vem spelar Katniss i Hunger Games?",o:["Emma Stone","Jennifer Lawrence","Shailene Woodley","Kristen Stewart"],a:1,d:1},
    {q:"Vilket år kom Twilight?",o:["2006","2008","2010","2012"],a:1,d:1},
    {q:"Vem spelar Edward i Twilight?",o:["Taylor Lautner","Kellan Lutz","Robert Pattinson","Jackson Rathbone"],a:2,d:1},
    {q:"Vilket år kom Hobbit-filmerna (del 1)?",o:["2010","2012","2014","2016"],a:1,d:1},
    {q:"Vem spelar Bilbo Baggins i Hobbit?",o:["Ian McKellen","Martin Freeman","Benedict Cumberbatch","Richard Armitage"],a:1,d:1},
    {q:"Vilket år kom Sagan om Ringen (del 1)?",o:["1999","2001","2003","2005"],a:1,d:2},
    {q:"Vem spelar Frodo i Sagan om Ringen?",o:["Sean Bean","Orlando Bloom","Elijah Wood","Dominic Monaghan"],a:2,d:2},
    {q:"Vilket år kom Divergent?",o:["2012","2014","2016","2018"],a:1,d:2},
    {q:"Vilket år kom The Maze Runner?",o:["2012","2014","2016","2018"],a:1,d:2},
    {q:"Vem spelar Albus Dumbledore i Harry Potter?",o:["Richard Harris/Michael Gambon","Ian McKellen","Patrick Stewart","Anthony Hopkins"],a:0,d:2},
    {q:"Vilket år kom Jumanji?",o:["1993","1995","1997","1999"],a:1,d:2},
    {q:"Vem spelar i Jumanji (1995)?",o:["Tom Hanks","Robin Williams","Jim Carrey","Steve Martin"],a:1,d:2},
    {q:"Vilket år kom Home Alone?",o:["1988","1990","1992","1994"],a:1,d:2},
    {q:"Vem spelar Kevin i Home Alone?",o:["Macaulay Culkin","Haley Joel Osment","Joseph Gordon-Levitt","Ryan Gosling"],a:0,d:2},
    {q:"Vilket år kom Matilda (filmen)?",o:["1992","1994","1996","1998"],a:2,d:2},
    {q:"Vad heter häxan i Roald Dahls 'Häxorna' (1990)?",o:["Anjelica Huston","Meryl Streep","Glenn Close","Sigourney Weaver"],a:0,d:3},
    {q:"Vilket år kom E.T.?",o:["1980","1982","1984","1986"],a:1,d:3},
    {q:"Vem regisserade E.T.?",o:["George Lucas","Steven Spielberg","Robert Zemeckis","Ron Howard"],a:1,d:3},
    {q:"Vilket år kom Goonies?",o:["1983","1985","1987","1989"],a:1,d:3},
    {q:"Vilket år kom Beetlejuice?",o:["1986","1988","1990","1992"],a:1,d:3},
    {q:"Vem regisserade Beetlejuice?",o:["John Hughes","Tim Burton","Joe Dante","Chris Columbus"],a:1,d:3},
    {q:"Vilket år kom Stand by Me?",o:["1984","1986","1988","1990"],a:1,d:3},
    {q:"Vem skriver böckerna om Harry Potter?",o:["Roald Dahl","J.R.R. Tolkien","J.K. Rowling","C.S. Lewis"],a:2,d:3},
  ],

  // ════════════════════════════════════
  //  SPORT
  // ════════════════════════════════════

  "⚽ Fotboll": [
    {q:"Vilket land vann fotbolls-VM 2022?",o:["Brasilien","Frankrike","Argentina","Portugal"],a:2,d:1},
    {q:"Vilket land vann fotbolls-VM 2018?",o:["Tyskland","Brasilien","Frankrike","Argentina"],a:2,d:1},
    {q:"Vem vann Ballon d'Or flest gånger?",o:["Cristiano Ronaldo","Lionel Messi","Ronaldinho","Zidane"],a:1,d:1},
    {q:"Vilket land är Zlatan Ibrahimović från?",o:["Danmark","Finland","Norge","Sverige"],a:3,d:1},
    {q:"Vilket lag spelar hemma på Camp Nou?",o:["Real Madrid","Atletico Madrid","FC Barcelona","Valencia"],a:2,d:1},
    {q:"Vilket lag vann Champions League 2023?",o:["Real Madrid","Manchester City","Bayern München","PSG"],a:1,d:1},
    {q:"Vilket land vann fotbolls-VM 2014?",o:["Brasilien","Argentina","Frankrike","Tyskland"],a:3,d:1},
    {q:"Hur många spelare finns i ett fotbollslag?",o:["10","11","12","9"],a:1,d:1},
    {q:"Vilket land har vunnit flest VM-guld i fotboll?",o:["Argentina","Tyskland","Italien","Brasilien"],a:3,d:1},
    {q:"Vilket lag spelar hemma på Old Trafford?",o:["Arsenal","Liverpool","Manchester United","Chelsea"],a:2,d:1},
    {q:"Vilket år grundades FIFA?",o:["1900","1904","1908","1912"],a:1,d:1},
    {q:"Vad heter Zlatan Ibrahimovićs moderklubb?",o:["Malmö FF","IFK Göteborg","AIK","Djurgårdens IF"],a:0,d:1},
    {q:"Vilket år vann Sverige VM-brons i fotboll?",o:["1950","1958","1966","1974"],a:1,d:2},
    {q:"Vilket år grundades Premier League?",o:["1988","1990","1992","1994"],a:2,d:2},
    {q:"Vem är historiens mestmålsgörare i Champions League?",o:["Lionel Messi","Raul","Cristiano Ronaldo","Karim Benzema"],a:2,d:2},
    {q:"Vilket år introducerades VAR i fotbolls-VM?",o:["2014","2016","2018","2020"],a:2,d:2},
    {q:"Vilket land vann damernas VM i fotboll 2023?",o:["USA","Australien","England","Spanien"],a:3,d:2},
    {q:"Vilket lag vann Champions League 2019?",o:["Barcelona","Juventus","Liverpool","PSG"],a:2,d:2},
    {q:"Hur många mål gjorde Ronaldo i en VM-kval-match (rekord)?",o:["3","4","5","6"],a:2,d:2},
    {q:"Vilket år grundades UEFA Champions League i nuvarande format?",o:["1990","1992","1994","1996"],a:1,d:2},
    {q:"Vilket lag har vunnit flest Premier League-titlar?",o:["Arsenal","Chelsea","Manchester United","Liverpool"],a:2,d:2},
    {q:"Vilket år spelades det första VM i fotboll?",o:["1926","1930","1934","1938"],a:1,d:2},
    {q:"Vilket år spelades Sverige sin första VM-match?",o:["1930","1934","1938","1950"],a:1,d:3},
    {q:"Hur lång är ett standard-fotbollsmatch?",o:["80 min","90 min","100 min","120 min"],a:1,d:3},
    {q:"Vilket land har flest VM-titlar?",o:["Argenthina","Frankrike","Brasilien","Italien"],a:2,d:3},
    {q:"Vad heter rekordet för flest mål i ett VM?",o:["Just Fontaine 1958","Pelé 1970","Gerd Müller 1970","Ronaldo 2002"],a:0,d:3},
    {q:"Vilket år kom VAR till Premier League?",o:["2017","2019","2021","2023"],a:1,d:3},
    {q:"Vem vann Ballon d'Or 2023?",o:["Erling Haaland","Kylian Mbappé","Lionel Messi","Vinicius Jr."],a:2,d:3},
    {q:"Vilket år vann Grekland EM i fotboll (storuppset)?",o:["2000","2002","2004","2006"],a:2,d:3},
    {q:"Vilket lag vann Champions League 2022?",o:["Liverpool","PSG","Bayern München","Real Madrid"],a:3,d:3},
  ],

  "🏒 Ishockey": [
    {q:"Vad heter den svenska elitligan i ishockey?",o:["SHL","SEL","SDHL","Hockeyallsvenskan"],a:0,d:1},
    {q:"Vilket land dominerade OS-guld i ishockey under kalla kriget?",o:["Sverige","USA","Kanada","Sovjet"],a:3,d:1},
    {q:"Vad heter NHL:s mästarpokal?",o:["Presidents Trophy","Hart Trophy","Stanley Cup","Conn Smythe"],a:2,d:1},
    {q:"Vilket lag vann Stanley Cup 2023?",o:["Colorado Avalanche","Tampa Bay Lightning","Vegas Golden Knights","Florida Panthers"],a:2,d:1},
    {q:"Hur många spelare per lag är på isen i ishockey?",o:["5","6","7","4"],a:1,d:1},
    {q:"Vilket land har vunnit flest OS-guld i ishockey (herrar)?",o:["Sverige","USA","Kanada","Sovjet/Ryssland"],a:2,d:1},
    {q:"Vad heter Peter Forsberg?",o:["'The Great One'","'The Rocket'","'Le Magnifique'","'Foppa'"],a:3,d:1},
    {q:"Vilket lag spelar i Stockholm i SHL?",o:["Brynäs IF","Frölunda","Djurgårdens IF","HV71"],a:2,d:1},
    {q:"Vad kallas Wayne Gretzky?",o:["'The Boss'","'The Great One'","'The Rocket'","'Mr. Hockey'"],a:1,d:1},
    {q:"Vilket lag spelar i Göteborg i SHL?",o:["Brynäs IF","Frölunda","Djurgårdens IF","HV71"],a:1,d:1},
    {q:"Vilket land vann VM i ishockey 2024?",o:["Sverige","Finland","Kanada","Tjeckien"],a:2,d:1},
    {q:"Hur många perioder spelas i ishockey?",o:["2","3","4","5"],a:1,d:1},
    {q:"Vilket år vann Sverige OS-guld i ishockey senast?",o:["1994","2002","2006","2018"],a:0,d:2},
    {q:"Vilket lag spelar hemma på Scandinavium i Göteborg?",o:["Brynäs IF","Frölunda","Djurgårdens IF","MODO"],a:1,d:2},
    {q:"Vem håller rekord för flest NHL-poäng?",o:["Mario Lemieux","Mark Messier","Wayne Gretzky","Gordie Howe"],a:2,d:2},
    {q:"Vilket år grundades NHL?",o:["1910","1917","1924","1930"],a:1,d:2},
    {q:"Vilket lag spelar i Gävle i SHL?",o:["Brynäs IF","Frölunda","Djurgårdens IF","HV71"],a:0,d:2},
    {q:"Hur lång är en ishockeyplan?",o:["Ca 50 m","Ca 60 m","Ca 70 m","Ca 80 m"],a:1,d:2},
    {q:"Vilket land vann damernas OS i ishockey 2022?",o:["Sverige","USA","Kanada","Finland"],a:1,d:2},
    {q:"Vilket lag vann Stanley Cup 2022?",o:["Colorado Avalanche","Tampa Bay Lightning","Vegas Golden Knights","Florida Panthers"],a:0,d:2},
    {q:"Vilket år kom MODO till SHL senast?",o:["2018","2020","2022","2024"],a:2,d:2},
    {q:"Vad heter längsta perioden i overtime NHL?",o:["Det finns ingen gräns","60 min","3 perioder extra","Sudden death"],a:3,d:2},
    {q:"Vilket år vann Sverige VM i ishockey senast?",o:["2016","2017","2018","2019"],a:1,d:3},
    {q:"Vem scorer mest poäng i NHL-historia på en enda säsong?",o:["Mario Lemieux","Brett Hull","Wayne Gretzky (215p 1985-86)","Jari Kurri"],a:2,d:3},
    {q:"Vilket år kom Melodifestivalen to NHL (allstars)?",o:["Fakefråga","Sverige","Finns ej","Vet ej"],a:2,d:3},
    {q:"Vilket år vann Tre Kronor Kanada Cup?",o:["1976","1981","1984","1991"],a:2,d:3},
    {q:"Vad heter trofén som ges till bäste NHL-målvakt?",o:["Vezina Trophy","Hart Trophy","Norris Trophy","Calder Trophy"],a:0,d:3},
    {q:"Vilket år grundades Djurgårdens IF hockey?",o:["1912","1921","1930","1945"],a:1,d:3},
    {q:"Hur många NHL-lag finns det?",o:["28","30","32","34"],a:2,d:3},
    {q:"Vilket lag vann Stanley Cup 2021?",o:["Colorado Avalanche","Tampa Bay Lightning","Vegas Golden Knights","Montreal Canadiens"],a:1,d:3},
  ],

  "🏅 Sport (allmänt)": [
    {q:"Vem satte 100m-rekordet på 9.58 sekunder?",o:["Carl Lewis","Maurice Greene","Usain Bolt","Justin Gatlin"],a:2,d:1},
    {q:"I vilken sport tävlar man i Tour de France?",o:["Triathlon","Löpning","Cykling","Simning"],a:2,d:1},
    {q:"Vilket år hölls OS i Stockholm?",o:["1908","1912","1920","1924"],a:1,d:1},
    {q:"Hur många Grand Slam finns det i tennis?",o:["2","3","4","5"],a:2,d:1},
    {q:"Vilken sport spelas i Wimbledon?",o:["Badminton","Squash","Tennis","Padel"],a:2,d:1},
    {q:"Hur långt är ett marathonlopp?",o:["40 km","42,195 km","45 km","50 km"],a:1,d:1},
    {q:"Vilket land har vunnit flest OS-guld totalt?",o:["Ryssland","Kina","USA","Tyskland"],a:2,d:1},
    {q:"Vem vann Formel 1-VM 2021?",o:["Lewis Hamilton","Max Verstappen","Valtteri Bottas","Sebastian Vettel"],a:1,d:1},
    {q:"I vilken sport tävlar man om 'yellow jersey'?",o:["Cykling","Triathlon","Löpning","Simning"],a:0,d:1},
    {q:"Vilket land vann OS-guld i fotboll 2020 (Tokyo)?",o:["Brasilien","Frankrike","Mexiko","Spanien"],a:0,d:1},
    {q:"Vilket år spelades de moderna OS för första gången?",o:["1894","1896","1900","1904"],a:1,d:1},
    {q:"Vem vann Wimbledon damer 2023?",o:["Iga Świątek","Coco Gauff","Markéta Vondroušová","Aryna Sabalenka"],a:2,d:1},
    {q:"Hur många Grand Slam har Roger Federer vunnit?",o:["18","20","22","24"],a:1,d:2},
    {q:"Vem vann Formel 1-VM flest gånger?",o:["Ayrton Senna","Michael Schumacher","Lewis Hamilton","Sebastian Vettel"],a:1,d:2},
    {q:"Vilket år grundades FIFA?",o:["1900","1904","1908","1912"],a:1,d:2},
    {q:"Vilket land har flest Tour de France-segrar (individuellt)?",o:["Frankrike","Belgien","Spanien","USA"],a:2,d:2},
    {q:"Vem satte världsrekordet på maraton 2023?",o:["Eliud Kipchoge","Kenenisa Bekele","Kelvin Kiptum","Geoffrey Kamworor"],a:2,d:2},
    {q:"Vilket år kom padel till Sverige?",o:["1995","2000","2005","2010"],a:2,d:2},
    {q:"Vilken nation har flest OS-guld i simning historiskt?",o:["Australien","Kina","Ryssland","USA"],a:3,d:2},
    {q:"Vilket år hölls OS i Rio de Janeiro?",o:["2012","2014","2016","2018"],a:2,d:2},
    {q:"Vem vann Formel 1-VM 2023?",o:["Lewis Hamilton","Max Verstappen","Charles Leclerc","Sergio Perez"],a:1,d:2},
    {q:"Vilket år hölls OS i Tokyo?",o:["2018","2020","2021","2022"],a:2,d:2},
    {q:"Vilket år grundades FIFA?",o:["1900","1904","1908","1912"],a:1,d:3},
    {q:"Hur många set spelas i herrtennismatch på Grand Slam?",o:["3","5","4","2"],a:1,d:3},
    {q:"Vem vann Wimbledon herrar 2023?",o:["Novak Djokovic","Carlos Alcaraz","Jannik Sinner","Daniil Medvedev"],a:1,d:3},
    {q:"Vilket år vann Sverige damernas VM i fotboll?",o:["Sverige har aldrig vunnit","1991","1995","2003"],a:0,d:3},
    {q:"Vilket land har vunnit flest Formel 1-VM (konstruktörer)?",o:["Ferrari","McLaren","Mercedes","Williams"],a:0,d:3},
    {q:"Hur lång är ett Formel 1-varv ungefär på Monza?",o:["4 km","5,8 km","6,9 km","7,5 km"],a:1,d:3},
    {q:"Vilket år vann Björn Borg sitt sista Wimbledon?",o:["1978","1980","1981","1983"],a:1,d:3},
    {q:"Vilket år hölls OS i München (där terrordådet skedde)?",o:["1968","1972","1976","1980"],a:1,d:3},
  ],

  // ════════════════════════════════════
  //  TEKNIK & VETENSKAP
  // ════════════════════════════════════

  "💻 Teknik & IT": [
    {q:"Vilket företag tillverkar PlayStation?",o:["Microsoft","Nintendo","Sony","Sega"],a:2,d:1},
    {q:"Vilket år lanserades första iPhone?",o:["2005","2007","2009","2011"],a:1,d:1},
    {q:"Vilket företag grundade Bill Gates?",o:["Apple","Amazon","Microsoft","Google"],a:2,d:1},
    {q:"Vilket år grundades Google?",o:["1996","1998","2000","2002"],a:1,d:1},
    {q:"Vad heter Apples smarta assistent?",o:["Cortana","Alexa","Google","Siri"],a:3,d:1},
    {q:"Vilket år grundades Apple?",o:["1974","1976","1978","1980"],a:1,d:1},
    {q:"Vilket år grundades Spotify?",o:["2004","2006","2008","2010"],a:2,d:1},
    {q:"Vad heter Googles mobiloperativsystem?",o:["iOS","Windows Mobile","Android","HarmonyOS"],a:2,d:1},
    {q:"Vilket år grundades Facebook?",o:["2002","2004","2006","2008"],a:1,d:1},
    {q:"Vilket år grundades Amazon?",o:["1992","1994","1996","1998"],a:1,d:1},
    {q:"Vilket år grundades Twitter?",o:["2004","2006","2008","2010"],a:1,d:1},
    {q:"Vem grundade Tesla?",o:["Elon Musk","Martin Eberhard","Jeff Bezos","Larry Page"],a:1,d:1},
    {q:"Vilket år kom första versionen av Windows?",o:["1981","1983","1985","1987"],a:2,d:2},
    {q:"Vad heter Microsofts molntjänst?",o:["AWS","Google Cloud","Azure","IBM Cloud"],a:2,d:2},
    {q:"Vilket år kom Instagram?",o:["2008","2010","2012","2014"],a:1,d:2},
    {q:"Vilket år kom TikTok globalt?",o:["2014","2016","2018","2020"],a:2,d:2},
    {q:"Vem grundade LinkedIn?",o:["Bill Gates","Reid Hoffman","Mark Zuckerberg","Jack Dorsey"],a:1,d:2},
    {q:"Vilket år grundades Uber?",o:["2007","2009","2011","2013"],a:1,d:2},
    {q:"Vilket år lanserades ChatGPT?",o:["2020","2021","2022","2023"],a:2,d:2},
    {q:"Vilket år lanserades Nintendo Switch?",o:["2015","2017","2019","2021"],a:1,d:2},
    {q:"Vilket år grundades NVIDIA?",o:["1989","1991","1993","1995"],a:2,d:2},
    {q:"Vem grundade SpaceX?",o:["Jeff Bezos","Richard Branson","Elon Musk","Larry Page"],a:2,d:2},
    {q:"Vem uppfann World Wide Web?",o:["Bill Gates","Steve Jobs","Tim Berners-Lee","Vint Cerf"],a:2,d:3},
    {q:"Vilket år kom första versionen av Linux?",o:["1989","1991","1993","1995"],a:1,d:3},
    {q:"Vad heter protokollet bakom internet?",o:["HTTP","TCP/IP","FTP","SMTP"],a:1,d:3},
    {q:"Vilket år grundades Intel?",o:["1964","1966","1968","1970"],a:2,d:3},
    {q:"Vad heter Alan Turings test för AI?",o:["Turing Test","Intelligence Test","Machine Test","Imitation Game"],a:0,d:3},
    {q:"Vilket år lanserades Bluetooth-standarden?",o:["1994","1998","2001","2004"],a:1,d:3},
    {q:"Vilket år grundades Anthropic (skaparna av Claude)?",o:["2019","2021","2022","2023"],a:1,d:3},
    {q:"Vad heter Googles kvantdator?",o:["Sycamore","Willow","Bristlecone","Both Sycamore & Willow"],a:3,d:3},
  ],

  "🔬 Vetenskap & Natur": [
    {q:"Vilket är det hårdaste naturliga materialet?",o:["Guld","Granit","Diamant","Järn"],a:2,d:1},
    {q:"Hur många ben har en insekt?",o:["4","6","8","10"],a:1,d:1},
    {q:"Vilket grundämne har kemisk symbol 'Au'?",o:["Silver","Aluminium","Guld","Koppar"],a:2,d:1},
    {q:"Vad är ett ljusår?",o:["Tid ljuset tar att nå solen","Avstånd ljuset färdas på ett år","Hur snabbt ljuset rör sig","Antalet fotoner per sekund"],a:1,d:1},
    {q:"Hur många planeter finns i solsystemet?",o:["7","8","9","10"],a:1,d:1},
    {q:"Vilket grundämne har kemisk symbol 'Fe'?",o:["Fluor","Fosfor","Järn","Francium"],a:2,d:1},
    {q:"Vad är den kemiska formeln för vatten?",o:["HO","H2O","H2O2","HO2"],a:1,d:1},
    {q:"Vilket är jordens närmaste stjärna (förutom solen)?",o:["Sirius","Vega","Proxima Centauri","Betelgeuse"],a:2,d:1},
    {q:"Hur många kromosompar har en människa?",o:["21","23","25","46"],a:1,d:1},
    {q:"Vilket år publicerade Darwin 'Arternas uppkomst'?",o:["1849","1859","1869","1879"],a:1,d:1},
    {q:"Vad är DNA?",o:["Proteinkomplex","Ribosomalt RNA","Deoxiribonukleinsyra","Adenosintrifosfat"],a:2,d:1},
    {q:"Vilket grundämne är flytande vid rumstemperatur (förutom kvicksilver)?",o:["Brom","Jod","Fosfor","Selen"],a:0,d:1},
    {q:"Vilket år publicerade Einstein sin relativitetsteori?",o:["1900","1905","1910","1915"],a:1,d:2},
    {q:"Vad heter kvantfysikens osäkerhetsprincip?",o:["Einsteins princip","Heisenbergs osäkerhetsprincip","Bohrs komplementaritet","Plancks kvantum"],a:1,d:2},
    {q:"Hur lång tid tar det för ljuset att nå jorden från solen?",o:["Ca 4 minuter","Ca 8 minuter","Ca 16 minuter","Ca 30 minuter"],a:1,d:2},
    {q:"Vilket grundämne har atomnummer 79?",o:["Platina","Silver","Guld","Koppar"],a:2,d:2},
    {q:"Vad är fotosyntesens formel?",o:["6CO2+6H2O→C6H12O6+6O2","6O2+6H2O→C6H12O6+6CO2","CO2+H2O→CH2O+O2","6CO2+H2O→C6H12O6+O2"],a:0,d:2},
    {q:"Vilket år sände Voyager 1 iväg?",o:["1973","1975","1977","1979"],a:2,d:2},
    {q:"Vad heter processen då en stjärna exploderar?",o:["Nova","Supernova","Neutronkollaps","Gamma-ray burst"],a:1,d:2},
    {q:"Vilket grundämne är radioaktivt och används i kärnkraft?",o:["Radium","Thorium","Uran","Plutonium"],a:2,d:2},
    {q:"Hur djup är Marianergraven ungefär?",o:["7 km","9 km","11 km","13 km"],a:2,d:2},
    {q:"Vad heter teorin om universums uppkomst?",o:["Steady State","Big Crunch","Big Bang","Inflation"],a:2,d:2},
    {q:"Vad är ett svart hål?",o:["En kollapsad stjärna med oändlig gravitation","En tomrum i rymden","En mörklagd nebulosa","En kvasar"],a:0,d:3},
    {q:"Vilket år togs det första svarta hålets bild?",o:["2015","2017","2019","2021"],a:2,d:3},
    {q:"Vad heter Schrödingers tankeexperiment?",o:["Schrödingers paradox","Schrödingers katt","Schrödingers box","Kvantparadoxen"],a:1,d:3},
    {q:"Vilket grundämne har flest kända isotoper?",o:["Uran","Cesium","Xenon","Tellurium"],a:3,d:3},
    {q:"Vad är Plancks konstant ungefär?",o:["6.626×10⁻³⁴ J·s","9.109×10⁻³¹ kg","1.602×10⁻¹⁹ C","6.022×10²³ mol⁻¹"],a:0,d:3},
    {q:"Vilket år beräknade Newton gravitationslagen?",o:["1666-1687 (publicerad 1687)","1700","1750","1800"],a:0,d:3},
    {q:"Vad heter den svagaste av de fyra naturkrafterna?",o:["Stark kärnkraft","Svag kärnkraft","Elektromagnetism","Gravitation"],a:3,d:3},
    {q:"Vilket år fick Curie sitt andra Nobelpris?",o:["1903","1907","1911","1915"],a:2,d:3},
  ],

  // ════════════════════════════════════
  //  ÖVRIGT
  // ════════════════════════════════════

  "🌍 Geografi & Historia": [
    {q:"Vad är Frankrikes huvudstad?",o:["Lyon","Marseille","Paris","Bordeaux"],a:2,d:1},
    {q:"Vilket hav är störst?",o:["Atlantiska","Indiska","Arktiska","Stilla havet"],a:3,d:1},
    {q:"Vilket land är störst till ytan?",o:["USA","Kanada","Kina","Ryssland"],a:3,d:1},
    {q:"Vad är Australiens huvudstad?",o:["Sydney","Melbourne","Canberra","Brisbane"],a:2,d:1},
    {q:"Vilket år föll Berlinmuren?",o:["1987","1989","1991","1993"],a:1,d:1},
    {q:"Vilket land har flest invånare?",o:["Indien","Kina","USA","Indonesien"],a:0,d:1},
    {q:"Vad är Japans huvudstad?",o:["Osaka","Kyoto","Tokyo","Hiroshima"],a:2,d:1},
    {q:"Vilket år landade människan på månen?",o:["1967","1969","1971","1973"],a:1,d:1},
    {q:"Vilket land var tidigare känt som Persien?",o:["Irak","Iran","Turkiet","Syrien"],a:1,d:1},
    {q:"Vad är Kanadas huvudstad?",o:["Toronto","Montreal","Vancouver","Ottawa"],a:3,d:1},
    {q:"Vilket år började andra världskriget?",o:["1937","1939","1941","1943"],a:1,d:1},
    {q:"Vilket land har flest UNESCO-världsarv?",o:["Kina","Italien","Spanien","Frankrike"],a:1,d:1},
    {q:"Vilket år grundades FN?",o:["1943","1945","1947","1949"],a:1,d:2},
    {q:"Vilket land avskaffade apartheid 1994?",o:["Zimbabwe","Kenya","Sydafrika","Nigeria"],a:2,d:2},
    {q:"Vilket är världens längsta flod?",o:["Amazonas","Yangtze","Mississipi","Nilen"],a:3,d:2},
    {q:"Vilket år grundades EU i Maastricht?",o:["1989","1991","1993","1995"],a:2,d:2},
    {q:"Vilket land har flest officiella språk?",o:["Schweiz","Belgien","Sydafrika","Kanada"],a:2,d:2},
    {q:"Vilket år skedde Franska revolutionen?",o:["1776","1789","1799","1815"],a:1,d:2},
    {q:"Vilken stad var Osmanska rikets huvudstad?",o:["Ankara","Bagdad","Konstantinopel","Kairo"],a:2,d:2},
    {q:"Vilket år sprack Sovjet upp?",o:["1989","1991","1993","1995"],a:1,d:2},
    {q:"Hur många länder finns i Afrika?",o:["44","54","64","74"],a:1,d:2},
    {q:"Vilket år invigdes Eiffeltornet?",o:["1885","1887","1889","1891"],a:2,d:2},
    {q:"Vilket år grundades Romerska riket?",o:["753 f.Kr.","509 f.Kr.","264 f.Kr.","27 f.Kr."],a:0,d:3},
    {q:"Vilket land var kolonialmakt i Vietnam?",o:["England","Holland","Frankrike","Portugal"],a:2,d:3},
    {q:"Vilket år grundades NATO?",o:["1945","1947","1949","1951"],a:2,d:3},
    {q:"Vilket land var först med kvinnlig rösträtt?",o:["Sverige","USA","Nya Zeeland","Finland"],a:2,d:3},
    {q:"Vilket år fick Finland självständighet?",o:["1915","1917","1919","1921"],a:1,d:3},
    {q:"Vad heter den kinesiska muren officiellt?",o:["Kinas långa mur","Wan Li Chang Cheng","Den Förbjudna Muren","Kejsarens Barriär"],a:1,d:3},
    {q:"Vilket år slöts Wienkongressen?",o:["1810","1815","1820","1825"],a:1,d:3},
    {q:"Vilket år dog Napoleon Bonaparte?",o:["1815","1819","1821","1825"],a:2,d:3},
  ],

  "🍕 Mat & Dryck": [
    {q:"Vad är huvudingrediensen i guacamole?",o:["Tomat","Avokado","Lime","Koriander"],a:1,d:1},
    {q:"Vilket land kommer sushi ifrån?",o:["Kina","Korea","Japan","Thailand"],a:2,d:1},
    {q:"Vilket land kommer pizza ifrån?",o:["Frankrike","Spanien","Italien","Grekland"],a:2,d:1},
    {q:"Vad är en cappuccino?",o:["Bara mjölk","Espresso och ångad mjölk","Te och mjölk","Kaffe och grädde"],a:1,d:1},
    {q:"Vilket land kommer paella ifrån?",o:["Italien","Portugal","Frankrike","Spanien"],a:3,d:1},
    {q:"Vad kallas den japanska rätten med rå fisk?",o:["Sushi","Sashimi","Ramen","Udon"],a:1,d:1},
    {q:"Vilket land kommer wienerbrød ifrån?",o:["Österrike","Danmark","Sverige","Norge"],a:1,d:1},
    {q:"Vad är tacos traditionellt gjort av?",o:["Vete","Majs","Ris","Potatis"],a:1,d:1},
    {q:"Vilket land producerar mest olivolja?",o:["Italien","Spanien","Grekland","Turkiet"],a:1,d:1},
    {q:"Vad är hummus gjort av?",o:["Linser","Kikärtor","Bönor","Ärtor"],a:1,d:1},
    {q:"Vilket land kommer kimchi ifrån?",o:["Japan","Kina","Korea","Vietnam"],a:2,d:1},
    {q:"Vad är en croissant?",o:["En schweizisk bulle","En österrikisk/fransk bakelse","En dansk pastej","En belgisk kaka"],a:1,d:1},
    {q:"Vilket land producerar mest vin i världen?",o:["Frankrike","Spanien","Italien","USA"],a:2,d:2},
    {q:"Vad är Worcestershiresås gjord av?",o:["Tomat","Ansjovis","Pepparrot","Senap"],a:1,d:2},
    {q:"Vad heter den franska rätten med sniglar?",o:["Foie gras","Bouillabaisse","Escargot","Soufflé"],a:2,d:2},
    {q:"Vilket land kommer maten 'Pad Thai' ifrån?",o:["Vietnam","Kina","Thailand","Malaysia"],a:2,d:2},
    {q:"Vad är 'umami'?",o:["Sött","Surt","Salty","Den femte grundsmaken"],a:3,d:2},
    {q:"Vilket land kommer 'Pho' ifrån?",o:["Kina","Laos","Thailand","Vietnam"],a:3,d:2},
    {q:"Vad heter den spanska kallrätten gjord av tomater?",o:["Salmorejo","Gazpacho","Sofrito","Pisto"],a:1,d:2},
    {q:"Vilket land kommer curryn ursprungligen ifrån?",o:["Bangladesh","Pakistan","Sri Lanka","Indien"],a:3,d:2},
    {q:"Vad är 'miso' gjort av?",o:["Ris","Sojabönor","Sesamfrön","Tofu"],a:1,d:2},
    {q:"Vilket land är känt för 'Moules-frites'?",o:["Frankrike","Holland","Belgien","Luxemburg"],a:2,d:2},
    {q:"Vad är en Maillard-reaktion?",o:["En kemisk reaktion vid jäsning","En brunningsreaktion vid upphettning","En saltningsprocess","En konserveringsmetod"],a:1,d:3},
    {q:"Vilket land producerar Grand Cru-viner?",o:["Italien","Spanien","Frankrike","Portugal"],a:2,d:3},
    {q:"Vad heter den japanska metoden att skära fisk?",o:["Ikejime","Sashimi","Katsu","Mirin"],a:0,d:3},
    {q:"Vilket år grundades McDonald's?",o:["1940","1948","1955","1960"],a:0,d:3},
    {q:"Vad är 'koji' i japansk matlagning?",o:["En fisk","En svamp/mögel","En sås","En ris-typ"],a:1,d:3},
    {q:"Vilket land uppfann champagnen?",o:["Spanien","Italien","Frankrike","Belgien"],a:2,d:3},
    {q:"Vad heter den mexikanska rätten med agave?",o:["Mezcal","Pulque","Tequila","Alla tre är agavebaserade"],a:3,d:3},
    {q:"Vilket år grundades Michelin-guiden?",o:["1895","1900","1910","1920"],a:1,d:3},
  ],

  "🏙️ Umeå & Norrland": [
    {q:"Umeå är beläget vid vilken älv?",o:["Luleälven","Ångermanälven","Umeälven","Skellefte­älven"],a:2,d:1},
    {q:"Vilket år utsågs Umeå till Europas kulturhuvudstad?",o:["2010","2012","2014","2016"],a:2,d:1},
    {q:"Vilket universitet finns i Umeå?",o:["Luleå tekniska","Uppsala","Umeå universitet","Mittuniversitetet"],a:2,d:1},
    {q:"Vad kallas Umeå ibland på grund av sina björkar?",o:["Björkstaden","Trädstaden","Norrlandsstaden","Älvstaden"],a:0,d:1},
    {q:"I vilket landskap ligger Umeå?",o:["Ångermanland","Lappland","Västerbotten","Norrbotten"],a:2,d:1},
    {q:"Vad heter Umeås ishockeylag i SHL?",o:["Umeå HC","Björklöven","IF Björklöven","Umeå Cowboys"],a:1,d:1},
    {q:"Vilken E-väg går genom Umeå?",o:["E4","E6","E10","E12"],a:0,d:1},
    {q:"Vilket år grundades Umeå universitet?",o:["1945","1955","1963","1971"],a:2,d:1},
    {q:"Vad heter Umeås stora köpcenter?",o:["Mitt i City","Syd","A6","Utopia"],a:3,d:1},
    {q:"Vad heter Umeås konstmuseum?",o:["Bildmuseet","Umeå konstmuseum","Norrlandsmuseet","Västerbottensmuseet"],a:0,d:1},
    {q:"Hur många invånare har Umeå ungefär?",o:["60 000","80 000","130 000","200 000"],a:2,d:1},
    {q:"Vilket landskap ligger Skellefteå i?",o:["Västernorrland","Norrbotten","Västerbotten","Lappland"],a:2,d:1},
    {q:"Vilken kändis från Umeå är känd inom höjdhopp?",o:["Stefan Holm","Patrik Sjöberg","Kajsa Bergqvist","Carolina Klüft"],a:0,d:2},
    {q:"Vilket år fick Umeå stadsrättigheter?",o:["1588","1622","1640","1700"],a:1,d:2},
    {q:"Vad heter Umeås lokaltidning?",o:["Västerbottens-Kuriren","Norrländska Socialdemokraten","Umeå Tidning","Norran"],a:0,d:2},
    {q:"Vilket museum finns i Gammlia?",o:["Bildmuseet","Länsmuseet Västernorrland","Västerbottens museum","Tekniska museet"],a:2,d:2},
    {q:"Vilket år brann Umeå ned och byggdes upp?",o:["1798","1888","1902","1920"],a:1,d:2},
    {q:"Hur långt är det från Umeå till Stockholm med bil?",o:["Ca 400 km","Ca 600 km","Ca 700 km","Ca 900 km"],a:3,d:2},
    {q:"Vilket år invigdes Umeå Arena?",o:["2010","2012","2014","2016"],a:2,d:2},
    {q:"Vad heter Umeås fotbollslag i division 1?",o:["IFK Umeå","Umeå FC","IK Umeå","Umeå IK"],a:3,d:2},
    {q:"Vilket landskap gränsar Västerbotten mot väster?",o:["Lappland","Norrbotten","Ångermanland","Finland"],a:0,d:2},
    {q:"Vad heter Umeås turistattraktion vid älven?",o:["Gammlia friluftsmuseum","Umeå Havsbad","Norrlandsoperan","Bildmuseet"],a:0,d:2},
    {q:"Vilket år grundades Västerbottens museum?",o:["1886","1900","1921","1945"],a:0,d:3},
    {q:"Vad heter bron över Umeälven i centrala Umeå?",o:["Tegsbron","Storbron","Umeå bron","Gammliabron"],a:1,d:3},
    {q:"Vilket år öppnade Umeå flygplats?",o:["1935","1944","1952","1960"],a:1,d:3},
    {q:"Vilket år grundades Umeå IF (fotboll)?",o:["1917","1927","1937","1947"],a:0,d:3},
    {q:"Vad heter Umeås äldsta kyrka?",o:["Umeå landsförsamlings kyrka","Umeå stadsförsamlings kyrka","Gammlia kyrka","Mariebergskyrkan"],a:0,d:3},
    {q:"Vilket år grundades Umeå som stad?",o:["1588","1621","1650","1700"],a:1,d:3},
    {q:"Vad heter kullen i centrala Umeå?",o:["Röbäckskullen","Umedalen","Backenkullen","Tomtebo"],a:0,d:3},
    {q:"Vilket år startade Umeå Open (tennis)?",o:["1980","1985","1990","1995"],a:2,d:3},
  ],

  "🎭 Allmänkultur & Käpphäst": [
    {q:"Vem målade Mona Lisa?",o:["Michelangelo","Raphael","Leonardo da Vinci","Botticelli"],a:2,d:1},
    {q:"Vilket år publicerades första Harry Potter-boken?",o:["1995","1997","1999","2001"],a:1,d:1},
    {q:"Vem skrev Romeo och Julia?",o:["Charles Dickens","Jane Austen","William Shakespeare","Homer"],a:2,d:1},
    {q:"Vilket är det hårdaste naturliga materialet?",o:["Guld","Granit","Diamant","Järn"],a:2,d:1},
    {q:"Vad är ett palindrom?",o:["Ett ord som rhymar","Ett ord som stavas lika framifrån och bakifrån","Ett gammalt ord","Ett lånat ord"],a:1,d:1},
    {q:"Vilket år kom Nobelpriset för första gången?",o:["1895","1901","1905","1910"],a:1,d:1},
    {q:"Vem var den första att gå på månen?",o:["Buzz Aldrin","Neil Armstrong","Yuri Gagarin","John Glenn"],a:1,d:1},
    {q:"Vilket land uppfann champagnen?",o:["Spanien","Italien","Frankrike","Belgien"],a:2,d:1},
    {q:"Vem är känd för teorin om relativitet?",o:["Isaac Newton","Niels Bohr","Albert Einstein","Max Planck"],a:2,d:1},
    {q:"Vilket år antog Sverige decimal­systemet?",o:["1850","1855","1858","1865"],a:2,d:1},
    {q:"Vilket år grundades Nobel priset?",o:["1895","1901","1905","1910"],a:0,d:1},
    {q:"Vem skrev 'Hamlet'?",o:["Christopher Marlowe","Ben Jonson","William Shakespeare","John Webster"],a:2,d:1},
    {q:"Vilket år kom första utgåvan av Bibeln på svenska?",o:["1521","1526","1541","1560"],a:2,d:2},
    {q:"Vem skapade Sherlock Holmes?",o:["Agatha Christie","Arthur Conan Doyle","Edgar Allan Poe","Wilkie Collins"],a:1,d:2},
    {q:"Vilket år antog Sverige kvinnlig rösträtt?",o:["1915","1921","1927","1933"],a:1,d:2},
    {q:"Vem målade 'Skrik'?",o:["Vincent van Gogh","Paul Gauguin","Edvard Munch","Gustav Klimt"],a:2,d:2},
    {q:"Vilket år publicerades Orwells '1984'?",o:["1945","1948","1949","1952"],a:2,d:2},
    {q:"Vem skrev 'Röda rummet'?",o:["Selma Lagerlöf","Hjalmar Söderberg","August Strindberg","Lars Ahlin"],a:2,d:2},
    {q:"Vilket år fick Sverige sin grundlag?",o:["1809","1814","1820","1866"],a:0,d:2},
    {q:"Vem komponerade 'Peer Gynt'?",o:["Jean Sibelius","Edvard Grieg","Carl Nielsen","Hugo Alfvén"],a:1,d:2},
    {q:"Vilket år dog Astrid Lindgren?",o:["1998","2000","2002","2004"],a:2,d:2},
    {q:"Vem skapade 'Don Quijote'?",o:["Lope de Vega","Miguel de Cervantes","Francisco de Quevedo","Calderón de la Barca"],a:1,d:2},
    {q:"Vilket år kom Gutenbergs bibel?",o:["1440","1450","1455","1460"],a:2,d:3},
    {q:"Vem skapade begreppet 'absurdism'?",o:["Jean-Paul Sartre","Simone de Beauvoir","Albert Camus","Søren Kierkegaard"],a:2,d:3},
    {q:"Vilket år dog Selma Lagerlöf?",o:["1936","1940","1944","1948"],a:1,d:3},
    {q:"Vem komponerade 'Rite of Spring'?",o:["Debussy","Ravel","Stravinsky","Prokofiev"],a:2,d:3},
    {q:"Vilket år grundades Kungliga Operan i Stockholm?",o:["1773","1782","1792","1802"],a:0,d:3},
    {q:"Vem målade 'Nattvarden'?",o:["Raphael","Michelangelo","Leonardo da Vinci","Botticelli"],a:2,d:3},
    {q:"Vilket år avled Ingmar Bergman?",o:["2003","2005","2007","2009"],a:2,d:3},
    {q:"Vem skrev 'Kejsaren av Portugallien'?",o:["Hjalmar Söderberg","August Strindberg","Selma Lagerlöf","Verner von Heidenstam"],a:2,d:3},
  ],

  "🌈 Blandat / Mix": [
    {q:"Vad är världens längsta flod?",o:["Amazonas","Yangtze","Mississipi","Nilen"],a:3,d:1},
    {q:"Vilket land kommer pizza ifrån?",o:["Frankrike","Spanien","Italien","Grekland"],a:2,d:1},
    {q:"Vem målade Mona Lisa?",o:["Michelangelo","Raphael","Leonardo da Vinci","Botticelli"],a:2,d:1},
    {q:"Vilket är det hårdaste naturliga materialet?",o:["Guld","Granit","Diamant","Järn"],a:2,d:1},
    {q:"Vilket år föll Berlinmuren?",o:["1987","1989","1991","1993"],a:1,d:1},
    {q:"Vem sjunger 'Rolling in the Deep'?",o:["Amy Winehouse","Adele","Duffy","Paloma Faith"],a:1,d:1},
    {q:"Vem spelar Iron Man i MCU?",o:["Chris Evans","Robert Downey Jr.","Chris Hemsworth","Mark Ruffalo"],a:1,d:1},
    {q:"Vilket land vann fotbolls-VM 2022?",o:["Brasilien","Frankrike","Argentina","Portugal"],a:2,d:1},
    {q:"Vilket år landade människan på månen?",o:["1967","1969","1971","1973"],a:1,d:1},
    {q:"Vad är DNA?",o:["Proteinkomplex","Ribosomalt RNA","Deoxiribonukleinsyra","Adenosintrifosfat"],a:2,d:1},
    {q:"Vilket spel är känt för 'Creeper'?",o:["Roblox","Fortnite","Minecraft","Terraria"],a:2,d:1},
    {q:"Vilket land kommer ABBA ifrån?",o:["Norge","Danmark","Sverige","Finland"],a:2,d:1},
    {q:"Vilket år grundades Google?",o:["1996","1998","2000","2002"],a:1,d:2},
    {q:"Vem regisserade Inception?",o:["Ridley Scott","Christopher Nolan","David Fincher","Darren Aronofsky"],a:1,d:2},
    {q:"Vilket år kom Breaking Bad?",o:["2006","2008","2010","2012"],a:1,d:2},
    {q:"Vilket land har flest invånare?",o:["Indien","Kina","USA","Indonesien"],a:0,d:2},
    {q:"Vem vann Formel 1-VM 2021?",o:["Lewis Hamilton","Max Verstappen","Valtteri Bottas","Sebastian Vettel"],a:1,d:2},
    {q:"Vilket år publicerades första Harry Potter-boken?",o:["1995","1997","1999","2001"],a:1,d:2},
    {q:"Vilket grundämne har kemisk symbol 'Au'?",o:["Silver","Aluminium","Guld","Koppar"],a:2,d:2},
    {q:"Vem producerade Michael Jacksons 'Thriller'?",o:["Berry Gordy","Quincy Jones","Teddy Riley","Babyface"],a:1,d:2},
    {q:"Vilket år kom Pixars 'Up'?",o:["2007","2009","2011","2013"],a:1,d:2},
    {q:"Vilket land har vunnit flest OS-guld totalt?",o:["Ryssland","Kina","USA","Tyskland"],a:2,d:2},
    {q:"Vem uppfann World Wide Web?",o:["Bill Gates","Steve Jobs","Tim Berners-Lee","Vint Cerf"],a:2,d:3},
    {q:"Vilket år kom Citizen Kane?",o:["1938","1941","1944","1947"],a:1,d:3},
    {q:"Vad heter kvantfysikens osäkerhetsprincip?",o:["Einsteins princip","Heisenbergs osäkerhetsprincip","Bohrs princip","Plancks kvantum"],a:1,d:3},
    {q:"Vilket år avskaffades apartheid?",o:["1988","1990","1992","1994"],a:3,d:3},
    {q:"Vad heter Schrödingers tankeexperiment?",o:["Schrödingers paradox","Schrödingers katt","Schrödingers box","Kvantparadoxen"],a:1,d:3},
    {q:"Vilket år grundades Antropic?",o:["2019","2021","2022","2023"],a:1,d:3},
    {q:"Vem skapade begreppet 'absurdism'?",o:["Jean-Paul Sartre","Simone de Beauvoir","Albert Camus","Søren Kierkegaard"],a:2,d:3},
    {q:"Vilket år kom Frank Oceans 'Blonde'?",o:["2014","2016","2018","2020"],a:1,d:3},
  ],
};

// Hjälpfunktion – hämta slumpmässiga frågor
function getQuestions(category, difficulty, count) {
  const allCats = category === 'mix' ? Object.keys(QUESTION_DB) : [category];
  let pool = [];
  allCats.forEach(cat => {
    const qs = QUESTION_DB[cat] || [];
    pool = pool.concat(qs.filter(q => q.d <= difficulty));
  });
  if (pool.length === 0) return [];
  // Crypto-quality shuffle
  const arr = pool.slice();
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor((crypto.getRandomValues(new Uint32Array(1))[0] / 0xFFFFFFFF) * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr.slice(0, count).map(q => ({
    question: q.q,
    options: q.o,
    correct: q.a,
    category: allCats.length > 1 ? '🌈 Mix' : category
  }));
}
