// questions11.js – 500+ fler frågor, alla kategorier, genomtänkta svårigheter
const QUESTION_DB11 = {

"🎵 80-tals musik": [
  // Lätt – välkända hits alla känner
  {q:"Vem sjunger 'Thriller'?",o:["Prince","Michael Jackson","David Bowie","Stevie Wonder"],a:1,d:1},
  {q:"Vilket band sjöng 'Don't Stop Believin''?",o:["Bon Jovi","Journey","Foreigner","REO Speedwagon"],a:1,d:1},
  {q:"Vem sjunger 'Fast Car' (1988)?",o:["Tracy Chapman","Joni Mitchell","Carole King","Bonnie Raitt"],a:0,d:1},
  {q:"Vilket band sjöng 'Livin' on a Prayer'?",o:["Aerosmith","Bon Jovi","Journey","Def Leppard"],a:1,d:1},
  {q:"Vem sjunger 'What's Love Got to Do with It'?",o:["Aretha Franklin","Diana Ross","Tina Turner","Donna Summer"],a:2,d:1},
  {q:"Vilket band sjöng 'Eye of the Tiger'?",o:["Foreigner","Night Ranger","Survivor","Asia"],a:2,d:1},
  // Medel
  {q:"Vilket år kom a-has debut 'Hunting High and Low'?",o:["1983","1985","1987","1989"],a:1,d:2},
  {q:"Vilket band sjöng 'The Power of Love' (1984 Jennifer Rush)?",o:["Air Supply","Jennifer Rush","Celine Dion","Laura Branigan"],a:1,d:2},
  {q:"Vilket år kom Princes album 'Purple Rain'?",o:["1982","1984","1986","1988"],a:1,d:2},
  {q:"Vilket band sjöng 'Relax' (Frankie Goes to Hollywood)?",o:["Pet Shop Boys","Erasure","Frankie Goes to Hollywood","Culture Club"],a:2,d:2},
  {q:"Vem sjunger 'Smalltown Boy'?",o:["Pet Shop Boys","Erasure","Bronski Beat","The Communards"],a:2,d:2},
  {q:"Vilket band sjöng 'Obsession' (1985)?",o:["Animotion","Berlin","Book of Love","When in Rome"],a:0,d:2},
  {q:"Vem sjunger 'I'm Still Standing'?",o:["Rod Stewart","David Bowie","Elton John","Billy Joel"],a:2,d:2},
  {q:"Vilket band sjöng 'White Wedding'?",o:["Siouxsie","Bauhaus","Billy Idol","The Cure"],a:2,d:2},
  {q:"Vilket år kom Michael Jacksons 'Off the Wall'?",o:["1977","1979","1981","1983"],a:1,d:2},
  // Svårt – riktiga musfällor
  {q:"Vem producerade Madonnas debut-singel 'Everybody'?",o:["Mark Kamins","Reggie Lucas","Jellybean Benitez","Steve Bray"],a:0,d:3},
  {q:"Vilket år kom Joy Divisions enda studioplatta 'Closer'?",o:["1978","1980","1982","1984"],a:1,d:3},
  {q:"Vad heter Depeche Modes originaltrummis?",o:["Andy Fletcher","Martin Gore","Vince Clarke","Dave Gahan"],a:2,d:3},
  {q:"Vilket skivbolag gav ut New Orders 'Blue Monday'?",o:["Factory Records","Rough Trade","4AD","Mute"],a:0,d:3},
  {q:"Vilket år kom Talking Heads 'Remain in Light'?",o:["1978","1980","1982","1984"],a:1,d:3},
],

"🎶 90-tals musik": [
  {q:"Vilket band sjöng 'Zombie' (The Cranberries)?",o:["Sinead O'Connor","The Cranberries","Enya","The Corrs"],a:1,d:1},
  {q:"Vem sjunger 'Baby Got Back'?",o:["MC Hammer","Vanilla Ice","Sir Mix-a-Lot","Coolio"],a:2,d:1},
  {q:"Vilket band sjöng 'Iris' (Goo Goo Dolls)?",o:["Goo Goo Dolls","Matchbox Twenty","Third Eye Blind","Counting Crows"],a:0,d:1},
  {q:"Vem sjunger 'Waterfalls'?",o:["Destiny's Child","En Vogue","TLC","Brandy"],a:2,d:1},
  {q:"Vilket band sjöng 'Wonderwall'?",o:["Blur","Pulp","Oasis","Suede"],a:2,d:1},
  {q:"Vem sjunger 'I Will Always Love You' (filmversionen)?",o:["Dolly Parton","Celine Dion","Whitney Houston","Mariah Carey"],a:2,d:1},
  {q:"Vilket band sjöng 'Semi-Charmed Life'?",o:["Matchbox Twenty","Third Eye Blind","Counting Crows","Spin Doctors"],a:1,d:2},
  {q:"Vilket år kom Oasis 'Definitely Maybe'?",o:["1992","1994","1996","1998"],a:1,d:2},
  {q:"Vilket band sjöng 'Common People' (Pulp)?",o:["Blur","Pulp","Oasis","Elastica"],a:1,d:2},
  {q:"Vem sjunger 'Stay (I Missed You)' (Lisa Loeb)?",o:["Lisa Loeb","Juliana Hatfield","Liz Phair","Belly"],a:0,d:2},
  {q:"Vilket år kom Nirvanas MTV Unplugged?",o:["1993","1994","1995","1996"],a:1,d:2},
  {q:"Vilket band sjöng 'Connection' (Elastica)?",o:["Garbage","PJ Harvey","Elastica","Echobelly"],a:2,d:2},
  {q:"Vem sjunger 'Doo Wop (That Thing)' (Lauryn Hill)?",o:["Missy Elliott","Lauryn Hill","Erykah Badu","Lil Kim"],a:1,d:2},
  {q:"Vilket band sjöng 'Mr Jones' (Counting Crows)?",o:["Gin Blossoms","Counting Crows","Blues Traveler","Toad the Wet Sprocket"],a:1,d:2},
  {q:"Vilket år kom Beck's 'Odelay'?",o:["1994","1996","1998","2000"],a:1,d:3},
  {q:"Vilket år kom Björks 'Homogenic'?",o:["1995","1997","1999","2001"],a:1,d:3},
  {q:"Vilket band sjöng 'Pepper' (Butthole Surfers)?",o:["Butthole Surfers","Ween","They Might Be Giants","Primus"],a:0,d:3},
  {q:"Vilket år kom Massive Attack 'Blue Lines'?",o:["1989","1991","1993","1995"],a:1,d:3},
  {q:"Vilket år kom Portishead 'Dummy'?",o:["1992","1994","1996","1998"],a:1,d:3},
  {q:"Vem producerade Alanis Morissettes 'Jagged Little Pill'?",o:["Rick Rubin","Glen Ballard","Butch Vig","Don Was"],a:1,d:3},
],

"🎤 Ny musik (2010-idag)": [
  {q:"Vem sjunger 'Shake It Off'?",o:["Katy Perry","Ariana Grande","Taylor Swift","Selena Gomez"],a:2,d:1},
  {q:"Vem sjunger 'Royals' (Lorde)?",o:["Lorde","Lana Del Rey","Halsey","Billie Eilish"],a:0,d:1},
  {q:"Vem sjunger 'Old Town Road'?",o:["Cardi B","Lil Nas X","Travis Scott","Post Malone"],a:1,d:1},
  {q:"Vem sjunger 'Blinding Lights'?",o:["Drake","The Weeknd","Post Malone","Travis Scott"],a:1,d:1},
  {q:"Vem sjunger 'Bad Guy' (Billie Eilish)?",o:["Ariana Grande","Billie Eilish","Dua Lipa","Olivia Rodrigo"],a:1,d:1},
  {q:"Vem sjunger 'Stay With Me' (Sam Smith)?",o:["Ed Sheeran","Sam Smith","James Arthur","Olly Murs"],a:1,d:1},
  {q:"Vem sjunger 'Sunflower' (Post Malone)?",o:["Post Malone och Swae Lee","Drake och Future","The Weeknd","Travis Scott"],a:0,d:1},
  {q:"Vem sjunger 'Anti-Hero' (Taylor Swift)?",o:["Billie Eilish","Olivia Rodrigo","Taylor Swift","Sabrina Carpenter"],a:2,d:1},
  {q:"Vilket år kom Olivia Rodrigos 'SOUR'?",o:["2019","2020","2021","2022"],a:2,d:2},
  {q:"Vilket år kom Dua Lipas 'Future Nostalgia'?",o:["2018","2020","2022","2024"],a:1,d:2},
  {q:"Vem sjunger 'Espresso' (2024)?",o:["Dua Lipa","Sabrina Carpenter","Olivia Rodrigo","Ariana Grande"],a:1,d:2},
  {q:"Vilket år kom Weeknds 'Beauty Behind the Madness'?",o:["2013","2015","2017","2019"],a:1,d:2},
  {q:"Vem sjunger 'Humble' (Kendrick Lamar)?",o:["Drake","J. Cole","Kendrick Lamar","Travis Scott"],a:2,d:2},
  {q:"Vilket år kom Taylor Swifts 'Folklore'?",o:["2018","2019","2020","2021"],a:2,d:2},
  {q:"Vem sjunger 'Good Days' (SZA)?",o:["H.E.R.","SZA","Summer Walker","Jhene Aiko"],a:1,d:2},
  {q:"Vilket år kom Kendrick Lamars 'To Pimp a Butterfly'?",o:["2013","2015","2017","2019"],a:1,d:3},
  {q:"Vilket år kom Frank Oceans 'Blonde'?",o:["2014","2016","2018","2020"],a:1,d:3},
  {q:"Vilket år kom Tyler the Creators 'IGOR'?",o:["2017","2019","2021","2023"],a:1,d:3},
  {q:"Vem producerade Dua Lipas 'Future Nostalgia'?",o:["Max Martin","Stuart Price","Ian Kirkpatrick","Jeff Bhasker"],a:1,d:3},
  {q:"Vilket år kom Kacey Musgraves 'Golden Hour'?",o:["2016","2018","2020","2022"],a:1,d:3},
],

"🎵 Popmusik (allmänt)": [
  {q:"Vem sjunger 'Crazy in Love' (Beyoncé)?",o:["Rihanna","Beyoncé","Alicia Keys","Mary J Blige"],a:1,d:1},
  {q:"Vem sjunger 'Beautiful' (2002 Christina Aguilera)?",o:["Alicia Keys","Nelly Furtado","Christina Aguilera","Beyoncé"],a:2,d:1},
  {q:"Vilket band sjöng 'Milkshake' (Kelis)?",o:["Kelis","Missy Elliott","M.I.A.","Lil Kim"],a:0,d:1},
  {q:"Vem sjunger 'Hero' (Mariah Carey)?",o:["Whitney Houston","Mariah Carey","Celine Dion","Beyoncé"],a:1,d:1},
  {q:"Vem sjunger 'Irreplaceable' (Beyoncé)?",o:["Rihanna","Alicia Keys","Beyoncé","Mary J Blige"],a:2,d:1},
  {q:"Vilket år kom Mariah Careys 'All I Want for Christmas'?",o:["1990","1992","1994","1996"],a:1,d:1},
  {q:"Vem sjunger 'Gold Digger' (Kanye West)?",o:["Jay-Z","Kanye West","Ludacris","T.I."],a:1,d:2},
  {q:"Vilket år kom Destiny's Child 'Survivor'?",o:["1999","2001","2003","2005"],a:1,d:2},
  {q:"Vilket år kom Usher 'Confessions'?",o:["2002","2004","2006","2008"],a:1,d:2},
  {q:"Vem sjunger 'Genie in a Bottle' (Christina Aguilera)?",o:["Britney Spears","Christina Aguilera","Jessica Simpson","Mandy Moore"],a:1,d:2},
  {q:"Vilket år kom Amy Winehouse 'Back to Black'?",o:["2004","2006","2008","2010"],a:1,d:2},
  {q:"Vem sjunger 'Crazy' (Gnarls Barkley)?",o:["Cee Lo Green","Bruno Mars","John Legend","Common"],a:0,d:2},
  {q:"Vilket år debuterade One Direction?",o:["2008","2009","2010","2011"],a:2,d:2},
  {q:"Vilket år kom Rihannas 'Good Girl Gone Bad'?",o:["2005","2007","2009","2011"],a:1,d:2},
  {q:"Vilket år kom P!nks 'Missundaztood'?",o:["1999","2001","2003","2005"],a:1,d:2},
  {q:"Vem sjunger 'My Immortal' (Evanescence)?",o:["Paramore","Evanescence","Flyleaf","Within Temptation"],a:1,d:3},
  {q:"Vilket år kom Nelly Furtados 'Loose'?",o:["2004","2006","2008","2010"],a:1,d:3},
  {q:"Vem sjunger 'Rehab' (Amy Winehouse)?",o:["Amy Winehouse","Duffy","Adele","Paloma Faith"],a:0,d:3},
  {q:"Vilket skivbolag är Taylor Swift på nu?",o:["Big Machine","Republic Records","Columbia","Universal"],a:1,d:3},
  {q:"Vilket år kom Adeles '30'?",o:["2019","2020","2021","2022"],a:2,d:3},
],

"🎸 Rock & Metal": [
  {q:"Vilket band sjöng 'Stairway to Heaven'?",o:["Deep Purple","Black Sabbath","Led Zeppelin","Uriah Heep"],a:2,d:1},
  {q:"Vem sjunger 'Born to Run' (Bruce Springsteen)?",o:["Tom Petty","Bruce Springsteen","John Mellencamp","Bob Seger"],a:1,d:1},
  {q:"Vilket band sjöng 'Sultans of Swing'?",o:["The Police","Dire Straits","U2","Fleetwood Mac"],a:1,d:1},
  {q:"Vem sjunger 'Piece of My Heart'?",o:["Tina Turner","Janis Joplin","Grace Slick","Aretha Franklin"],a:1,d:1},
  {q:"Vilket band sjöng 'Fortunate Son' (CCR)?",o:["Creedence Clearwater Revival","The Eagles","Lynyrd Skynyrd","ZZ Top"],a:0,d:1},
  {q:"Vilket band sjöng 'More Than a Feeling' (Boston)?",o:["Journey","Foreigner","Boston","REO Speedwagon"],a:2,d:1},
  {q:"Vem sjunger 'Free Bird' (Lynyrd Skynyrd)?",o:["The Allman Brothers","Lynyrd Skynyrd","ZZ Top","38 Special"],a:1,d:1},
  {q:"Vilket band sjöng 'Dream On' (Aerosmith)?",o:["Bon Jovi","Aerosmith","Kiss","Twisted Sister"],a:1,d:1},
  {q:"Vem sjunger 'Barracuda' (Heart)?",o:["Joan Jett","Pat Benatar","Heart","Stevie Nicks"],a:2,d:1},
  {q:"Vilket band sjöng 'Killing in the Name' (RATM)?",o:["Rage Against the Machine","Soundgarden","Tool","System of a Down"],a:0,d:1},
  {q:"Vilket band sjöng 'Do I Wanna Know' (Arctic Monkeys)?",o:["The Black Keys","Arctic Monkeys","The Strokes","Interpol"],a:1,d:2},
  {q:"Vilket band sjöng 'Comfortably Numb' (Pink Floyd)?",o:["Led Zeppelin","Deep Purple","Pink Floyd","Genesis"],a:2,d:2},
  {q:"Vilket år kom The Clash 'London Calling'?",o:["1977","1979","1981","1983"],a:1,d:2},
  {q:"Vilket band sjöng 'Schism' (Tool)?",o:["Rage Against the Machine","Tool","System of a Down","Mastodon"],a:1,d:2},
  {q:"Vilket år kom Queens of the Stone Age 'Songs for the Deaf'?",o:["2000","2002","2004","2006"],a:1,d:2},
  {q:"Vilket år kom Radioheads 'In Rainbows'?",o:["2005","2007","2009","2011"],a:1,d:2},
  {q:"Vilket band sjöng 'A Design for Life' (Manic Street Preachers)?",o:["Oasis","Manic Street Preachers","Blur","Suede"],a:1,d:3},
  {q:"Vilket år kom My Bloody Valentines 'Loveless'?",o:["1989","1991","1993","1995"],a:1,d:3},
  {q:"Vilket år kom Pixies 'Doolittle'?",o:["1987","1989","1991","1993"],a:1,d:3},
  {q:"Vem spelar trummor i Led Zeppelin?",o:["Keith Moon","Ginger Baker","John Bonham","Ian Paice"],a:2,d:3},
],

"🔥 Heavy Metal": [
  {q:"Vilket band sjöng 'Run to the Hills' (Iron Maiden)?",o:["Judas Priest","Saxon","Iron Maiden","Motörhead"],a:2,d:1},
  {q:"Vilket band sjöng 'One' (1988 Metallica)?",o:["Slayer","Metallica","Megadeth","Anthrax"],a:1,d:1},
  {q:"Vilket band sjöng 'Painkiller' (Judas Priest)?",o:["Iron Maiden","Saxon","Judas Priest","Motörhead"],a:2,d:1},
  {q:"Vilket band sjöng 'Crazy Train' (Ozzy Osbourne)?",o:["Black Sabbath","Ozzy Osbourne","Dio","Rainbow"],a:1,d:1},
  {q:"Vilket band sjöng 'Seek and Destroy' (Metallica)?",o:["Slayer","Metallica","Megadeth","Anthrax"],a:1,d:1},
  {q:"Vilket band sjöng 'The Beautiful People' (Marilyn Manson)?",o:["Nine Inch Nails","Marilyn Manson","Rob Zombie","White Zombie"],a:1,d:1},
  {q:"Vilket band sjöng 'Fuel' (Metallica)?",o:["Slayer","Metallica","Megadeth","Anthrax"],a:1,d:1},
  {q:"Vilket band sjöng 'Roots Bloody Roots' (Sepultura)?",o:["Slayer","Pantera","Sepultura","Machine Head"],a:2,d:1},
  {q:"Vilket band sjöng 'Cowboys from Hell' (Pantera)?",o:["Slayer","Pantera","Sepultura","Machine Head"],a:1,d:1},
  {q:"Vilket band sjöng 'Laid to Rest' (Lamb of God)?",o:["Slipknot","Trivium","Lamb of God","Machine Head"],a:2,d:2},
  {q:"Vilket år kom Pantera 'Vulgar Display of Power'?",o:["1990","1992","1994","1996"],a:1,d:2},
  {q:"Vilket band sjöng 'Before I Forget' (Slipknot)?",o:["Korn","Slipknot","Disturbed","Drowning Pool"],a:1,d:2},
  {q:"Vilket band sjöng 'Holy Wars' (Megadeth)?",o:["Slayer","Megadeth","Metallica","Anthrax"],a:1,d:2},
  {q:"Vilket band sjöng 'The Pot' (Tool)?",o:["Rage Against the Machine","Tool","System of a Down","Mastodon"],a:1,d:2},
  {q:"Vilket band sjöng 'Walk' (Pantera)?",o:["Metallica","Megadeth","Pantera","Sepultura"],a:2,d:2},
  {q:"Vilket år kom Gojira 'From Mars to Sirius'?",o:["2003","2005","2007","2009"],a:1,d:3},
  {q:"Vilket år kom Opeth 'Blackwater Park'?",o:["1999","2001","2003","2005"],a:1,d:3},
  {q:"Vilket år kom Neurosis 'A Sun That Never Sets'?",o:["1999","2001","2003","2005"],a:1,d:3},
  {q:"Vem är sångare i Mastodon?",o:["Troy Sanders och Brann Dailor","Randy Blythe","Phil Labonte","Claudio Sanchez"],a:0,d:3},
  {q:"Vilket år kom Tool 'Aenima'?",o:["1994","1996","1998","2000"],a:1,d:3},
],

"🇸🇪 Svensk musik": [
  {q:"Vem sjunger 'Dancing on My Own' (Robyn)?",o:["Zara Larsson","Robyn","Tove Lo","MØ"],a:1,d:1},
  {q:"Vad heter Aviciis mest kända låt?",o:["Fade into Darkness","Levels","Wake Me Up","Hey Brother"],a:1,d:1},
  {q:"Vilket band sjöng 'Erase Rewind' (The Cardigans)?",o:["Roxette","Robyn","The Cardigans","Ace of Base"],a:2,d:1},
  {q:"Vem sjunger 'Euphoria' (Eurovision 2012)?",o:["Carola","Charlotte Perrelli","Loreen","Petra Mede"],a:2,d:1},
  {q:"Vilket band sjöng 'Hate to Say I Told You So' (The Hives)?",o:["The Hellacopters","The Hives","Refused","Soundtrack of Our Lives"],a:1,d:1},
  {q:"Vem sjunger 'Karolina' (Håkan Hellström)?",o:["Håkan Hellström","Lars Winnerbäck","Bob Hund","Ulf Lundell"],a:0,d:1},
  {q:"Vem sjunger 'Habits Stay High' (Tove Lo)?",o:["Zara Larsson","Robyn","Tove Lo","MØ"],a:2,d:1},
  {q:"Vilket band sjöng 'Sommartider' (Gyllene Tider)?",o:["Gyllene Tider","Roxette","Per Gessle solo","Bob Hund"],a:0,d:1},
  {q:"Vilket år kom The Hives 'Veni Vidi Vicious'?",o:["1998","2000","2002","2004"],a:1,d:2},
  {q:"Vilket år kom Robyn 'Body Talk'?",o:["2008","2010","2012","2014"],a:1,d:2},
  {q:"Vilket år bildades Refused?",o:["1989","1991","1993","1995"],a:1,d:2},
  {q:"Vem sjunger 'I Follow Rivers' (Lykke Li)?",o:["Lykke Li","Robyn","Fever Ray","Little Dragon"],a:0,d:2},
  {q:"Vilket år kom Aviciis 'True'?",o:["2011","2013","2015","2017"],a:1,d:2},
  {q:"Vilket år vann Loreen Eurovision andra gången?",o:["2021","2022","2023","2024"],a:2,d:2},
  {q:"Vem sjunger 'Torsdag' (Lars Winnerbäck)?",o:["Lars Winnerbäck","Håkan Hellström","Bob Hund","Ulf Lundell"],a:0,d:2},
  {q:"Vilket år kom The Knifes 'Silent Shout'?",o:["2004","2006","2008","2010"],a:1,d:3},
  {q:"Vad heter Tove Los riktiga namn?",o:["Tova Magnusson-Forssa","Tova Nilsson","Tova Lindqvist","Tova Andersson"],a:0,d:3},
  {q:"Vilket år kom Kents sista album?",o:["2014","2016","2018","2020"],a:1,d:3},
  {q:"Vilket år kom Refused 'The Shape of Punk to Come'?",o:["1996","1998","2000","2002"],a:1,d:3},
  {q:"Vem var sångare i Imperiet (Joakim Thåström)?",o:["Håkan Hellström","Joakim Thåström","Thomas Eriksson","Ulf Lundell"],a:1,d:3},
],

"🎬 Movie Quiz": [
  {q:"Vem spelar Iron Man i MCU?",o:["Chris Evans","Robert Downey Jr.","Chris Hemsworth","Mark Ruffalo"],a:1,d:1},
  {q:"Vilket år kom Titanic?",o:["1995","1996","1997","1998"],a:2,d:1},
  {q:"Vem spelar Jack i Titanic?",o:["Brad Pitt","Johnny Depp","Leonardo DiCaprio","Matt Damon"],a:2,d:1},
  {q:"Vem spelar Neo i Matrix?",o:["Brad Pitt","Keanu Reeves","Tom Cruise","Will Smith"],a:1,d:1},
  {q:"Vilket år kom The Dark Knight?",o:["2006","2008","2010","2012"],a:1,d:1},
  {q:"Vem regisserade Goodfellas?",o:["Francis Ford Coppola","Brian De Palma","Martin Scorsese","Quentin Tarantino"],a:2,d:1},
  {q:"Vilket år kom Joker 2019?",o:["2017","2019","2021","2023"],a:1,d:1},
  {q:"Vem spelar Joker i Joker 2019?",o:["Heath Ledger","Jared Leto","Joaquin Phoenix","Jack Nicholson"],a:2,d:1},
  {q:"Vem spelar i Barbie 2023?",o:["Margot Robbie","Scarlett Johansson","Emma Stone","Jennifer Lawrence"],a:0,d:1},
  {q:"Vilket år kom Nolans Oppenheimer?",o:["2021","2022","2023","2024"],a:2,d:1},
  {q:"Vem regisserade Fight Club?",o:["Quentin Tarantino","David Fincher","Christopher Nolan","Darren Aronofsky"],a:1,d:2},
  {q:"Vilket år kom The Social Network?",o:["2008","2010","2012","2014"],a:1,d:2},
  {q:"Vem regisserade Arrival 2016?",o:["Christopher Nolan","Denis Villeneuve","Ridley Scott","David Fincher"],a:1,d:2},
  {q:"Vem spelar i Dune 2021 huvudroll?",o:["Tom Holland","Timothée Chalamet","Ansel Elgort","Lucas Hedges"],a:1,d:2},
  {q:"Vilket år kom Everything Everywhere All at Once?",o:["2020","2022","2023","2024"],a:1,d:2},
  {q:"Vilket år kom Scorseses The Departed?",o:["2004","2006","2008","2010"],a:1,d:2},
  {q:"Vem regisserade Once Upon a Time in Hollywood?",o:["Martin Scorsese","Quentin Tarantino","Paul Thomas Anderson","Wes Anderson"],a:1,d:2},
  {q:"Vilket år kom Paul Thomas Andersons There Will Be Blood?",o:["2005","2007","2009","2011"],a:1,d:3},
  {q:"Vem spelade Travis Bickle i Taxi Driver?",o:["Al Pacino","Jack Nicholson","Robert De Niro","Dustin Hoffman"],a:2,d:3},
  {q:"Vilket år kom Kubricks Barry Lyndon?",o:["1973","1975","1977","1979"],a:1,d:3},
],

"📺 TV-serier": [
  {q:"Vem spelar Tommy Shelby i Peaky Blinders?",o:["Tom Hardy","Cillian Murphy","Idris Elba","James McAvoy"],a:1,d:1},
  {q:"Vilket år kom Squid Game?",o:["2019","2021","2022","2023"],a:1,d:1},
  {q:"Vilket land producerade Squid Game?",o:["Japan","Kina","Sydkorea","Thailand"],a:2,d:1},
  {q:"Vem spelar i Euphoria huvudroll?",o:["Billie Eilish","Zendaya","Olivia Rodrigo","Ariana Grande"],a:1,d:1},
  {q:"Vilket år kom The Last of Us HBO?",o:["2021","2023","2024","2025"],a:1,d:1},
  {q:"Vem spelar Logan Roy i Succession?",o:["Brian Cox","Jeff Bridges","Anthony Hopkins","Gary Oldman"],a:0,d:1},
  {q:"Vem spelar Walter White i Breaking Bad?",o:["Bryan Cranston","Aaron Paul","Bob Odenkirk","Dean Norris"],a:0,d:1},
  {q:"Vilket år kom Game of Thrones?",o:["2009","2011","2013","2015"],a:1,d:1},
  {q:"Vilket år kom Stranger Things?",o:["2014","2016","2018","2020"],a:1,d:1},
  {q:"Vilket år kom Succession?",o:["2016","2018","2020","2022"],a:1,d:2},
  {q:"Vilket år kom Better Call Saul?",o:["2013","2015","2017","2019"],a:1,d:2},
  {q:"Vilket år kom Twin Peaks?",o:["1988","1990","1992","1994"],a:1,d:2},
  {q:"Vem skapade Twin Peaks?",o:["Steven Spielberg","David Lynch och Mark Frost","Ridley Scott","Jim Jarmusch"],a:1,d:2},
  {q:"Vilket år kom Dark tysk Netflix-serie?",o:["2015","2017","2019","2021"],a:1,d:2},
  {q:"Vem spelar Kendall Roy i Succession?",o:["Matthew Macfadyen","Jeremy Strong","Kieran Culkin","Nicholas Braun"],a:1,d:2},
  {q:"Vilket år kom Mad Men?",o:["2005","2007","2009","2011"],a:1,d:2},
  {q:"Vem skapade Breaking Bad?",o:["David Chase","David Simon","Vince Gilligan","Matthew Weiner"],a:2,d:3},
  {q:"Vem skapade The Wire?",o:["David Chase","David Simon","Vince Gilligan","Ed Burns"],a:1,d:3},
  {q:"Vem skapade The Sopranos?",o:["David Chase","David Simon","Vince Gilligan","Matthew Weiner"],a:0,d:3},
  {q:"Vilket år kom Treme HBO?",o:["2008","2010","2012","2014"],a:1,d:3},
],

"⚽ Fotboll": [
  {q:"Vilket land vann fotbolls-VM 2022?",o:["Brasilien","Frankrike","Argentina","Portugal"],a:2,d:1},
  {q:"Vilket lag spelar hemma på Camp Nou?",o:["Real Madrid","Atletico Madrid","FC Barcelona","Valencia"],a:2,d:1},
  {q:"Vem vann Ballon d'Or flest gånger totalt?",o:["Cristiano Ronaldo","Lionel Messi","Ronaldinho","Zidane"],a:1,d:1},
  {q:"Vilket lag spelar hemma på Old Trafford?",o:["Arsenal","Liverpool","Manchester United","Chelsea"],a:2,d:1},
  {q:"Vilket lag spelar hemma på Anfield?",o:["Arsenal","Everton","Liverpool","Manchester City"],a:2,d:1},
  {q:"Vad heter Zlatans moderklubb?",o:["Malmo FF","IFK Goteborg","AIK","Djurgarden"],a:0,d:1},
  {q:"Vilket lag vann Champions League 2023?",o:["Real Madrid","Manchester City","Bayern München","PSG"],a:1,d:1},
  {q:"Vilket land vann EM 2021?",o:["Frankrike","England","Portugal","Italien"],a:3,d:1},
  {q:"Vem vann Ballon d'Or 2023?",o:["Erling Haaland","Kylian Mbappe","Lionel Messi","Vinicius Jr."],a:2,d:2},
  {q:"Vilket lag spelar hemma på Allianz Arena?",o:["Borussia Dortmund","Bayern München","RB Leipzig","Bayer Leverkusen"],a:1,d:2},
  {q:"Vem var toppscorar i VM 2022?",o:["Messi","Mbappe","Benzema","Neymar"],a:1,d:2},
  {q:"Vilket lag vann Champions League 2024?",o:["Liverpool","PSG","Bayern München","Real Madrid"],a:3,d:2},
  {q:"Vilket år grundades Premier League?",o:["1988","1990","1992","1994"],a:2,d:2},
  {q:"Hur många VM har Brasilien vunnit?",o:["3","4","5","6"],a:2,d:2},
  {q:"Vilket lag vann Champions League flest gånger?",o:["Barcelona","Bayern München","Real Madrid","AC Milan"],a:2,d:2},
  {q:"Vilket år grundades FIFA?",o:["1900","1904","1908","1912"],a:1,d:3},
  {q:"Vilket år spelades det första VM?",o:["1926","1930","1934","1938"],a:1,d:3},
  {q:"Vad heter rekordet för flest mål i ett VM?",o:["Just Fontaine 1958","Pele 1970","Gerd Muller 1970","Ronaldo 2002"],a:0,d:3},
  {q:"Vilket lag vann Champions League 2014?",o:["Bayern München","Barcelona","Atletico Madrid","Real Madrid"],a:3,d:3},
  {q:"Vilket år vann Grekland EM i fotboll?",o:["2000","2002","2004","2006"],a:2,d:3},
],

"🏒 Ishockey": [
  {q:"Vad heter NHL:s mästarskapstrofe?",o:["Presidents Trophy","Hart Trophy","Stanley Cup","Conn Smythe"],a:2,d:1},
  {q:"Vad kallas Wayne Gretzky?",o:["The Boss","The Great One","The Rocket","Mr. Hockey"],a:1,d:1},
  {q:"Vilket lag spelar i Gavle i SHL?",o:["Brynas IF","Frolunda","Djurgardens IF","HV71"],a:0,d:1},
  {q:"Hur manga perioder spelas i ishockey?",o:["2","3","4","5"],a:1,d:1},
  {q:"Vem håller rekord för flest NHL-poäng?",o:["Mario Lemieux","Mark Messier","Wayne Gretzky","Gordie Howe"],a:2,d:1},
  {q:"Vilket lag spelar hemma på Scandinavium?",o:["Brynas IF","Frolunda","Djurgardens IF","MODO"],a:1,d:1},
  {q:"Hur många lag finns i NHL?",o:["28","30","32","34"],a:2,d:1},
  {q:"Vilket år vann Sverige OS-guld i ishockey?",o:["1994","2002","2006","2018"],a:0,d:1},
  {q:"Vilket lag vann Stanley Cup 2024?",o:["Colorado Avalanche","Florida Panthers","Edmonton Oilers","Rangers"],a:1,d:2},
  {q:"Vilket lag vann Stanley Cup 2022?",o:["Colorado Avalanche","Tampa Bay Lightning","Vegas Golden Knights","Florida Panthers"],a:0,d:2},
  {q:"Vad heter trofén för bäste målvakt i NHL?",o:["Vezina Trophy","Hart Trophy","Norris Trophy","Calder Trophy"],a:0,d:2},
  {q:"Vilket år kom Nicklas Backstrom till NHL?",o:["2005","2007","2009","2011"],a:1,d:2},
  {q:"Vilket år kom William Nylander till NHL?",o:["2014","2016","2018","2020"],a:1,d:2},
  {q:"Vilket land vann OS-guld i ishockey 2018 herrar?",o:["Sverige","Finland","Kanada","Ryssland OAR"],a:3,d:2},
  {q:"Vad heter trofén för MVP i NHL playoffs?",o:["Vezina Trophy","Hart Trophy","Conn Smythe Trophy","Norris Trophy"],a:2,d:2},
  {q:"Vem scores mest poäng i NHL-historia en säsong?",o:["Mario Lemieux","Brett Hull","Wayne Gretzky 215p","Jari Kurri"],a:2,d:3},
  {q:"Vilket år grundades Brynas IF?",o:["1908","1920","1930","1940"],a:2,d:3},
  {q:"Vad heter trofén för mest poäng i NHL-säsong?",o:["Vezina Trophy","Hart Trophy","Art Ross Trophy","Maurice Richard Trophy"],a:2,d:3},
  {q:"Vilket år kom Elias Pettersson till NHL?",o:["2016","2018","2020","2022"],a:1,d:3},
  {q:"Vilket lag spelar hemma på Bell Centre?",o:["Toronto Maple Leafs","Ottawa Senators","Montreal Canadiens","Quebec Nordiques"],a:2,d:3},
],

"🏅 Sport (allmänt)": [
  {q:"Vem satte 100m-rekordet på 9.58 sek?",o:["Carl Lewis","Maurice Greene","Usain Bolt","Justin Gatlin"],a:2,d:1},
  {q:"Hur långt är ett marathonlopp?",o:["40 km","42.195 km","45 km","50 km"],a:1,d:1},
  {q:"Vilket land har flest OS-guld totalt?",o:["Ryssland","Kina","USA","Tyskland"],a:2,d:1},
  {q:"Vilken sport spelas i Wimbledon?",o:["Badminton","Squash","Tennis","Padel"],a:2,d:1},
  {q:"Vem vann Formel 1-VM 2021?",o:["Lewis Hamilton","Max Verstappen","Valtteri Bottas","Sebastian Vettel"],a:1,d:1},
  {q:"I vilken sport tävlar man i Tour de France?",o:["Triathlon","Löpning","Cykling","Simning"],a:2,d:1},
  {q:"Vem vann Wimbledon damer 2023?",o:["Iga Swiatek","Coco Gauff","Marketa Vondrousova","Aryna Sabalenka"],a:2,d:1},
  {q:"Vilket år hölls OS i Rio de Janeiro?",o:["2012","2014","2016","2018"],a:2,d:1},
  {q:"Hur många Grand Slam har Roger Federer vunnit?",o:["18","20","22","24"],a:1,d:2},
  {q:"Vem vann Formel 1-VM flest gånger?",o:["Ayrton Senna","Michael Schumacher","Lewis Hamilton","Sebastian Vettel"],a:1,d:2},
  {q:"Vem vann Tour de France 2024?",o:["Tadej Pogacar","Jonas Vingegaard","Egan Bernal","Primoz Roglic"],a:0,d:2},
  {q:"Vem vann Wimbledon herrar 2023?",o:["Novak Djokovic","Carlos Alcaraz","Jannik Sinner","Daniil Medvedev"],a:1,d:2},
  {q:"Vilket år hölls OS i Barcelona?",o:["1988","1992","1996","2000"],a:1,d:2},
  {q:"Vem vann Formel 1-VM 2023?",o:["Lewis Hamilton","Max Verstappen","Charles Leclerc","Sergio Perez"],a:1,d:2},
  {q:"Vem vann Formel 1-VM 2024?",o:["Lewis Hamilton","Max Verstappen","Charles Leclerc","Lando Norris"],a:1,d:2},
  {q:"Vilket år vann Bjorn Borg sitt sista Wimbledon?",o:["1978","1980","1981","1983"],a:1,d:3},
  {q:"Vilket land har flest Formel 1 VM konstruktorer?",o:["Ferrari","McLaren","Mercedes","Williams"],a:0,d:3},
  {q:"Vilket år grundades FIFA?",o:["1900","1904","1908","1912"],a:1,d:3},
  {q:"Vad heter Formel 1-banan i Monaco?",o:["Circuit de Monaco","Monte Carlo Circuit","Monaco GP Circuit","Circuit des Princes"],a:0,d:3},
  {q:"Vilket år hölls OS i Seoul?",o:["1984","1988","1992","1996"],a:1,d:3},
],

"💻 Teknik & IT": [
  {q:"Vilket år lanserades första iPhone?",o:["2005","2007","2009","2011"],a:1,d:1},
  {q:"Vilket företag grundade Bill Gates?",o:["Apple","Amazon","Microsoft","Google"],a:2,d:1},
  {q:"Vilket år grundades Google?",o:["1996","1998","2000","2002"],a:1,d:1},
  {q:"Vad heter Apples smarta assistent?",o:["Cortana","Alexa","Google","Siri"],a:3,d:1},
  {q:"Vilket år grundades Apple?",o:["1974","1976","1978","1980"],a:1,d:1},
  {q:"Vad heter Googles mobiloperativsystem?",o:["iOS","Windows Mobile","Android","HarmonyOS"],a:2,d:1},
  {q:"Vilket år grundades Facebook?",o:["2002","2004","2006","2008"],a:1,d:1},
  {q:"Vad heter Amazons smarta assistent?",o:["Siri","Cortana","Alexa","Google"],a:2,d:1},
  {q:"Vilket år kom Instagram?",o:["2008","2010","2012","2014"],a:1,d:2},
  {q:"Vilket år lanserades ChatGPT?",o:["2020","2021","2022","2023"],a:2,d:2},
  {q:"Vilket år köpte Elon Musk Twitter?",o:["2020","2021","2022","2023"],a:2,d:2},
  {q:"Vad heter Metas VR-headset?",o:["HoloLens","Vision Pro","Quest","Vive"],a:2,d:2},
  {q:"Vilket år lanserades Apples M1-chip?",o:["2018","2020","2022","2024"],a:1,d:2},
  {q:"Vilket år kom TikTok globalt?",o:["2014","2016","2018","2020"],a:2,d:2},
  {q:"Vem grundade LinkedIn?",o:["Bill Gates","Reid Hoffman","Mark Zuckerberg","Jack Dorsey"],a:1,d:2},
  {q:"Vilket år grundades OpenAI?",o:["2013","2015","2017","2019"],a:1,d:2},
  {q:"Vem uppfann World Wide Web?",o:["Bill Gates","Steve Jobs","Tim Berners-Lee","Vint Cerf"],a:2,d:3},
  {q:"Vilket år kom första versionen av Linux?",o:["1989","1991","1993","1995"],a:1,d:3},
  {q:"Vad heter Alan Turings test för AI?",o:["Turing Test","Intelligence Test","Machine Test","Imitation Game"],a:0,d:3},
  {q:"Vilket år grundades Intel?",o:["1964","1966","1968","1970"],a:2,d:3},
],

"🔬 Vetenskap & Natur": [
  {q:"Vilket är det hårdaste naturliga materialet?",o:["Guld","Granit","Diamant","Järn"],a:2,d:1},
  {q:"Hur många planeter finns i solsystemet?",o:["7","8","9","10"],a:1,d:1},
  {q:"Vad är den kemiska formeln för vatten?",o:["HO","H2O","H2O2","HO2"],a:1,d:1},
  {q:"Vilket grundämne har kemisk symbol Au?",o:["Silver","Aluminium","Guld","Koppar"],a:2,d:1},
  {q:"Vad är DNA?",o:["Proteinkomplex","Ribosomalt RNA","Deoxiribonukleinsyra","Adenosintrifosfat"],a:2,d:1},
  {q:"Hur många kromosompar har en människa?",o:["21","23","25","46"],a:1,d:1},
  {q:"Vilket grundämne har kemisk symbol Fe?",o:["Fluor","Fosfor","Järn","Francium"],a:2,d:1},
  {q:"Vad är ljusets hastighet?",o:["200000 km/s","300000 km/s","400000 km/s","500000 km/s"],a:1,d:1},
  {q:"Vilket år publicerade Darwin Arternas uppkomst?",o:["1849","1859","1869","1879"],a:1,d:2},
  {q:"Hur gammal är universum?",o:["8 miljarder år","10 miljarder år","13.8 miljarder år","20 miljarder år"],a:2,d:2},
  {q:"Vilket år sände James Webb-teleskopet sina första bilder?",o:["2020","2021","2022","2023"],a:2,d:2},
  {q:"Hur många grundämnen finns i periodiska systemet?",o:["98","108","118","128"],a:2,d:2},
  {q:"Vad heter den kemiska formeln för koldioxid?",o:["CO","CO2","C2O","C2O2"],a:1,d:2},
  {q:"Hur djup är Marianergraven?",o:["7 km","9 km","11 km","13 km"],a:2,d:2},
  {q:"Vad är den kemiska formeln för glukos?",o:["C5H10O5","C6H12O6","C6H10O5","C12H22O11"],a:1,d:2},
  {q:"Vad heter den process där atomer klyvs?",o:["Fusion","Fission","Klyvning","Radioaktivitet"],a:1,d:2},
  {q:"Vad är ett svart hål?",o:["Kollapsad stjärna med extrem gravitation","Tomrum i rymden","Mörklagd nebulosa","En kvasar"],a:0,d:3},
  {q:"Vad heter Schrödingers tankeexperiment?",o:["Schrödingers paradox","Schrödingers katt","Schrödingers box","Kvantparadoxen"],a:1,d:3},
  {q:"Vilket år fick Curie sitt andra Nobelpris?",o:["1903","1907","1911","1915"],a:2,d:3},
  {q:"Vad är absolut nollpunkt i Kelvin?",o:["0 K","minus 100 K","100 K","273 K"],a:0,d:3},
],

"🌍 Geografi & Historia": [
  {q:"Vad är Frankrikes huvudstad?",o:["Lyon","Marseille","Paris","Bordeaux"],a:2,d:1},
  {q:"Vilket land är störst till ytan?",o:["USA","Kanada","Kina","Ryssland"],a:3,d:1},
  {q:"Vilket år föll Berlinmuren?",o:["1987","1989","1991","1993"],a:1,d:1},
  {q:"Vilket land har flest invånare?",o:["Indien","Kina","USA","Indonesien"],a:0,d:1},
  {q:"Vad är Japans huvudstad?",o:["Osaka","Kyoto","Tokyo","Hiroshima"],a:2,d:1},
  {q:"Vilket år landade människan på månen?",o:["1967","1969","1971","1973"],a:1,d:1},
  {q:"Vad är Kanadas huvudstad?",o:["Toronto","Montreal","Vancouver","Ottawa"],a:3,d:1},
  {q:"Vilket år började andra världskriget?",o:["1937","1939","1941","1943"],a:1,d:1},
  {q:"Vilket år grundades FN?",o:["1943","1945","1947","1949"],a:1,d:2},
  {q:"Vilket år sprack Sovjet upp?",o:["1989","1991","1993","1995"],a:1,d:2},
  {q:"Vilket år byggdes Berlinmuren?",o:["1959","1961","1963","1965"],a:1,d:2},
  {q:"Vilket land kallades Ceylon?",o:["Indien","Bangladesh","Myanmar","Sri Lanka"],a:3,d:2},
  {q:"Vilket år inträffade Tjernobylolyckan?",o:["1984","1986","1988","1990"],a:1,d:2},
  {q:"Hur många länder finns i Afrika?",o:["44","54","64","74"],a:1,d:2},
  {q:"Vilket år förenades Öst och Västtyskland?",o:["1988","1990","1992","1994"],a:1,d:2},
  {q:"Vilket år grundades Romerska riket?",o:["753 f.Kr.","509 f.Kr.","264 f.Kr.","27 f.Kr."],a:0,d:3},
  {q:"Vilket år grundades NATO?",o:["1945","1947","1949","1951"],a:2,d:3},
  {q:"Vilket land var det sista att avskaffa slaveriet?",o:["USA","Brasilien","Saudi-Arabien","Mauretanien"],a:3,d:3},
  {q:"Vilket år grundades Kinas kommunistparti?",o:["1919","1921","1925","1930"],a:1,d:3},
  {q:"Vilket år startade Koreakriget?",o:["1948","1950","1952","1954"],a:1,d:3},
],

"🍕 Mat & Dryck": [
  {q:"Vad är huvudingrediensen i guacamole?",o:["Tomat","Avokado","Lime","Koriander"],a:1,d:1},
  {q:"Vilket land kommer sushi ifrån?",o:["Kina","Korea","Japan","Thailand"],a:2,d:1},
  {q:"Vilket land kommer paella ifrån?",o:["Italien","Portugal","Frankrike","Spanien"],a:3,d:1},
  {q:"Vad är hummus gjort av?",o:["Linser","Kikärtor","Bönor","Ärtor"],a:1,d:1},
  {q:"Vilket land producerar mest olivolja?",o:["Italien","Spanien","Grekland","Turkiet"],a:1,d:1},
  {q:"Vad är umami?",o:["Sött","Surt","Salt","Den femte grundsmaken"],a:3,d:1},
  {q:"Vilket land är känt för Moules-frites?",o:["Frankrike","Holland","Belgien","Luxemburg"],a:2,d:1},
  {q:"Vad heter den japanska rätten av risnudlar med buljong?",o:["Udon","Soba","Ramen","Somen"],a:2,d:1},
  {q:"Vad heter den franska rätten med sniglar?",o:["Foie gras","Bouillabaisse","Escargot","Soufflé"],a:2,d:2},
  {q:"Vilket land kom kebab ifrån?",o:["Libanon","Turkiet","Irak","Iran"],a:1,d:2},
  {q:"Vilket land producerar mest vin i världen?",o:["Frankrike","Spanien","Italien","USA"],a:2,d:2},
  {q:"Vilket år grundades McDonalds?",o:["1940","1948","1955","1960"],a:0,d:2},
  {q:"Vad heter den mexikanska rätten med fylld tortilla som stekes?",o:["Burrito","Taco","Quesadilla","Enchilada"],a:2,d:2},
  {q:"Vad heter den schweiziska rätten av smält ost?",o:["Raclette","Fondue","Rösti","Schnitzel"],a:1,d:2},
  {q:"Vilket land är ursprunget till baklava?",o:["Grekland","Libanon","Turkiet","Iran"],a:2,d:2},
  {q:"Vad är en Maillard-reaktion?",o:["Kemisk reaktion vid jäsning","Brunningsreaktion vid upphettning","Saltningsprocess","Konserveringsmetod"],a:1,d:3},
  {q:"Vilket land producerar Grand Cru-viner?",o:["Italien","Spanien","Frankrike","Portugal"],a:2,d:3},
  {q:"Vad heter den japanska metoden att slakta fisk humant?",o:["Ikejime","Sashimi","Katsu","Mirin"],a:0,d:3},
  {q:"Vilket år grundades Michelin-guiden?",o:["1895","1900","1910","1920"],a:1,d:3},
  {q:"Vad heter det peruanska rätten med citrusmarinerad fisk?",o:["Ceviche","Tiradito","Leche de tigre","Anticucho"],a:0,d:3},
],

"🎭 Allmänkultur & Käpphäst": [
  // Allmänkultur
  {q:"Vem målade Mona Lisa?",o:["Michelangelo","Raphael","Leonardo da Vinci","Botticelli"],a:2,d:1},
  {q:"Vem skrev Romeo och Julia?",o:["Charles Dickens","Jane Austen","William Shakespeare","Homer"],a:2,d:1},
  {q:"Vem var den första att gå på månen?",o:["Buzz Aldrin","Neil Armstrong","Yuri Gagarin","John Glenn"],a:1,d:1},
  {q:"Vem är känd för teorin om relativitet?",o:["Isaac Newton","Niels Bohr","Albert Einstein","Max Planck"],a:2,d:1},
  {q:"Vem målade Skrik?",o:["Vincent van Gogh","Paul Gauguin","Edvard Munch","Gustav Klimt"],a:2,d:1},
  {q:"Vem skapade Sherlock Holmes?",o:["Agatha Christie","Arthur Conan Doyle","Edgar Allan Poe","Wilkie Collins"],a:1,d:1},
  {q:"Vem skulpterade David (renässansen)?",o:["Raphael","Leonardo da Vinci","Michelangelo","Donatello"],a:2,d:2},
  {q:"Vilket år dog Beethoven?",o:["1820","1823","1827","1831"],a:2,d:2},
  {q:"Vem målade Nattvakten?",o:["Vermeer","Rembrandt","Frans Hals","Jan van Eyck"],a:1,d:2},
  {q:"Vem skulpterade Tänkaren?",o:["Michelangelo","Bernini","Auguste Rodin","Donatello"],a:2,d:2},
  {q:"Vem komponerade Symfoni nr 9?",o:["Mozart","Brahms","Beethoven","Schubert"],a:2,d:2},
  {q:"Vilket år dog Mozart?",o:["1787","1789","1791","1793"],a:2,d:2},
  // Käpphästar – intressen och hobby-fakta
  {q:"Vilket år kom det populära brädspelet Catan?",o:["1991","1993","1995","1997"],a:2,d:1},
  {q:"Vilket är det mest sålda brädspelet i världen?",o:["Schack","Monopol","Scrabble","Cluedo"],a:1,d:1},
  {q:"Vilket år lanserades Twitch?",o:["2009","2011","2013","2015"],a:1,d:1},
  {q:"Vilket år kom Dungeons and Dragons?",o:["1970","1972","1974","1976"],a:2,d:2},
  {q:"Vilket år lanserades Magic the Gathering?",o:["1989","1991","1993","1995"],a:2,d:2},
  {q:"Vad heter den mest populära esportsturneringen i League of Legends?",o:["ESL Pro League","World Championship","LCS Finals","MSI"],a:1,d:2},
  {q:"Vilket år kom Netflix som streamingtjänst?",o:["2005","2007","2009","2011"],a:1,d:1},
  {q:"Vad heter filosofen som sade Jag tänker alltså är jag?",o:["John Locke","David Hume","Immanuel Kant","René Descartes"],a:3,d:1},
  {q:"Vilket år kom Wikipedia?",o:["1999","2001","2003","2005"],a:1,d:1},
  {q:"Vilket är det mest spelade TV-spelet genom tiderna?",o:["Minecraft","Tetris","GTA V","PUBG"],a:1,d:2},
  {q:"Vilket år kom Pokemon Go?",o:["2014","2016","2018","2020"],a:1,d:1},
  {q:"Vem skapade Simpsons?",o:["Seth MacFarlane","Mike Judge","Matt Groening","Trey Parker"],a:2,d:1},
  {q:"Vilket år kom South Park?",o:["1995","1997","1999","2001"],a:1,d:1},
  {q:"Vilket år kom Game of Thrones spelet?",o:["2010","2012","2014","2016"],a:1,d:2},
  {q:"Vad heter den populäraste podcasten Joe Rogans?",o:["Joe Rogan Show","JRE","The Joe Rogan Experience","Rogan Radio"],a:2,d:1},
  {q:"Vilket år grundades Reddit?",o:["2003","2005","2007","2009"],a:1,d:2},
  {q:"Vilket år kom första iPhone appen App Store?",o:["2006","2008","2010","2012"],a:1,d:2},
  {q:"Vad heter Worlds största e-sportsarena?",o:["Blizzard Arena","Seoul eSports Stadium","Fiserv Forum","Madison Square Garden"],a:1,d:3},
],

"🌈 Blandat / Mix": [
  {q:"Vilket land kom Ikea ifrån?",o:["Danmark","Norge","Finland","Sverige"],a:3,d:1},
  {q:"Vad är PI ungefär?",o:["2.14","3.14","3.41","4.14"],a:1,d:1},
  {q:"Vilket år dog Elvis Presley?",o:["1975","1977","1979","1981"],a:1,d:1},
  {q:"Vad heter det minsta landet i världen?",o:["Monaco","San Marino","Vatikanstaten","Liechtenstein"],a:2,d:1},
  {q:"Vilket år dog Freddie Mercury?",o:["1989","1991","1993","1995"],a:1,d:1},
  {q:"Vem målade Guernica?",o:["Salvador Dalí","Joan Miró","Pablo Picasso","Francis Bacon"],a:2,d:1},
  {q:"Vilket land uppfann papperet?",o:["Japan","Indien","Kina","Egypten"],a:2,d:1},
  {q:"Vem skapade Simpsons?",o:["Seth MacFarlane","Mike Judge","Matt Groening","Trey Parker"],a:2,d:1},
  {q:"Vad heter det minsta benet i kroppen?",o:["Stapes stigbygeln","Hammer","Amboss","Radius"],a:0,d:2},
  {q:"Vilket år kom flygplanet Wright Brothers?",o:["1899","1901","1903","1905"],a:2,d:2},
  {q:"Vilket land har flest tidszoner?",o:["Ryssland","USA","Kina","Frankrike"],a:3,d:2},
  {q:"Vilket år kom Darwin's On the Origin of Species?",o:["1849","1859","1869","1879"],a:1,d:2},
  {q:"Vilket år dog Alan Turing?",o:["1950","1952","1954","1956"],a:2,d:2},
  {q:"Vilket land uppfann glassen?",o:["Italien","Frankrike","Kina","USA"],a:2,d:2},
  {q:"Hur många bitar ingår i en byte?",o:["4","6","8","10"],a:2,d:2},
  {q:"Vilket land vann fotbolls-EM 2024?",o:["Frankrike","England","Spanien","Portugal"],a:2,d:2},
  {q:"Vilket år skedde månlandningen?",o:["1967","1969","1971","1973"],a:1,d:1},
  {q:"Vad heter den snabbaste fågeln?",o:["Örn","Vandringsfalk","Albatross","Swift"],a:1,d:2},
  {q:"Vilket år kom smartphones med pekskärm?",o:["2005","2007","2009","2011"],a:1,d:1},
  {q:"Vilket grundämne har atomnummer 1?",o:["Helium","Väte","Litium","Beryllium"],a:1,d:2},
],

"🏙️ Umeå & Norrland": [
  {q:"Umeå är beläget vid vilken älv?",o:["Luleälven","Ångermanälven","Umeälven","Skellefteälven"],a:2,d:1},
  {q:"Vilket år utsågs Umeå till Europas kulturhuvudstad?",o:["2010","2012","2014","2016"],a:2,d:1},
  {q:"Vilket universitet finns i Umeå?",o:["Luleå tekniska","Uppsala","Umeå universitet","Mittuniversitetet"],a:2,d:1},
  {q:"Vad kallas Umeå ibland på grund av sina björkar?",o:["Björkstaden","Trädstaden","Norrlandsstaden","Älvstaden"],a:0,d:1},
  {q:"I vilket landskap ligger Umeå?",o:["Ångermanland","Lappland","Västerbotten","Norrbotten"],a:2,d:1},
  {q:"Vilket år grundades Umeå universitet?",o:["1945","1955","1963","1971"],a:2,d:1},
  {q:"Vad heter Umeås stora köpcentrum?",o:["Mitt i City","Syd","A6","Utopia"],a:3,d:1},
  {q:"Vad heter Umeås konstmuseum?",o:["Bildmuseet","Umeå konstmuseum","Norrlandsmuseet","Västerbottensmuseet"],a:0,d:1},
  {q:"Hur många invånare har Umeå ungefär?",o:["60000","80000","130000","200000"],a:2,d:1},
  {q:"Vilket landskap gränsar Västerbotten mot väster?",o:["Lappland","Norrbotten","Ångermanland","Finland"],a:0,d:2},
  {q:"Vilken kändis från Umeå är känd inom höjdhopp?",o:["Stefan Holm","Patrik Sjöberg","Kajsa Bergqvist","Carolina Klüft"],a:0,d:2},
  {q:"Vilket år fick Umeå stadsrättigheter?",o:["1588","1622","1640","1700"],a:1,d:2},
  {q:"Vad heter Umeås lokaltidning?",o:["Västerbottens-Kuriren","Norrländska Socialdemokraten","Umeå Tidning","Norran"],a:0,d:2},
  {q:"Vilket år brann Umeå ned och byggdes upp?",o:["1798","1888","1902","1920"],a:1,d:2},
  {q:"Hur långt är det från Umeå till Stockholm?",o:["Ca 400 km","Ca 600 km","Ca 700 km","Ca 900 km"],a:3,d:2},
  {q:"Vilket år öppnade Northvolt-fabriken i Skellefteå?",o:["2019","2021","2022","2023"],a:1,d:2},
  {q:"Vilket år grundades Västerbottens museum?",o:["1886","1900","1921","1945"],a:0,d:3},
  {q:"Vilket år öppnade Umeå flygplats?",o:["1935","1944","1952","1960"],a:1,d:3},
  {q:"Vilket år grundades Umeå som stad?",o:["1588","1621","1650","1700"],a:1,d:3},
  {q:"Vad heter kullen i centrala Umeå?",o:["Röbäckskullen","Umedalen","Backenkullen","Tomtebo"],a:0,d:3},
],

"🕺 70-tals musik": [
  {q:"Vilket band sjöng 'Bohemian Rhapsody'?",o:["Led Zeppelin","The Beatles","Queen","Rolling Stones"],a:2,d:1},
  {q:"Vem sjunger 'Rocket Man' (1972)?",o:["David Bowie","Rod Stewart","Elton John","Billy Joel"],a:2,d:1},
  {q:"Vem sjunger 'I Will Survive' (Gloria Gaynor)?",o:["Donna Summer","Gloria Gaynor","Diana Ross","Tina Turner"],a:1,d:1},
  {q:"Vilket band sjöng 'Stayin Alive' (1977)?",o:["Earth Wind & Fire","KC and the Sunshine Band","Bee Gees","Chic"],a:2,d:1},
  {q:"Vem sjunger 'Piano Man' (Billy Joel)?",o:["Elton John","Billy Joel","James Taylor","Carole King"],a:1,d:1},
  {q:"Vilket band sjöng 'Le Freak' (Chic)?",o:["Earth Wind & Fire","Chic","Kool & the Gang","Parliament"],a:1,d:1},
  {q:"Vem sjunger 'Jolene' (Dolly Parton)?",o:["Loretta Lynn","Tammy Wynette","Dolly Parton","Emmylou Harris"],a:2,d:1},
  {q:"Vilket år kom Pink Floyds 'Dark Side of the Moon'?",o:["1971","1973","1975","1977"],a:1,d:2},
  {q:"Vem sjunger 'Maggie May' (Rod Stewart)?",o:["Mick Jagger","Rod Stewart","Joe Cocker","Eric Clapton"],a:1,d:2},
  {q:"Vilket år kom Fleetwood Macs 'Rumours'?",o:["1975","1977","1979","1981"],a:1,d:2},
  {q:"Vilket band sjöng 'Night Fever' (Bee Gees)?",o:["Earth Wind & Fire","Bee Gees","Chic","Kool & the Gang"],a:1,d:2},
  {q:"Vilket år kom David Bowies 'Heroes'?",o:["1975","1977","1979","1981"],a:1,d:2},
  {q:"Vem sjunger 'Fast Car' (Tracy Chapman)?",o:["Tracy Chapman","Joni Mitchell","Carole King","Bonnie Raitt"],a:0,d:2},
  {q:"Vilket band sjöng 'Fortunate Son' (CCR)?",o:["Creedence Clearwater Revival","The Eagles","Lynyrd Skynyrd","ZZ Top"],a:0,d:2},
  {q:"Vem producerade Chics 'Good Times'?",o:["Barry White","Quincy Jones","Nile Rodgers","Giorgio Moroder"],a:2,d:3},
  {q:"Vilket år kom The Clashs 'London Calling'?",o:["1977","1979","1981","1983"],a:1,d:3},
  {q:"Vem sjunger 'Killing Me Softly' original 1973?",o:["Carly Simon","Roberta Flack","Nina Simone","Phoebe Snow"],a:1,d:3},
  {q:"Vilket år kom Talking Heads 'Remain in Light'?",o:["1978","1980","1982","1984"],a:1,d:3},
],

"🎤 K-pop & Asiatisk musik": [
  {q:"Vilket K-pop band sjöng 'Dynamite' (BTS)?",o:["EXO","BLACKPINK","BTS","TWICE"],a:2,d:1},
  {q:"Vilket K-pop band sjöng 'How You Like That'?",o:["EXO","BLACKPINK","BTS","aespa"],a:1,d:1},
  {q:"Vem sjunger 'Gangnam Style'?",o:["Rain","G-Dragon","PSY","Taeyang"],a:2,d:1},
  {q:"Vad heter BTS fansen officiellt?",o:["Blinks","Stays","Army","Carats"],a:2,d:1},
  {q:"Vilket K-pop band sjöng 'Kill This Love'?",o:["EXO","BLACKPINK","BTS","MAMAMOO"],a:1,d:1},
  {q:"Vilket K-pop band sjöng 'Fancy' (TWICE)?",o:["TWICE","BLACKPINK","Red Velvet","ITZY"],a:0,d:1},
  {q:"Vad heter BLACKPINK fansen?",o:["Army","Blinks","Stays","Reveluvs"],a:1,d:1},
  {q:"Vilket år debuterade BTS?",o:["2011","2013","2015","2017"],a:1,d:2},
  {q:"Vilket K-pop band sjöng 'Butter' (BTS)?",o:["EXO","BLACKPINK","BTS","TXT"],a:2,d:2},
  {q:"Vilket år debuterade BLACKPINK?",o:["2014","2016","2018","2020"],a:1,d:2},
  {q:"Vilket K-pop band sjöng 'Next Level' (aespa)?",o:["TWICE","BLACKPINK","Red Velvet","aespa"],a:3,d:2},
  {q:"Vilket K-pop band sjöng 'ELEVEN' (IVE)?",o:["aespa","IVE","NMIXX","NewJeans"],a:1,d:3},
  {q:"Vilket år kom NewJeans debut?",o:["2020","2021","2022","2023"],a:2,d:3},
  {q:"Vilket K-pop band sjöng 'Cupid' (FIFTY FIFTY)?",o:["aespa","IVE","FIFTY FIFTY","NewJeans"],a:2,d:2},
  {q:"Vad heter TWICE fansen?",o:["Army","Blinks","Stays","Once"],a:3,d:2},
  {q:"Vilket K-pop band sjöng 'TOMBOY' (G I-DLE)?",o:["G I-DLE","aespa","IVE","NMIXX"],a:0,d:3},
  {q:"Vilket år debuterade TWICE?",o:["2013","2015","2017","2019"],a:1,d:3},
],

"🌌 Astronomi & Rymden": [
  {q:"Vilket är solsystemets störst planet?",o:["Saturn","Uranus","Jupiter","Neptunus"],a:2,d:1},
  {q:"Vad heter vår galax?",o:["Andromeda","Vintergatan","Triangeln","Magellanska molnet"],a:1,d:1},
  {q:"Hur lång tid tar ljuset från solen till jorden?",o:["4 min","8 min","20 min","1 timme"],a:1,d:1},
  {q:"Hur många måndar har Mars?",o:["0","1","2","3"],a:2,d:1},
  {q:"Vad heter den närmaste galaxen?",o:["Triangelgalaxen","Andromeda","Stora Magellanska molnet","Lilla Magellanska molnet"],a:1,d:2},
  {q:"Vilket år sände Voyager 1 ut?",o:["1973","1975","1977","1979"],a:2,d:2},
  {q:"Vad heter det svarta hålet i centrum av Vintergatan?",o:["Sagittarius A*","Cygnus X-1","TON 618","M87*"],a:0,d:2},
  {q:"Vilket år togs första fotot av ett svart hål?",o:["2015","2017","2019","2021"],a:2,d:2},
  {q:"Vilket år landade Curiosity på Mars?",o:["2008","2010","2012","2014"],a:2,d:2},
  {q:"Vad heter Jupiters störst måne?",o:["Europa","Ganymedes","Callisto","Io"],a:1,d:3},
  {q:"Hur lång tid tar Neptunus att kretsa runt solen?",o:["84 år","100 år","165 år","248 år"],a:2,d:3},
  {q:"Vad är en pulsar?",o:["En roterande neutronsstjärna","En kollapsad vit dvärg","En quasar","En röd jätte"],a:0,d:3},
],

"🍹 Alkohol & Drinkar": [
  {q:"Vad är huvudingrediensen i en Margarita?",o:["Vodka","Rum","Tequila","Gin"],a:2,d:1},
  {q:"Vilket land kommer Scotch Whisky ifrån?",o:["Irland","Skottland","USA","Japan"],a:1,d:1},
  {q:"Vad är en Mojito gjord på?",o:["Vodka och lime","Rum mynta lime och socker","Gin och tonic","Tequila och citron"],a:1,d:1},
  {q:"Vilket land kommer Bourbon ifrån?",o:["Skottland","Irland","Kanada","USA"],a:3,d:1},
  {q:"Vad är en Aperol Spritz gjord på?",o:["Aperol Campari och soda","Aperol prosecco och soda","Aperol gin och tonic","Aperol vodka och lime"],a:1,d:1},
  {q:"Vad heter den irländska stout ölen?",o:["Heineken","Guinness","Carlsberg","Stella Artois"],a:1,d:1},
  {q:"Vilket land producerar Rioja-vin?",o:["Frankrike","Italien","Spanien","Portugal"],a:2,d:1},
  {q:"Vad är en Old Fashioned gjord på?",o:["Vodka angostura och socker","Bourbon eller rye angostura och socker","Rum angostura och socker","Gin angostura och socker"],a:1,d:2},
  {q:"Vilket land producerar mest vin i världen?",o:["Frankrike","Spanien","Italien","USA"],a:2,d:2},
  {q:"Vad är Cointreau?",o:["En rom","En apelsinlikör","En vodka","En gin"],a:1,d:2},
  {q:"Vad är en Espresso Martini gjord på?",o:["Vodka kaffelikör och espresso","Gin kaffelikör och espresso","Rum kaffelikör och espresso","Bourbon kaffelikör och espresso"],a:0,d:2},
  {q:"Vilket land producerar mest öl i världen?",o:["Tyskland","USA","Kina","Tjeckien"],a:2,d:2},
  {q:"Vad heter cocktailen med vodka lime och ginger beer?",o:["Paloma","Moscow Mule","Dark and Stormy","Gin Mule"],a:1,d:2},
  {q:"Vad är Campari?",o:["En italiensk bitter likör","En fransk vin-aperitif","En spansk sherry","En belgisk öl"],a:0,d:2},
  {q:"Vilket år grundades Guinness?",o:["1749","1759","1769","1779"],a:1,d:3},
  {q:"Vilket land uppfann ölet historiskt?",o:["England","Mesopotamien","Egypten","Kina"],a:1,d:3},
  {q:"Vad heter den klassiska New Orleans-cocktailen med rye?",o:["Hurricane","Sazerac","Ramos Gin Fizz","Vieux Carré"],a:1,d:3},
  {q:"Vilket år kom Baileys Irish Cream?",o:["1967","1972","1977","1982"],a:1,d:3},
],
};

(function() {
  if (typeof QUESTION_DB === 'undefined') return;
  const existing = new Set();
  Object.values(QUESTION_DB).forEach(qs => qs.forEach(q => existing.add(q.q.toLowerCase().trim())));
  let added = 0, skipped = 0;
  Object.keys(QUESTION_DB11).forEach(cat => {
    const newQs = QUESTION_DB11[cat].filter(q => {
      const key = q.q.toLowerCase().trim();
      if(existing.has(key)){skipped++;return false;}
      existing.add(key);
      return true;
    });
    if(QUESTION_DB[cat]){ QUESTION_DB[cat]=QUESTION_DB[cat].concat(newQs); }
    else { QUESTION_DB[cat]=newQs; }
    added += newQs.length;
  });
  console.log('questions11.js: '+added+' added, '+skipped+' dupes skipped');
})();
