// ═══════════════════════════════════════════════════════
//  Combitech AW Quiz – Frågedatabas v4
//  Format: { q:"Fråga?", o:["A","B","C","D"], a:0, d:1 }
//  d = svårighetsgrad: 1=lätt, 2=medel, 3=svårt
// ═══════════════════════════════════════════════════════

const QUESTION_DB = {

  "🎵 80-tals musik": [
    {q:"Vilket band sjöng 'Wake Me Up Before You Go-Go'?",o:["Duran Duran","Wham!","Culture Club","Spandau Ballet"],a:1,d:1},
    {q:"Vem sjunger 'Like a Virgin'?",o:["Cyndi Lauper","Pat Benatar","Madonna","Tina Turner"],a:2,d:1},
    {q:"Vilket band sjöng 'Don't You (Forget About Me)'?",o:["The Cure","Simple Minds","New Order","Depeche Mode"],a:1,d:1},
    {q:"Vem sjunger 'Girls Just Want to Have Fun'?",o:["Madonna","Pat Benatar","Cyndi Lauper","Blondie"],a:2,d:1},
    {q:"Vilket band sjöng 'Take On Me'?",o:["a-ha","Roxette","Europe","Ace of Base"],a:0,d:1},
    {q:"Vilket band sjöng 'Africa'?",o:["Foreigner","Toto","Journey","Boston"],a:1,d:1},
    {q:"Vem sjunger 'Sweet Dreams (Are Made of This)'?",o:["Siouxsie","Eurythmics","Kate Bush","Yazoo"],a:1,d:1},
    {q:"Vilket band sjöng 'Every Breath You Take'?",o:["The Police","U2","Dire Straits","Genesis"],a:0,d:1},
    {q:"Vem sjunger 'Jump' (1984)?",o:["Van Halen","Bon Jovi","Aerosmith","Def Leppard"],a:0,d:1},
    {q:"Vilket band sjöng 'Come On Eileen'?",o:["The Clash","Madness","Dexys Midnight Runners","The Specials"],a:2,d:1},
    {q:"Vem sjunger 'Purple Rain'?",o:["Michael Jackson","Prince","David Bowie","Stevie Wonder"],a:1,d:1},
    {q:"Vilket band sjöng 'Don't Stop Me Now'?",o:["Dire Straits","Queen","Elton John","David Bowie"],a:1,d:1},
    {q:"Vem sjunger 'Billie Jean'?",o:["Prince","James Brown","Michael Jackson","Stevie Wonder"],a:2,d:1},
    {q:"Vilket band sjöng '99 Luftballons'?",o:["Falco","Nena","Sandra","C.C. Catch"],a:1,d:1},
    {q:"Vem sjunger 'Material Girl'?",o:["Cyndi Lauper","Pat Benatar","Madonna","Debbie Harry"],a:2,d:1},
    {q:"Vilket band sjöng 'Karma Chameleon'?",o:["Duran Duran","Spandau Ballet","Culture Club","A Flock of Seagulls"],a:2,d:1},
    {q:"Vilket band sjöng 'The Final Countdown'?",o:["Def Leppard","Whitesnake","Europe","Scorpions"],a:2,d:1},
    {q:"Vilket band sjöng 'Don't You Want Me'?",o:["Erasure","Pet Shop Boys","Human League","Yazoo"],a:2,d:1},
    {q:"Vilket band sjöng 'With or Without You'?",o:["Simple Minds","Depeche Mode","U2","The Police"],a:2,d:1},
    {q:"Vem sjunger 'Total Eclipse of the Heart'?",o:["Celine Dion","Bonnie Tyler","Kim Carnes","Stevie Nicks"],a:1,d:1},
    {q:"Vilket år kom a-has debutalbum 'Hunting High and Low'?",o:["1983","1985","1987","1989"],a:1,d:2},
    {q:"Vilket år kom Prince's 'Purple Rain'?",o:["1982","1984","1986","1988"],a:1,d:2},
    {q:"Vilket band sjöng 'Enola Gay'?",o:["Ultravox","Soft Cell","OMD","Gary Numan"],a:2,d:2},
    {q:"Vem producerade David Bowies 'Let's Dance'?",o:["Brian Eno","Tony Visconti","Nile Rodgers","Giorgio Moroder"],a:2,d:2},
    {q:"Vilket år kom Michael Jacksons 'Bad'?",o:["1985","1987","1989","1991"],a:1,d:2},
    {q:"Vilket band sjöng 'Relax' (1984)?",o:["Pet Shop Boys","Erasure","Frankie Goes to Hollywood","Culture Club"],a:2,d:2},
    {q:"Vilket år kom U2s 'The Joshua Tree'?",o:["1985","1987","1989","1991"],a:1,d:2},
    {q:"Vilket band sjöng 'West End Girls'?",o:["Erasure","Pet Shop Boys","Bronski Beat","Soft Cell"],a:1,d:2},
    {q:"Vem sjunger 'Gloria' (1982)?",o:["Tina Turner","Laura Branigan","Kim Wilde","Pat Benatar"],a:1,d:2},
    {q:"Vilket band sjöng 'True' (1983)?",o:["Duran Duran","Spandau Ballet","ABC","Heaven 17"],a:1,d:2},
    {q:"Vilket år kom Joy Divisions debutalbum 'Unknown Pleasures'?",o:["1977","1979","1981","1983"],a:1,d:3},
    {q:"Vilket skivbolag gav ut The Smiths tidiga singlar?",o:["Factory","Rough Trade","4AD","Creation"],a:1,d:3},
    {q:"Vilket år kom New Orders 'Blue Monday'?",o:["1981","1983","1985","1987"],a:1,d:3},
    {q:"Vad heter synthpop-duon bakom 'Tainted Love'?",o:["Erasure","Pet Shop Boys","Soft Cell","Yazoo"],a:2,d:3},
    {q:"Vilket skivbolag gav ut Joy Divisions musik?",o:["Rough Trade","4AD","Factory Records","Creation"],a:2,d:3},
    {q:"Vem sjunger 'The Killing Moon' (1984)?",o:["The Cure","Echo and the Bunnymen","The Jesus and Mary Chain","Bauhaus"],a:1,d:3},
    {q:"Vilket år kom Depeche Modes 'Some Great Reward'?",o:["1982","1984","1986","1988"],a:1,d:3},
    {q:"Vad heter Marc Almonds band?",o:["Erasure","Pet Shop Boys","Soft Cell","Yazoo"],a:2,d:3},
  ],

  "🎶 90-tals musik": [
    {q:"Vilket band sjöng 'Smells Like Teen Spirit'?",o:["Pearl Jam","Soundgarden","Nirvana","Alice in Chains"],a:2,d:1},
    {q:"Vilket band sjöng 'Wannabe'?",o:["TLC","Destiny's Child","Spice Girls","En Vogue"],a:2,d:1},
    {q:"Vem sjunger 'Baby One More Time'?",o:["Christina Aguilera","Britney Spears","Madonna","Mariah Carey"],a:1,d:1},
    {q:"Vilket band sjöng 'Ironic'?",o:["Sheryl Crow","Alanis Morissette","Shania Twain","Jewel"],a:1,d:1},
    {q:"Vilket band sjöng 'Losing My Religion'?",o:["U2","REM","Radiohead","Pearl Jam"],a:1,d:1},
    {q:"Vilket band sjöng 'Basket Case'?",o:["The Offspring","Rancid","Green Day","Blink-182"],a:2,d:1},
    {q:"Vem sjunger 'I Will Always Love You' (filmversion)?",o:["Dolly Parton","Celine Dion","Whitney Houston","Mariah Carey"],a:2,d:1},
    {q:"Vilket band sjöng 'Wonderwall'?",o:["Blur","Pulp","Oasis","Suede"],a:2,d:1},
    {q:"Vilket band sjöng 'MMMBop'?",o:["New Kids on the Block","Backstreet Boys","Hanson","NSYNC"],a:2,d:1},
    {q:"Vilket band sjöng 'Zombie'?",o:["The Pretenders","Sinead O'Connor","The Cranberries","Enya"],a:2,d:1},
    {q:"Vem sjunger 'Un-Break My Heart'?",o:["Whitney Houston","Mariah Carey","Toni Braxton","Celine Dion"],a:2,d:1},
    {q:"Vilket band sjöng 'Killing Me Softly' (1996)?",o:["TLC","Destiny's Child","Fugees","En Vogue"],a:2,d:1},
    {q:"Vem sjunger 'Believe'?",o:["Madonna","Kylie Minogue","Cher","Whitney Houston"],a:2,d:1},
    {q:"Vilket band sjöng 'Torn'?",o:["Natalie Imbruglia","Alanis Morissette","Sheryl Crow","Shania Twain"],a:0,d:1},
    {q:"Vem sjunger 'No Scrubs'?",o:["Destiny's Child","En Vogue","TLC","SWV"],a:2,d:1},
    {q:"Vilket år kom Oasis 'Definitely Maybe'?",o:["1992","1994","1996","1998"],a:1,d:2},
    {q:"Vilket år kom Madonnas 'Ray of Light'?",o:["1996","1998","2000","2002"],a:1,d:2},
    {q:"Vad heter Lauryn Hills soloalbum från 1998?",o:["The Score","The Miseducation of Lauryn Hill","Killing Me Softly","Ex-Factor"],a:1,d:2},
    {q:"Vilket år kom Jay-Zs debutalbum?",o:["1994","1996","1998","2000"],a:1,d:2},
    {q:"Vilket år kom Daft Punks debutalbum 'Homework'?",o:["1995","1997","1999","2001"],a:1,d:2},
    {q:"Vilket band sjöng 'No Diggity'?",o:["Boyz II Men","Blackstreet","112","Dru Hill"],a:1,d:2},
    {q:"Vilket band sjöng 'Gangsta's Paradise'?",o:["Coolio","Ice Cube","Snoop Dogg","Dr. Dre"],a:0,d:2},
    {q:"Vilket år kom Nirvanas 'In Utero'?",o:["1991","1993","1995","1997"],a:1,d:2},
    {q:"Vilket år kom Radioheads 'The Bends'?",o:["1993","1995","1997","1999"],a:1,d:2},
    {q:"Vem producerade Alanis Morissettes 'Jagged Little Pill'?",o:["Rick Rubin","Glen Ballard","Butch Vig","Don Was"],a:1,d:3},
    {q:"Vad heter Biggie Smalls riktiga namn?",o:["Christopher Williams","Christopher Wallace","Christopher Martin","Christopher Brown"],a:1,d:3},
    {q:"Vilket skivbolag var Nirvana på när Kurt Cobain dog?",o:["Sub Pop","DGC Records","Geffen","Epitaph"],a:1,d:3},
    {q:"Vilket år kom Tupacs 'All Eyez on Me'?",o:["1994","1996","1998","2000"],a:1,d:3},
    {q:"Vad heter Dr. Dres riktiga namn?",o:["Andre Young","Dre Williams","Calvin Broadus","Andre Brown"],a:0,d:3},
    {q:"Vilket år kom Radioheads 'OK Computer'?",o:["1995","1997","1999","2001"],a:1,d:3},
    {q:"Vad heter Alanis Morissettes genombrott salbum?",o:["Supposed Former Infatuation Junkie","So-Called Chaos","Jagged Little Pill","Under Rug Swept"],a:2,d:3},
    {q:"Vilket år bildades Destiny's Child?",o:["1990","1992","1994","1997"],a:3,d:3},
    {q:"Vilket år kom Fugees album 'The Score'?",o:["1994","1996","1998","2000"],a:1,d:3},
    {q:"Vem producerade Daft Punks 'Homework'?",o:["Todd Terry","Daft Punk själva","Basement Jaxx","Armand Van Helden"],a:1,d:3},
  ],

  "🎤 Ny musik (2010-idag)": [
    {q:"Vem sjunger 'Shape of You'?",o:["Justin Bieber","Ed Sheeran","Sam Smith","Harry Styles"],a:1,d:1},
    {q:"Vem sjunger 'Bad Guy'?",o:["Ariana Grande","Billie Eilish","Dua Lipa","Olivia Rodrigo"],a:1,d:1},
    {q:"Vem sjunger 'Hello' (2015)?",o:["Beyoncé","Rihanna","Adele","Lady Gaga"],a:2,d:1},
    {q:"Vem sjunger 'Blinding Lights'?",o:["Drake","The Weeknd","Post Malone","Travis Scott"],a:1,d:1},
    {q:"Vem sjunger 'Old Town Road'?",o:["Cardi B","Lil Nas X","Travis Scott","Post Malone"],a:1,d:1},
    {q:"Vem sjunger 'Levitating'?",o:["Dua Lipa","Doja Cat","Olivia Rodrigo","Ariana Grande"],a:0,d:1},
    {q:"Vem sjunger 'drivers license'?",o:["Billie Eilish","Dua Lipa","Olivia Rodrigo","Ariana Grande"],a:2,d:1},
    {q:"Vem sjunger 'Anti-Hero'?",o:["Billie Eilish","Olivia Rodrigo","Taylor Swift","Sabrina Carpenter"],a:2,d:1},
    {q:"Vem sjunger 'As It Was'?",o:["Ed Sheeran","Harry Styles","Niall Horan","Louis Tomlinson"],a:1,d:1},
    {q:"Vem sjunger 'Shake It Off'?",o:["Katy Perry","Ariana Grande","Taylor Swift","Selena Gomez"],a:2,d:1},
    {q:"Vem sjunger 'Royals'?",o:["Lorde","Lana Del Rey","Halsey","Billie Eilish"],a:0,d:1},
    {q:"Vem sjunger 'Happy'?",o:["Bruno Mars","Justin Timberlake","Pharrell Williams","Jason Derulo"],a:2,d:1},
    {q:"Vilket band sjöng 'Uptown Funk'?",o:["Bruno Mars","Mark Ronson ft. Bruno Mars","Pharrell","Justin Timberlake"],a:1,d:1},
    {q:"Vem sjunger 'Watermelon Sugar'?",o:["Ed Sheeran","Harry Styles","Niall Horan","Shawn Mendes"],a:1,d:1},
    {q:"Vem sjunger 'Stay With Me'?",o:["Ed Sheeran","Sam Smith","James Arthur","Olly Murs"],a:1,d:1},
    {q:"Vilket år kom Adeles '21'?",o:["2009","2011","2013","2015"],a:1,d:2},
    {q:"Vilket år kom Taylor Swifts '1989'?",o:["2012","2014","2016","2018"],a:1,d:2},
    {q:"Vem sjunger 'Humble'?",o:["Drake","J. Cole","Kendrick Lamar","Travis Scott"],a:2,d:2},
    {q:"Vem sjunger 'God's Plan'?",o:["Travis Scott","Post Malone","Drake","The Weeknd"],a:2,d:2},
    {q:"Vilket år kom Dua Lipas 'Future Nostalgia'?",o:["2018","2020","2022","2024"],a:1,d:2},
    {q:"Vilket år vann Billie Eilish fyra Grammy Awards?",o:["2019","2020","2021","2022"],a:1,d:2},
    {q:"Vem sjunger 'Espresso'?",o:["Dua Lipa","Sabrina Carpenter","Olivia Rodrigo","Ariana Grande"],a:1,d:2},
    {q:"Vilket år kom Kendrick Lamars 'DAMN.'?",o:["2015","2017","2019","2021"],a:1,d:2},
    {q:"Vem sjunger 'Industry Baby'?",o:["Lil Nas X ft. Jack Harlow","Travis Scott","Cardi B","Megan Thee Stallion"],a:0,d:2},
    {q:"Vad heter Billie Eilish's bror och producent?",o:["Ryan","Finneas","Declan","Ryder"],a:1,d:3},
    {q:"Vilket år kom Kendrick Lamars 'To Pimp a Butterfly'?",o:["2013","2015","2017","2019"],a:1,d:3},
    {q:"Vilket år kom Frank Oceans 'Blonde'?",o:["2014","2016","2018","2020"],a:1,d:3},
    {q:"Vilket år kom Tyler the Creators 'IGOR'?",o:["2017","2019","2021","2023"],a:1,d:3},
    {q:"Vilket skivbolag är Olivia Rodrigo på?",o:["Republic","Geffen","Interscope","Geffen/Interscope"],a:3,d:3},
    {q:"Vilket år kom SZAs debutalbum 'Ctrl'?",o:["2015","2017","2019","2021"],a:1,d:3},
    {q:"Vilket år kom The Weeknds 'After Hours'?",o:["2018","2020","2022","2024"],a:1,d:3},
    {q:"Vem producerade Dua Lipas 'Future Nostalgia'?",o:["Max Martin","Stuart Price","Ian Kirkpatrick","Jeff Bhasker"],a:1,d:3},
    {q:"Vilket år kom Taylor Swifts 'Folklore'?",o:["2018","2019","2020","2021"],a:2,d:3},
    {q:"Vilket år kom Kendrick vs Drake-fejden?",o:["2022","2023","2024","2025"],a:2,d:3},
  ],

  "🎵 Popmusik (allmänt)": [
    {q:"Vilket land kommer ABBA ifrån?",o:["Norge","Danmark","Sverige","Finland"],a:2,d:1},
    {q:"Vem är känd som 'King of Pop'?",o:["Elvis Presley","Prince","Michael Jackson","David Bowie"],a:2,d:1},
    {q:"Vilket band sjöng 'Bohemian Rhapsody'?",o:["Led Zeppelin","The Beatles","Queen","Rolling Stones"],a:2,d:1},
    {q:"Vem sjunger 'Rolling in the Deep'?",o:["Amy Winehouse","Adele","Duffy","Paloma Faith"],a:1,d:1},
    {q:"Vem sjunger 'Someone Like You'?",o:["Adele","Amy Winehouse","Duffy","Ellie Goulding"],a:0,d:1},
    {q:"Vilket år vann ABBA Eurovision med 'Waterloo'?",o:["1972","1974","1976","1978"],a:1,d:1},
    {q:"Vem sjunger 'Toxic'?",o:["Christina Aguilera","Britney Spears","Kylie Minogue","Pink"],a:1,d:1},
    {q:"Vilket land vann Eurovision 2023?",o:["Sverige","Finland","Ukraina","Italien"],a:0,d:1},
    {q:"Vem sjunger 'Chandelier'?",o:["Lorde","Lana Del Rey","Sia","Ellie Goulding"],a:2,d:1},
    {q:"Vilket band sjöng 'Mr. Brightside'?",o:["The Strokes","The Killers","Interpol","Franz Ferdinand"],a:1,d:1},
    {q:"Vem sjunger 'Poker Face'?",o:["Katy Perry","Rihanna","Lady Gaga","Pink"],a:2,d:1},
    {q:"Vilket år kom PSY's 'Gangnam Style'?",o:["2010","2012","2014","2016"],a:1,d:1},
    {q:"Vad heter Madonnas debutalbum?",o:["True Blue","Like a Virgin","Madonna","Immaculate Collection"],a:2,d:2},
    {q:"Vad heter Beyoncés soloalbum från 2003?",o:["Lemonade","4","Dangerously in Love","B'Day"],a:2,d:2},
    {q:"Vem sjunger 'Born This Way'?",o:["Katy Perry","Rihanna","Lady Gaga","Kesha"],a:2,d:2},
    {q:"Vilket år vann Loreen Eurovision första gången?",o:["2010","2012","2014","2016"],a:1,d:2},
    {q:"Vilket år kom Rihannas 'Umbrella'?",o:["2005","2007","2009","2011"],a:1,d:2},
    {q:"Vilket år grundades Spice Girls?",o:["1992","1994","1996","1998"],a:1,d:2},
    {q:"Vilket år kom Adeles '21'?",o:["2009","2011","2013","2015"],a:1,d:2},
    {q:"Vad heter Lady Gagas riktiga namn?",o:["Stefani Germanotta","Stefani Joanne Germanotta","Joanne Germanotta","Stefani Angelina"],a:1,d:2},
    {q:"Vilket land vann Eurovision 2024?",o:["Sverige","Schweiz","Spanien","Kroatien"],a:1,d:2},
    {q:"Vem sjunger 'Flowers'?",o:["Dua Lipa","Miley Cyrus","Selena Gomez","Lizzo"],a:1,d:2},
    {q:"På vilket skivbolag debuterade ABBA?",o:["Polar","Epic","CBS","Atlantic"],a:0,d:3},
    {q:"Vem producerade Michael Jacksons 'Thriller'?",o:["Berry Gordy","Quincy Jones","Teddy Riley","Babyface"],a:1,d:3},
    {q:"Vad heter ABBA-medlemmens Agnethas efternamn?",o:["Fältskog","Lindqvist","Andersson","Björk"],a:0,d:3},
    {q:"Vilket år bildades Queen?",o:["1968","1970","1972","1974"],a:1,d:3},
    {q:"Vem producerade Madonnas 'Like a Prayer'?",o:["Nile Rodgers","Patrick Leonard","Jellybean Benitez","Steve Bray"],a:1,d:3},
    {q:"Vad heter Beyoncés album från 2016?",o:["Renaissance","4","Lemonade","Self-titled"],a:2,d:3},
    {q:"Vilket skivbolag gav ut Lady Gagas debutalbum?",o:["Universal","Interscope","Atlantic","Columbia"],a:1,d:3},
    {q:"Vilket år kom Kylie Minogues 'Fever'?",o:["1999","2001","2003","2005"],a:1,d:3},
  ],

  "🎸 Rock & Metal": [
    {q:"Vilket band sjöng 'Smells Like Teen Spirit'?",o:["Pearl Jam","Soundgarden","Nirvana","Alice in Chains"],a:2,d:1},
    {q:"Vilket band spelade 'Enter Sandman'?",o:["Slayer","Metallica","Megadeth","Anthrax"],a:1,d:1},
    {q:"Vem kallas 'The Boss' inom rock?",o:["Jon Bon Jovi","Bruce Springsteen","Mick Jagger","Tom Petty"],a:1,d:1},
    {q:"Vilket band sjöng 'Back in Black'?",o:["AC/DC","Aerosmith","Kiss","Motörhead"],a:0,d:1},
    {q:"Vem är sångare i Iron Maiden?",o:["Rob Halford","Ozzy Osbourne","Bruce Dickinson","Dio"],a:2,d:1},
    {q:"Vilket band sjöng 'Welcome to the Jungle'?",o:["Mötley Crüe","Def Leppard","Guns N' Roses","Poison"],a:2,d:1},
    {q:"Vilket band sjöng 'Paranoid'?",o:["Deep Purple","Black Sabbath","Judas Priest","Ozzy Osbourne"],a:1,d:1},
    {q:"Vilket band sjöng 'Seven Nation Army'?",o:["The Strokes","The White Stripes","The Black Keys","The Raconteurs"],a:1,d:1},
    {q:"Vem sjunger i Foo Fighters?",o:["Eddie Vedder","Chris Cornell","Dave Grohl","Scott Weiland"],a:2,d:1},
    {q:"Vilket band sjöng 'Come As You Are'?",o:["Pearl Jam","Soundgarden","Nirvana","Alice in Chains"],a:2,d:1},
    {q:"Vilket band sjöng 'Livin' on a Prayer'?",o:["Aerosmith","Bon Jovi","Journey","Def Leppard"],a:1,d:1},
    {q:"Vilket band sjöng 'Thunderstruck'?",o:["Aerosmith","Kiss","AC/DC","Motörhead"],a:2,d:1},
    {q:"Vilket band sjöng 'Yellow'?",o:["Travis","Keane","Coldplay","Snow Patrol"],a:2,d:1},
    {q:"Vem sjunger i Guns N' Roses?",o:["Sebastian Bach","Steven Tyler","Axl Rose","David Coverdale"],a:2,d:1},
    {q:"Vilket band sjöng 'Whole Lotta Love'?",o:["Deep Purple","Black Sabbath","Led Zeppelin","Free"],a:2,d:1},
    {q:"Vilket år kom Metallicas svarta album?",o:["1989","1991","1993","1995"],a:1,d:2},
    {q:"Vad heter Nirvanas debutalbum?",o:["Nevermind","In Utero","Bleach","Incesticide"],a:2,d:2},
    {q:"Vilket år kom The White Stripes 'Elephant'?",o:["2001","2003","2005","2007"],a:1,d:2},
    {q:"Vilket band sjöng 'Numb'?",o:["Korn","Slipknot","Linkin Park","Papa Roach"],a:2,d:2},
    {q:"Vilket år kom Radioheads 'OK Computer'?",o:["1995","1997","1999","2001"],a:1,d:2},
    {q:"Vilket band sjöng 'Under the Bridge'?",o:["Pearl Jam","Red Hot Chili Peppers","Soundgarden","Stone Temple Pilots"],a:1,d:2},
    {q:"Vilket band sjöng 'Knights of Cydonia'?",o:["Radiohead","Muse","Placebo","Biffy Clyro"],a:1,d:2},
    {q:"Vilket år kom Arctic Monkeys debutalbum?",o:["2004","2006","2008","2010"],a:1,d:2},
    {q:"Vem spelade bas i The Beatles?",o:["John Lennon","George Harrison","Paul McCartney","Ringo Starr"],a:2,d:2},
    {q:"På vilket skivbolag debuterade Nirvana?",o:["DGC Records","Sub Pop","Geffen","Epitaph"],a:1,d:3},
    {q:"Vem producerade Nevermind?",o:["Steve Albini","Rick Rubin","Butch Vig","Jack Endino"],a:2,d:3},
    {q:"Vad heter Iron Maidens maskot?",o:["Vic","Eddie","Spike","Axe"],a:1,d:3},
    {q:"Vilket år kom Pixies 'Doolittle'?",o:["1987","1989","1991","1993"],a:1,d:3},
    {q:"Vilket band sjöng 'Where Is My Mind'?",o:["The Breeders","Belly","Pixies","Throwing Muses"],a:2,d:3},
    {q:"Vilket år kom Sonic Youths 'Daydream Nation'?",o:["1986","1988","1990","1992"],a:1,d:3},
  ],

  "🔥 Heavy Metal": [
    {q:"Vilket band spelade 'Enter Sandman'?",o:["Slayer","Metallica","Megadeth","Anthrax"],a:1,d:1},
    {q:"Vem är sångare i Iron Maiden?",o:["Rob Halford","Ozzy Osbourne","Bruce Dickinson","Dio"],a:2,d:1},
    {q:"Vilket band sjöng 'Paranoid'?",o:["Deep Purple","Black Sabbath","Judas Priest","Ozzy Osbourne"],a:1,d:1},
    {q:"Vilket band sjöng 'Welcome to the Jungle'?",o:["Mötley Crüe","Def Leppard","Guns N' Roses","Poison"],a:2,d:1},
    {q:"Vem är sångare i Judas Priest?",o:["Ozzy Osbourne","Rob Halford","Bruce Dickinson","Ronnie James Dio"],a:1,d:1},
    {q:"Vilket band sjöng 'Ace of Spades'?",o:["Black Sabbath","Deep Purple","Motörhead","Venom"],a:2,d:1},
    {q:"Vilket band sjöng 'Master of Puppets'?",o:["Slayer","Megadeth","Metallica","Anthrax"],a:2,d:1},
    {q:"Vilket band sjöng 'War Pigs'?",o:["Deep Purple","Black Sabbath","Judas Priest","Led Zeppelin"],a:1,d:1},
    {q:"Vilket band sjöng 'Raining Blood'?",o:["Metallica","Megadeth","Slayer","Anthrax"],a:2,d:1},
    {q:"Vilket band sjöng 'Holy Diver'?",o:["Black Sabbath","Rainbow","Dio","Ozzy Osbourne"],a:2,d:1},
    {q:"Vilket band sjöng 'Fear of the Dark'?",o:["Judas Priest","Saxon","Iron Maiden","Motörhead"],a:2,d:1},
    {q:"Vilket band sjöng 'Breaking the Law'?",o:["Black Sabbath","Iron Maiden","Judas Priest","Motörhead"],a:2,d:1},
    {q:"Vilket band sjöng 'The Trooper'?",o:["Judas Priest","Saxon","Iron Maiden","Motörhead"],a:2,d:1},
    {q:"Vilket band sjöng 'Symphony of Destruction'?",o:["Metallica","Megadeth","Slayer","Anthrax"],a:1,d:1},
    {q:"Vilket band sjöng 'Cowboys from Hell'?",o:["Slayer","Pantera","Sepultura","Machine Head"],a:1,d:1},
    {q:"Vilket år kom Pantera 'Cowboys from Hell'?",o:["1988","1990","1992","1994"],a:1,d:2},
    {q:"Vilket band sjöng 'Down with the Sickness'?",o:["Slipknot","Disturbed","Drowning Pool","Papa Roach"],a:1,d:2},
    {q:"Vilket år kom Slipknots debutalbum?",o:["1997","1999","2001","2003"],a:1,d:2},
    {q:"Vilket band sjöng 'Chop Suey!'?",o:["Slipknot","Korn","System of a Down","Linkin Park"],a:2,d:2},
    {q:"Vilket band sjöng 'B.Y.O.B.'?",o:["Slipknot","Korn","System of a Down","Linkin Park"],a:2,d:2},
    {q:"Vilket år kom Iron Maidens 'Number of the Beast'?",o:["1980","1982","1984","1986"],a:1,d:2},
    {q:"Vilket band sjöng 'Toxicity'?",o:["Slipknot","Korn","System of a Down","Linkin Park"],a:2,d:2},
    {q:"Vilket band sjöng 'Freak on a Leash'?",o:["Slipknot","Mudvayne","Korn","Deftones"],a:2,d:2},
    {q:"Vilket år kom Metallicas 'Ride the Lightning'?",o:["1982","1984","1986","1988"],a:1,d:2},
    {q:"Vad heter gitarristen i Metallica (ej James Hetfield)?",o:["Dave Mustaine","Kirk Hammett","Phil Demmel","Marty Friedman"],a:1,d:3},
    {q:"Vilket år kom Slayers 'Reign in Blood'?",o:["1984","1986","1988","1990"],a:1,d:3},
    {q:"Vad heter basgitarristen i Motörhead?",o:["Lemmy Kilmister","Phil Campbell","Mikkey Dee","Fast Eddie Clarke"],a:0,d:3},
    {q:"Vilket år dog Dimebag Darrell?",o:["2002","2004","2006","2008"],a:1,d:3},
    {q:"Vad heter Tools sångare?",o:["Maynard James Keenan","Phil Anselmo","Corey Taylor","Chino Moreno"],a:0,d:3},
    {q:"Vilket år kom Black Sabbaths debutalbum?",o:["1968","1970","1972","1974"],a:1,d:3},
    {q:"Vem grundade Megadeth?",o:["Lars Ulrich","Kirk Hammett","Dave Mustaine","Jason Newsted"],a:2,d:3},
    {q:"Vilket skivbolag gav ut Metallicas tidiga album?",o:["Columbia","Megaforce/Elektra","Atlantic","Roadrunner"],a:1,d:3},
  ],

  "🇸🇪 Svensk musik": [
    {q:"Vilket band sjöng 'The Sign'?",o:["Roxette","ABBA","Ace of Base","Robyn"],a:2,d:1},
    {q:"Vad heter Aviciis mest kända låt?",o:["Fade into Darkness","Levels","Wake Me Up","Hey Brother"],a:1,d:1},
    {q:"Vilket band sjöng 'It Must Have Been Love'?",o:["ABBA","Ace of Base","Roxette","Carola"],a:2,d:1},
    {q:"Var är Håkan Hellström uppvuxen?",o:["Stockholm","Malmö","Göteborg","Uppsala"],a:2,d:1},
    {q:"Vem sjunger 'Euphoria' (Eurovision 2012)?",o:["Carola","Charlotte Perrelli","Loreen","Petra Mede"],a:2,d:1},
    {q:"Vilket band sjöng 'Lovefool'?",o:["Roxette","The Cardigans","Ace of Base","Sahara Hotnights"],a:1,d:1},
    {q:"Vad heter Aviciis riktiga namn?",o:["Tim Bergling","Tim Svensson","Tim Lindqvist","Tim Berg"],a:0,d:1},
    {q:"Vilket band är Per Gessle med i?",o:["ABBA","Ace of Base","Roxette","The Hellacopters"],a:2,d:1},
    {q:"Vem sjunger 'Dancing on My Own'?",o:["Zara Larsson","Robyn","Tove Lo","MØ"],a:1,d:1},
    {q:"Vilket band sjöng 'Hate to Say I Told You So'?",o:["The Hellacopters","The Hives","Refused","Soundtrack of Our Lives"],a:1,d:1},
    {q:"Vilket band sjöng 'Erase/Rewind'?",o:["Roxette","Robyn","The Cardigans","Ace of Base"],a:2,d:1},
    {q:"Vem sjunger 'Tattoo' (Eurovision 2023)?",o:["Cornelia Jakobs","Loreen","Linda Bengtzing","Carola"],a:1,d:1},
    {q:"Vad heter Max Martins riktiga namn?",o:["Martin Sandberg","Max Sandberg","Martin Carlsson","Max Karlsson"],a:0,d:2},
    {q:"Vilket år grundades Swedish House Mafia?",o:["2002","2004","2006","2008"],a:2,d:2},
    {q:"Vem vann Melodifestivalen 2012?",o:["Loreen","Eric Saade","Danny Saucedo","Sonja Aldén"],a:0,d:2},
    {q:"Vad heter Swedish House Mafias tre medlemmar?",o:["Axwell/Steve Angello/Sebastian Ingrosso","Axwell/Avicii/Alesso","Avicii/Alesso/Ingrosso","Axwell/Tiesto/Ingrosso"],a:0,d:2},
    {q:"Vilken stad kommer The Hives ifrån?",o:["Stockholm","Göteborg","Fagersta","Örebro"],a:2,d:2},
    {q:"Vilket år bildades Gyllene Tider?",o:["1974","1976","1978","1980"],a:1,d:2},
    {q:"Vilket år debuterade Robyn?",o:["1993","1995","1997","1999"],a:1,d:2},
    {q:"Vilket år kom Aviciis 'True'?",o:["2011","2013","2015","2017"],a:1,d:2},
    {q:"Vem sjunger 'Habits (Stay High)'?",o:["Zara Larsson","Robyn","Tove Lo","MØ"],a:2,d:2},
    {q:"Vilket år vann Loreen Eurovision andra gången?",o:["2021","2022","2023","2024"],a:2,d:2},
    {q:"Vilket år kom Robyn's 'Body Talk'?",o:["2008","2010","2012","2014"],a:1,d:2},
    {q:"Vad heter Tove Lo's riktiga namn?",o:["Tova Magnusson-Forssa","Tova Nilsson","Tova Lindqvist","Tova Andersson"],a:0,d:3},
    {q:"På vilket skivbolag debuterade ABBA?",o:["Polar","Epic","CBS","Atlantic"],a:0,d:3},
    {q:"Vad heter The Cardigans sångerskas fullständiga namn?",o:["Nina Persson","Nina Carlsson","Nina Lindqvist","Nina Svensson"],a:0,d:3},
    {q:"Vilket år bildades Roxette?",o:["1982","1984","1986","1988"],a:1,d:3},
    {q:"Vem var sångare i Imperiet?",o:["Håkan Hellström","Joakim Thåström","Thomas Eriksson","Ulf Lundell"],a:1,d:3},
    {q:"Vilket år grundades Ace of Base?",o:["1987","1989","1991","1993"],a:1,d:3},
    {q:"Vilket år kom The Hives 'Veni Vidi Vicious'?",o:["1998","2000","2002","2004"],a:1,d:3},
    {q:"Vilket år kom Gyllene Tiiders 'Puls'?",o:["1980","1982","1984","1986"],a:1,d:3},
    {q:"Vem spelade trummor som session-musiker på ABBA-skivor?",o:["Ola Brunkert","Roger Palm","Christer Eklund","Malando Gassama"],a:0,d:3},
  ],

  "🎬 Movie Quiz": [
    {q:"Vem spelar Iron Man i MCU?",o:["Chris Evans","Robert Downey Jr.","Chris Hemsworth","Mark Ruffalo"],a:1,d:1},
    {q:"Vilket år kom Titanic?",o:["1995","1996","1997","1998"],a:2,d:1},
    {q:"Vem regisserade Jurassic Park?",o:["James Cameron","Steven Spielberg","George Lucas","Ridley Scott"],a:1,d:1},
    {q:"Vilket år kom första Star Wars-filmen?",o:["1975","1977","1979","1981"],a:1,d:1},
    {q:"Vem spelar Jack i Titanic?",o:["Brad Pitt","Johnny Depp","Leonardo DiCaprio","Matt Damon"],a:2,d:1},
    {q:"Vem spelar Forrest Gump?",o:["Tom Cruise","Tom Hanks","Tom Selleck","Tom Hardy"],a:1,d:1},
    {q:"Vad heter Batmans alter ego?",o:["Clark Kent","Peter Parker","Bruce Wayne","Tony Stark"],a:2,d:1},
    {q:"Vem spelar Neo i Matrix?",o:["Brad Pitt","Keanu Reeves","Tom Cruise","Will Smith"],a:1,d:1},
    {q:"Vilket år kom Inception?",o:["2008","2010","2012","2014"],a:1,d:1},
    {q:"Vem spelar Thor i MCU?",o:["Chris Evans","Robert Downey Jr.","Chris Hemsworth","Mark Ruffalo"],a:2,d:1},
    {q:"Vilket år kom The Dark Knight?",o:["2006","2008","2010","2012"],a:1,d:1},
    {q:"Vem spelar Joker i 'Joker' (2019)?",o:["Heath Ledger","Jared Leto","Joaquin Phoenix","Jack Nicholson"],a:2,d:1},
    {q:"Vilket år kom Avengers: Endgame?",o:["2017","2019","2021","2023"],a:1,d:1},
    {q:"Vem regisserade Goodfellas?",o:["Francis Ford Coppola","Brian De Palma","Martin Scorsese","Quentin Tarantino"],a:2,d:1},
    {q:"Vem spelar Gandalf i Sagan om Ringen?",o:["Ian McKellen","Patrick Stewart","Anthony Hopkins","Christopher Lee"],a:0,d:1},
    {q:"Vem regisserade The Dark Knight?",o:["Tim Burton","Joel Schumacher","Christopher Nolan","Zack Snyder"],a:2,d:2},
    {q:"Vem regisserade Pulp Fiction?",o:["Martin Scorsese","Quentin Tarantino","Coen Brothers","David Fincher"],a:1,d:2},
    {q:"Vilket år kom Fight Club?",o:["1997","1999","2001","2003"],a:1,d:2},
    {q:"Vem regisserade Fight Club?",o:["Quentin Tarantino","David Fincher","Christopher Nolan","Darren Aronofsky"],a:1,d:2},
    {q:"Vilket år kom The Shawshank Redemption?",o:["1992","1994","1996","1998"],a:1,d:2},
    {q:"Vem spelar Don Corleone i The Godfather?",o:["Al Pacino","Robert De Niro","Marlon Brando","Jack Nicholson"],a:2,d:2},
    {q:"Vilket år kom No Country for Old Men?",o:["2005","2007","2009","2011"],a:1,d:2},
    {q:"Vilket år kom The Social Network?",o:["2008","2010","2012","2014"],a:1,d:2},
    {q:"Vilket år vann Parasite Oscar för bästa film?",o:["2018","2019","2020","2021"],a:2,d:2},
    {q:"Vem komponerade musiken till Star Wars?",o:["Hans Zimmer","Danny Elfman","John Williams","Ennio Morricone"],a:2,d:3},
    {q:"Vilket år kom Citizen Kane?",o:["1938","1941","1944","1947"],a:1,d:3},
    {q:"Vem regisserade 2001: A Space Odyssey?",o:["Steven Spielberg","Stanley Kubrick","Ridley Scott","Francis Ford Coppola"],a:1,d:3},
    {q:"Vem spelade Travis Bickle i Taxi Driver?",o:["Al Pacino","Jack Nicholson","Robert De Niro","Dustin Hoffman"],a:2,d:3},
    {q:"Vilket år kom Chinatown?",o:["1972","1974","1976","1978"],a:1,d:3},
    {q:"Vem regisserade Chinatown?",o:["Francis Ford Coppola","Roman Polanski","Martin Scorsese","Sidney Lumet"],a:1,d:3},
    {q:"Vem regisserade 'Days of Heaven'?",o:["Terrence Malick","Robert Altman","Hal Ashby","Bob Rafelson"],a:0,d:3},
    {q:"Vilket år kom Kubricks 'Barry Lyndon'?",o:["1973","1975","1977","1979"],a:1,d:3},
  ],

  "📺 TV-serier": [
    {q:"Vilket TV-program handlade om vänner i New York?",o:["Seinfeld","Friends","Frasier","Will & Grace"],a:1,d:1},
    {q:"Vem spelar Walter White i Breaking Bad?",o:["Bryan Cranston","Aaron Paul","Bob Odenkirk","Dean Norris"],a:0,d:1},
    {q:"Vilket år kom Game of Thrones?",o:["2009","2011","2013","2015"],a:1,d:1},
    {q:"Vem spelar Tony Soprano i The Sopranos?",o:["Joe Pesci","Robert De Niro","James Gandolfini","Al Pacino"],a:2,d:1},
    {q:"Vilket år kom Stranger Things?",o:["2014","2016","2018","2020"],a:1,d:1},
    {q:"Vem spelar Daenerys i Game of Thrones?",o:["Sophie Turner","Natalie Dormer","Emilia Clarke","Kit Harington"],a:2,d:1},
    {q:"Vem spelar Tommy Shelby i Peaky Blinders?",o:["Tom Hardy","Cillian Murphy","Idris Elba","James McAvoy"],a:1,d:1},
    {q:"Vilket år kom Squid Game?",o:["2019","2021","2022","2023"],a:1,d:1},
    {q:"Vilket land producerade Squid Game?",o:["Japan","Kina","Sydkorea","Thailand"],a:2,d:1},
    {q:"Vem spelar i Euphoria (huvudroll)?",o:["Billie Eilish","Zendaya","Olivia Rodrigo","Ariana Grande"],a:1,d:1},
    {q:"Vilket år kom Peaky Blinders?",o:["2011","2013","2015","2017"],a:1,d:1},
    {q:"Vem spelar Logan Roy i Succession?",o:["Brian Cox","Jeff Bridges","Anthony Hopkins","Gary Oldman"],a:0,d:1},
    {q:"Vilket år kom Breaking Bad?",o:["2006","2008","2010","2012"],a:1,d:2},
    {q:"Vilket år kom Succession?",o:["2016","2018","2020","2022"],a:1,d:2},
    {q:"Vilket år kom Better Call Saul?",o:["2013","2015","2017","2019"],a:1,d:2},
    {q:"Vilket år kom Ozark?",o:["2015","2017","2019","2021"],a:1,d:2},
    {q:"Vem spelar Marty Byrde i Ozark?",o:["Bryan Cranston","Jason Bateman","Kevin Spacey","Michael C. Hall"],a:1,d:2},
    {q:"Vilket år kom Twin Peaks?",o:["1988","1990","1992","1994"],a:1,d:2},
    {q:"Vilket år kom The Last of Us (HBO)?",o:["2021","2023","2024","2025"],a:1,d:2},
    {q:"Vilket år kom Lost?",o:["2002","2004","2006","2008"],a:1,d:2},
    {q:"Vilket år kom Six Feet Under?",o:["1999","2001","2003","2005"],a:1,d:2},
    {q:"Vem skapade Twin Peaks?",o:["Steven Spielberg","David Lynch & Mark Frost","Ridley Scott","Jim Jarmusch"],a:1,d:2},
    {q:"Vem skapade Breaking Bad?",o:["David Chase","David Simon","Vince Gilligan","Matthew Weiner"],a:2,d:3},
    {q:"Vem skapade The Wire?",o:["David Chase","David Simon","Vince Gilligan","Ed Burns"],a:1,d:3},
    {q:"Vem skapade The Sopranos?",o:["David Chase","David Simon","Vince Gilligan","Matthew Weiner"],a:0,d:3},
    {q:"Vilket år kom Mr. Robot?",o:["2013","2015","2017","2019"],a:1,d:3},
    {q:"Vem spelar Elliot i Mr. Robot?",o:["Christian Slater","Rami Malek","B.D. Wong","Martin Wallström"],a:1,d:3},
    {q:"Vem skapade Mad Men?",o:["David Chase","David Simon","Vince Gilligan","Matthew Weiner"],a:3,d:3},
    {q:"Vem skapade Deadwood?",o:["David Chase","David Milch","Vince Gilligan","Alan Ball"],a:1,d:3},
    {q:"Vilket år kom Battlestar Galactica (nya versionen)?",o:["2001","2003","2005","2007"],a:1,d:3},
    {q:"Vem skapade Succession?",o:["David Chase","Jesse Armstrong","Vince Gilligan","Matthew Weiner"],a:1,d:3},
    {q:"Vilket år kom Treme (HBO)?",o:["2008","2010","2012","2014"],a:1,d:3},
  ],

  "🏰 Disney Klassiker": [
    {q:"Vad heter lejonungen i Lejonkungen?",o:["Simba","Nala","Mufasa","Pumba"],a:0,d:1},
    {q:"Vad heter fiskens pappa i Hitta Nemo?",o:["Martin","Marlin","Marcel","Marco"],a:1,d:1},
    {q:"Vad heter cowboyen i Toy Story?",o:["Buzz","Woody","Rex","Hamm"],a:1,d:1},
    {q:"Vad heter prinsessan i Törnrosa?",o:["Aurora","Ariel","Belle","Jasmine"],a:0,d:1},
    {q:"Vilket djur är Dumbo?",o:["Häst","Giraff","Elefant","Noshörning"],a:2,d:1},
    {q:"Vilket år kom Lejonkungen?",o:["1990","1992","1994","1996"],a:2,d:1},
    {q:"Vad heter rymdkommandot i Toy Story?",o:["Woody","Buzz Lightyear","Rex","Hamm"],a:1,d:1},
    {q:"Vad heter musen i Ratatouille?",o:["Emile","Gusteau","Remy","Anton"],a:2,d:1},
    {q:"Vad heter Ariels bästa fiskekompis i Sjöjungfrun?",o:["Sebastian","Flounder","Scuttle","Louis"],a:1,d:1},
    {q:"Vad heter häxan i Törnrosa?",o:["Ursula","Maleficent","Den onda drottningen","Mother Gothel"],a:1,d:1},
    {q:"Vad heter Timons kompis i Lejonkungen?",o:["Simba","Nala","Pumba","Rafiki"],a:2,d:1},
    {q:"Vilket år kom Den lilla sjöjungfrun?",o:["1987","1989","1991","1993"],a:1,d:1},
    {q:"Vilket år kom Toy Story?",o:["1993","1995","1997","1999"],a:1,d:2},
    {q:"Vilket år kom Hitta Nemo?",o:["2001","2003","2005","2007"],a:1,d:2},
    {q:"Vem röstade Woody i Toy Story originalet?",o:["Tom Hanks","Tim Allen","Billy Crystal","John Goodman"],a:0,d:2},
    {q:"Vilket år kom Aladdin?",o:["1990","1992","1994","1996"],a:1,d:2},
    {q:"Vilket år kom Beauty and the Beast?",o:["1989","1991","1993","1995"],a:1,d:2},
    {q:"Vem röstade Simba (vuxen) i Lejonkungen?",o:["Will Smith","Matthew McConaughey","Matthew Broderick","James Earl Jones"],a:2,d:2},
    {q:"Vem röstade Mufasa i Lejonkungen?",o:["Morgan Freeman","James Earl Jones","Samuel L. Jackson","Denzel Washington"],a:1,d:2},
    {q:"Vilket år kom 101 Dalmatiner?",o:["1959","1961","1963","1965"],a:1,d:2},
    {q:"Vilket år kom Djungelboken (Disney)?",o:["1964","1966","1968","1970"],a:1,d:2},
    {q:"Vad heter antagonisten i 101 Dalmatiner?",o:["Maleficent","Cruella de Vil","Ursula","Lady Tremaine"],a:1,d:2},
    {q:"Vilket år kom Disneys första film Snövit?",o:["1934","1937","1940","1943"],a:1,d:3},
    {q:"Vem röstade Scar i Lejonkungen originalet?",o:["Tim Curry","Jeremy Irons","Ian McKellen","Alan Rickman"],a:1,d:3},
    {q:"Vem komponerade musiken till Lejonkungen?",o:["Alan Menken","Howard Ashman","Hans Zimmer","Elton John"],a:2,d:3},
    {q:"Vem röstade Genie i Aladdin originalet?",o:["Jim Carrey","Steve Martin","Robin Williams","Billy Crystal"],a:2,d:3},
    {q:"Vilket år kom Fantasia?",o:["1938","1940","1942","1944"],a:1,d:3},
    {q:"Vem röstade Ursula i Den lilla sjöjungfrun?",o:["Cloris Leachman","Bette Midler","Pat Carroll","Rosie O'Donnell"],a:2,d:3},
    {q:"Vilket år kom Disneys 'Sleeping Beauty'?",o:["1957","1959","1961","1963"],a:1,d:3},
    {q:"Vem komponerade musiken i Den lilla sjöjungfrun?",o:["Elton John","Alan Menken","Phil Collins","Randy Newman"],a:1,d:3},
  ],

  "❄️ Frost & Moderna Disney": [
    {q:"Vad heter prinsessorna i Frost?",o:["Anna och Bella","Elsa och Anna","Elsa och Sofia","Anna och Kristina"],a:1,d:1},
    {q:"Vilket år kom Frost?",o:["2011","2013","2015","2017"],a:1,d:1},
    {q:"Vad heter rendjuret i Frost?",o:["Olaf","Kristoff","Sven","Hans"],a:2,d:1},
    {q:"Vad heter snögubben i Frost?",o:["Olaf","Sven","Kristoff","Hans"],a:0,d:1},
    {q:"Vilket år kom Frost 2?",o:["2017","2019","2021","2023"],a:1,d:1},
    {q:"Vad heter antagonisten i Frost?",o:["Kristoff","Hans","Duke of Weselton","Marshmallow"],a:1,d:1},
    {q:"Vilket år kom Vaiana/Moana?",o:["2014","2016","2018","2020"],a:1,d:1},
    {q:"Vad heter halvguden i Vaiana?",o:["Tamatoa","Maui","Hei Hei","Te Ka"],a:1,d:1},
    {q:"Vilket år kom Encanto?",o:["2019","2021","2022","2023"],a:1,d:1},
    {q:"Vad heter huvudpersonen i Encanto?",o:["Luisa","Isabela","Mirabel","Dolores"],a:2,d:1},
    {q:"Vilket år kom Zootopia?",o:["2014","2016","2018","2020"],a:1,d:1},
    {q:"Vilket år kom Coco (Pixar)?",o:["2015","2017","2019","2021"],a:1,d:1},
    {q:"Vem sjunger 'Let It Go' i Frost?",o:["Idina Menzel","Kristen Bell","Anna Kendrick","Lea Michele"],a:0,d:2},
    {q:"Vilket år kom Big Hero 6?",o:["2012","2014","2016","2018"],a:1,d:2},
    {q:"Vad heter roboten i Big Hero 6?",o:["Baymax","Hiro","Tadashi","Go Go"],a:0,d:2},
    {q:"Vad heter Elsas och Annas mamma?",o:["Elsa","Iduna","Gerda","Ingrid"],a:1,d:2},
    {q:"Vilket år kom Inside Out?",o:["2013","2015","2017","2019"],a:1,d:2},
    {q:"Vilket år kom Inside Out 2?",o:["2022","2023","2024","2025"],a:2,d:2},
    {q:"Vad heter det nya känslot i Inside Out 2?",o:["Stress","Anxiety","Embarrassment","Envy"],a:1,d:2},
    {q:"Vilket år kom Raya and the Last Dragon?",o:["2019","2021","2022","2023"],a:1,d:2},
    {q:"Vad heter Moanas hane i Vaiana?",o:["Tamatoa","Maui","Hei Hei","Te Fiti"],a:2,d:2},
    {q:"Vilket år kom Turning Red (Pixar)?",o:["2020","2022","2023","2024"],a:1,d:2},
    {q:"Vem regisserade Frost?",o:["John Lasseter","Pete Docter","Chris Buck & Jennifer Lee","Andrew Stanton"],a:2,d:3},
    {q:"Vad heter byn i Encanto?",o:["Casita","Colombia","La Familia","Madrigal"],a:0,d:3},
    {q:"Vem sjunger 'We Don't Talk About Bruno'?",o:["Mirabel","Dolores","Camilo","Flera karaktärer"],a:3,d:3},
    {q:"Vilket år kom Pixars 'Soul'?",o:["2018","2020","2022","2024"],a:1,d:3},
    {q:"Vilket år kom Lightyear (Pixar)?",o:["2020","2022","2023","2024"],a:1,d:3},
    {q:"Vad heter hästen i Tangled/Trassel?",o:["Maximus","Samson","Angus","Achilles"],a:0,d:3},
    {q:"Vilket år kom Pixars 'Luca'?",o:["2019","2021","2022","2023"],a:1,d:3},
    {q:"Vem sjunger 'Surface Pressure' i Encanto?",o:["Luisa","Mirabel","Isabela","Dolores"],a:0,d:3},
  ],

  "🎠 Barnfilmer & Ungdomsfilmer": [
    {q:"Vem spelar Harry Potter?",o:["Rupert Grint","Daniel Radcliffe","Tom Felton","Matthew Lewis"],a:1,d:1},
    {q:"Vilket år kom första Harry Potter-filmen?",o:["1999","2001","2003","2005"],a:1,d:1},
    {q:"Vad heter Hagrids hund i Harry Potter?",o:["Fang","Fluffy","Buckbeak","Nox"],a:0,d:1},
    {q:"Vilket år kom Shrek?",o:["1999","2001","2003","2005"],a:1,d:1},
    {q:"Vad heter åsnan i Shrek?",o:["Donkey","Burro","Mule","Percy"],a:0,d:1},
    {q:"Vilket år kom Narnia: Häxan och lejonet?",o:["2003","2005","2007","2009"],a:1,d:1},
    {q:"Vem spelar Katniss i Hunger Games?",o:["Emma Stone","Jennifer Lawrence","Shailene Woodley","Kristen Stewart"],a:1,d:1},
    {q:"Vem spelar Edward i Twilight?",o:["Taylor Lautner","Kellan Lutz","Robert Pattinson","Jackson Rathbone"],a:2,d:1},
    {q:"Vem spelar Bilbo i Hobbit?",o:["Ian McKellen","Martin Freeman","Benedict Cumberbatch","Richard Armitage"],a:1,d:1},
    {q:"Vilket år kom E.T.?",o:["1980","1982","1984","1986"],a:1,d:1},
    {q:"Vilket år kom Twilight?",o:["2006","2008","2010","2012"],a:1,d:1},
    {q:"Vilket år kom Hobbit (del 1)?",o:["2010","2012","2014","2016"],a:1,d:1},
    {q:"Vilket år kom Sagan om Ringen (del 1)?",o:["1999","2001","2003","2005"],a:1,d:2},
    {q:"Vem spelar Frodo i Sagan om Ringen?",o:["Sean Bean","Orlando Bloom","Elijah Wood","Dominic Monaghan"],a:2,d:2},
    {q:"Vem spelar Albus Dumbledore i Harry Potter (ursprungligen)?",o:["Richard Harris","Michael Gambon","Ian McKellen","Patrick Stewart"],a:0,d:2},
    {q:"Vilket år kom Home Alone?",o:["1988","1990","1992","1994"],a:1,d:2},
    {q:"Vem spelar Kevin i Home Alone?",o:["Macaulay Culkin","Haley Joel Osment","Joseph Gordon-Levitt","Ryan Gosling"],a:0,d:2},
    {q:"Vilket år kom Matilda (filmen)?",o:["1992","1994","1996","1998"],a:2,d:2},
    {q:"Vilket år kom Jumanji?",o:["1993","1995","1997","1999"],a:1,d:2},
    {q:"Vem spelar i Jumanji (1995)?",o:["Tom Hanks","Robin Williams","Jim Carrey","Steve Martin"],a:1,d:2},
    {q:"Vilket år kom Divergent?",o:["2012","2014","2016","2018"],a:1,d:2},
    {q:"Vilket år kom The Maze Runner?",o:["2012","2014","2016","2018"],a:1,d:2},
    {q:"Vem skriver böckerna om Harry Potter?",o:["Roald Dahl","J.R.R. Tolkien","J.K. Rowling","C.S. Lewis"],a:2,d:3},
    {q:"Vilket år kom Goonies?",o:["1983","1985","1987","1989"],a:1,d:3},
    {q:"Vilket år kom Stand by Me?",o:["1984","1986","1988","1990"],a:1,d:3},
    {q:"Vilket år kom Beetlejuice?",o:["1986","1988","1990","1992"],a:1,d:3},
    {q:"Vem regisserade Beetlejuice?",o:["John Hughes","Tim Burton","Joe Dante","Chris Columbus"],a:1,d:3},
    {q:"Vem regisserade E.T.?",o:["George Lucas","Steven Spielberg","Robert Zemeckis","Ron Howard"],a:1,d:3},
    {q:"Vilket år kom Karate Kid (originalet)?",o:["1982","1984","1986","1988"],a:1,d:3},
    {q:"Vad heter häxan i Roald Dahls Häxorna (1990)?",o:["Anjelica Huston","Meryl Streep","Glenn Close","Sigourney Weaver"],a:0,d:3},
  ],

  "⚽ Fotboll": [
    {q:"Vilket land vann fotbolls-VM 2022?",o:["Brasilien","Frankrike","Argentina","Portugal"],a:2,d:1},
    {q:"Vilket land vann fotbolls-VM 2018?",o:["Tyskland","Brasilien","Frankrike","Argentina"],a:2,d:1},
    {q:"Vem vann Ballon d'Or flest gånger?",o:["Cristiano Ronaldo","Lionel Messi","Ronaldinho","Zidane"],a:1,d:1},
    {q:"Vilket land är Zlatan Ibrahimovic fraan?",o:["Danmark","Finland","Norge","Sverige"],a:3,d:1},
    {q:"Vilket lag spelar hemma pa Camp Nou?",o:["Real Madrid","Atletico Madrid","FC Barcelona","Valencia"],a:2,d:1},
    {q:"Vilket lag vann Champions League 2023?",o:["Real Madrid","Manchester City","Bayern Munchen","PSG"],a:1,d:1},
    {q:"Vilket land vann fotbolls-VM 2014?",o:["Brasilien","Argentina","Frankrike","Tyskland"],a:3,d:1},
    {q:"Vilket land har vunnit flest VM-guld i fotboll?",o:["Argentina","Tyskland","Italien","Brasilien"],a:3,d:1},
    {q:"Vilket lag spelar hemma pa Old Trafford?",o:["Arsenal","Liverpool","Manchester United","Chelsea"],a:2,d:1},
    {q:"Vem vann Ballon d'Or 2022?",o:["Erling Haaland","Kylian Mbappe","Karim Benzema","Vinicius Jr."],a:2,d:1},
    {q:"Vilket land vann EM i fotboll 2021?",o:["Frankrike","England","Portugal","Italien"],a:3,d:1},
    {q:"Vad heter Zlatans moderklubb?",o:["Malmo FF","IFK Goteborg","AIK","Djurgarden"],a:0,d:1},
    {q:"Vilket ar vann Sverige VM-brons i fotboll?",o:["1950","1958","1966","1974"],a:1,d:2},
    {q:"Vilket ar grundades Premier League?",o:["1988","1990","1992","1994"],a:2,d:2},
    {q:"Vem ar historiens mestmalsgörare i Champions League?",o:["Lionel Messi","Raul","Cristiano Ronaldo","Karim Benzema"],a:2,d:2},
    {q:"Vilket ar introducerades VAR i fotbolls-VM?",o:["2014","2016","2018","2020"],a:2,d:2},
    {q:"Vilket land vann damernas VM 2023?",o:["USA","Australien","England","Spanien"],a:3,d:2},
    {q:"Hur manga VM har Brasilien vunnit?",o:["3","4","5","6"],a:2,d:2},
    {q:"Vilket lag vann Champions League flest ganger?",o:["Barcelona","Bayern Munchen","Real Madrid","AC Milan"],a:2,d:2},
    {q:"Vem vann Ballon d'Or 2023?",o:["Erling Haaland","Kylian Mbappe","Lionel Messi","Vinicius Jr."],a:2,d:2},
    {q:"Vilket ar vann Frankrike sitt andra VM-guld?",o:["2014","2016","2018","2020"],a:2,d:2},
    {q:"Vilket land har flest VM-titlar for damer?",o:["Brasilien","Sverige","USA","Australien"],a:2,d:2},
    {q:"Vilket ar spelade Sverige sin forsta VM-match?",o:["1930","1934","1938","1950"],a:1,d:3},
    {q:"Vad heter rekordet for flest mal i ett VM?",o:["Just Fontaine 1958","Pele 1970","Gerd Muller 1970","Ronaldo 2002"],a:0,d:3},
    {q:"Vilket ar vann Grekland EM i fotboll?",o:["2000","2002","2004","2006"],a:2,d:3},
    {q:"Vilket lag vann Champions League 2012?",o:["Barcelona","Bayern Munchen","Chelsea","Real Madrid"],a:2,d:3},
    {q:"Vilket ar grundades FIFA?",o:["1900","1904","1908","1912"],a:1,d:3},
    {q:"Vilket ar kom offside-regeln i fotboll?",o:["1863","1878","1896","1925"],a:3,d:3},
    {q:"Vilket lag vann Champions League 2024?",o:["Liverpool","PSG","Bayern Munchen","Real Madrid"],a:3,d:3},
    {q:"Vem satte rekord for flest mal i en Premier League-sasong?",o:["Wayne Rooney","Thierry Henry","Alan Shearer","Mohamed Salah"],a:3,d:3},
  ],

  "🏒 Ishockey": [
    {q:"Vad heter NHL:s mastarskapstrofe?",o:["Presidents Trophy","Hart Trophy","Stanley Cup","Conn Smythe"],a:2,d:1},
    {q:"Vilket lag vann Stanley Cup 2024?",o:["Colorado Avalanche","Florida Panthers","Edmonton Oilers","Rangers"],a:1,d:1},
    {q:"Vad kallas Wayne Gretzky?",o:["The Boss","The Great One","The Rocket","Mr. Hockey"],a:1,d:1},
    {q:"Vilket land har vunnit flest VM i ishockey?",o:["Sverige","Finland","Kanada","Sovjet/Ryssland"],a:2,d:1},
    {q:"Hur manga perioder spelas i ishockey?",o:["2","3","4","5"],a:1,d:1},
    {q:"Vilket lag spelar hemma pa Scandinavium?",o:["Brynas IF","Frolunda","Djurgardens IF","MODO"],a:1,d:1},
    {q:"Vilket lag spelar i Gavle i SHL?",o:["Brynas IF","Frolunda","Djurgardens IF","HV71"],a:0,d:1},
    {q:"Vilket lag spelar i Jonkoping i SHL?",o:["Brynas IF","Frolunda","Djurgardens IF","HV71"],a:3,d:1},
    {q:"Vilket ar grundades NHL?",o:["1910","1917","1924","1930"],a:1,d:1},
    {q:"Vem haller rekord for flest NHL-poang?",o:["Mario Lemieux","Mark Messier","Wayne Gretzky","Gordie Howe"],a:2,d:1},
    {q:"Vilket ar vann Sverige OS-guld i ishockey (herrar)?",o:["1994","2002","2006","2018"],a:0,d:1},
    {q:"Hur manga lag finns i NHL?",o:["28","30","32","34"],a:2,d:1},
    {q:"Vilket lag vann Stanley Cup 2021?",o:["Colorado Avalanche","Tampa Bay Lightning","Vegas Golden Knights","Montreal Canadiens"],a:1,d:2},
    {q:"Vilket lag vann Stanley Cup 2022?",o:["Colorado Avalanche","Tampa Bay Lightning","Vegas Golden Knights","Florida Panthers"],a:0,d:2},
    {q:"Vilket ar kom Peter Forsberg till NHL?",o:["1993","1995","1997","1999"],a:1,d:2},
    {q:"Vad heter trofeen for baste malvakt i NHL?",o:["Vezina Trophy","Hart Trophy","Norris Trophy","Calder Trophy"],a:0,d:2},
    {q:"Vilket ar kom William Nylander till NHL?",o:["2014","2016","2018","2020"],a:1,d:2},
    {q:"Hur lang ar en ishockeyplan (standard)?",o:["Ca 50 m","Ca 60 m","Ca 70 m","Ca 80 m"],a:1,d:2},
    {q:"Vilket land vann damernas OS i ishockey 2022?",o:["Sverige","USA","Kanada","Finland"],a:1,d:2},
    {q:"Vilket ar vann Sverige VM i ishockey senast?",o:["2016","2017","2018","2019"],a:1,d:2},
    {q:"Vilket ar grundades Djurgardens IF hockey?",o:["1912","1921","1930","1945"],a:1,d:2},
    {q:"Vilket ar kom Nicklas Backstrom till NHL?",o:["2005","2007","2009","2011"],a:1,d:2},
    {q:"Vem scores mest poang i NHL-historia en sasong?",o:["Mario Lemieux","Brett Hull","Wayne Gretzky 215p 85-86","Jari Kurri"],a:2,d:3},
    {q:"Vad heter trofeen for baste rookie i NHL?",o:["Vezina Trophy","Hart Trophy","Norris Trophy","Calder Trophy"],a:3,d:3},
    {q:"Vilket ar grundades Brynas IF?",o:["1908","1920","1930","1940"],a:2,d:3},
    {q:"Vad heter trofeen for mest poang i NHL-sasong?",o:["Vezina Trophy","Hart Trophy","Art Ross Trophy","Maurice Richard Trophy"],a:2,d:3},
    {q:"Vilket ar vann Tre Kronor OS-guld senast?",o:["1994","2002","2006","2018"],a:0,d:3},
    {q:"Vilket ar grundades Frolunda HC?",o:["1938","1944","1951","1960"],a:2,d:3},
    {q:"Vad heter trofeen for MVP i NHL playoffs?",o:["Vezina Trophy","Hart Trophy","Conn Smythe Trophy","Norris Trophy"],a:2,d:3},
    {q:"Vilket ar kom Viktor Hedman till NHL?",o:["2007","2009","2011","2013"],a:1,d:3},
  ],

  "🏅 Sport (allmänt)": [
    {q:"Vem satte 100m-rekordet pa 9.58 sekunder?",o:["Carl Lewis","Maurice Greene","Usain Bolt","Justin Gatlin"],a:2,d:1},
    {q:"I vilken sport tavlar man i Tour de France?",o:["Triathlon","Lopning","Cykling","Simning"],a:2,d:1},
    {q:"Vilket ar holls OS i Stockholm?",o:["1908","1912","1920","1924"],a:1,d:1},
    {q:"Vilken sport spelas i Wimbledon?",o:["Badminton","Squash","Tennis","Padel"],a:2,d:1},
    {q:"Hur langt ar ett marathonlopp?",o:["40 km","42.195 km","45 km","50 km"],a:1,d:1},
    {q:"Vilket land har vunnit flest OS-guld totalt?",o:["Ryssland","Kina","USA","Tyskland"],a:2,d:1},
    {q:"Vem vann Formel 1-VM 2021?",o:["Lewis Hamilton","Max Verstappen","Valtteri Bottas","Sebastian Vettel"],a:1,d:1},
    {q:"Vilket ar spelades de moderna OS forsta gangen?",o:["1894","1896","1900","1904"],a:1,d:1},
    {q:"Hur manga Grand Slam finns det i tennis?",o:["2","3","4","5"],a:2,d:1},
    {q:"Vilket ar holls OS i Rio de Janeiro?",o:["2012","2014","2016","2018"],a:2,d:1},
    {q:"Vem vann Wimbledon damer 2023?",o:["Iga Swiatek","Coco Gauff","Marketa Vondrousova","Aryna Sabalenka"],a:2,d:1},
    {q:"I vilken sport tavlar man om 'yellow jersey'?",o:["Cykling","Triathlon","Lopning","Simning"],a:0,d:1},
    {q:"Hur manga Grand Slam har Roger Federer vunnit?",o:["18","20","22","24"],a:1,d:2},
    {q:"Vem vann Formel 1-VM flest ganger?",o:["Ayrton Senna","Michael Schumacher","Lewis Hamilton","Sebastian Vettel"],a:1,d:2},
    {q:"Vem satte varldrekordet pa maraton 2023?",o:["Eliud Kipchoge","Kenenisa Bekele","Kelvin Kiptum","Geoffrey Kamworor"],a:2,d:2},
    {q:"Vilket land har flest Tour de France-segrar?",o:["Frankrike","Belgien","Spanien","USA"],a:2,d:2},
    {q:"Vilken nation har flest OS-guld i simning?",o:["Australien","Kina","Ryssland","USA"],a:3,d:2},
    {q:"Vem vann Formel 1-VM 2023?",o:["Lewis Hamilton","Max Verstappen","Charles Leclerc","Sergio Perez"],a:1,d:2},
    {q:"Vilket ar holls OS i Tokyo?",o:["2018","2020","2021","2022"],a:2,d:2},
    {q:"Vilket ar kom padel till Sverige?",o:["1995","2000","2005","2010"],a:2,d:2},
    {q:"Vem vann Wimbledon herrar 2023?",o:["Novak Djokovic","Carlos Alcaraz","Jannik Sinner","Daniil Medvedev"],a:1,d:2},
    {q:"Vilket land har vunnit flest Formel 1-VM konstruktorer?",o:["Ferrari","McLaren","Mercedes","Williams"],a:0,d:2},
    {q:"Vilket ar vann Bjorn Borg sitt sista Wimbledon?",o:["1978","1980","1981","1983"],a:1,d:3},
    {q:"Vilket ar holls OS i Munchen dar terrordastet skedde?",o:["1968","1972","1976","1980"],a:1,d:3},
    {q:"Hur manga set spelas i herrtennismatch pa Grand Slam?",o:["3","5","4","2"],a:1,d:3},
    {q:"Vilket ar vann Sverige damernas VM i fotboll?",o:["Sverige har aldrig vunnit","1991","1995","2003"],a:0,d:3},
    {q:"Hur lang ar ett Formel 1-varv pa Monza?",o:["4 km","5.8 km","6.9 km","7.5 km"],a:1,d:3},
    {q:"Vilket ar grundades FIFA?",o:["1900","1904","1908","1912"],a:1,d:3},
    {q:"Vem vann Tour de France flest ganger?",o:["Bernard Hinault","Eddy Merckx","Miguel Indurain","Lance Armstrong disqualified"],a:1,d:3},
    {q:"Vilket ar kom nya regler for formel 1-bilar?",o:["2020","2022","2023","2024"],a:1,d:3},
  ],

  "💻 Teknik & IT": [
    {q:"Vilket foretag tillverkar PlayStation?",o:["Microsoft","Nintendo","Sony","Sega"],a:2,d:1},
    {q:"Vilket ar lanserades forsta iPhone?",o:["2005","2007","2009","2011"],a:1,d:1},
    {q:"Vilket foretag grundade Bill Gates?",o:["Apple","Amazon","Microsoft","Google"],a:2,d:1},
    {q:"Vilket ar grundades Google?",o:["1996","1998","2000","2002"],a:1,d:1},
    {q:"Vad heter Apples smarta assistent?",o:["Cortana","Alexa","Google","Siri"],a:3,d:1},
    {q:"Vilket ar grundades Apple?",o:["1974","1976","1978","1980"],a:1,d:1},
    {q:"Vilket ar grundades Spotify?",o:["2004","2006","2008","2010"],a:2,d:1},
    {q:"Vad heter Googles mobiloperativsystem?",o:["iOS","Windows Mobile","Android","HarmonyOS"],a:2,d:1},
    {q:"Vilket ar grundades Facebook?",o:["2002","2004","2006","2008"],a:1,d:1},
    {q:"Vilket ar grundades Amazon?",o:["1992","1994","1996","1998"],a:1,d:1},
    {q:"Vilket ar kom YouTube?",o:["2003","2005","2007","2009"],a:1,d:1},
    {q:"Vem grundade Tesla?",o:["Elon Musk","Martin Eberhard","Jeff Bezos","Larry Page"],a:1,d:1},
    {q:"Vilket ar kom forsta versionen av Windows?",o:["1981","1983","1985","1987"],a:2,d:2},
    {q:"Vad heter Microsofts molntjanst?",o:["AWS","Google Cloud","Azure","IBM Cloud"],a:2,d:2},
    {q:"Vilket ar kom Instagram?",o:["2008","2010","2012","2014"],a:1,d:2},
    {q:"Vilket ar lanserades ChatGPT?",o:["2020","2021","2022","2023"],a:2,d:2},
    {q:"Vilket ar grundades Uber?",o:["2007","2009","2011","2013"],a:1,d:2},
    {q:"Vem grundade LinkedIn?",o:["Bill Gates","Reid Hoffman","Mark Zuckerberg","Jack Dorsey"],a:1,d:2},
    {q:"Vilket ar grundades NVIDIA?",o:["1989","1991","1993","1995"],a:2,d:2},
    {q:"Vem grundade SpaceX?",o:["Jeff Bezos","Richard Branson","Elon Musk","Larry Page"],a:2,d:2},
    {q:"Vilket ar kom TikTok globalt?",o:["2014","2016","2018","2020"],a:2,d:2},
    {q:"Vilket ar grundades OpenAI?",o:["2013","2015","2017","2019"],a:1,d:2},
    {q:"Vem uppfann World Wide Web?",o:["Bill Gates","Steve Jobs","Tim Berners-Lee","Vint Cerf"],a:2,d:3},
    {q:"Vilket ar kom forsta versionen av Linux?",o:["1989","1991","1993","1995"],a:1,d:3},
    {q:"Vad heter protokollet bakom internet?",o:["HTTP","TCP/IP","FTP","SMTP"],a:1,d:3},
    {q:"Vilket ar grundades Intel?",o:["1964","1966","1968","1970"],a:2,d:3},
    {q:"Vad heter Alan Turings test for AI?",o:["Turing Test","Intelligence Test","Machine Test","Imitation Game"],a:0,d:3},
    {q:"Vilket ar grundades Anthropic (Claude)?",o:["2019","2021","2022","2023"],a:1,d:3},
    {q:"Vad heter Intels grundare?",o:["Bill Gates","Gordon Moore & Robert Noyce","Andy Grove","Ted Hoff"],a:1,d:3},
    {q:"Vilket ar kom USB-standarden?",o:["1992","1994","1996","1998"],a:2,d:3},
    {q:"Vilket ar kom forsta versionen av Python?",o:["1987","1989","1991","1993"],a:2,d:3},
    {q:"Vad heter Googles kvantdator-chip?",o:["Sycamore","Willow","Bristlecone","Quantum"],a:1,d:3},
  ],

  "🔬 Vetenskap & Natur": [
    {q:"Vilket ar det hardaste naturliga materialet?",o:["Guld","Granit","Diamant","Jarn"],a:2,d:1},
    {q:"Hur manga ben har en insekt?",o:["4","6","8","10"],a:1,d:1},
    {q:"Vilket grundamne har kemisk symbol 'Au'?",o:["Silver","Aluminium","Guld","Koppar"],a:2,d:1},
    {q:"Hur manga planeter finns i solsystemet?",o:["7","8","9","10"],a:1,d:1},
    {q:"Vilket grundamne har kemisk symbol 'Fe'?",o:["Fluor","Fosfor","Jarn","Francium"],a:2,d:1},
    {q:"Vad ar den kemiska formeln for vatten?",o:["HO","H2O","H2O2","HO2"],a:1,d:1},
    {q:"Vilket ar jordens narmaste stjarna (forutom solen)?",o:["Sirius","Vega","Proxima Centauri","Betelgeuse"],a:2,d:1},
    {q:"Hur manga kromosompar har en manniska?",o:["21","23","25","46"],a:1,d:1},
    {q:"Vilket ar publicerade Darwin Arternas uppkomst?",o:["1849","1859","1869","1879"],a:1,d:1},
    {q:"Vad ar DNA?",o:["Proteinkomplex","Ribosomalt RNA","Deoxiribonukleinsyra","Adenosintrifosfat"],a:2,d:1},
    {q:"Vad ar ett ljusar?",o:["Tid ljuset tar att na solen","Avstand ljuset fardas pa ett ar","Hur snabbt ljuset ror sig","Antalet fotoner per sekund"],a:1,d:1},
    {q:"Vilket grundamne ar flytande vid rumstemperatur (forutom kvicksilver)?",o:["Brom","Jod","Fosfor","Selen"],a:0,d:1},
    {q:"Vilket ar publicerade Einstein sin relativitetsteori?",o:["1900","1905","1910","1915"],a:1,d:2},
    {q:"Hur lang tid tar det for ljuset att na jorden fran solen?",o:["Ca 4 minuter","Ca 8 minuter","Ca 16 minuter","Ca 30 minuter"],a:1,d:2},
    {q:"Vilket grundamne har atomnummer 79?",o:["Platina","Silver","Guld","Koppar"],a:2,d:2},
    {q:"Vilket ar sande Voyager 1 ivig?",o:["1973","1975","1977","1979"],a:2,d:2},
    {q:"Vad heter processen da en stjarna exploderar?",o:["Nova","Supernova","Neutronkollaps","Gamma-ray burst"],a:1,d:2},
    {q:"Hur djup ar Marianergraven ungefar?",o:["7 km","9 km","11 km","13 km"],a:2,d:2},
    {q:"Vad heter teorin om universums uppkomst?",o:["Steady State","Big Crunch","Big Bang","Inflation"],a:2,d:2},
    {q:"Vad ar kvantfysikens osäkerhetsprincip?",o:["Einsteins princip","Heisenbergs osäkerhetsprincip","Bohrs komplementaritet","Plancks kvantum"],a:1,d:2},
    {q:"Vilket grundamne har flest kanda isotoper?",o:["Uran","Cesium","Xenon","Tellurium"],a:3,d:2},
    {q:"Vilket ar togs det forsta svarta halets bild?",o:["2015","2017","2019","2021"],a:2,d:2},
    {q:"Vad ar ett svart hal?",o:["En kollapsad stjarna med oandlig gravitation","En tomrum i rymden","En morklagd nebulosa","En kvasar"],a:0,d:3},
    {q:"Vad heter Schrödingers tankeexperiment?",o:["Schrödingers paradox","Schrödingers katt","Schrödingers box","Kvantparadoxen"],a:1,d:3},
    {q:"Vad ar Plancks konstant ungefar?",o:["6.626x10-34 Js","9.109x10-31 kg","1.602x10-19 C","6.022x10+23 mol-1"],a:0,d:3},
    {q:"Vilket ar beraknade Newton gravitationslagen?",o:["1666 publicerad 1687","1700","1750","1800"],a:0,d:3},
    {q:"Vad heter den svagaste av de fyra naturkrafterna?",o:["Stark karnkraft","Svag karnkraft","Elektromagnetism","Gravitation"],a:3,d:3},
    {q:"Vilket ar fick Curie sitt andra Nobelpris?",o:["1903","1907","1911","1915"],a:2,d:3},
    {q:"Vad ar fotosyntesens formel?",o:["6CO2+6H2O=C6H12O6+6O2","6O2+6H2O=C6H12O6+6CO2","CO2+H2O=CH2O+O2","6CO2+H2O=C6H12O6+O2"],a:0,d:3},
    {q:"Vilket ar kom kvantteorin om superledning?",o:["1957","1962","1968","1972"],a:0,d:3},
  ],

  "🌍 Geografi & Historia": [
    {q:"Vad ar Frankrikes huvudstad?",o:["Lyon","Marseille","Paris","Bordeaux"],a:2,d:1},
    {q:"Vilket hav ar storst?",o:["Atlantiska","Indiska","Arktiska","Stilla havet"],a:3,d:1},
    {q:"Vilket land ar storst till ytan?",o:["USA","Kanada","Kina","Ryssland"],a:3,d:1},
    {q:"Vad ar Australiens huvudstad?",o:["Sydney","Melbourne","Canberra","Brisbane"],a:2,d:1},
    {q:"Vilket ar foll Berlinmuren?",o:["1987","1989","1991","1993"],a:1,d:1},
    {q:"Vilket land har flest invanare?",o:["Indien","Kina","USA","Indonesien"],a:0,d:1},
    {q:"Vad ar Japans huvudstad?",o:["Osaka","Kyoto","Tokyo","Hiroshima"],a:2,d:1},
    {q:"Vilket ar landade manniskan pa manen?",o:["1967","1969","1971","1973"],a:1,d:1},
    {q:"Vilket land var tidigare kant som Persien?",o:["Irak","Iran","Turkiet","Syrien"],a:1,d:1},
    {q:"Vad ar Kanadas huvudstad?",o:["Toronto","Montreal","Vancouver","Ottawa"],a:3,d:1},
    {q:"Vilket ar borjade andra varldskriget?",o:["1937","1939","1941","1943"],a:1,d:1},
    {q:"Vilket land har flest UNESCO-varldssarv?",o:["Kina","Italien","Spanien","Frankrike"],a:1,d:1},
    {q:"Vilket ar grundades FN?",o:["1943","1945","1947","1949"],a:1,d:2},
    {q:"Vilket land avsaffade apartheid 1994?",o:["Zimbabwe","Kenya","Sydafrika","Nigeria"],a:2,d:2},
    {q:"Vilket ar skedde Franska revolutionen?",o:["1776","1789","1799","1815"],a:1,d:2},
    {q:"Vilken stad var Osmanska rikets huvudstad?",o:["Ankara","Bagdad","Konstantinopel","Kairo"],a:2,d:2},
    {q:"Vilket ar sprack Sovjet upp?",o:["1989","1991","1993","1995"],a:1,d:2},
    {q:"Hur manga lander finns i Afrika?",o:["44","54","64","74"],a:1,d:2},
    {q:"Vilket ar invigdes Eiffeltornet?",o:["1885","1887","1889","1891"],a:2,d:2},
    {q:"Vilket ar grundades EU i Maastricht?",o:["1989","1991","1993","1995"],a:2,d:2},
    {q:"Vilket land var kolonialmakt over Vietnam?",o:["England","Holland","Frankrike","Portugal"],a:2,d:2},
    {q:"Vilket land har flest officiella sprak?",o:["Schweiz","Belgien","Sydafrika","Kanada"],a:2,d:2},
    {q:"Vilket ar grundades Romerska riket?",o:["753 f.Kr.","509 f.Kr.","264 f.Kr.","27 f.Kr."],a:0,d:3},
    {q:"Vilket ar grundades NATO?",o:["1945","1947","1949","1951"],a:2,d:3},
    {q:"Vilket land var forst med kvinnlig rosttratt?",o:["Sverige","USA","Nya Zeeland","Finland"],a:2,d:3},
    {q:"Vilket ar fick Finland sjalvstandighet?",o:["1915","1917","1919","1921"],a:1,d:3},
    {q:"Vilket ar slotes Wienkongressen?",o:["1810","1815","1820","1825"],a:1,d:3},
    {q:"Vilket ar dog Napoleon Bonaparte?",o:["1815","1819","1821","1825"],a:2,d:3},
    {q:"Vad heter den kinesiska muren officiellt?",o:["Kinas langa mur","Wan Li Chang Cheng","Den Forbjudna Muren","Kejsarens Barrikar"],a:1,d:3},
    {q:"Vilket ar borjade Forsta varldskriget?",o:["1912","1914","1916","1918"],a:1,d:3},
  ],

  "🍕 Mat & Dryck": [
    {q:"Vad ar huvudingrediensen i guacamole?",o:["Tomat","Avokado","Lime","Koriander"],a:1,d:1},
    {q:"Vilket land kommer sushi ifran?",o:["Kina","Korea","Japan","Thailand"],a:2,d:1},
    {q:"Vilket land kommer pizza ifran?",o:["Frankrike","Spanien","Italien","Grekland"],a:2,d:1},
    {q:"Vad ar en cappuccino?",o:["Bara mjolk","Espresso och angad mjolk","Te och mjolk","Kaffe och gradde"],a:1,d:1},
    {q:"Vilket land kommer paella ifran?",o:["Italien","Portugal","Frankrike","Spanien"],a:3,d:1},
    {q:"Vad kallas den japanska ratten med ra fisk?",o:["Sushi","Sashimi","Ramen","Udon"],a:1,d:1},
    {q:"Vilket land producerar mest olivolja?",o:["Italien","Spanien","Grekland","Turkiet"],a:1,d:1},
    {q:"Vad ar hummus gjort av?",o:["Linser","Kikartor","Bonor","Artor"],a:1,d:1},
    {q:"Vilket land kommer kimchi ifran?",o:["Japan","Kina","Korea","Vietnam"],a:2,d:1},
    {q:"Vad ar tacos traditionellt gjort av?",o:["Vete","Majs","Ris","Potatis"],a:1,d:1},
    {q:"Vilket land producerar mest vin i varlden?",o:["Frankrike","Spanien","Italien","USA"],a:2,d:1},
    {q:"Vad ar en croissant?",o:["En schweizisk bulle","En osterrikisk och fransk bakelse","En dansk pastej","En belgisk kaka"],a:1,d:1},
    {q:"Vad heter den franska ratten med sniglar?",o:["Foie gras","Bouillabaisse","Escargot","Souffle"],a:2,d:2},
    {q:"Vilket land kommer maten Pad Thai ifran?",o:["Vietnam","Kina","Thailand","Malaysia"],a:2,d:2},
    {q:"Vad ar umami?",o:["Sott","Surt","Salt","Den femte grundsmaken"],a:3,d:2},
    {q:"Vilket land kommer Pho ifran?",o:["Kina","Laos","Thailand","Vietnam"],a:3,d:2},
    {q:"Vad heter den spanska kallratten gjord av tomater?",o:["Salmorejo","Gazpacho","Sofrito","Pisto"],a:1,d:2},
    {q:"Vad ar miso gjort av?",o:["Ris","Sojabonor","Sesamfron","Tofu"],a:1,d:2},
    {q:"Vilket land ar kant for Moules-frites?",o:["Frankrike","Holland","Belgien","Luxemburg"],a:2,d:2},
    {q:"Vad ar Worcestershiresas gjord av?",o:["Tomat","Ansjovis","Pepparrot","Senap"],a:1,d:2},
    {q:"Vilket ar grundades McDonalds?",o:["1940","1948","1955","1960"],a:0,d:2},
    {q:"Vilket land uppfann champagnen?",o:["Spanien","Italien","Frankrike","Belgien"],a:2,d:2},
    {q:"Vad ar en Maillard-reaktion?",o:["En kemisk reaktion vid jasning","En brunningsreaktion vid upphettning","En saltningsprocess","En konserveringsmetod"],a:1,d:3},
    {q:"Vilket land producerar Grand Cru-viner?",o:["Italien","Spanien","Frankrike","Portugal"],a:2,d:3},
    {q:"Vad heter den japanska metoden att skara fisk?",o:["Ikejime","Sashimi","Katsu","Mirin"],a:0,d:3},
    {q:"Vad ar koji i japansk matlagning?",o:["En fisk","En svamp och mogel","En sas","En ris-typ"],a:1,d:3},
    {q:"Vilket ar grundades Michelin-guiden?",o:["1895","1900","1910","1920"],a:1,d:3},
    {q:"Vad heter den mexikanska ratten med agave?",o:["Mezcal","Pulque","Tequila","Alla tre ar agavebaserade"],a:3,d:3},
    {q:"Vilken druvsorta anvands i Champagne?",o:["Chardonnay och Pinot Noir","Merlot och Cabernet","Riesling och Gewurztraminer","Syrah och Grenache"],a:0,d:3},
    {q:"Vilket ar uppfanns pizza Margherita?",o:["1860","1889","1900","1920"],a:1,d:3},
  ],

  "🏙️ Umeå & Norrland": [
    {q:"Umeå är beläget vid vilken älv?",o:["Luleälven","Ångermanälven","Umeälven","Skellefte­älven"],a:2,d:1},
    {q:"Vilket år utsågs Umeå till Europas kulturhuvudstad?",o:["2010","2012","2014","2016"],a:2,d:1},
    {q:"Vilket universitet finns i Umeå?",o:["Luleå tekniska","Uppsala","Umeå universitet","Mittuniversitetet"],a:2,d:1},
    {q:"Vad kallas Umeå ibland på grund av sina björkar?",o:["Björkstaden","Trädstaden","Norrlandsstaden","Älvstaden"],a:0,d:1},
    {q:"I vilket landskap ligger Umeå?",o:["Ångermanland","Lappland","Västerbotten","Norrbotten"],a:2,d:1},
    {q:"Vilket år grundades Umeå universitet?",o:["1945","1955","1963","1971"],a:2,d:1},
    {q:"Vad heter Umeås stora köpcenter?",o:["Mitt i City","Syd","A6","Utopia"],a:3,d:1},
    {q:"Vad heter Umeås konstmuseum?",o:["Bildmuseet","Umeå konstmuseum","Norrlandsmuseet","Västerbottensmuseet"],a:0,d:1},
    {q:"Hur många invånare har Umeå ungefär?",o:["60 000","80 000","130 000","200 000"],a:2,d:1},
    {q:"Vilket landskap ligger Skellefteå i?",o:["Västernorrland","Norrbotten","Västerbotten","Lappland"],a:2,d:1},
    {q:"Vilken E-väg går genom Umeå?",o:["E4","E6","E10","E12"],a:0,d:1},
    {q:"Vad heter Umeås ishockeylag i SHL?",o:["Umeå HC","Björklöven","IF Björklöven","Umeå Cowboys"],a:1,d:1},
    {q:"Vilken kändis från Umeå är känd inom höjdhopp?",o:["Stefan Holm","Patrik Sjöberg","Kajsa Bergqvist","Carolina Klüft"],a:0,d:2},
    {q:"Vilket år fick Umeå stadsrättigheter?",o:["1588","1622","1640","1700"],a:1,d:2},
    {q:"Vad heter Umeås lokaltidning?",o:["Västerbottens-Kuriren","Norrländska Socialdemokraten","Umeå Tidning","Norran"],a:0,d:2},
    {q:"Vilket museum finns i Gammlia?",o:["Bildmuseet","Länsmuseet Västernorrland","Västerbottens museum","Tekniska museet"],a:2,d:2},
    {q:"Vilket år brann Umeå ned och byggdes upp?",o:["1798","1888","1902","1920"],a:1,d:2},
    {q:"Hur långt är det från Umeå till Stockholm?",o:["Ca 400 km","Ca 600 km","Ca 700 km","Ca 900 km"],a:3,d:2},
    {q:"Vilket år invigdes Umeå Arena?",o:["2010","2012","2014","2016"],a:2,d:2},
    {q:"Vilket landskap gränsar Västerbotten mot väster?",o:["Lappland","Norrbotten","Ångermanland","Finland"],a:0,d:2},
    {q:"Vilket år grundades Västerbottens museum?",o:["1886","1900","1921","1945"],a:0,d:3},
    {q:"Vad heter bron över Umeälven i centrala Umeå?",o:["Tegsbron","Storbron","Umeå bron","Gammliabron"],a:1,d:3},
    {q:"Vilket år öppnade Umeå flygplats?",o:["1935","1944","1952","1960"],a:1,d:3},
    {q:"Vilket år grundades Umeå IF fotboll?",o:["1917","1927","1937","1947"],a:0,d:3},
    {q:"Vad heter Umeås äldsta kyrka?",o:["Umeå landsförsamlings kyrka","Umeå stadsförsamlings kyrka","Gammlia kyrka","Mariebergskyrkan"],a:0,d:3},
    {q:"Vilket år grundades Umeå som stad?",o:["1588","1621","1650","1700"],a:1,d:3},
    {q:"Vad heter kullen i centrala Umeå?",o:["Röbäckskullen","Umedalen","Backenkullen","Tomtebo"],a:0,d:3},
    {q:"Vilket år startade Umeå Open tennis?",o:["1980","1985","1990","1995"],a:2,d:3},
  ],
};

function getQuestions(category, difficulty, count) {
  const allCats = category === 'mix' ? Object.keys(QUESTION_DB) : [category];
  function buildPool(maxDiff) {
    let pool = [];
    allCats.forEach(cat => {
      const qs = QUESTION_DB[cat] || [];
      pool = pool.concat(qs.filter(q => q.d <= maxDiff));
    });
    return pool;
  }
  let pool = buildPool(difficulty);
  if (pool.length < count && difficulty < 3) pool = buildPool(difficulty + 1);
  if (pool.length < count) pool = buildPool(3);
  if (pool.length === 0) return [];
  const arr = pool.slice();
  for (let i = arr.length - 1; i > 0; i--) {
    const j = Math.floor((crypto.getRandomValues(new Uint32Array(1))[0] / 0xFFFFFFFF) * (i + 1));
    [arr[i], arr[j]] = [arr[j], arr[i]];
  }
  return arr.slice(0, count).map(q => ({
    question: q.q,
    options: q.o,
    correct: q.a,
    category: allCats.length > 1 ? '🌈 Mix' : category
  }));
}
